### ISSUE TITLE
[ENHANCE] configs

### ISSUE THREAD

**Issue by FoxPotato** [DarkholmeTenk/TardisModIssues#100]
You should really change the names of the configs because it's really hard to find stuff??
is it in misc? in tardiscore? maybe in tardismod?? idk

**Comment by Soyaro666** [comment]
i've found the same settings in two different config files... and i've found the same 2 lines multiple times in another document... just noticed it to be related to this topic...

**Comment by DarkholmeTenk** [comment]
examples pls

**Comment by Soyaro666** [comment]
the Thaumcraft lines are in misc.cfg and in components.cfg.
in misc:
line 23: max aspect:I:32
line 35: num aspects:I:32
in components:
line 31: max aspect:I:16
line 23: num aspects:I:32

the related descriptions are exactly the same in both files, the only difference is the value of max aspect.

the part with the 2 identical lines in one file where my mistake, they are only nearly identical.
I'm not sure if those where all. I'll read more attentive tomorrow.

**Comment by DarkholmeTenk** [comment]
that's because I moved them and have no way to clear configs:P

**Comment by FoxPotato** [comment]
But you should really clean up the configs, Like i said. Theres a TARDIScore and a TARDISmain and that sounds pretty similair to me and it's confusing.
maybe make a config just for the internal buffers and stuff.
and a config for idk, other stuff. cant think of any.

**Comment by Soyaro666** [comment]
or maybe one single cfg where different topics are grouped?

**Comment by FoxPotato** [comment]
Nah, I think the multiple configs can be handy, as long as it's all neatly done :p

**Comment by DarkholmeTenk** [comment]
Done
