### ISSUE TITLE
[ENHANCE] Hiding the TARDIS

### ISSUE THREAD

**Issue by FoxPotato** [DarkholmeTenk/TardisModIssues#103]
I'd love to have a function which like makes the TARDIS invisible or just makes it be 1 second out of sync, like in the end of time. 
This could be handy for stealth missions, or if you're going offline or something on a smp server.

**Comment by DarkholmeTenk** [comment]
Uncoordinated flight + stabilizers?

**Comment by FoxPotato** [comment]
I'm talking about while you're outside the TARDIS, or is the recall + uncoordinated flight fixed?

**Comment by DarkholmeTenk** [comment]
Oh, for outside the TARDIS. I'll sort something out :).

**Comment by Soyaro666** [comment]
well, at least it could work like uncoordinated flight + stabilizers. the Screwdriver already has some remote functions (recall), why not adding an ability to set 5 elements to a specific state. I mean: uncoordinated flight and stabilizers to true, than the start routine, all set in 1 second. and of course one could still pull the quantum handbrake when on the inside. I guess this would require to rewrite the recall a little bit. Or is it already able to recall if the Tardis is in uncoordinated flight? If not it should be, even without this remote start feature, but that's just my oppinion.

**Comment by FoxPotato** [comment]
We only need an option for outside the TARDIS, inside you just use the drift. so there is no need for an option inside.
