### ISSUE TITLE
[BUG] TARDIS deletes blocks in between rooms

### ISSUE THREAD

**Issue by Jwtc2000** [DarkholmeTenk/TardisModIssues#104]
TARDIS will delete blocks in between rooms 
![bug1] (https://i.imgur.com/k0ehBNT.png)
![bug2] (https://i.imgur.com/McI65UD.png)

**Comment by laz2727** [comment]
Tardis should really stop trying to fix broken doors. If an indestructible door
is broken, it's intentional, dammit.

2015-05-14 10:00 GMT+06:00 Jwtc2000 <notifications@github.com>:

**Comment by laz2727** [comment]
And there should be a way to unlock doors that have primary door from the
other side.

2015-05-14 12:51 GMT+06:00 Lubimov Nikolay <laz2727@gmail.com>:

**Comment by FoxPotato** [comment]
What do you mean by unlocking doors with a primary door on the other side?

**Comment by laz2727** [comment]
Sometimes, when room is generated, it fails to delete the door afterwards.
And there's a primary door behind that glitched door.

2015-05-14 15:03 GMT+06:00 FoxPotato <notifications@github.com>:

**Comment by FoxPotato** [comment]
Oh really? I never had that.
Might just go spam rooms, any rooms in particular?

**Comment by laz2727** [comment]
I dunno. Maybe that happens because i break stuff in creative.

2015-05-14 15:54 GMT+06:00 FoxPotato <notifications@github.com>:

**Comment by FoxPotato** [comment]
like what? I'm not able to recreate the bug. I've literally placed 60 rooms in a random order. not just corridors also rooms and lifts.

**Comment by FoxPotato** [comment]
@jwtc2000 how long does it usually take before the TARDIS deletes the blocks

**Comment by DarkholmeTenk** [comment]
Believe it's multiplayer on server restarts that this happens.
