### ISSUE TITLE
[ENHANCE] Color coding for bookmarks

### ISSUE THREAD

**Issue by Jwtc2000** [DarkholmeTenk/TardisModIssues#105]
~~Shift+right click on bookmarks to change color?~~

Edit(FP): Right Click with dye

#168 :+1:

**Comment by FoxPotato** [comment]
Or right click with a dye, that avoids having to scroll for your fav colour :p

**Comment by DarkholmeTenk** [comment]
Doesn't work with the fact that some bookmarks are slightly blue for flight control
