### ISSUE TITLE
[BUG] Unbreakable my ass

### ISSUE THREAD

**Issue by FoxPotato** [DarkholmeTenk/TardisModIssues#106]
The sonic blaster, which is in the dalek mod, is able to destroy all blocks in the console room, even the console and time rotor.
might wanna fix that ;'D

**Comment by DarkholmeTenk** [comment]
I made the blocks as hard as bedrock; if something can destroy bedrock, that's not my problem :P

**Comment by FoxPotato** [comment]
The sonic blaster can't destroy bedrock tho.
And when you destroy the time rotor you cannot leave the TARDIS anymore.

**Comment by laz2727** [comment]
6000000.0F =/= -1.0F, @DarkholmeTenk.

2015-05-14 18:22 GMT+06:00 FoxPotato <notifications@github.com>:

**Comment by Jwtc2000** [comment]
![:P] (http://i.imgur.com/iCuYA4C.png)

**Comment by DarkholmeTenk** [comment]
Sent a message to 1WTC about fixing this.

**Comment by DarkholmeTenk** [comment]
1WTC has written a patch so the sonic blaster won't break unbreakable blocks anymore and hopes to get it out in the next few days :D

**Comment by FoxPotato** [comment]
huzzah!
