### ISSUE TITLE
[BUG] doors locked

### ISSUE THREAD

**Issue by Soyaro666** [DarkholmeTenk/TardisModIssues#109]
Configuration: FTB Infinity 1.3.4 + darkcore + Tardis, Singleplayer, Creativemode (most of the time, but in survival the bugs appeared too)
in all cases my Tardis had at least level 6 before these Bugs appeared.

After I rightclicked a control block in a room with the screwdiver, reconfigure mode, it locked all doors with me on the inside. after deleting the room to get free all doors from control room where locked too.

Sometimes if I delete a room and am ported back into control room, all doors out of it are locked like there whouldn't be a room behind it. I'm not entirely sure how to reproduce this but after generating and deleting 5 to 10 rooms I've had it in every savegame I played yet.
if a door is locked for whatever reasons and there's a room behind that door there is no way to open the doors again since there's no space to place another room (no matter if different or exact the same type of room)...

Of course it's possible to smash the doors in creative but after one of these Bugs appeared I've been teleported into a fully locked Controlroom and had to smash the Doors again every time I deleted any room. after "reopening" doors multiple times i've got every single door in the entire Tardis locked when the bug appeared again

**Comment by DarkholmeTenk** [comment]
Is this with the latest version on the jenkins?

**Comment by Soyaro666** [comment]
we are using Tardis Mod v0.98 from curse.com if that's what you want to know. downloaded and installed it (and your core) before not more than 48 hours

**Comment by DarkholmeTenk** [comment]
Shouldn't do; the door code doesn't touch the level code. Could you download the latest versions of both Darkcore and TardisMod from the jenkins at http://darkhol.me:8080 and see if you can replicate the bug?

**Comment by Soyaro666** [comment]
scenario I left: all Doors were locked, behind 2 of them were normal corridors, behind the third was nothing.
installed build 82 and loaded the savegame. all 3 doors from the control room were gone (even the one without anything behind it). i built that door in creative and tried do spawned a normal corridor. "not enough space".
created a new savegame. everything looked as expected (control room, 3 doors, nothing behind them). i spawned a normal corridor. all tree doors disappeared, the corridor was created but the door at it's end was missing too. tried to rebuild one of the doors from creative. "not enough space".

**Comment by DarkholmeTenk** [comment]
K. I'll look into it.

**Comment by DarkholmeTenk** [comment]
How 'bout now?

**Comment by Soyaro666** [comment]
bug fixed.

caution: a previously damaged savegame is still damaged! but after deleting 1 room all doors appeared like they should and the deleted room could be rebuilt without any problems. I suggest to delete and rebuild an empty room like a corridor - which room doesn't matter (had multiple damaged savegames to confirm that)

**Comment by DarkholmeTenk** [comment]
Happy times :)
