### ISSUE TITLE
[BUG] can't enter another Players Tardis

### ISSUE THREAD

**Issue by Soyaro666** [DarkholmeTenk/TardisModIssues#110]
Configuration: Vanilla Minecraft + Darkcore, Tardis and Waila, multiplayer (1 other player), Creative

Both of us spawned a Tardis. Even after I set my Tardis door to "open for all" he kept getting the message "You already own a Tardis".
I didn't try to enter his Tardis and we didn't try to spawn a second Tardis after we entered both in the first. We will test both cases soon and I'll add our results here.

**Comment by DarkholmeTenk** [comment]
"You already own a TARDIS" suggests he was right clicking on an exterior which wasn't linked to an interior. Are you sure that the exterior he was right clicking on linked to your TARDIS? Try flying to the same spot and see if it dematerializes/rematerializes correctly.

**Comment by Soyaro666** [comment]
before and after he got that message I've been able to enter and leave the Tardis using that exterior. but I'll try to reproduce it while testing the other two cases.

**Comment by DarkholmeTenk** [comment]
Very odd; is this over lan or with a proper server? Could be that the lan server works in a way that I didn't expect, maybe.

**Comment by Soyaro666** [comment]
it's been on a lan server. well, kinda - he opened it to the web through port fowarding. thats the way we test stuff usually. I'll suggest to use his root server with a new instance of our Infinity server package for our next multiplayer tests.

**Comment by DarkholmeTenk** [comment]
by lan server vs proper server, I mean is he launching his client and doing open to lan or is he launching the server jar :P

**Comment by micmou** [comment]
Another reason to have some kind of social system with friends and who is allowed inside you companion system :P

**Comment by FoxPotato** [comment]
You can port forward your LAN world if you didn't know. That's how I play with friends.
You open a LAN world, port forward the port with utorrent and then give your ip + port to your friend.

**Comment by Soyaro666** [comment]
well, we're using settings of his router to get the server online. but yes, in general its like FoxPotato said.
what I want to do: reproduce the Problem and test it in every direction (the different scenarios I named previously) at first in a LAN-Server and, if we can reproduce the problems, repeat the tests on a standalone server (the server.jar my other player already has running on his root server).

**Comment by DarkholmeTenk** [comment]
@micmou there should be nothing stopping people getting in your tardis, this is a bug unrelated to companions.

@Soyaro666 I like your plan, nice and sufficiently comprehensive :)

**Comment by micmou** [comment]
I know Dark I was being Facetious :3

**Comment by Soyaro666** [comment]
I weren't able to reproduce the bug while we were using the same configuration with newer builds. I guess this bug were a result of something else you changed/fixed the last days. nevermind...
