### ISSUE TITLE
[ENHANCE] Soulbound

### ISSUE THREAD

**Issue by FoxPotato** [DarkholmeTenk/TardisModIssues#111]
I think it would be a great addition to make the sonic screwdriver soul bound. Seeing as you can die in another dimension or really far away and easily lose your TARDIS. :p

**Comment by Soyaro666** [comment]
The screwdriver is enchantable with an enchantment book "Soulbound 1" from the Ender IO Enchanter (tested it a few seconds before this post).
but I'd support the Soulbound to be there by default. or at least a way to craft a calling device for the Tardis with resources you can easily get in the Overworld (which would make a lot more sense if the screwdriver would work with other mods too, but I'm losing the topic)

**Comment by FoxPotato** [comment]
I don't really like ender io so i don't have that achievement.
In my latest world i barely have any tech mods at all ;p

**Comment by DarkholmeTenk** [comment]
The screwdriver should work as a wrench for most mods; I removed bc support a while back because of a big refactor in BC, but I'll add it back in when I get time.

I'm going to work on a way to summon the TARDIS using overworld components, but I may add something similar to soulbound too.

**Comment by micmou** [comment]
So wait did you just say it works as a wrench as well <3 
Like an omni wrench...

Hmm also Dark if you have a statenheim remote it is built into the engine and as long as you are organically linked to your tardis it can find you. you could build the remote outside of the tardis and safely recall it with overworld items :D

**Comment by DarkholmeTenk** [comment]
In reconfigure mode, it should work like a TE wrench. It definitely works with EnderIO conduits and machines; it doesn't play as nice with railcraft engines, which I think is due to the lack of the IToolHammer interface.

**Comment by micmou** [comment]
Hmm well you should work on adding more wrecnh compatibilities to it then maybe RR will add it
RR Is Reasonant Rise :D

**Comment by laz2727** [comment]
I think you can make it a "wrench" tool for extra compatability. Unless
it's already is.

**Comment by FoxPotato** [comment]
It already is a wrench for some mods.

**Comment by DarkholmeTenk** [comment]
Except buildcraft

**Comment by laz2727** [comment]
I know.

**Comment by zach2639** [comment]
:3...idea:
i have a upgade post https://github.com/DarkholmeTenk/TardisModIssues/issues/187
 anyhow a (new added by this) tiny upgrade holder under the place you can
stick your screwdriver into on the temporary engines then stick a refill (this adds) upgrade in there and
if you loose your screwdriver you get a new one (consumes 20 more arton than normal) then you can summon your tardis with it (the recived one always gets the recall feature...but is one use then berecks)

**Comment by DarkholmeTenk** [comment]
Just use the TARDIS recaller :P

**Comment by zach2639** [comment]
what if you cant get one...my tardis went boom...yeh cant get new one nor do i think tardis recaller would work...
