### ISSUE TITLE
[BUG] /help broken

### ISSUE THREAD

**Issue by wrothmonk** [DarkholmeTenk/TardisModIssues#113]
It appears theres an issue with the /help when I have this installed. Trying to get page 3, 4, and 6 crashes the game. I've only installed the mod itself and the cores (COFH and dark) and there were no issues before tardismod was put in.

Crash log: http://pastebin.com/aLmMM7BU

Also this might be related or my information could just be out of date; /tardisLoad is apparently not a recognized command.

**Comment by DarkholmeTenk** [comment]
the command is /tardisload all lowercase; I'll look into it

**Comment by wrothmonk** [comment]
Looks like that was the issue with the tardisload command, still having issues with /help though.

**Comment by FoxPotato** [comment]
yup, /help 3 crashed my game. Haven't tried the other ones.
