### ISSUE TITLE
[ENHANCE] Models

### ISSUE THREAD

**Issue by FoxPotato** [DarkholmeTenk/TardisModIssues#116]
It would be awesome if you could actually connect the model TARDIS model to the item. Because 1, it looks nicer and 2, I've found a way to pick up my TARDIS in survival so it's possible to get the TARDIS block.
(That sonic blaster thing is really overpowered)

**Comment by DarkholmeTenk** [comment]
The sonic blaster shouldn't be overpowered for long (thanks to 1WTC)

I'll like the itemblock to the renderer tomorrow.

**Comment by FoxPotato** [comment]
thanks Dark ^^
