### ISSUE TITLE
[ERROR] There are no doors in the TARDIS.

### ISSUE THREAD

**Issue by Valiec** [DarkholmeTenk/TardisModIssues#117]
I am on build 83, and all the doors in the TARDIS are gone. The doorways that aren't connected to rooms open into space. This is not a chunk loading error! I walked out of one and would have fallen out of the world had the TARDIS not transmatted me back.

**Comment by Soyaro666** [comment]
He already know. it's happening since he tried to fix the doors locked bug i reported yesterday...

**Comment by FoxPotato** [comment]
Well idk if he know's about this because this sounds like a whole other problem. Like the exact opposite lmao

**Comment by Soyaro666** [comment]
read the report i've been talking about. there I informed him and he reacted so I guess he read about it ;-)

**Comment by FoxPotato** [comment]
My mistake, I didn't really care about that report so I didn't read it. I can't help people with coding bugs.

**Comment by DarkholmeTenk** [comment]
I'll fix it when I can, but I'm not going to be at my pc until tomorrow, unfortunately :P

**Comment by Soyaro666** [comment]
This door bug happens since Build 82 so my suggestion would be to use 81 'til the doors are fixed

**Comment by DarkholmeTenk** [comment]
May require building and removing a room to fix.
