### ISSUE TITLE
[Enhance] Craftable versions of all the tardis blocks

### ISSUE THREAD

**Issue by kurokuno** [DarkholmeTenk/TardisModIssues#123]
when building inside the tardis the inability to hide cables in a neat way because of the lack of creatable tardis blocks is a real put off for building

**Comment by DarkholmeTenk** [comment]
Probably won't end up doing roundels, but I may do the solid/flat blocks

**Comment by Soyaro666** [comment]
sounds good to me. I can't even think of a use for craftable roundels. In the Tardis there are enough of them and on the outside I would probably prefer using a landing pad and/or completely other systems that are handled easier...

**Comment by DarkholmeTenk** [comment]
Fun fact: If you place a landing pad in the TARDIS it Will draw energy from the TARDIS and act entirely like a roundel.

**Comment by FoxPotato** [comment]
Oh wow, is that on purpose or one of those things that just happened and you were like, eh why not.

**Comment by DarkholmeTenk** [comment]
Dun (DS branch)
