### ISSUE TITLE
[ENHANCE] new permission system

### ISSUE THREAD

**Issue by Soyaro666** [DarkholmeTenk/TardisModIssues#127]
in multiplayer everyone is allowed to recolor the interior even without permission to change the Tardis. right now that permission only means de-/generating rooms. For me this appears to be a bug...

**Comment by Soyaro666** [comment]
after another test I have to correct my post. Right now the permission affects the sonic screwdriver but nothing else

**Comment by DarkholmeTenk** [comment]
It also affects the engine, the roundels, the delete all rooms button...

**Comment by Soyaro666** [comment]
the roundels are opened by the screw driver so I meaned that too.
engine? do you meen the buttons to pay skillpoints or set aditional screwdriver abilities? I just hadn't them in mind in my original post. at least I didn't try to allow the other player to use them. I spent the skill points as soon as they were available ^^
the room deletion control is something I didn't ever use. It's something I would completely disable if I could (a config setting maybe?)
but back to topic. the permission to change the tardis should affect the feature to recolor blocks. otherwise at least one player on our server would change my rooms to pink if I ever let him in ;-)

**Comment by Soyaro666** [comment]
thought about it. I guess there could be aditional buttons with different permissions. you could place the roundels, the changeability of rooms (recoloring), the generating and removing of rooms and the usage of the room deletion control on separate buttons. got to this because I don't want one who's helping me with some machines to be able to restructure my rooms or destroy them all if he's mad...

**Comment by DarkholmeTenk** [comment]
Open an issue just for the coloring; I can fix that quicker than I can implement a big change like this.

**Comment by Soyaro666** [comment]
since something similar became topic in another thread: another permission button could un-/lock flight mechanics. so if one hasn't the permission he's not able to change coordinates or use the quantum handbrake. Maybe you could think about let those players help with pushing the glowing buttons of not (since they may not use the Tardis, maybe they don't even see the buttons glow and couldn't use them?)
And I think recall souldn't be affected by this since thats a screwdriver ability that can already be set. I would only suggest those screwdriver features are disabled by default and need to be activated like player permissions.

**Comment by DarkholmeTenk** [comment]
Done.
