### ISSUE TITLE
dimension energy requirements

### ISSUE THREAD

**Issue by Soyaro666** [DarkholmeTenk/TardisModIssues#130]
not sure if this is a bug or a feature.
I wanted to travel to another dimension that I hadn't add to the Dimensions.cfg (twilight forest, but that doesn't really matter) and got "Not enough energy to take off". My Tardis had 4000 energy and were level 8. seems like I'm not able to travel to any dimension that hasn't a minimum energy level in Dimensions.cfg which leads to an incompatibility with Mystcraft since every new Dimension needs to be noted in config before the Tardis can travel there.
Bug or feature, or does there exist a minimum energy requirement for unknown/undefined dimensions that I simply haven't reached yet?

**Comment by DarkholmeTenk** [comment]
Energy cost is calculated as ((energy cost of dest dim + energy cost of current dim)/2); if you haven't explicitely defined a dimension, it defaults to the TARDIS core's config value for "Dimension jump cost". However, being at full speed will multiply that cost by 3 and being at 0 will multiply it by 0.5 (although I'm about to remove that)

**Comment by DarkholmeTenk** [comment]
Check if it works as expected, now :)

**Comment by Durpady** [comment]
Care to try some Mystcraft integration?  Instead of defining a cost for each Mystcraft age, could you perhaps allow the player to specify a value for all Mystcraft ages?

**Comment by DarkholmeTenk** [comment]
I really don't want to be building in support for individual mods dimensions though; I'd recommend setting a fixed cost for all of your normal dimensions and then using the dimension jump cost to apply to all non-normal dimensions :P

**Comment by Soyaro666** [comment]
since it's been a feature I don't know why you changed anything. how does it work now? (btw: my jump didn't work because of max speed, according to your formula I had an energy requirement of 6000 which my Tardis hadn't available)

**Comment by DarkholmeTenk** [comment]
It now works by doing ((energy cost of dest dim + energy cost of current dim)/2) so it averages the energy costs. No calculation is done involving speed anymore because it's bloody annoying when you try to recall and you can't because the speed is too high.

**Comment by Soyaro666** [comment]
did some calculations. right now, with your default settings, it would cost 2500 Energy to reach the Nether (cfg says 3000), 3500 to reach the End (cfg says 5000). shouldn't the Tardis use the higher value instead of their average?

**Comment by DarkholmeTenk** [comment]
Fine.
