### ISSUE TITLE
[BUG] Cable Interface - Itemduct

### ISSUE THREAD

**Issue by Soyaro666** [DarkholmeTenk/TardisModIssues#131]
I have a Chest that I want to be automatically emptied through a landing pad. while I built it everything worked well. then I traveled to the Nether, collected some stuff and put it in that chest. Netherack got pulled in instantly but of course stayed in the wire system. later I returned to my landing pad and the netherack got pulled out but the tardis refuses to accept anything else since then. Netherack still gets pulled in and leaves the System as desired...

**Comment by DarkholmeTenk** [comment]
Sounds like the internal inventory doesn't have any empty slots

**Comment by Soyaro666** [comment]
thats true. but I can't pull any items out so they are empty and the tardis doesnt know or they aren't and my servo can't pull what's in which would be really strange since another servo (same item ID) must have put it in before

**Comment by laz2727** [comment]
Maybe they're full of zero stacks that don't get deleted properly?

**Comment by Soyaro666** [comment]
just to note: restarting didn't help either. but i've been playing with build 102 so I'll see how it works with 107 later. can't do any tests now, it's late for me and I have an important test tomorrow. I'll write as soon as I know if it works ;-)

**Comment by DarkholmeTenk** [comment]
Well if they were full of 0 stacks, that's what I changed in the commit above so it should fix it

**Comment by Soyaro666** [comment]
It still needed a little help. After I sent some Netherack trough it (5 stacks went in, 4 came out - nothing I would miss) it cleaned it's slots and were able to accept everything again. Well done!
