### ISSUE TITLE
[ENHANCE] TARDIS Lock Down Mechanism

### ISSUE THREAD

**Issue by Jwtc2000** [DarkholmeTenk/TardisModIssues#133]
A button that prevents the TARDIS from any movement (No Recall etc.)

**Comment by DarkholmeTenk** [comment]
I can guarantee you're going to turn this on and then complain when you can't recall

**Comment by Soyaro666** [comment]
doesn't it already exist? down at the engine, a landing pad lockdown?

**Comment by FoxPotato** [comment]
What would be the use of this? Like, if you don't want your TARDIS being recalled. don't recall it. ._.
and the landing pad lockdown decides if a landing pad is allowed to connect with the TARDIS, like pumping stuff in and out.

**Comment by DarkholmeTenk** [comment]
Think the idea is it's owner only and it stops others with your screwdriver or others in your tardis from moving it at all.

**Comment by FoxPotato** [comment]
I do like the idea of other people not being able to fly away. maybe make it a sonic function? so people can still recall if they're the owner ;D
Like that fixes the forgetting to turn it off when walking away or dying.

**Comment by DarkholmeTenk** [comment]
The door can be locked with an empty hand or anything that allows sneak right clicks, if you're on the inside. Key only on the outside, though.
With the permissions system, I'm calling this done :P
