### ISSUE TITLE
Experience System

### ISSUE THREAD

**Issue by Soyaro666** [DarkholmeTenk/TardisModIssues#134]
Not an Issue, just a question.
How does the experience System of the Tardis work? In uncoordinated flight mode with stabilizers activated it doesn't get experience at all, thats what I already know. More speed means more buttons and levers that need to be used and it seems to get more experience (or is that just my imagination?), but are there any other factors and how do they affect the experience gained?

**Comment by DarkholmeTenk** [comment]
Every button press is (speed+4) xp. Landing with stabilizers on gives 15 xp, landing without stabilizers on gives (45 - instability) xp.

Every successful button press subtracts (0.5*speed) from instability
Every missed button press adds (1*speed) to instability
0 <= instability <= 100

Speed is the speed on the lever before rooms are taken into account.

**Comment by Soyaro666** [comment]
"rooms are taken into account"? so I can lose rooms if instability is too high? or just space for new rooms?
thanks for the information so far. at least I seem to be a good pilot since I didn't experience something like that yet ^^

**Comment by DarkholmeTenk** [comment]
No, the speed you actually get is lower than max because of the number of rooms you have.
e.g. if you have max rooms, you can only ever actually reach half speed

**Comment by Soyaro666** [comment]
okay, sorry. for me it's around 7 in the morning, I'm not really awake yet
thanks again. so my only option is to keep flying uncoordinated without stabilizers on a low speed to have enough time for reaching buttons. I did expect distances of dimensional changes to affect too but since those define flight time in coordinated flight they kinda do. nice work!
