### ISSUE TITLE
Bigger Exterior,more schematics, Eye of Harmony room, heart of Tardis

### ISSUE THREAD

**Issue by TARDIS2016** [DarkholmeTenk/TardisModIssues#141]
It would be cool if it was possible to have all the rooms from "Journey to the Centre of the TARDIS" in schematic form.

**Comment by Jwtc2000** [comment]
#79 #64

**Comment by FoxPotato** [comment]
And ofc, you can always build them yourself. (:

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2420176-tardis-mod?page=4#c75

And the exterior is always gonna be 1x2x1

**Comment by DarkholmeTenk** [comment]
#149
