### ISSUE TITLE
[ENHANCE] Time Ram (sort of-ish)

### ISSUE THREAD

**Issue by Jwtc2000** [DarkholmeTenk/TardisModIssues#142]
Concept:
When TARDIS vs. TARDIS combat becomes a thing "ramming" your TARDIS into your enemys TARDIS could be a way of lowering their shields and then damaging their TARDIS itself eventually rendering their TARDIS for the most part disabled and forcing them to Emergency land.

Sounds #23 

http://www.whoniverse.net/tardis/timeram (sort of-isshh)

**Comment by FoxPotato** [comment]
"While the attacking TARDIS sometimes survives in a Time Ram, a more likely outcome is that both TARDISes will be destroyed, as well their Eyes of Harmony. This will result in the uncontrolled release of enough Energy to destroy most of a solar system."
I guess this is why you said sort of :p
But a combat system would be awesome tbh.

**Comment by micmou** [comment]
Umm so my suggestions are not good @FoxPotato XD

**Comment by FoxPotato** [comment]
I never said that?

**Comment by DarkholmeTenk** [comment]
Not useful until a combat system is implemented. Will consider it then.
