### ISSUE TITLE
[BUG] Decorative blocks.

### ISSUE THREAD

**Issue by FoxPotato** [DarkholmeTenk/TardisModIssues#144]
I think you messed something up. the floor in the console under the temporal engine consists of decorative blocks, which have no texture.
Black and purple squares galore \o/

**Comment by Soyaro666** [comment]
that's not completely right. this only affects the Tenthish control room. Main and Full don't have this bug

**Comment by FoxPotato** [comment]
Yeah he told me, And it's not really a bug either bc he's saving it or something

**Comment by Soyaro666** [comment]
imo it's a bug. as long as those blocks are used they are supposed to have a texture. they haven't so it needs to be fixed.

**Comment by FoxPotato** [comment]
It's on purpose tho, Dark is just lazy. Like the most of us gamers.

**Comment by DarkholmeTenk** [comment]
It's not on purpose, it's just going to be fixed with the console room redesigns :P

**Comment by Soyaro666** [comment]
redesigns? you mean additional designs I hope. anyway it sounds like good news ^^
