### ISSUE TITLE
[BUG] Crash

### ISSUE THREAD

**Issue by FoxPotato** [DarkholmeTenk/TardisModIssues#148]
I'm playing on a server, and whenever i left click animals with the transmat I crash "internal server error"
And there are no errors in the console.

**Comment by Soyaro666** [comment]
might be a permission conflict. had similar problems on my server. are you allowed to teleport other entitys? if not that could be the problem

**Comment by DarkholmeTenk** [comment]
Fixed already. Server isn't up to date with the jenkins.
