### ISSUE TITLE
[BUG] trouble with recent builds

### ISSUE THREAD

**Issue by Soyaro666** [DarkholmeTenk/TardisModIssues#150]
installed the recent builds (Darkcore 27 and tardis 125) on my girlfriends pc. since I haven't been around she had tardis build 90 installed. with build 125 she spawned in the overworld (which souldn't have happened since we saved in the tardis). a quick check showed: the Mod weren't loaded, nothing in NEI. I  downgraded her installation to build 124 (the last one I tried at home) and every block were available again. The game remembers for her Tardis but we have no way to get it back. a creative spawned screwdriver isn't linked to her so it isn't linked to her Tardis and since the Tardis already existed the key doesn't work to call it. Any suggestions?

**Comment by FoxPotato** [comment]
use "/treg list" and then "/ttp (tardis dimension id)"

**Comment by Soyaro666** [comment]
thanks. I came to the dimension. unfortunately since the savegame was loaded while I had no Tardis blocks installed the world is empty. beside the vanilla blocks we placed in there. walls, roof, floor, doors, controls, everything is lost...
at least this topic is an information for Darkholme. No idea why it happened but maybe he can find the reason.

**Comment by DarkholmeTenk** [comment]
Don't know if there's going to be a findable reason; all I can say is that I'm not sure when the colorable blocks were added and you could have switched from a version with normal blocks to the colorable blocks, replacing those with nothing when you installed a functional version of the mod.

**Comment by Soyaro666** [comment]
I installed and tested the colorable blocks on this PC so that can't be the Problem. (btw, this problem became hypotetical in the moment I found her backup folder but others may still get this).
The problem was: Minecraft didn't accept Tardis Build 125. in NEI by searching "tardis" nothing was found. key and screwdriver were erased from her inventory. and the tardis dim was cleaned from every block that was in the tardis. actually I weren't able to find Tardis in the ingame mod list. so at least something can cause minecraft to completely ignore build 125 what is a real problem when you used previous builds.
my configuration was FTB Infinity + Tardis build 125 + Darkcore build 27 when the problem occured. after a downgrade to tardis build 124 (still using core build 27) and restoring the savegame from her backup everything worked as expected. maybe with this information you can trace the problem...

**Comment by DarkholmeTenk** [comment]
what about 127?

**Comment by Soyaro666** [comment]
hadn't time before so I tested Build 128. No problems with that so whatever it was it got fixed.
