### ISSUE TITLE
[ENHANCE] Roundel Monitor (LookingGlassAPI)

### ISSUE THREAD

**Issue by Jwtc2000** [DarkholmeTenk/TardisModIssues#151]
A Roundel monitor to view the exterior from Matt smiths TARDIS using the [Looking Glass API](http://www.curse.com/mc-mods/minecraft/230541-lookingglass)

![StarshipUK] (http://i.gyazo.com/e40b99de540c60a77b0a5f732760e938.jpg)

**Comment by FoxPotato** [comment]
Holy shit

**Comment by Soyaro666** [comment]
that really would be an enhancement. if the looking glass mod does what it promises the tardis mod needs an option to enable it. maybe it could be a roundel interface thing that's only available if the lookingglass mod is successfully installed?

**Comment by FoxPotato** [comment]
Or just make it an requirement, and have it be on a certain level.
I mean, cofhcore was a requirement too for a while. So this can be one too.

**Comment by DarkholmeTenk** [comment]
Or you know, we could wait for xcompwiz to release the api and javadocs for looking glass (probably next weekend) before we start raving about it :3
It'll either be on the main door or on the landing sensor. (which may become a bit bigger to compensate) :P
I'll probably add a client side option for it, incase your pc can't handle it; other than that it'll be a case of if the mod exists, it will be used; if not, it won't.

**Comment by DarkholmeTenk** [comment]
Closed as there is not going to be a roundel implementation

**Comment by Soyaro666** [comment]
I think the landing sensor would be a better place since the original in tv show where around the controls and I don't like the Windows XP wallpaper that's currently shown there...
