### ISSUE TITLE
[ENHANCE] Moon/Sun in TARDIS ---> Eye of Harmony 

### ISSUE THREAD

**Issue by Jwtc2000** [DarkholmeTenk/TardisModIssues#152]
Is it possible to replace the sun/moon in the TARDIS to look like a Eye of Harmony?
Like an enlarged more angry looking sun texture of some sort? (lol)
(Not trying to be lore friendly)

![Eyeofharmony] (http://img4.wikia.nocookie.net/__cb20140311172106/tardis/images/b/bc/Eye_of_Harmony_JourneyCentreTARDIS.jpg)

<sub><sup>Teletubbies Tax</sup></sub>
<img src="http://i.imgur.com/xhVvJ.png" width="50">

**Comment by micmou** [comment]
@Jwtc2000 Not really as if i remember correctly the soon and moon is the same between all of the worlds. Also the eye of harmony is a black hole and outside the interior of the tardis is not really possible technically when you look outside the tardis you are looking at the exterior hence why no windows in the actual show. So a black hole or if you want to be specific a frozen star would have to be kept in a containment shield like the actual iris of the eye of harmony :D 

Tardis Expert at your service BTW not to many people can out Tardis me.

**Comment by Jwtc2000** [comment]
I know that it's not actually like this in the show but I don't see the point of having a giant room dedicated to it.

**Comment by FoxPotato** [comment]
It is not actually a black hole tho, it's a star thats on the verge of becoming a black hole

**Comment by Jwtc2000** [comment]
Also GalacticCraft was able to change the sky in different dimensions, so I don't see why Dark couldn't do it if he wanted to

**Comment by Soyaro666** [comment]
beside galacticraft there is also the possibility to add multiple suns/moons to a mystcraft world so they simply are objects that are added. other objects could be added too. The problem I see would be a Button that wouldn't have any function if sun and moon are replaced by the Eye of Harmony since it does toggle day- and nighttime. how should it behave? like a sun (permanent daytime) or like a moon (permanent nighttime) or should it replace both (so the toggle would still be working and switching the different lightlevels the eye emits)?

**Comment by FoxPotato** [comment]
You can even change the skybox, it's possible with optifine and a resourcepack.
And that's a good question. I mean, a giant sun would be awesome, but some people might like having a moon.
(i dont see why, having day time fixes lighting bugs and gives free energy)

**Comment by Jwtc2000** [comment]
I was thinking that one mode would be the Eye of harmony but dark and the other light as if it was day, So the toggle option would still be there

**Comment by micmou** [comment]
@FoxPotato Exactly why I called it a frozen start

http://en.wikipedia.org/wiki/Frozen_star_%28hypothetical_star%29

**Comment by Soyaro666** [comment]
so it should be switchable. I could get used to it I think. but I would prefer it to be an object in a specific room instead of an object in sky...
FoxPotato, night can become important if you're playing with witchery and want to become a vampire.

**Comment by FoxPotato** [comment]
ah yes ofc.
But still, that's one of the only pros i can think of of having a night sky. except aesthetics.

And idont think the eye of harmony is 0 degrees celcius.
I mean the sun in journey to the heart or centre of the tardis or whatever, you know what episode i mean, it would've killed them if they stayed too long in that room. And if you've seen that episode, you know what it did to those people. I think we can safely assume that that star isn't frozen, except in time ofc.

**Comment by micmou** [comment]
Actually I meant that a start that because of the solar disk plane expanding could not collapse into a blackhole therfore the start is frozen between the state of star and blackhole perpetually collapsing until the heat death of the universe. Hence the name frozen star as it is stuck in a state of collapse. Which is what the Eye of Harmony is...

**Comment by DarkholmeTenk** [comment]
Well your wikipedia link is just a star that's ended its main sequence with a temperature approaching 0K, which has nothing to do with black holes.

http://www.whoniverse.net/tardis/infrastructure suggests there is an outside to the rooms

www.whoniverse.net/tardis/tardiseye suggests actual black hole :P

Either way, not going to change the skybox; it's just a projection of the sky, not an actual exterior.

**Comment by micmou** [comment]
@DarkholmeTenk 

The Endo-Sphere is thought to be unobservable until there is something in it...

Also if you want to get really incredibly technical about it The Heart Of The TARDIS is not the Eye of harmony it is a block transfer mathematical mass copy of the potential naked singularity predicted to be contained in the eye once it finally collapses that connects to the original eye of harmony on galifrey absorbing energy through chrono conduction channels. The doctor some how in the new series acquired the actual eye of harmony that was designed by Omegah the chief interstellar engineer around point zero when the Time Lords Ascended to the temporal plane of thought or noosphere knowledge and there are even things time lords are incapable of doing that other more advanced species can do IE the great ones and the vampire kings
