### ISSUE TITLE
[ENHANCE] TARDIS Handbook

### ISSUE THREAD

**Issue by Jwtc2000** [DarkholmeTenk/TardisModIssues#153]
In-Game Manual
--------
<sub><sup>Sort of like #85</sup></sub>

An in game manual of sorts in book form on things like Flight,Roundels,Circuits etc.
(Basically the GitHub Wiki In Book Form)

Should be given to player upon entering their TARDIS for the first time.

Crafting Recipe
-------------------------------
Chronosteel + book = Manual
<img src="http://i.imgur.com/JV1uSnf.png" width="100">

<img src="http://www.whoniverse.net/sites/default/files/tardis/manual.jpg" width="150">

**Comment by micmou** [comment]
or my suggestion of the Index File system but he already told me maybe in game documentation definite updated wiki

**Comment by Soyaro666** [comment]
while a book is a common idea since Tinkers Construct, Botania, Thaumcraft etc are using it I don't think it will come to Tardis mod because Darkholme doesn't like GUIs.

**Comment by Jwtc2000** [comment]
![OkThen] (http://i.imgur.com/JYwRKcS.png)
