### ISSUE TITLE
[Enhance] Shields/Explosions ideas

### ISSUE THREAD

**Issue by wrothmonk** [DarkholmeTenk/TardisModIssues#155]
I've come up with a couple ideas for when/if you implement a damage system for the explosions.

1. Explosions can change the coordinates of your landing site. For example each explosion could change one value at random (X Y or Z) by a random amount in a range (change X/Z from -100 to +100, y from -10 to +10). 

2. Sort of an addition to the previous idea; allow the player to change the landing coordinates mid-flight. Essentially this would allow players to counteract the explosions throwing them off course, provided they notice.

3. Add in a Tardis repairing cycle such as seen in The Eleventh Hour. After shields are depleted each explosion would add time to a repair cycle. Once the tardis lands and the player leaves the tardis, the tardis door becomes locked and won't open until the repair cycle completes. 

I'd recommend adding in a point where the tardis is forced to land (or crash) once the repair cycle reaches a certain amount of time, just to prevent players from not being able to access their tardis for a long period.

**Comment by Soyaro666** [comment]
guess the third idea would lead to many bug reports. I think while damaged Tardis simply can't start sounds better. with an element on the console showing how much damage has to be repaired before it's flyable again.

**Comment by wrothmonk** [comment]
I don't think the third idea would cause people to think it was a bug as long as its handled right. I was thinking there would be a specific error message saying the tardis is repairing when you try to enter it and have some warning before leaving a tardis that needs to repair.

**Comment by TARDIS2016** [comment]
what would be cool is  while the damaged TARDIS is repairing, the Cloister Bell would be going off signaling to the player that his/her TARDIS is damaged and is going through the repair cycle.

**Comment by wrothmonk** [comment]
I had completely forgotten about that bell. Come to think of it that would serve as the perfect indication for the tardis being repaired.

**Comment by TARDIS2016** [comment]
yeah I think it would be really cool. But what would be even cooler would be a Cloister Room that could be the source of the sound for the Cloister Bell

**Comment by Jwtc2000** [comment]
Some sounds       #23

**Comment by Jwtc2000** [comment]
https://www.youtube.com/watch?v=wLd7PhJMkTA   loolol

**Comment by FoxPotato** [comment]
Now that, is what I call quality.
10/10 would watch again

**Comment by TheAmazingSpy** [comment]
Another thing, how about you can reconfigure a roundel and then use a wrench or something for a repair of 10% and the console can be opened and I don't know, inspect the wring? For a repair of 50% and then if say I repair it through the console when it has 60% health, it will supercharge the TARDIS

**Comment by FoxPotato** [comment]
repairs will be handled on the engine. on the iirc still empty panel.

**Comment by TheAmazingSpy** [comment]
What does the iirc mean? And stop commenting on my posts, it's like your trying to put me down by making my ideas sound bad. I only started yesterday or something, so please stop.

**Comment by FoxPotato** [comment]
If i recall correctly, and I'm not targeting you. I'm emptying out my notifcations, you're just posting alot :p

**Comment by TheAmazingSpy** [comment]
Oh, sorry, I'm just full of ideas, need to burn them off to put some space in my head

**Comment by TheAmazingSpy** [comment]
Why does every revolve around the empty panel on the engine? Man, not everything is through the engine.

**Comment by FoxPotato** [comment]
Because it's(was, actually) empty and it needed something.

**Comment by TheAmazingSpy** [comment]
How about if it's on multiplayer, a bit of a novelty idea, if one TARDISes shields are down enough, another TARDIS has a 1 in 100 chance of materialising inside the TARDIS with the low shields. This is based off 'Time Crash' where the Tenth and Fifth Doctors meet up because Tenth had to take down the shields. And also, if this happens, after 5 minutes your TARDIS will explode. And please add a cloister bell

**Comment by FoxPotato** [comment]
It sounds cool-ish. But chances are it won't happen. 

A cloister bell woud be really really nice tho.

**Comment by DarkholmeTenk** [comment]
DS branch has this now.
