### ISSUE TITLE
[ENHANCE] Proxy blocks

### ISSUE THREAD

**Issue by AlienXtream** [DarkholmeTenk/TardisModIssues#157]
NOTE: dark, if this is the wrong place for suggestions then plz reply with a link to the correct place

hey dark, i just had an idea that would eleminate the issue of free resorces from schema's with mineable blocks in them. you could use a "proxy" block. a creative only block (with stair/slab variant) that uses the flat block texture but rightclicking with certain items changes the texture, much like the coloring of blocks. it would only work for spesific blocks, an example would be Book=bookcase, Brick=bricks glass=glass. additionaly you could use the coloring feature with them to hue the blocks texture. i say this cos i built a library and had to use bookcases in it and then (in another post) saw you say the library was planed but without books. doing this would grant the best of both worlds :) what do you think dark? yes? no? mabye? :P

**Comment by FoxPotato** [comment]
This is the place for suggestions, just put an [ENHANCE] in your title (:

**Comment by AlienXtream** [comment]
thx Fox :) anyaway, what you think if my idea?

**Comment by FoxPotato** [comment]
well, kinda mixed opinions. I like the idea of blocks already in the library and such, but I also like the idea of having to fill rooms yourself :p

**Comment by Jwtc2000** [comment]
I think being able to fill the rooms your self adds customizability  v.s. it all being the same

**Comment by AlienXtream** [comment]
no no no, you misunderstand. it would be no different from dyeing the blocks, just instead of a color it applies a texture. lets say i want to make a library using one of the existing rooms and i want the walls to be wood. normaly this would be impossible without going into creative and replacing the existing blocks but with my idea you would just "dye" the blocks to LOOK like oak wood :) (of course the consumption of the item would be optional via config like the dyeing)

**Comment by DarkholmeTenk** [comment]
Still limits the customizability though, imo, if there are unbreakable blocks in set places
