### ISSUE TITLE
[OFF TOPIC] My Lifetime Project

### ISSUE THREAD

**Issue by TARDIS2016** [DarkholmeTenk/TardisModIssues#158]
I realize this is for Tardis Mod issues but I want to tell everybody about my project I am going to embark on. I hope this post does not get closed the moment I post this but I will go ahead and say this. I am embarking on building or "growing" a real life working TARDIS. Although it would take years and years, I want to do it. I will need a bunch of people on my team to help me design a way to grow the TARDIS. I want everyone's opinions and comments.

**Comment by laz2727** [comment]
gl/hf.

2015-05-26 22:22 GMT+06:00 TARDIS2016 <notifications@github.com>:

**Comment by DarkholmeTenk** [comment]
Sounds fun, but not relevant :P

**Comment by micmou** [comment]
@TARDIS2016 I have a impossible time taking you serious at all...

A tardis is a fictional object that is made up if you believ in any way that what I have described in this github in any issues relevates to actual science well umm...

Not so serious note 

To start bring me a star and enough energy ohh say 300,000 atomic bombs and I will teach you how to grow a functional type 105 :D
