### ISSUE TITLE
[BUG] Temporal Dirt

### ISSUE THREAD

**Issue by FoxPotato** [DarkholmeTenk/TardisModIssues#159]
When growing a rubber tree from mfr on tempral dirt it deletes the dirt.
maybe it's somethin you added, but pretty sure it's a bug.

**Comment by micmou** [comment]
@FoxPotato Function of MFR to replace the dirt with another piece of wood

**Comment by FoxPotato** [comment]
Dark told me all trees do this, He has no idea what's causing it.

**Comment by DanNetwalker** [comment]
Still happenng with all vanilla trees and some mod plants (Extra Utilities' ender lilies), on Minecraft 1.7.10 and Tardis 0.985-178. 

It was fixed and reappeared? Maybe it should be changed to only allow crops and not trees...

**Comment by DarkholmeTenk** [comment]
Definitely not still happening with vanilla trees; I have an automated tree farm powering my logistics system running on 1 block of temporal dirt with mfr harvester and planters.
Ender lilies I can't do much about, temporal dirt runs the bonemeal code on crops which kills ender lilies. Also ender lilies require a day night cycle to grow, so you can't grow them in the tardis anyways.
The latest version on the jenkins is tardismod-1.7.10-0.99-220.jar so you're quite a bit behind (and the latest version of darkcore fixes the mob transmat issue) :P
