### ISSUE TITLE
[ENHANCE] Screwdriver Mode: Craft

### ISSUE THREAD

**Issue by Lightwave413** [DarkholmeTenk/TardisModIssues#160]
opens a crafting table when used.  It'd be a useful little feature.

"They're screwdrivers!  What are you going to do?  Assemble a cabinet at them?"

**Comment by DarkholmeTenk** [comment]
GUIs! Blasphemy!
https://www.youtube.com/watch?v=znGBU5oODz8

**Comment by Lightwave413** [comment]
Since when do Daleks have a concept of Blasphemy?

Anyways, I thought the GUI thing would be negligible considering that the crafting table GUI is vanilla.  But I understand your desire to keep your mod GUI-Free.

**Comment by FoxPotato** [comment]
you could always install I think translocator, it adds a crafting table which you can place with like a keybinding. its just a simple grid drawing like thing on the ground :)

**Comment by Soyaro666** [comment]
or talk to Darkholme to add the feature FoxPotato described as a Screwdriver mode...

**Comment by FoxPotato** [comment]
That would be blatantly copying another mod tho, if he found another way that would be awesome. but i dont think its nice to steal ideas directly from other mods.

**Comment by Soyaro666** [comment]
what about a Keybind mode? in settings there could be set a key that's pressed. with that and theother mod you could use a 3-key-combination to place a crafting field and that combination could be set in the screwdriver. It would be possible but I don't think Dark would do it because it isn't Tardis-Related... ;-)

**Comment by FoxPotato** [comment]
I don't think he won't add a keybind sonic function because it's not tardis related. but most likely because it's already on a key so why would you need it on your sonic??

**Comment by Soyaro666** [comment]
maybe because one is too lazy to learn all key bindings his modpack needs...

**Comment by FoxPotato** [comment]
even then, you could just go to controls. Having keybinds on the sonic will just clog it with functions

**Comment by DarkholmeTenk** [comment]
Yup, sonic is not getting keybinds anytime soon. I may restrict sonics to only having a maximum number of functions at a time.
So then I could add more functions but you'd only be able to select from like 5/6 at a time.
Either way, definitely not copying translocators.
