### ISSUE TITLE
[ENHANCE] Creative Leveling Item

### ISSUE THREAD

**Issue by Lightwave413** [DarkholmeTenk/TardisModIssues#161]
Creative-Only Item that, when used inside a Tardis, will increase that Tardis's Level by 1.
Maybe also have it as very rare loot?

**Comment by DarkholmeTenk** [comment]
Why not just use the /txp command?

**Comment by Lightwave413** [comment]
Because I didn't know about it.  I apologize, I'm new to this mod.
I still think it might be a neat find as rare loot.

**Comment by DarkholmeTenk** [comment]
I concur, that may get added eventually :)

**Comment by epicnesslol** [comment]
sounds good too...but 1 use ONLY (mabey more but that would be SOOO op if it was ∞)

**Comment by epicnesslol** [comment]
wait...EVEN BETTER there is diffrent lvls as lvls go up rarity does to... R=LX2
R=rarity
L=lvl
