### ISSUE TITLE
[BUG] recall in tardis = crash

### ISSUE THREAD

**Issue by AlienXtream** [DarkholmeTenk/TardisModIssues#163]
i know this was an issue once before and it was "fixed" by disalowing the selection of recall mode whilst inside the tardis BUT there is a way still to do it. if, while outside the tardis, i select recall when entering the tardis it retains its setting. i suggest ether intercepting the recall function if activated inside the tardis pushing a chat message something like "[Tardis] Cannot Materealize here!". alternativly have all sonic screwdrivers that are in the inventory/picked inside the tardis get set to reconfigure mode (default) i know its a low priority issue since you would have to be a total derp like me to do it more than once, and the crash isnt world breaking so it dose no harm beyond an inconvinience but...a bug is a bug and so im reporting it :P

**Comment by FoxPotato** [comment]
thats what it does, you can have the setting inside the TARDIS but if you right click it gives you a message.

**Comment by AlienXtream** [comment]
ok, must have used an older version without realizing. that's what happens when you mess with mods that get frequent updates :P

**Comment by AlienXtream** [comment]
also, i have NO idea how to close github posts...

**Comment by FoxPotato** [comment]
write a comment and then next to the comment there is a comment and close button :p

**Comment by DarkholmeTenk** [comment]
Fixed already, a while back, iirc
