### ISSUE TITLE
[ENHANCE] Codex

### ISSUE THREAD

**Issue by FoxPotato** [DarkholmeTenk/TardisModIssues#164]
Well, all the pictures in the codex have like stripes to make it seem like a sort of screen. but the text doesnt? I guess it's like a font, but maybe you could kinda change the font to make it not seem so out of place.

**Comment by Jwtc2000** [comment]
I thought the text did have the lines :question:

**Comment by FoxPotato** [comment]
nope, I just checked again. better safe than sorry :p

**Comment by Jwtc2000** [comment]
Also it should have animated lines sort of like the James Bond N64 Watch https://www.youtube.com/watch?feature=player_embedded&v=suCfg6PXLaI#t=48

**Comment by Jwtc2000** [comment]
bzzz bzzzz
bzzzzzzzz

**Comment by FoxPotato** [comment]
I think that's what he was going for, the retro screen look. :p

**Comment by DarkholmeTenk** [comment]
Problem is the text on the left is rendered where the text on the right is part of the image with the overlay :P

**Comment by FoxPotato** [comment]
There must be a way to have like a custom font right. Or you could have a second layer or something over the text.

**Comment by DarkholmeTenk** [comment]
More effort than I can be bothered mustering; will probably just disable the scanlines

**Comment by FoxPotato** [comment]
... that works, I mean. It's a time machine I don't think it would have less than crystal clear screens ;'D
