### ISSUE TITLE
[ENHANCE] Travel distance meter

### ISSUE THREAD

**Issue by Barbrule** [DarkholmeTenk/TardisModIssues#165]
Maybe add some sort of meter or screen that will tell you around or exactly how far you have to your destination. Requires level 15 or something and gets more and more accurate as you level up. 
![image of Travel screen](http://i.imgur.com/4px2OFi.png)

**Comment by Jwtc2000** [comment]
I think it would make the TARDIS a bit less TARDISey, I feel that you should land when you land. *shrugs*

**Comment by DarkholmeTenk** [comment]
Not done yet

**Comment by Soyaro666** [comment]
maybe you could use it to replace the message you get when you click on the sensor while flying? I know I can't see my coordinates while flying so right now that display is useless most of the time...

**Comment by DarkholmeTenk** [comment]
Whoops, forgot to close

**Comment by Soyaro666** [comment]
okay, that's a good looking solution. totally forgot that display from the show ^^

**Comment by DarkholmeTenk** [comment]
It's even better when you realise it replaces the destination guessing chat spam :)

**Comment by Soyaro666** [comment]
does it show the destination coordinates too? and does it need a level to appear?

**Comment by DarkholmeTenk** [comment]
The ETA requires a level; the screen does not. Play around with it :D (or look around my imgur ( http://darkholmetenk.imgur.com/all/ ))

**Comment by Soyaro666** [comment]
"DarkholmeTenk's images are not publicly available."
I'm allready downloading your update so it doesn't matter

**Comment by FoxPotato** [comment]
http://darkholmetenk.imgur.com/
just remove the all :p
