### ISSUE TITLE
inaccurate room counter

### ISSUE THREAD

**Issue by Ying12** [DarkholmeTenk/TardisModIssues#167]
the room counter thing thinks that I have 30 rooms when I have 5-10 I put some levels into upgrading my room capacity but after a bit it decides that it is full or close to full. Is this just happening to me or are others getting this as well?

**Comment by DarkholmeTenk** [comment]
Are you using the latest version from the jenkins?

**Comment by Ying12** [comment]
thanks it seems to be working

**Comment by DarkholmeTenk** [comment]
Cool
