### ISSUE TITLE
[ENHANCE] Add wrothmonk's Schemas

### ISSUE THREAD

**Issue by Jwtc2000** [DarkholmeTenk/TardisModIssues#169]
http://www.minecraftforum.net/members/wrothmonk
+
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2420176-tardis-mod-updated-to-v0-9825-on-17-05-2015?comment=674

![1] (http://i.gyazo.com/cb8343fe81603240d2b78180c6e1ec23.png)

![2] (http://i.imgur.com/t0dg9m9.png)

Replace iron bars w/ some kind of fence?

**Comment by FoxPotato** [comment]
his schematics are indeed hella good.

**Comment by micmou** [comment]
Ohh hell yes please Dark :D

**Comment by Jwtc2000** [comment]
Just realized that he would have to make that shape of console room the same for every theme... hmmmmmmmmmm

**Comment by Soyaro666** [comment]
hm? @Jwtc2000 
why should he? this one as a fourth control room shema would work. or as a 3rd since the pre-colored shema is damaged because of missing textures... I'm worried more about the missing gateways to the sides...

**Comment by wrothmonk** [comment]
I'm flattered that anyone would suggest this.

Also @Soyaro666 What missing textures are you referring to? I don't see any myself when loading it in, otherwise I would have fixed that. As far as the missing side gateways go I left them out because the interior of the actual (tv) console room doesn't have doors there. I could easily make a variant that includes them.

**Comment by Soyaro666** [comment]
@wrothmonk last time I checked the Tenthish shema had missing textures on the lower floor. that's what I referred to

**Comment by wrothmonk** [comment]
@Soyaro666 Could you send me some screenshots then of exactly where? Again I can't seem to find them myself. Just PM me on the minecraft forums.

**Comment by Soyaro666** [comment]
"last time I checked" was weeks ago. the problem got solved I guess. I don't really like Tenthish so maybe it got fixed and I simply don't know. If it would still be there you wouldn't need any help to find it, it affected the whole floor down there ^^

**Comment by FoxPotato** [comment]
It didn't affect the whole floor, just the floor surrounding the engine. like just a ring. But yeah it got fixed like a week ago I think.

**Comment by DarkholmeTenk** [comment]
These can now be uploaded to TFPP [ http://foxpotato.com ]
