### ISSUE TITLE
[Enhance/Fix] Mass coloring annoyance

### ISSUE THREAD

**Issue by Nihilumbra** [DarkholmeTenk/TardisModIssues#170]
If there is a way to toggle the fill area when jumping mechanism (button on console/ temporal engine); currently flying counts as jumping and its very annoying to try to design the tall rooms.

**Comment by DarkholmeTenk** [comment]
that mechanism's handled outside the TARDIS mod, it's handled inside Darkcore; I can make it only happen when jumping and not flying, if you'd prefer :P

**Comment by laz2727** [comment]
Have you tried holding both shift and space?

2015-05-29 14:46 GMT+06:00 DarkholmeTenk <notifications@github.com>:

**Comment by DarkholmeTenk** [comment]
Shift asin sneaking means nothing happens; shift clicks using ItemDye do not get passed to the block. For some unknown reason, Mojang decided the default is for shift clicking with an item is for it to not pass anything to the block at all :P

**Comment by Nihilumbra** [comment]
Eh doesn't matter to me i'd be happy with a command, you do it however you think you need to or however works
