### ISSUE TITLE
[ENHANCE] screen

### ISSUE THREAD

**Issue by FoxPotato** [DarkholmeTenk/TardisModIssues#171]
Maybe instead of the text TARDIS data screen have the blue screensaver thing that the 10th doctor had.

https://www.youtube.com/watch?v=b4rMdyd6SvU

**Comment by Soyaro666** [comment]
the video looks very good, no question. well, it has milions of pixels. how could it look in minecraft? It would need a full redo that fits into minecraft graphics. and it would need a lot of code to allow minecraft to play videos. too much work for one single screen I think...

**Comment by FoxPotato** [comment]
Well, it's not possible. the render system for the block is different than normal blocks so animated textures won't work.
But I ain't giving up!
