### ISSUE TITLE
2 ideas (first mid travel stop,second is starting away from counsole

### ISSUE THREAD

**Issue by epicnesslol** [DarkholmeTenk/TardisModIssues#172]
make it so that you can stop in mid flight,and when you do,if you can alredy,make it so that you stop in the middle of space, and if you tie a lead on your sonic then on the start lever when you power it it cuts the rope and it starts the tardis up (the second idea i want because i have stabelizers for my lab and everything but...most of my flights are only a few seconds...not enof time to get to my lab and make some stuff so)

**Comment by FoxPotato** [comment]
1. already possible to stop mid flight and land. 2. use drifting mode. or put a battery that's on flying mode next to it :)

**Comment by epicnesslol** [comment]
1. i said "and if you can already,make it so that you stop in the middle of space"
2.witch one is flight

**Comment by Soyaro666** [comment]
to "stop in the middle of space" you can simply activate "drift mode", like FoxPotato said. thats drifting through the Time Vortex without a pre-set destination so without a place to leave the vortex automatically. that works fine for my lab too...
try around with the battery. it has 3 modes, place some iron in your lab and toggle the modes, the one your lab starts to work with should be flight mode I guess...

**Comment by DarkholmeTenk** [comment]
The uppy downy one and the spinny all the same wayey one are the flight ones.

**Comment by epicnesslol** [comment]
this is all i have for a manule http://tardismod.com/

im gussing its theinfanate flight mode one?

**Comment by FoxPotato** [comment]
place down the library schematic. it has a TARDIS codex which has a more updated flight manual :)

**Comment by zach2639** [comment]
???

**Comment by Soyaro666** [comment]
you can build the room "library", there you will get instructions for every button the console has. now sou should find it

**Comment by DarkholmeTenk** [comment]
If you use the build from the jenkins, you even get info on the landing pads and stuff
