### ISSUE TITLE
[BUG] destination change

### ISSUE THREAD

**Issue by Soyaro666** [DarkholmeTenk/TardisModIssues#173]
my test: I set every lever and wheel to maximum, absolute coordinates, and started. on around 70% distance I switched to uncoordinated flight, switched to relative coordinates and swiched back to coordinated. It kept it's speed so it did what I wanted, but surprisingly it started from my last position in overworld so my destination didn't change a lot but I had to fly the whole distance again.
I expected it to recalculate the new flight based on my current position or current flight or anything like that...
suggestions to remove this behave: the easiest way would be to simply set my destination as new start point and add the remaining flight distance to the new distance. the most accurate way would be to recalculate my current position based on the percentage my tardis already moved. of couse this doesn't need to calculate the exact position since the tardis keeps it's speed while in uncoordinated flight.

**Comment by DarkholmeTenk** [comment]
That should be done already; the problem is probably the relative coordinates switch

**Comment by DarkholmeTenk** [comment]
Been looking into this. Are you sure you had to fly the whole distance again? The distance travelled gets set to 0 when switching from drifting to normal, but it recalculates the start position before it does that, so the distance to travel should be less than before.

**Comment by DarkholmeTenk** [comment]
``` java
        SimpleCoordStore newStart = null;
        TardisTileEntity ext = gDS().getExterior();
        if (ext != null)
            newStart = new SimpleCoordStore(gDS().getExterior());
        else if ((sourceLocation != null) && (destLocation != null)) newStart = sourceLocation.travelTo(destLocation, distanceTravelled / distanceToTravel, true).floor();
        if (newStart != null)
        {
            ConsoleTileEntity con = getConsole();
            if (con != null)
            {
                fast = (con.shouldLand() && isFastLanding());
                sourceLocation = newStart;
                destLocation = con.getCoordsFromControls(newStart);
                distanceToTravel = sourceLocation.distance(destLocation);
                distanceTravelled = 0;
            }
        }
```

Is the relevant code. As you can see, if there is no exterior and there is a destination, it takes the distance you've travelled and should calculate the new start point from that.

**Comment by Soyaro666** [comment]
imo this issue is unimportant. The Tardis reaches the destination and shouldn't need to travel much longer than without this issue unless you're traveling really far.
But yes, according to your quote it uses the percentual progress of the current flight to calculate the new start.

well, it looked like my start coordinates were simply added to my destination coordinates since before and after changing to relative mode the destination coords were nearly identical.
Could it simply be the coordinate guesser on x side, that didn't get the new start coordinates for it's calculation? I never checked where I finally arrived tbh. I was experimenting with the speed and didn't care for my actual destination ^^

**Comment by DarkholmeTenk** [comment]
Oh, it's just the coordinate guesser that's got the issue? In that case, it could be because the recalculation is done when you switch from drifting to normal flight.

**Comment by Soyaro666** [comment]
well, I checked the destination after resuming my flight because I was confused about percentage and time on screen. I don't know where it get's its coordinates from. maybe it's using the origin start for its prognosis?
