### ISSUE TITLE
problem with dim selection

### ISSUE THREAD

**Issue by Soyaro666** [DarkholmeTenk/TardisModIssues#174]
testing build 148 with multiple other mods (added Galacticraft and 4Space, maybe those are the problem) and now I'm not able to select the Overworld. I can set the lever in the correct position but the display get's no update (so the last selected dimension is shown as destination). my workaround is to set the lever to any other dim and load the coordinates where i saved the spawn (fortunately I always save that coordinates first).
Could this be a bug or just an incompatibility with Galacticraft?

**Comment by DarkholmeTenk** [comment]
You can select the overworld, put the dim lever to the top and twiddle one of the other levers. This has been a bug for a while, you've just never noticed it before :3

**Comment by Soyaro666** [comment]
Galacticraft adds Dims that are placed "above" Overworld. below it I have the End, above it I have Moon. and starting with the wrong information on screen sets destination to the wrong dimension even if the lever is on the correct position. and no, that bug never happened to me before. I usually tripple-check my destination before starting...

**Comment by DarkholmeTenk** [comment]
Either way, if you put your dimension lever to the correct position and then move any of the other y levers, it seems to fix it :P
Still looking into it though

**Comment by DarkholmeTenk** [comment]
Latest version plox :)

**Comment by DarkholmeTenk** [comment]
Closing; assuming it's fixed since no complaints.

**Comment by Soyaro666** [comment]
sorry, had no time to test yet...
edit: yep, seems to be fixed

**Comment by DarkholmeTenk** [comment]
If it still has the problem when you test, let me know :)

**Comment by Soyaro666** [comment]
thats what I meaned in my edit, sorry if I weren't clear about that. It's been working. I checked it again after my edit, with and without actually flying to destination dim, and it worked like it should so everything is fine
