### ISSUE TITLE
[ENHANCE] clock

### ISSUE THREAD

**Issue by Soyaro666** [DarkholmeTenk/TardisModIssues#175]
Since the Tardis is a time machine it's annoying to have to leave the Tardis to know what time it is right now. isn't it supposed to show the time (or at least the daytime) from the outside in any way?

**Comment by FoxPotato** [comment]
Once looking glass is out and ready to use We will be able to see the outside without actually leaving the TARDIS. This will allow live video from outside :)

**Comment by Soyaro666** [comment]
yep, and it will be an enhancement on it's own, but right now I'm only interested into the current time because of my survival savegame ^^

**Comment by FoxPotato** [comment]
A config option to sync the dimension with the outside would be awesome, maybe impossible maybe not, but still awesome.
Or just a scanner thing yeah.
But there isn't any danger of going outside to check. If you get hit instantly you get transmatted back inside, and if you die inside the transmat radius you get teleported right before you die.

**Comment by Soyaro666** [comment]
cool. didn't know any of these. well, I managed to spawn in lava once so I got damage but I didn't tp back inside...
and if I fall out of the world, what happens? (possible in The End, skyland worlds / floating islands from Mystcraft or the Asteroids from Galacticraft)

**Comment by FoxPotato** [comment]
well, if you're inside the radius you get teleported before it kills you. so if something takes half a heart every second like fire, it would transmat you with half a heart. quite ncie tbh.
don't know the exact range, gotta ask dark some time.
this is also how i explore worlds, every now and then I recall my TARDIS. :p

**Comment by Soyaro666** [comment]
nice to know. thanks for the information. anyways, there are situations where it doesn't teleport me. If i managed to get a Tardis without having an armor yet (incredible luck, stupidity or cheating make this possible) I don't want to leave the Tardis at night so I would want to know if it's night before I leave the Tardis. Or maybe I'm waiting for something I can only do during nighttime (a witchery ritual I don't want to perform in my tardis for example), want to work in the Tardis during daytime and it's verry laggy to continuously change Dimensions (common situation for my girlfriend if we're playing online) a clock would be useful too. arguments for a clock can be found. It could be added in the external scanner (it already outputs 5 lines on rightclick, a 6th line wouldn't hurt I think) and it would be faster to rightclick the scanner than to leave and enter the Tardis even with a good connection or in singleplayer...

**Comment by FoxPotato** [comment]
switching dimensions wouldnt be too laggy bc the outside chunk is already kinda loaded, but i get what you mean.
and i dont think there is gonna be another line, i think he might code in that all the info appears on the screen :p

**Comment by DarkholmeTenk** [comment]
You underestimate minecraft, it unloads chunks aggressively and ineffectively

**Comment by FoxPotato** [comment]
really? damn

**Comment by Soyaro666** [comment]
well, a Clock instead of this Tardis Interface stuff would be nice too. it just felt like it belongs to the sensor ;-)
