### ISSUE TITLE
[SUGGESTION] Manual use of lab (without adding a GUI)

### ISSUE THREAD

**Issue by Nova001Sol** [DarkholmeTenk/TardisModIssues#177]
It's simple. Right-click with anything used in a lab recipe to insert enough of it to complete the recipe once, so right-clicking with a stack of dirt would insert it all but right-clicking with a stack of chronosteel would insert only one.

Right-click with an empty hand to take out whatever is in the output 'slot'. It does nothing if there is no output, as should be expected.

Sneak-right-click with an empty hand to make the lab return everything it contains, both input and output.

Please let me know what you think.

EDIT: fixed the chronosteel example on the input. Temporal dirt only consumes one chronosteel after all, not two.

**Comment by Soyaro666** [comment]
right now it would work. but what if more recipes are added and ingredients repeat? lets say we get another metal that bases on multiple iron and something else, should the lab consume one iron (chronosteel) or multiple (the new metal)?
I would suggest: right clicking inserts one item, right clicking with an empty hand removes one item, shift+right clicking does the same with a full stack. and, to be honest, I would always suggest to place the Lab on top of a Chest to allow it to automatically output stuff...
btw, what's bad at placing a hopper on the lab?

**Comment by Nova001Sol** [comment]
Aside from me just disliking hoppers? Not much, I just think that options are always a good thing to have in a game.

**Comment by Soyaro666** [comment]
hoppers are one option given by vanilla minecraft. alternatives are any mods that add item pipes/tubes/ducts.
don't misunderstand me. I like the idea of placing items in the lab per hand and I'm sure dark will find a good way to implement it if he choses to.

**Comment by DarkholmeTenk** [comment]
Hoppers and pipes are the way I'm choosing; adding items by hands removes a layer of abstraction in my code that I want to keep. Also right clicking with an empty hand turns the lab on/off currently.
