### ISSUE TITLE
Recall function not working correctly, Dimension Issues.

### ISSUE THREAD

**Issue by Ayria** [DarkholmeTenk/TardisModIssues#178]
I ended up in the Nether and attempted to use the Tardis to return to the overworld, only it wasn't an available dimension on the lever. Built portal in the Nether and returned to the overworld that way. Attempted to recall Tardis with Sonic while in the overworld but failed. Built recall block, was able to bring the Tardis back to the overworld.

I landed in the Twilight Forest and attempted to recall Tardis to a location that didn't cause a negative status affect so that I could play the progression in the Twilight. Sonic failed to recall. I attempted this several times in many different areas of the Twilight.

Overworld isn't a dimensional option most of the time, even if I'm in that Dimension. 

In case it matters, here's my the mod list:
http://pastebin.com/2Y2QXanP

I am also running this on a personal server.

**Comment by Soyaro666** [comment]
sounds familiar. in #174 I posted a similar problem with dimension selection. got to test if I have the same recall problems.

**Comment by DarkholmeTenk** [comment]
Try using the latest build on the jenkins.
There was a bug (with the screen) which stopped overworld from showing on the screen and going from the nether to the overworld using a portal could've put you in a position the tardis couldn't reach, e.g. x=10k in the nether -> x=80k in the overworld.

**Comment by Ayria** [comment]
Similar to when you don't have enough energy to go somewhere when setting the controls yourself?

**Comment by DarkholmeTenk** [comment]
Nope, there are just certain areas that can't be reached by the normal coordinates system; it's why the relative coordinates system exists.

**Comment by DarkholmeTenk** [comment]
Closing. Asssuming it's fixed.
