### ISSUE TITLE
[BUG] drifting

### ISSUE THREAD

**Issue by FoxPotato** [DarkholmeTenk/TardisModIssues#179]
I was flying some distance, decided to pull the drifting mode lever. when i went into coordinated mode again the screen said landing and I leveled up. I don't know if i really leveled up. but after that happened it resumed it's flight without actually landing.

EDIT: I actually landed, got xp, leveled up. But the flying sound went on for a bit more, the landing sound happened and i got the level up sound again.

**Comment by DarkholmeTenk** [comment]
sounds like a client server sync issue; the client shouldn't be able to play sounds though :P

**Comment by AlienXtream** [comment]
I guess fox's client dont care what we thinkit can/cannot do :P
