### ISSUE TITLE
[ENHANCE]  Crafting Recipe for TARDIS interior blocks

### ISSUE THREAD

**Issue by Jwtc2000** [DarkholmeTenk/TardisModIssues#18]
Crafting recipe for TARDIS blocks (breakable versions) 

e.g.  
![BrownBlockSlab](http://i.gyazo.com/7f742643ef9553e52dd61977de53cdfb.png)     
  ![GrateSlab](http://i.gyazo.com/8dc4ce25c59f29709d7dc0659ffcd1d7.png)   
 ![BrownBlockStripe](http://i.gyazo.com/89a5a831145521862b9ee567123586e6.png)

**Comment by DarkholmeTenk** [comment]
Lol @ this #123
