### ISSUE TITLE
[BUG] NAME CHANGING

### ISSUE THREAD

**Issue by FoxPotato** [DarkholmeTenk/TardisModIssues#180]
When changing your username teh TARDIS doesn't update and you don't have permission anymore.

**Comment by Soyaro666** [comment]
changing username? do you mean login with another Account or renaming the account you used before?

**Comment by DarkholmeTenk** [comment]
Renaming the account; I've known this was going to be a problem ever since mojang announced name changes

**Comment by FoxPotato** [comment]
why not use UUID's tho

**Comment by DarkholmeTenk** [comment]
UUID->name translation isn't a thing that can be done clientside, as far as I'm aware.
Edit: Actually, it looks like UUID->name translation isn't even a thing :P

**Comment by FoxPotato** [comment]
really? that's a shame :/

**Comment by DarkholmeTenk** [comment]
I think I'm gonna store a map in darkcore :P

**Comment by DarkholmeTenk** [comment]
Fixed. I am awesome.
