### ISSUE TITLE
RANDOM CIRCUT

### ISSUE THREAD

**Issue by zach2639** [DarkholmeTenk/TardisModIssues#182]
In S4E4 of the new dr who they mentioned a "random circut " of some sort that takes you...some were random... plz add it :D

**Comment by Soyaro666** [comment]
may I suggest you to read post #25 
beside that, I'm awaiting the implementation of this too

**Comment by FoxPotato** [comment]
It is confirmed that he is going to add a way to have random coords.

**Comment by DarkholmeTenk** [comment]
Duplicate of #25

**Comment by zach2639** [comment]
oh...LOL

**Comment by zach2639** [comment]
sry about duplicate...i just rewached that episode...

**Comment by DarkholmeTenk** [comment]
It's cool. All the code's been in place for a while; I just need to make a
model for the zigzag plotter
