### ISSUE TITLE
[ENHANCE] fuel

### ISSUE THREAD

**Issue by Soyaro666** [DarkholmeTenk/TardisModIssues#185]
http://tardis.wikia.com/wiki/Zeiton-7
maybe to speed up movement (everything like it is right now without it but movement speed is increased if Zeiton 7 is available)
quicksilver
slightly speeds up energy generation

btw: still awaiting energy zones like mentioned in #88 which could work like quicksilver but much more effective

**Comment by FoxPotato** [comment]
the TARDIS increses speed with 1b/t ever time 50artron energy is consumed.
And I dont think he is gonna add an item to speed up energy generation if you can upgrade it using points.

**Comment by Soyaro666** [comment]
you can upgrade generation speed but those are small steps and level points aren't cheap
with Zeiton 7 you can invest your points more balanced or have the option to repower your tardis if you got stuck in another dim (to me this happens often on levelups). and the speed increases, but with quicksilver you could raise it more rapid so it gets interesting on longer flights (many thausand blocks). and this high speed would add another variable you'd have to deal with: unstable flight even if you've activated stabilizers (well, without stabilizers you could damage the tardis by using quicksilver and/or max speed)... on it's own, on short distances, on low levels, lets say in common use, both are useless (maybe dangerous) but in extreme situations they may be an interesting option.

**Comment by DarkholmeTenk** [comment]
See #187
