### ISSUE TITLE
[ENHANCE] upgrades

### ISSUE THREAD

**Issue by zach2639** [DarkholmeTenk/TardisModIssues#187]
## (the last post i did on this topic was a little confusing so i open a new one)

i think you should add upgrades (list below soon) there are 2 types (toggle and meter) to install a upgrade switch your sonic device to reconfigure and go to the "temporal engine" and go to the upgrade panel(the blank one) and sonic it. You will see 4 slots(default size 1) (upgradeable) in these slots you can insert any upgrade listed below.(right clicking on a upgrade slot with a iron ingot changes size)

------------Removal--------

To remove a upgrade you need a level 10 sonic (the sonic gotten from a level 10 tardis) set to dismantle then right click a upgrade then shift right click and it will pop out in a slightly used verson.To fix it, simpily insert the used version in flight with a blank module and a brand new version will pop out ready to be used again

-------------Upgrades---------

here are all the upgrades possible (or some extra)

level-up! (absorbed...adds a level,uncraftable,rarity 3,size:1)

repair(repairs tardis damadge caused by your wreckless driving XD,uncraftable,rarity 4,SIZE:5)

fast chip (allows tardis to go a little faster,uncraftable,rarity 7,size:3)

artron chip(allows artron batterys to be charged faster,recipie:energy moduleX5,dispach module:size:2)

regen chip(allows tardis to regenerate as the real tardis does,resets current tardis to first tardis...gets better,rarity 50:size:10)

bookmark chip (right click in hand to save location put in tardis to save location to tardis save pad,recipie: blank module,action module,artron module,dispatch module,save module:size:7)

safety chip (tardis damadge repaired over time at the cost of artron energy,chips cand get corrupted and have a verry low cance of falling out:size:5)

Power chip (fills up all power,recipie:artron chip,full artron battery,artron adapter:size:1)

Biome Finder (finds the nearest biome of specified type and goes there,found in the respected biomes ex:desetr chip= desert,size:3)

Clock (right click on it to set time,requires a counsole panel to operate,blank module,action module,clock,energy module,size:3)

sloterer(adds 1 ugrade slot(max 8),rarity:1000 )

thats all (more in future)

---------Modules
modules are the components of upgrades they are (so far):

Speed module (rarity:2)
blank module (rarity:1)
action module (rarity 5)
energy module(rarity 4)
dispach module(rarity 10)
save module(rarity 2)
artron adapter(rarity 7)

--------------------flight problem consequences

chip might fall out or be destroyed
chip might get corrupted and do the opposite of listed buffs

-------------------councole stuff

on the side with the deletion button you have a few boundable panels(not a few...ONE)... to open them,sonic them in reconfigure mode,after opening go down to the temporal engine and sonic the upgrade you want to have a little panel then sonic the panel again,afterwards, the panel will have a lever or the clock thingy for time chip(required for time chip so you can control the time)

**Comment by Soyaro666** [comment]
to do you a favor...

An upgrade system sounds nice. It could be the base for many requests that are still waiting for implementation. while you had a lot of ideas how to craft the one upgrade you already described in #186, you didn't list any other upgrades. with only one feature it add's I doubt Darkholme would even think about that much work your suggestion would be for him.

**Comment by FoxPotato** [comment]
What other requests  actually?
And it is quite a nice idea, minus the part where you get more panels when you level up. I think it should stay at like 4 panels, or maybe even 1. Else it might become a bit too OP.

**Comment by DarkholmeTenk** [comment]
May be added to the repair panel. Instaflight is a definite nope; cost of flight is only calculated with speed increases.

**Comment by Soyaro666** [comment]
possible upgrades? I quickly read the open issues and got some ideas.

speed (probably not, according to Darkholme in #186 it will be skillable by level points)
time jump ( #184 )
external scanner upgrade with LookingGlass ( #181 )
invisible exterior ( #103 )
Zigzag Plotter ( #25 )
biome as destination ( #188 )
and so on. not all of these have to be upgrades, they can be rewards for leveling the tardis too. every function that would enhance the Tardis could simply be there, could appear on a specific level or could be added as an upgrade. even features that are already there (dimension selection maybe? just a thougt)

@epicnesslol shouldn't it be your job to make suggestions what your suggestion could do? :-P

**Comment by FoxPotato** [comment]
the biome and time jump, and maybe invisible exterior seem like the best ones to me tbh.
zigzag plotter is gonna be either by level or standard, and the lookingglass implementation is also probably either gonna be leveled or standard. I think.
and speed is a definate no, seeing as that is what dark literally said above you :p

**Comment by Soyaro666** [comment]
he said instaflight is a no. increased flight speed will be skillable like you can read in #186 
I didn't want to say "these have to be upgrades", I just wanted to give examples what could be upgrades.
btw, now that i'm Thinking about it: installing upgrades could unlock skills too. And why should upgrades be removable? maybe some items (that unlock skills for example) get absorbed by the Tardis after they are used the first time so the used slot get's free without losing the advantages provided by the upgrade...

as I said before: It's a nice idea with many possibilities. and don't be fooled, I wouldn't like half the suggestions I made, I'm just saying "these could be used as upgrades"

**Comment by FoxPotato** [comment]
Yeah I know, I was jsut giving my opinion of which ones from that list sounded like things that could be added :p 
Even if some things get absorbed by the TARDIS, I think finite slots would still be the best idea. So people had to choose.

**Comment by Soyaro666** [comment]
yes, of course. maybe one slot for absorbable items and others for not absorbable? or the procedure to remove a not absorbable item to be able to install an item for absorbtion?

**Comment by zach2639** [comment]
i thoght of a new one ^^

**Comment by Soyaro666** [comment]
a new what?

**Comment by FoxPotato** [comment]
chameleon circuit is a no, Dark will maybe add toher exteriors but they will still be 1x2x1.
And time chip would be good with #184 (which is probably also where you got it from)

**Comment by zach2639** [comment]
fixed the instaflight thing (now a chip that allows the speed gashe to go faster,but not instant)

**Comment by zach2639** [comment]
fox...the extiriors are still 1x2x1...there small

**Comment by epicnesslol** [comment]
leaves
wood

...XD its a tree in growth

**Comment by epicnesslol** [comment]
should the speed chip be absorbed pool

**Comment by Soyaro666** [comment]
actually Darkholme wanted to make the speed a new skill. and I don't think you should work on that much details. Darkholme will implement it how he thinks, if it is implemented but not like your ideas you will be frustrated about every detail that didn't make it into the game.

a list of possible chip types (absorbable, maybe a consumable that gets destroyed and needs to be replaced?) and a list of possible chips are fine, Darkholme will combine them as he things it's best

**Comment by zach2639** [comment]
i no but...suggestions

its upto dark anyways

 XD yeh i talk way to much

**Comment by Soyaro666** [comment]
don't worry. read through my posts around here, I have the exact same problem. and two of us at the same place are good - we can stop each other before it becomes complicated ^^

**Comment by epicnesslol** [comment]
XD

**Comment by epicnesslol** [comment]
new stuff :smiley:

**Comment by zach2639** [comment]
omg ive posted 3 times and u guys are the only ones ive met...coecedentily all of you were on all 3 posts at some point so far :D

**Comment by Soyaro666** [comment]
so you know who currently are the active visitors of this project ^^

**Comment by DarkholmeTenk** [comment]
@epicnesslol  you can edit your previous posts :P

**Comment by zach2639** [comment]
i hnow

**Comment by zach2639** [comment]
...the flash of silence...will fall

**Comment by zach2639** [comment]
XD

**Comment by zach2639** [comment]
...i stay up way to late...c ya

**Comment by Soyaro666** [comment]
actually if the last post is yours you should edit that one instead of adding a new...

**Comment by Soyaro666** [comment]
every upgrade-slot could be linked to a position on console. If you add an upgrade the corresponting feature appears at the linked position. upgrades that suggest to add multiple elements like my time jump suggestion would do (one for daytime, one for moonphase) would need to be splitted into two upgrades since they add two elements to the console.

Upgrade slots could be features that raise with level. with a new tardis no upgrade slots are available. while it gets levelups there appear up to n slots while n is a value chosen by Darkholme - at least its his decision how many upgrade slots will come anyways.
linked positions could be on the right from z levers, on the right from facing wheel, above speedometer and instead of any small blue "flight control" lever. the size of the appearing feature should be fitting to its position which can be done by one of two options. 1.: the appearing feature resizes to fit into its position (may be harder to code) or 2.: not every upgrade fits in every slot because it's too big for the corresponting position. this could be done by giving levels to upgrades. For the highest level I whould suggest a maximum of 3 since there already exist three different lever, display and button types and it's less work if you can reuse existing objects.

**Comment by FoxPotato** [comment]
I like the idea of not every upgrade fitting into every slot, It gives it a more realistic feel.
Also the z control panel is already kinda crowded, I'd suggest the X control side.
And I feel this is gonna take alot of rebuilding the console, bc there is barely any place anywhere. Maybe when he makes a new console there'll be more place.

**Comment by Soyaro666** [comment]
like I said, every existing flight control lever can be removed, the space can be bound to an upgrade slot. Or they could only recolor in the moment they get a function

**Comment by FoxPotato** [comment]
But less flight levers would mean that flying would become easier, and less running around. So in my opinion the flight controls shouldn't be deleted but just moved.

**Comment by Soyaro666** [comment]
why should a Button (I thought for the one below Land Ground Control) randomly change dest coords while you're flying? so many buttons and levers that don't do anything while the Tardis isn't flying... and the save slots are used as flight controls too while you're flying, aren't they?
to make clear what I thought about: an element with multiple functions, one while landed, one while flying, would work. the save slots are working that way right now.

**Comment by FoxPotato** [comment]
the waypoint panel only works as flight controls bc the other levers lock into place. And thus can't be used as flight controls. I guess.

**Comment by Soyaro666** [comment]
another thought: the flight controls between speed lever and facing wheel could toggle different modi. while they are in (default) everything works like it does right now. while one is pulled, one of the coordinate facings could so something completely different (biomes instead of dimensions, time instead of x/z coordinate, I'm sure we could find a lot more possibilities about this) and all three flight controls need to be in to allow start sequence. and while flying they are acting exactly like we're used to it.

I have way too many ideas for this mod O.ô

**Comment by FoxPotato** [comment]
It would be kinda weird if suddenly the console changed. It does sound like a cool idea, but looking at it from a realistic view; you'd either have to fit everything in the buttons and levers already.

**Comment by Soyaro666** [comment]
yes, that's what I just said. the levers and wheels could get new functions by toggling the flight control elements I mentioned without any element being replaced by something else.
btw, the console currently is suddenly changing. indicated by levelups, of course, but it's doing it. and yes, it is weird until you get used to it...

**Comment by FoxPotato** [comment]
Yeah, it's still weird. I try to ignore it and jsut think that I'm installing them myself, and they stay after you level up once. What I meant with suddenly changing I mean, like the x side suddenly only having buttons or something. 
I still like the idea of changing what controls do by pulling one of those levers, but i don't see how Dark would do it. He probably will find a way if he's gonna implement this :p

**Comment by Soyaro666** [comment]
he could simply add a variable that toggles what the lever states are got from and used for. that part whouldn't be that hard. to implement the alternative algorythms is the hard part in this coding I think.

**Comment by FoxPotato** [comment]
It's not the control part that's probably gonna be hard, it's gonna have to work with the levers already there. Because like I said, It would be kinda weird if a lot of levers and buttons suddenly appeared when you pushed a button and stuff. And seeing as they're pretty specific for the uses they are used for right now, I can't really think how to implement those examples you gave into the existing levers. Well, not in an efficient way. If you try hard enough everything fits.

**Comment by Soyaro666** [comment]
the dim lever changes its range when new dimensions get unlocked. it could do the same for biomes. the facing wheel could toggle moon phases too. the coord wheels could toggle moon phases or daytime. they whould behave like before but affect something else. of course they should be chosen to fit the function they're supposed to do. random coords on a wheel doesn't make sence, moon phases on a lever would be strange, a button to manage biomes couldn't work in a comfortable way. that's one reason (actually three reasons) for upgrade levels and slots that can't be used for every level.

**Comment by FoxPotato** [comment]
The moon phases and time of day one sounds pretty reasonable. But Biomes on the dimension lever, Like you said it already clogs when you have too many dimension mods, and seeing as vanilla already has a shit ton of biomes it wouldn't be too nice with mods :p 
And the random coordinates thing is gonna be implemented in another way iirc.

**Comment by Soyaro666** [comment]
at least you could give every biome a number and select those numbers by coordinate levers if you don't like the dim lever idea (of course this would require a table of biomes and their numbers. an addon for library maybe? ^^). and I didn't read anything about how random coordinates will be implemented. And of course I can explain how I whould do it but that can't be any more than examples since I'm not even able to code in java ^^

**Comment by FoxPotato** [comment]
I swear he said it somewhere on github.
And to make that table using the library, I guess you mean the codex, it would be kinda awkward I think. He'd have to implement a numberpad which wouldn't be the hard part, but idek if you're able to scroll and stuff. being able to travel by biome would be cool but idk how he would add it in a way which wouldn't be too difficult.

**Comment by Soyaro666** [comment]
it would be hard because he won't add a gui for it but that's the interesting part about Tardismod. you have to think different or you aren't even able to start the engine. It will be complicated to implement a biome selection system that can handle all biomes and it will be complicated to use it but where's the challenge if it wouldn't be? I guess the Tardis isn't supposed to be easy...

**Comment by zach2639** [comment]
i ran out of upgrade ideas...

**Comment by FoxPotato** [comment]
It's gotta be challenging, but like it should stay at the level it's at rn I think. It has to stay fun challenging, not I want to rip my hairs out challenging. :p

**Comment by Soyaro666** [comment]
if you have a table of all biomes, maybe biomes with unknown coordinates in gray and biomes with known koordinates in white, you could set the number of one like you can set a specific coordinate if you could switch one coordinate side to biome mode. is this solution that challenging if you can read the number and the corresponding biome on screen?

**Comment by FoxPotato** [comment]
What you are describing is just possible via waypoints. Or by opening a notepad file. Heck, you could even put it on a sign. While I love the idea of having to go to a dimension first before you can go their with the TARDIS it wouldn't work for biomes I think. Only if it would also look for other coordinates with that biome. BUt then you get all the stuff we talked about in #188

**Comment by Soyaro666** [comment]
yep. thats because I listed #188 as possible upgrade 2 days ago and I'm reffering to that list all the time

**Comment by FoxPotato** [comment]
I know, I was just too lazy to note down again why that wouldn't work, so I referenced that post.

**Comment by zach2639** [comment]
troll chip is atualy usefull to the owner of the tardis too :) instead of haveing to flip levers all over the place you can shift left click and save the co ordnates

**Comment by Soyaro666** [comment]
you already are able to save coordinates easily

**Comment by zach2639** [comment]
i no but if you find someone elses tardis its funny XD
sooooo evil
and its sooooooo rare

**Comment by epicnesslol** [comment]
sooooo evil

**Comment by epicnesslol** [comment]
and its sooooooo rare

**Comment by epicnesslol** [comment]
:hankey: looks like poo

**Comment by zach2639** [comment]
AND the tardis dosent have to be there to save it...so no flipping at randomness to find somewere cool THEN save it

**Comment by Soyaro666** [comment]
the moment you use the save function it stores the current lever position. so it doesn't matter where your tardis actually is as long as the levers are set to whatever you want to save.

**Comment by zach2639** [comment]
still requires to find out if that place is cool, like for instance asmall cool thing, how long would it take and how much artron would it take to get exactly on it

**Comment by Soyaro666** [comment]
depends on Level. note coords, go to tardis, set coords. or stay there and recall your Tardis... it's mostly a travelling device I guess

**Comment by zach2639** [comment]
still funny since you can put it in a freinds tardis

**Comment by Soyaro666** [comment]
Actually you can't. In most cases the Door will be locked for you. And even if you can enter the friends tardis you would need to have permissions for changing upgrades which you usually wouldn't have. And after he created the permission system we're using right now I don't think Darkholme will implement a way to avoid the set permissions...

**Comment by zach2639** [comment]
and without a trace of you doing it...so your friend will think hell land at 100 100 100 but he is at 1902 7 4537 ad the tardis will say 100 100 100

**Comment by Soyaro666** [comment]
while I hope such a griefing tool will never come it may be a nice Problem you could have do live with if the tardis get damaged... just saying...

**Comment by FoxPotato** [comment]
I can already tell you thats not gonna be implemented, just because it doesn't make any sense and has no use at all.

**Comment by Soyaro666** [comment]
well, it had the use of griefing which is an additional reason for not implementing it. but like I said, it could be a thought about problems resulting from a damaged tardis

**Comment by zach2639** [comment]
lol i  was wondering if we had griefers among us
cus i dont like spam...many servers in the past that i created (not here) were spammed to annilation ever since ive done stuff like this for no spamm tests
not on this website...

**Comment by epicnesslol** [comment]
test

**Comment by epicnesslol** [comment]
cus i dont like spam...many servers in the past that i created (not here) were spammed to annilation ever since ive done stuff like this for no spamm tests

**Comment by epicnesslol** [comment]
not on this website...

**Comment by DarkholmeTenk** [comment]
The troll thing won't be implemented because it's not something I want to
do. However a way to store bookmarks in an item intrigues me.

.

**Comment by Soyaro666** [comment]
4 messages in 3 minutes... you don't like spam? doesn't appear like that's true :-P

**Comment by FoxPotato** [comment]
Storing waypoints in items does sound fun, you ca give them to other people so they can acces your base easily.
Kinda like the disc in Blink only it doesnt home in on the doctor :p

**Comment by DarkholmeTenk** [comment]
@epicnesslol stop making me merge your comments plz

**Comment by zach2639** [comment]
im talketive but spam is the same thing a million times

**Comment by zach2639** [comment]
atully the original itea was a bookmark you can right click anywere then put in to allow for it to put all saved locations on the tardis save pad thing

but i molded it into a troll device for a test,original up above on my thing ^ ^

**Comment by Soyaro666** [comment]
there won't be any troll device... but the Idea of saving single positions sounds nice... maybe an item you can craft from the lab - maybe the map incredients inserted into lab? - to store one location at a time? or maybe an upgrade system for screwdriver where you have to craft the screwdriver together wich a specified item do activate the special ability to save a location - wait, it's still saving absolute coordinates I guess... Maybe you should simply implement a more effective algorythm for coordinates? and yes, to clear up what I'm talking about: I still want to see my formula in action... actually I'm proud of not publishing it so nobody knows how it enhances the thardis - they only know it may enhance something about it... please, implement it at least as an option in cfg...

**Comment by FoxPotato** [comment]
No need to keep telling dark to do something, if you messaged him about it and he hasn't answered just be patient. He'll see it eventually. He's a busy person and usually takes his time to reply to stuff :p

**Comment by zach2639** [comment]
upgrade place:on the bland panel...its blank

**Comment by micmou** [comment]
I suggested something like this a while ago...

**Comment by zach2639** [comment]
k

**Comment by Soyaro666** [comment]
because of #233 I had the idea of a furnace upgrade that would smelt/cook stuff (food, ores, whatever can be smelted by a furnace) that's sent through the tardis. Of course this should have a toggle to de/activate it as needed, maybe by making it easily un/installable...

**Comment by zach2639** [comment]
upgrade:S.I.U.P(super intelligent upgrade permitter) this will tell you what upgrades you have and allow to remove upgrades also makes it hard for upgrades to break
(another bad thing that can happen to upgrades is implosion tardis loses 20 HP and you get a data chip(one type for each upgrade) wich after intence crafting you can fix the upgrade)

**Comment by zach2639** [comment]
and darkholm...furnace upgrade could jest be bound the tardis counsole...no remove the counsole "free" spaces a sugggested would deactivate it (deactives dont glow when you look at them in the upgrade panels)

**Comment by zach2639** [comment]
new ideas (some sugggested,some not :D) 
^^^
| | |

**Comment by TheAmazingSpy** [comment]
How about 1. The tardis console panels lift up (no animation) and then it exposes wires and stuff like that, which can be used for repairing the tardis and putting in some upgrades 2. There could be a hatch or chest below the temporal engine to put items in, and with food, it will either be deleted or cook, after flying. It would be on chances, with factors such as, shield levels etc

**Comment by zach2639** [comment]
i put it on the temporal engine already....but good ideas!

**Comment by FoxPotato** [comment]
The repair stuff is already on the now still empty panel on the engine.

**Comment by TheAmazingSpy** [comment]
FoxPotato, the temporal engine should be ONE of the places to repair your TT Capsule, as the Doctor will repair it in other places, not just the temporal engine/underneath the floor
