### ISSUE TITLE
[BUG] Colorable Floor Blocks

### ISSUE THREAD

**Issue by iyloMC** [DarkholmeTenk/TardisModIssues#189]
Client crash upon right-clicking a Flat TARDIS Block with an orange dye.

Full crash report:
http://pastebin.com/pNKChvCm

**Comment by DarkholmeTenk** [comment]
Jenkins tardismod, non-jenkins darkcore

**Comment by Soyaro666** [comment]
beside that: Tardis slabs aren't colorable. the metadata that are used to color the other blocks are used by slabs to save where they are (up or down)
