### ISSUE TITLE
[ENHANCE] Placeholder in blacklisted dim names

### ISSUE THREAD

**Issue by Soyaro666** [DarkholmeTenk/TardisModIssues#190]
The reason for this request is another mod I'm currently testing: Dimensional Doors. With that you can generate so called "Pocket Dimensions" (rooms with 30x30x30 blocks). beside that there exists a dungeon concept where you can enter a random generated labyrinth of corridors and dimensional doors. I ran around in there for 20 minutes I guess and now my Tardis has PocketDim 2 to PocketDim 45 available as targets. Of course I could blacklist them one by one in my single player to clean up dest dims, but in multiplayer (yep, I want to use both mods on our server) it would be too much work to remove all that dimensions where I can't even fly to with my Tardis (hit a target of 30x30x30 blocks at an unknown coordinate somewhere in the void - you see the problem?). As I mentioned above they all are named like PocketDim # where # is a number between 2 and the amount of Pocket Dimensions that currently exist. It would be verry helpful if I had a placeholder so I could simply write PocketDim\* (for example) in Blacklist and none of them will ever be reachable by a Tardis.

**Comment by Soyaro666** [comment]
be honest, you own a tardis in reallife! O.ô
thanks for this fast reaction ^^

Edit: tested, works as expected. well done, thanks again

**Comment by Soyaro666** [comment]
well, I'm sorry but I have to correct my last message a little. dims I entered after start appear on my dest dim lever again. right now there are 3 Dimensions available that should be affected by PocketDim\* (they are called "PocketDim 2", "PocketDim 48" and "PocketDim 49"). Is this because the Blacklist doesn't affect newly generated dimensions or because the blacklist doesn't work at all in this special case? (since Dimensional Doors has a unique way to save dimensions this could be possible)

**Comment by DarkholmeTenk** [comment]
![TARDIS](http://i.imgur.com/LNPftqm.jpg) I might own a TARDIS :3

**Comment by Soyaro666** [comment]
well... something might be wrong in current blacklist code...

![2015-06-03_07 42 33](https://cloud.githubusercontent.com/assets/12465756/7953366/27113e66-09c4-11e5-97fb-ae4c11f85062.png)
![2015-06-03_07 45 15](https://cloud.githubusercontent.com/assets/12465756/7953397/7e6f9900-09c4-11e5-831a-6e9b0dbb865e.png)

As the screen may suggest: yes, I landed it there... and beside that dimension only Overworld is available while my Tardis was able to reach every other dimension before I updated to build 163... guess my suggestion for blacklists wasnt that easy I thought before... at least I'm able to perfectly hide my tardis now ^^

**Comment by DarkholmeTenk** [comment]
Was supposed to be: if(Helper.isTardisDimension(world))return false; //i.e. don't add if this is a TARDISdimension
But I put: if(Helper.isTardisDimension(world)) //i.e. only add it if it's a TARDIS dimension
because I'm a derp.

**Comment by Soyaro666** [comment]
well, I don't even want to know how often something similar happened to me... imo Jenkins version is kind of an alpha test I guess so it's kinda supposed to do strange things sometimes...

**Comment by Soyaro666** [comment]
PocketDims still show up after they got visited the first time. That mod seems to handle dimensions in a way that completely avoids your blacklist. And in addition something went wrong with PocketDim names. some of the Pocket Dims are showing up without a name so the blacklist can't block them.
May the problem result from the way Dimensional Doors saves the dimensions? while other dims are saved in saves folder DimDoors has a subfolder named "DimensionalDoors" where it saves the pocket dimensions. I guess the Tardis doesn't understand that...
It was supposed to be an easy request. sorry for that much work it generated until now :-/

Edit: forget that part about the dimensions without names, that's a conflict between DimDoors and another mod I'm experimenting with right now. I added that one and it registered DimIDs that where used by DimDoors previously
