### ISSUE TITLE
[ENHANCE] Mob transmat

### ISSUE THREAD

**Issue by FoxPotato** [DarkholmeTenk/TardisModIssues#193]
When deleting a room, mobs get deleted with it. which is quite a pain.
I guess there might be reason why you didn't add it, but I'm suggesting it anyway.

**Comment by iyloMC** [comment]
Possibly turn all mobs "deleted" this way into spawn eggs and put them into the owner's inventory? Or into a specified chest?

**Comment by FoxPotato** [comment]
I think that would be a bit too OP, just have them transmatted would be the best option. Now i think about it I can just transmat them myself. But still, I've lost quite some villagers thanks to this.

**Comment by DarkholmeTenk** [comment]
Not technically true, what actually happens is they get teleported to the overworld, but keep their current position, because for some reason that was what I decided to do aeons ago.

**Comment by FoxPotato** [comment]
wait
so that is possible, but you can't transmat mobs out of the TARDIS yet.
