### ISSUE TITLE
[ENHANCE] Stablized Time Rotor Sound / Blue Button Sound Effect

### ISSUE THREAD

**Issue by Jwtc2000** [DarkholmeTenk/TardisModIssues#194]
Stabilized Time Rotor
https://www.youtube.com/watch?v=_fsvWNClEH0
~
Blue Button Sound
https://www.youtube.com/watch?v=BXqWjHxsvL4

**Comment by PrincessOfEvil** [comment]
I'm pretty sure stabilized Tardis played 4'33".

2015-06-03 15:31 GMT+06:00 Jordan C. notifications@github.com:

**Comment by DarkholmeTenk** [comment]
Not going to implement; I like the sounds as they are now :P
