### ISSUE TITLE
[BUG]Morphing in tardis is buggy

### ISSUE THREAD

**Issue by AlienXtream** [DarkholmeTenk/TardisModIssues#198]
using morph inside the tardis produces some strange issues.

**Comment by DarkholmeTenk** [comment]
Such as?
Console output?
Screenshots?
Steps to reproduce?

**Comment by AlienXtream** [comment]
incorrect render and hitbox of player when morphed. to reproduce? just install ihcunns morph mod and attempt to morph in the tardis Dim. a list of effects i can think of ways to describe are. Morph's Render and hitbox fail to update correctly when morphing INTO entities, morphing from them updated the render and box but it then remains stuck on tthe preveous morphs render and box. morphing to default has no issues. camera fails to reposition (related to hit box issues) and lastly, all morphs revert to their default orientation (they donot rotate with the camera). i am unsure how it would handle using other player morphs. on a funny note, i entered the tardis as a Zpigman and the sonic was rendered in his mouth like a cigarette XD

**Comment by DarkholmeTenk** [comment]
This sounds a lot more like a morph bug than a tardismod bug

**Comment by AlienXtream** [comment]
Well it omly happens in the tardis. Outside its fine. My guess is that neither mod is to blame but still might be worth loking into. Low priority issue really

**Comment by Soyaro666** [comment]
doesn't the current morph mod versions change your health to the health of your new body? the tardis is watching your health to transmat you if you're in danger. maybe this causes conflicts?

**Comment by DarkholmeTenk** [comment]
The tardis doesn't watch your health if you're inside the tardis though :p
