### ISSUE TITLE
[BUG] Horses do weird things to the TARDIS

### ISSUE THREAD

**Issue by NezcalSpindrake** [DarkholmeTenk/TardisModIssues#199]
If you right click on the outside TARDIS door while riding a horse, you get spawned in the TARDIS dimension, but there's nothing anywhere, you slowly fall (akin to spawning into a server with a very high ping), and the horse stays outside. Transmatting sends you to the right coordinates, but there's nothing there. Shift right clicking in Transmat mode fixes the nothing being there. Unless you updated since early this morning, I believe I'm using the most recent jenkins version. (1.7.10-0.985-170)

**Comment by DarkholmeTenk** [comment]
Is this the first time you right clicked on the door? i.e. new tardis?

**Comment by NezcalSpindrake** [comment]
No, this was an established TARDIS. It behaved this way every time I did
the same thing.

**Comment by DarkholmeTenk** [comment]
Did the interior just fail to download or was it entirely deleted?

**Comment by NezcalSpindrake** [comment]
It just doesn't load until you shift right click in transmat mode on the
sonic.

**Comment by DarkholmeTenk** [comment]
Simple fix: make any teleport force a dismount :P
