### ISSUE TITLE
[BUG] Transmat hurts mobs and angers villagers

### ISSUE THREAD

**Issue by AlienXtream** [DarkholmeTenk/TardisModIssues#204]
like the title says. also, entities with the invincible tag wont transmat at all.

**Comment by DarkholmeTenk** [comment]
If hitting the entity doesn't cause the hitEntity function to be called, there's pretty much nothing I can.

**Comment by AlienXtream** [comment]
is there a way you can at least make it so that entities dont take damage like with snowballs?

**Comment by FoxPotato** [comment]
He could make the attack damage 0. Would be kinda fitting, the sonic isn't a weapon but a scientific tool :p

**Comment by DarkholmeTenk** [comment]
iirc, attack damage 0 still causes damage with melee stuff :P

**Comment by FoxPotato** [comment]
not with attributes. You can spawn in swords with +0 attack damage and it doesn't do anything I thought.

**Comment by DarkholmeTenk** [comment]
Sort of done. Knockback still occurs. Doesn't seem to trigger iron golem anger at all.

**Comment by AlienXtream** [comment]
player summoned iron golems dont anger to players
