### ISSUE TITLE
[BUG] - Non critical - Console spam

### ISSUE THREAD

**Issue by AlienXtream** [DarkholmeTenk/TardisModIssues#208]
the tardis sometimes spams my console with 

[18:34:40] [Server thread/INFO]: [tardis.common.tileents.CoreTileEntity]: Rechecking doors

this persists across restarts and the trigger is unknown. i feel as though this is choaking my tps a little.
any idea why this is doing this? also i have dissabled all debug options in the debug config file

**Comment by DarkholmeTenk** [comment]
This is the TARDIS checking if any of the doorways are still open when they need to be shut or vice versa. It should only happen once when each TARDIS is loaded and when rooms are added/removed.

**Comment by AlienXtream** [comment]
well it was happening over and over each tick

**Comment by Soyaro666** [comment]
in TardisMod.cfg I found "Sets the level of debug output" which is set to 3 by default. @DarkholmeTenk If we set this to a lower number, would it raise or reduce the output? I guess that could be related to this topic...

**Comment by DarkholmeTenk** [comment]
Lol, that depends entirely on which function I've used to print the output \o/
