### ISSUE TITLE
[Enhance] Chunk-load outside the tardis

### ISSUE THREAD

**Issue by Nihilumbra** [DarkholmeTenk/TardisModIssues#209]
Would it be difficult to make the TARDIS exterior a chunk loader or at-least make an upgrade for it at a certain level, It would be nice for an area to already be loading for people without ultra high end pcs or people playing on laptops etc.

**Comment by DarkholmeTenk** [comment]
It already is/should be

**Comment by Nihilumbra** [comment]
played around with it for a bit and chunks aren't loaded when leaving the TARDIS, longest time I waited inside was about an hour
