### ISSUE TITLE
cant go to GC Planets with Tardis

### ISSUE THREAD

**Issue by MoonlightSystem** [DarkholmeTenk/TardisModIssues#211]
I'm using the latest version from jenkins but i cant go to galacticraft dimensions 'cause when i try it says the door is obstructed

**Comment by DarkholmeTenk** [comment]
Are you sure you haven't landed in a location where the door is actually obstructed?
Try setting the y lever as high as it can go and make sure the land ground control is on.

**Comment by AlienXtream** [comment]
this is not an issue. i have just tested it and you can go to GC planets no problem....if you enjoy not breathing ;P

**Comment by DarkholmeTenk** [comment]
Assuming door was actually obstructed :)
