### ISSUE TITLE
Stuck in TARDIS

### ISSUE THREAD

**Issue by TehBrownie** [DarkholmeTenk/TardisModIssues#213]
I'm stuck in the TARDIS. I tried EVERYTHING. Halp pls.

**Comment by DarkholmeTenk** [comment]
define stuck

**Comment by Soyaro666** [comment]
do you have a key in your inventory? sometimes the Tardis doesn't let you use the door without. or did you shift+rightclick the door with a key or screwdriver? if yes: repeat that 'til you read a mode you like in chat. shift+rightclick toggles the lock states. or does the chat give a message when you try to leave? maybe there's a block on the other side of the door...

**Comment by DarkholmeTenk** [comment]
Closing due to no info
