### ISSUE TITLE
[ENCHANCE] Config

### ISSUE THREAD

**Issue by EntraptaJ** [DarkholmeTenk/TardisModIssues#214]
Config option to disable explosions. Personally I find it annoying, I'm not the fastest at getting to the levers and controls to fix the highlighted ones.

**Comment by DarkholmeTenk** [comment]
Lower the speed, lower the frequency of controls that need to be pressed :P

**Comment by DarkholmeTenk** [comment]
Also, set the explosion chance config to 0 or below to disable explosions

**Comment by EntraptaJ** [comment]
Thanks, I'm a huge doctor who fan. Seen almost every single episode of original series.

**Comment by EntraptaJ** [comment]
At first i couldn't find the config. Sorry!!
