### ISSUE TITLE
[ISSUE] Monsters in Tardis

### ISSUE THREAD

**Issue by Soyaro666** [DarkholmeTenk/TardisModIssues#215]
I don't really know what happened. At first I thought it spawned in there. My second thought was it used the door (it was from another mod so I don't know it's abilitys) but that wouldn't make any sense since it had no hands. After I left the Tardis I got attacked by multiple other mobs of the same kind. I landed in the middle of a pack I guess. Did the monster transmat into the Tardis because I landed on it? If yes that's a cool but dangerous feature. I would like to have the ability to kick unwanted creatures out of my Tardis if something similar happens again. Or does a solution already exist and I just dismissed it?

**Comment by DarkholmeTenk** [comment]
Landing on a creature/player does cause them to enter the TARDIS if they don't move. However, normally, they get pushed out because it's a solid block. Apparently, there not being any players nearby disables their AI enough that they stay in the block and get into the TARDIS.

**Comment by Soyaro666** [comment]
well, in this pack I added a skill system. without the required skill you can't kill some creatures. So I had Hunter level 3 and got attacked by a level 12 creature. Usually there would be no way to continue using the Tardis before I reach level 12. that's why I'm asking for a way to kick creatures out...

the fact I can transmat creatures inside with landing on them is very cool, btw. but in this modpack it causes problems...

**Comment by FoxPotato** [comment]
Or just remove the whole thing, I mean. If you wanted to teleport a creature into the TARDIS just use the transmat. It's not really usable and quite annoying sometimes.
Of course a way to also transmat mobs outside is really useful.

**Comment by PrincessOfEvil** [comment]
Some monsters spawn anywhere player is, like warp mobs from TC.

**Comment by Soyaro666** [comment]
@laz2727 that may be right but that's okay because those can't hurt me or I can hurt them so at least I can get rid of them by killing them. But I have monsters I can't kill before I reached their hunter level so if this happens with them (what happened 12 hours ago) I have a problem.
Guess a monster that hurts you by 3 to 4 hearts and that can't be hurt in any way by you sit's between the console and the entry door... Fortunately it's been a creative savegame so I was able to kick it into the void...

@FoxPotato That feature is adopted from the TV show so I would want to keep it. imo a way to transmat entities out would be a better solution.

**Comment by FoxPotato** [comment]
I know it's adapted from the show. But it barely works :p 
You can only really get mobs in the TARDIS with that feature if you're lucky. And it doesn't work with players. So a quick solution, until he fixes it (if its even possible to fix) so that the mobs and player don't have to stay still. And I mean, before this happened you didn't even know it could happen ;p

**Comment by Soyaro666** [comment]
@FoxPotato I had an idea about it. I managed to be caught by a tardis i recalled once but didn't really care in that moment. And I rarely played in multiplayer with tardis mod installed so I had no chance to test it...
I like the feature and in multiplayer I possibly would like to use it (friend under attack? I could fly to rescue him/her easily like the doctor did often) but imo a way to kick entities out of the tardis is neccessary with this feature enabled.

**Comment by FoxPotato** [comment]
A way to kick out enitties is needed anyway, with or without this feature. And you won't be teleported into the TARDIS unless you're standing completely still, and like Dark already told us. You will get pushed away because it's a solid block suddenly appearing on you.
But yeah, there should be a way to probably just flush mobs out or something.

**Comment by PrincessOfEvil** [comment]
There are some mobs that actually can hurt you in the eldritch branch.
And why can't you deal at least scratch damage? That sounds horribly
inconvenient.

**Comment by DarkholmeTenk** [comment]
any entity within 2 (configurable) blocks of the transmat destination point will now be transmatted out if you try to transmat them (inc player)

**Comment by Soyaro666** [comment]
@DarkholmeTenk thanks! I'll test how it works and will post my experiences about it.

@laz2727 it's the mod "Advent of Ascension". Ask the creators why monsters are immortal before a player reaches their level, I simply don't know. For me it's useful since this modpack is supposed to be hard in many ways ;-)
