### ISSUE TITLE
[BUG] transmat

### ISSUE THREAD

**Issue by Soyaro666** [DarkholmeTenk/TardisModIssues#216]
Szenario: spawned a villager from spawn egg into my tardis, set screwdriver to transmat, clicked.
Result: Server terminated.
Log: http://pastebin.com/Jb6LdwbP

**Comment by FoxPotato** [comment]
have you tried updating your darkcore to 0.25 build 36? it seems you have build 35 :)

**Comment by Soyaro666** [comment]
oh, I forgot to check. I'll update and try to reproduce, thanks for the hint. (the pack is loading a while. results should be here in 30 minutes I guess)

**Comment by FoxPotato** [comment]
Pretty sure that's the problem though. It's trying to call a method which doesn't exist in your darkcore version :p 
ofc i could be wrong

**Comment by Soyaro666** [comment]
yep, thet's been the problem. like I said, I simply forgot about darkcore. creating a modpack can be annoying because of dependencies...
