### ISSUE TITLE
[BUG] stuck in unreachable dimension

### ISSUE THREAD

**Issue by Soyaro666** [DarkholmeTenk/TardisModIssues#217]
I changed some configs and came into a really annoying situation.
In uncoordinated flight mode the Tardis changed the Dimension. Normally this would be okay because the destination dimension has no own energy settings and falls back to the default energy level. In this case I raised the default energy level to 15k while I defined Dim 0 to energycosts of 2k. I wanted to make a lot Dimensions unreachable until the Tardis level raises high enough. Well, I got stuck in that Dimension because the tardis is only level 5 and hasn't nearly enough energy to get into or out of that dimension.
I solved this by changing the configs back to default but this problem shouldn't be possible I guess.

btw: do different levers/buttons glow for different players? I was leveling my Tardis with my girlfriend before this happened and she saw completely different levers/buttons than me. a feature because of 2 active pilots or just another bug?

**Comment by FoxPotato** [comment]
The problem you mentioned does indeed not really exist, so i suggest you close it. And even if it happened to someone, they would be playing with the configs and thus could easily fix it.

**Comment by DarkholmeTenk** [comment]
Was the tardis changing dimension over a server restart?

**Comment by Soyaro666** [comment]
The server was running until I realized I had to change the config file. It's been my local savegame opened to LAN and 2 persons were active in Tardis from start to landing.
I guess it's a problem with default energy levels. I guess you didn't expect the default energy to be higher than the overworld energy level?

**Comment by DarkholmeTenk** [comment]
I don't know, can't think why it would happen

**Comment by wrothmonk** [comment]
I had a similar issue earlier today. I was flying the tardis in uncoordinated flight mode to level it up, I leveled it up once (to 3) and then landed in the nether even though I had it originally set to the overworld. The only thing I can think of was when I leveled up the tardis unlocked the nether and automatically switched to it. I'm not certain thats exactly what happened but its the most reasonable thing I can think of.

**Comment by Soyaro666** [comment]
@wrothmonk yep, the Tardis does that. My problem was different because I didn't unlock the destination dimension through levelup (it's already been available because it had no level limits) but the required energy was 5 times that much my Tardis had...

**Comment by wrothmonk** [comment]
@Soyaro666 I didn't have enough energy either. I still had it at the minimum 2000 not the 3000 required to visit the nether.

**Comment by Soyaro666** [comment]
@DarkholmeTenk so there is a new description.
Lets say the lowest position the dim lever has is 0, which is associated with Overworld by default. If a dimension (Nether) is unlocked that new dimension can be associated with 0 while Overworld becomes associated with 1 (as you can see, I'm not talking about Dim ID's but about positions in lever table) while the lever was set to position 0 and stays there, even if the tardis would need more energy than it has to reach the dimension that's now on levers current position. I think I mentioned this problem before...
I guess this could have been my problem too but I didn't understand it in that moment...

**Comment by FoxPotato** [comment]
But wouldn't that just tell you you don't have enough energy? Or is that the bug, that it ignores the energy amount.

**Comment by Soyaro666** [comment]
if you're flying while you have a levelup the lever stays on its current "table position" while the value of that table may change (so the destination dimension changes mid-flight without additional energy costs).

**Comment by FoxPotato** [comment]
I got the staying in the same position. Just thought dark would've put in a way to stop that. Seeing as u cant change the lever during flight :p

**Comment by Soyaro666** [comment]
you can't change the lever during flight and that's okay, but the lever may change it's value during flight without any check if the Tardis actually has enough energy to reach (or, more importalt, leave) that new destination. this clearly is a bug.
I guess in program terms it should act like "store current DestDim into a variable, if the lever is set to a different destination than previously stored dim it's changed to the stored DestDim". this would prevent players from changing DestDim too (if they do the lever resets itself) and it would solve this bug.
