### ISSUE TITLE
[ENHANCE/BUG] TARDIS and Galacticraft Sattelites

### ISSUE THREAD

**Issue by Patrick13542** [DarkholmeTenk/TardisModIssues#219]
Iv been tinkering with this mod in my experimental modpack, and Iv noticed something... When I use this mod with Galacticcraft, A TARDIS can travel to people's space stations, which is a major problem, since MicDoodle8 made space stations with the intention of, them being private. And now a TARDIS can travel to them.. I have tried adding the space stations ID to the list of dimensions that the TARDIS is not allowed to travel to, But it doesn't work since MicDoodle8 made space stations dynamic, meaning that the dimension only exists when the owner of the space station is online. And that each time someone creates a space station its assigned a new ID. You see the problem? Anyway is it possible for You guys to fix this?

**Comment by DarkholmeTenk** [comment]
Is there anything shared like a part of the name? E.g. "Space Station: <name>"?
If there is, you can already blacklist by parts of names.

**Comment by Soyaro666** [comment]
@Patrick13542 simply go into Dimensions.cfg and add *station* to the end of the line that begins with "Blacklisted Dimension Names" (should be line 3). You'll need to write the \* before and after it too! This will blacklist every dimension with "station" in it's name which should fit for every Space Station. (generated a space station in a creative test savegame, Tardis recognized dim name as "space station 68" while 68 was the Dimension ID - shema seems to be "space station [DimID]")

Btw, even if the Tardis can reach that Dimension it's still very dangerous to do so. The Tardis Pilot usually doesn't know the stations coordinates so he can't actually land on it before he were there at least once. And I'm not sure about landing on a rotating space station. I'm not saying "you don't need to blacklist them". I'm giving you more reasons for blacklisting them to protect your players from doing a dangerous mistake.

@DarkholmeTenk I guess I didn't mention: It finally works for the Pocket Dimensions I had trouble with. Thanks again for adding the wildcard feature ;-)

**Comment by DarkholmeTenk** [comment]
If there is something like station in the name, then this is already solved \o/
