### ISSUE TITLE
[Critical] Does not works dimension switch

### ISSUE THREAD

**Issue by handicraftsman** [DarkholmeTenk/TardisModIssues#222]
Downloaded latest jenkins build. Result - does not work dimension switcher. No reaction when i am clicking. No console output. Like removed button.

**Comment by FoxPotato** [comment]
Have you unlocked another dimension yet, from what i've heard you can't use the lever unless you got a dimension you can travel to. try unlocking level 5 first. :)

**Comment by handicraftsman** [comment]
I have level 102 (upgraded with tardisxp)

**Comment by handicraftsman** [comment]
P. S. I see this _switch_ (old: button), but technically it does not exists.

**Comment by FoxPotato** [comment]
what do you mean it does not exist. Which button or lever is it. Where is it located.

**Comment by handicraftsman** [comment]
I see dimension switch. But when i am clicking, it does not reacts. And i don't have any console output. No message like "hit x y z", no other click information. Other switches and buttons are working.

**Comment by FoxPotato** [comment]
did you try in another world? and if you did, was it there from the start or did it come after level 5?

**Comment by DarkholmeTenk** [comment]
Do you have any dimensions which are not blacklisted?

**Comment by handicraftsman** [comment]
I am full idiot. It's HELMIC REGULATOR!!!
