### ISSUE TITLE
[BUG] transmat

### ISSUE THREAD

**Issue by Soyaro666** [DarkholmeTenk/TardisModIssues#225]
I'm hosting a savegame to LAN, my girlfriend joined.
If she tries to transmat an animal into tardis it disappears like it were successful but they never appear in my tardis. still build 180 (didn't manage to update yet)

**Comment by DarkholmeTenk** [comment]
Are you using the latest version from the jenkins? That should have been fixed since build 180

**Comment by Soyaro666** [comment]
ah, answered with edit right in that moment...

**Comment by DarkholmeTenk** [comment]
Bugs like this make me cry :'(

**Comment by Soyaro666** [comment]
she can transmat herself but at least 5 cows, 3 sheeps and 2 pigs were sent into the void... hope you can find a solution...

**Comment by DarkholmeTenk** [comment]
Can you try this with a proper server, instead of lan? I have a feeling that this is a lan server bug :P
Edit: Also, update and check out the manual ;)

**Comment by Soyaro666** [comment]
which wouldn't bring a solution I guess. but I was thinking about creating a server-pack with this modpack before so this will happen sooner or later. for now I just wanted to let you know about it still happening

**Comment by Soyaro666** [comment]
latest test: Tardismod build 185, Darkcore build 37, singleplayer, creative
transmating a villager into the tardis failed. He disappeared when I hit him but he never appeared in the Tardis which was less then 10 blocks away (I landet in that village and tried to transmat the first villager I saw).
Maybe this report isn't about a problem with LAN-Server mechanics? If this could be a mod conflict (yep, there where other mods installed) I can give you a full list.
btw: did you add a cloud effect to transmat? or did that come from another mod maybe? the weather mod I'm using is doing strange things if it can add particles...

**Comment by DarkholmeTenk** [comment]
The weather particles are probably the villagers getting mad at you?
I've moved the transmat point closer to the core. The only thing I could replicate is a villager moving at speed got stuck in the doorway and suffocated and an iron golem did too.
Edit: If it's still happening, can you make sure you've got the latest darkcore and post the console output pls? :)

**Comment by Soyaro666** [comment]
this is console output from following actions:
I left the Tardis, that's why JourneyMap started mapping. I transmatted 3 entities (2 villager and one from Witchery) and then transmatted myself into Tardis. Only I arrived there.

Edit: moved output to pastebin: http://pastebin.com/DrvX4DxE

"Dimensional Nightmare" currently includes these mods: http://pastebin.com/52pUz38B
