### ISSUE TITLE
[ENCHANCE] Misc

### ISSUE THREAD

**Issue by handicraftsman** [DarkholmeTenk/TardisModIssues#226]
1. Daleks.
2. More instructions at the library (like crafts from mod, vanilla crafts)
3. Teleport system (first player must place teleport hub (room) to select needed transport at the "teleport console")
4. Easter egg.
5. MRU (from Essential Craft) support.

**Comment by DarkholmeTenk** [comment]
1. Nope
2. Such as?
3. Transmat?
4. Maybe there already is?
5. Can't find any api, gave it a very very quick glance, but I'll look again when I've got time
