### ISSUE TITLE
[ENHANCE] Screwdriver - ProjectRed

### ISSUE THREAD

**Issue by Soyaro666** [DarkholmeTenk/TardisModIssues#228]
actually the title says what I want to be enhanced and with what I want it to be enhanced.

The sonic screwdriver doesn't act as a screwdriver for ProjectRed which is a little bit confusing I think...
Sorry if this suggestion is a duplicate, I'm not aware if it already is around here...

**Comment by handicraftsman** [comment]
Also it doesn't work as wrench from AM2.

**Comment by DarkholmeTenk** [comment]
It isn't possible nor sensible to make it work as a wrench from AM2, as far as I'm aware

**Comment by Soyaro666** [comment]
I don't even know what AM2 is... O.ô

edit: Ah, Ars Magica. There has been a request around for the screwdriver as a thaumcraft wand which got refused too. the screwdriver isn't a magical device and I don't think this will change ever...

**Comment by DarkholmeTenk** [comment]
That plus I'm pretty sure the ars wrench thing has its own code and can't just be implemented with a simple interface :P

**Comment by Soyaro666** [comment]
what ever. did you think about ProjectRed screwdrivers yet?

**Comment by DarkholmeTenk** [comment]
I'll have a look to see if I can find an api, when I can

**Comment by Werner1201** [comment]
I think the screwdriver could have sort of a GUI (I know that you consider GUIs BLASPHEMY but What can I do it's a Idea :v ) Because if notice in the Doctor who series he (the doctor ) uses the screwdriver to analize everything and then he looks at it  to take conclusions ,So I think it could have more uses having a GUI. And don't work in the exact same time on wood just after a long time has passed.
And sorry for any grammar errors

**Comment by FoxPotato** [comment]
The sonic should not have a gui, it doesn't have a screen in the show so guis wouldnt be possible. And a text message would be enough in most cases. For example, right clicking a roundel with a liquiduct interface gives you a message how much mb is occupied/left

**Comment by PrincessOfEvil** [comment]
Why text? Make it color-coded.

**Comment by FoxPotato** [comment]
What do you mean?

**Comment by PrincessOfEvil** [comment]
Change color of sonic's lights.

**Comment by FoxPotato** [comment]
They already do, they tell you which function you're using. And it's not as precise.

**Comment by PrincessOfEvil** [comment]
Exactly.

**Comment by FoxPotato** [comment]
What. I dont get you at all right now. The guy suggested a sort of analyse function i guess. Ehich then gave you a gui. But then i said, the sonic doesnt have a screen of some sorts so it would be more logical if it use text. Usually in the show the doctor puts it to his ear and listens to it.

**Comment by DarkholmeTenk** [comment]
Decided to narrow the issue to something I plan to look into.

**Comment by Soyaro666** [comment]
I just wanted to say Thank you, @DarkholmeTenk 
ProjectRed Screwdrivers have a durability that's going down very fast. And they are nearly useless because they can't be used for any other mod. including the logic issue (a sonic screwdriver that didn't work as screwdriver) you solved 3 issues players could have with ProjectRed. Thank you for that. I hope the work was worth for you too.

**Comment by DarkholmeTenk** [comment]
As a note, I will haven't had the chance to test whether or not it actually works.

**Comment by Soyaro666** [comment]
I am able to turn ProjectRed logicgates which I previously wasn't so the most important function is there ^^
