### ISSUE TITLE
roundels multiplying items

### ISSUE THREAD

**Issue by squall2044** [DarkholmeTenk/TardisModIssues#230]
Whenever I send something through the Tardis piping all of a sudden I have 64 of them.

**Comment by Soyaro666** [comment]
an important information would be the version of tardismod and darkcore you're using. what pipes do you use to connect to the roundels?

**Comment by squall2044** [comment]
darkcore-0.25-35
tardismod-1.7.10-0.985-178
and im using impulse itemducts

**Comment by Soyaro666** [comment]
both got updates since then. could you try to reproduce with nevest versions? http://darkcraft.io:8080/

**Comment by squall2044** [comment]
i will didn't realize there was an update

**Comment by FoxPotato** [comment]
Most people dont. There should be like a warning that u should update before posting a bug :p

**Comment by squall2044** [comment]
even with darkcore-0.25-37 and tardismod-1.7.10-0.985-187 the items are still duplicating themselves

**Comment by Soyaro666** [comment]
hmmm... I can't reproduce it with usual Itemducts. I'm using roundels in my survival savegame without any problems but the Items I'm sending through it aren't stackable to 64.

what items are you using for tests?

**Comment by squall2044** [comment]
try grass just turned 28 of them into 1700

**Comment by laz2727** [comment]
Try updating TE. Both of you.

**Comment by squall2044** [comment]
this will take a bit as i have to update forge as well

**Comment by Soyaro666** [comment]
laz2727 why should I install another version of TE? It's working fine for me. Beside that I can't find a DL with a higher version number than the one I'm already using.

**Comment by laz2727** [comment]
Because every pipe mod has serious bugs on launch.

**Comment by squall2044** [comment]
still doing it updated to forge 10.13.4.1448 and the latest thermal foundation, expansion, and dynamics as well as the latest darkcore and tardis mod

**Comment by squall2044** [comment]
inside to outside and outside to inside seem to work just fine its when im trying to move things around inside the tardis to somewhere else inside the tardis

**Comment by Soyaro666** [comment]
could you post a complete list of your mods? I want to compare it to my mods list...
windows cmd: dir /B > mods.txt (running in your mods-folder) will generate a txt-file with all your mods

**Comment by squall2044** [comment]
there are five folders at the top which I deleted from the list.
the list is as follows:
Aroma1997Core-1.7.10-1.0.2.13.jar
Baubles-1.7.10-1.0.1.10.jar
BetterChests-1.7.10-1.1.1.9.jar
BiblioCraft[v1.10.4][MC1.7.10].jar
buildcraft-7.0.11.jar
ChickenChunks-1.7.10-1.3.4.16-universal.jar
CodeChickenCore-1.7.10-1.0.4.29-universal.jar
CoFHCore-[1.7.10]3.0.3-303.jar
ComputerCraft1.73.jar
CustomNPCs_1.7.10d.jar
darkcore-0.25-37.jar
Draconic-Evolution-1.7.10-1.0.1c.jar
DynamicLights-1.7.10.jar
DynamicTransport-0.1.2.0.jar
EnderIO-1.7.10-2.2.8.381.jar
Extra-Utilities-Mod-1.7.10.jar
Galacticraft-Planets-1.7-3.0.12.344.jar
GalacticraftCore-1.7-3.0.12.344.jar
Hide Names-1.7.10-1.1.8.jar
HoloInventory-1.7.10-1.9.0.108.jar
InvisibLights-2.3-7.jar
MicdoodleCore-1.7-3.0.12.344.jar
mod_worldeditwrapper_1.2.0_we5.6.2_mc1.7.10.litemod
More-Planets-1.7.10-1.2.9.jar
MorePistons-1.7.10-1.5.2.0.jar
NotEnoughItems-1.7.10-1.0.4.90-universal.jar
Numina-Mod-1.7.10.jar
ObsidiPlates-1.7.10-universal-3.0.0.18.jar
ProjectSuperhuman - v1.2 - 1.7.10.jar
RedstonePasteMod-1.7.10-1.6.2.jar
Reis-Minimap-Mod-1.7.10.jar
RenderPlayerAPI-1.7.10-1.0.jar
secretroomsmod-1.7.10-4.7.1.413.jar
SGCraft-1.9.3-mc1.7.10.jar
simplycurrency-1.0.0.jar
SlimevoidLibrary-2.0.4.7.jar
StevesCarts2.0.0.b18.jar
Tall-Doors-Mod-1.7.10.jar
tardismod-1.7.10-0.985-187.jar
TerritorialDealings_1.7.10_b9.jar
ThermalDynamics-[1.7.10]1.1.0-161.jar
ThermalExpansion-[1.7.10]4.0.3B1-218.jar
ThermalFoundation-[1.7.10]1.2.0-102.jar
ttCore-MC1.7.10-0.1.0-67.jar
Waila-1.5.10_1.7.10.jar
WailaHarvestability-mc1.7.x-1.1.2.jar
WAILAPlugins-MC1.7.10-0.0.1-15.jar
WorldEdit-CUI-Mod-1.7.10.litemod
WR-CBE-1.7.10-1.4.1.9-universal.jar
[1.7.10] SecurityCraft v1.7.4.1.jar

**Comment by Soyaro666** [comment]
I thought this could be a Mod conflict and if you had a few other mods than me I could say which one could cause the problem. Unfortunately you only have 6 mods that have been aproved by me to not causeing your problem.
Those are:
BiblioCraft
EnderIO
StevesCarts
ttCore
Waila
WailaHarvestability

I simply don't know your other mods...
try to update all of them, try to reduce your mods (playing singleplayer/creative) while you're removing your mods one by one and IF this is a mod conflict you'll find out where the problem comes from sooner or later... that's all I can do. Does someone have better ideas?

**Comment by DarkholmeTenk** [comment]
Try to replicate this with just tardismod and thermal dynamics (and their prereqs).

**Comment by squall2044** [comment]
I updated everything and pulled a few (almost half) of the mods out and it seems to have settled
