### ISSUE TITLE
[ENHANCE] Monitor to select short distance travels ?

### ISSUE THREAD

**Issue by Werner1201** [DarkholmeTenk/TardisModIssues#232]
I have been playing Garrys mod and I saw that the tardis mod of the garrys mod have a monitor to select on the map a location to teleport (or travel ) I will attact some images for to see the model. I'm asking this because When I got to a high level on the tardis I have to still move a lot to move to some place close . And I think if I have high tardis level all this work should be reduced . 
![2015-07-29_00003](https://cloud.githubusercontent.com/assets/8631657/8959909/ba8c023e-35e3-11e5-9822-6802105f8ca9.jpg)
![2015-07-29_00006](https://cloud.githubusercontent.com/assets/8631657/8959912/c14f5f76-35e3-11e5-846f-8198806895ee.jpg)
![2015-07-29_00007](https://cloud.githubusercontent.com/assets/8631657/8959913/c16cacfc-35e3-11e5-8840-a6fe2b0adc15.jpg)
![2015-07-29_00008](https://cloud.githubusercontent.com/assets/8631657/8959914/c1732636-35e3-11e5-9f86-fedbc383f942.jpg)
![2015-07-29_00009](https://cloud.githubusercontent.com/assets/8631657/8959915/c173eea4-35e3-11e5-87ae-0ed7ae8b77ff.jpg)
![2015-07-29_00001](https://cloud.githubusercontent.com/assets/8631657/8959916/c1767b10-35e3-11e5-853c-50000f22d940.jpg)
![2015-07-29_00002](https://cloud.githubusercontent.com/assets/8631657/8959917/c17b92d0-35e3-11e5-8a74-461ebad9ffb6.jpg)
![2015-07-29_00003](https://cloud.githubusercontent.com/assets/8631657/8959918/c17e590c-35e3-11e5-8053-4ca445604655.jpg)
![2015-07-29_00004](https://cloud.githubusercontent.com/assets/8631657/8959919/c18a81f0-35e3-11e5-9259-1ea5af059759.jpg)
![2015-07-29_00005](https://cloud.githubusercontent.com/assets/8631657/8959920/c18c69a2-35e3-11e5-9f11-37b90e8402c8.jpg)

**Comment by Werner1201** [comment]
And Know that You HATE GUIs but You can't Run all your life

**Comment by FoxPotato** [comment]
It wouldn't really be useful tho. Just flick a lever or 2 and you're there.
The only reason gmod has that is because of the small sizes of maps.

**Comment by DarkholmeTenk** [comment]
When you actually work out how the controls work, making very small jumps is pretty easy to do. Also if it's a location which you travel to often, that's what the bookmarks are for.
Also, isn't running pretty much dr who's central theme?
Hence https://www.youtube.com/watch?v=BAi4izfvXo4
