### ISSUE TITLE
tardis roundels - just a question

### ISSUE THREAD

**Issue by Soyaro666** [DarkholmeTenk/TardisModIssues#235]
I'm writing here instead of MCF PM because it could be interesting for others.

How many different types of items can be stored in Tardis wires/roundels? I know I have at least 1 stack of coal in there for my generators but roundels are still able to transport items into my food storage so I have more than one item at a time traveling. I'm thinking about keeping more than one type of item ready for other things but I need to know if that would stop my farm from working...

**Comment by DarkholmeTenk** [comment]
Pretty sure it's configurable, but it won't let you put any more than one stack of a single item type in

**Comment by handicraftsman** [comment]
Привет, мир!)

**Comment by Soyaro666** [comment]
And what about fluids? multiple possible at the same time? just had a little trouble receiving lava while transfering water otherwhere and I'm not sure if it's been the Tardis that didn't let me or me who isn't intelligent enough to use fluiducts properly ;-)

**Comment by Soyaro666** [comment]
finally I found these values in misc.cfg:
30 item slots, 6 tanks (each with space for 16 Buckets) and 50000*Tardis-Level RF storage. Very nice!
