### ISSUE TITLE
[ENHANCE] Enable/disable schemas on-the-fly and/or schema-as-an-item

### ISSUE THREAD

**Issue by liftoff** [DarkholmeTenk/TardisModIssues#236]
I have this great idea for a Modpack of sorts where you start out with a TARDIS and need to "unlock" rooms to make your way through the story.  It would be absolutely awesome if there were a way I could include a bunch of schemas in the modpack but players can only unlock or otherwise obtain them after completing a quest, as dungeon loot, or similar.  I just need a way to enable/disable schemas or add them to a TARDIS via an item.

What do you think?

**Comment by DarkholmeTenk** [comment]
See #11

**Comment by liftoff** [comment]
You know, I looked and for some reason that title didn't register in my mind as being the same thing...  But upon reading it it's obviously the same sort of request.  I'll close this one out and refer to #11 from how on.  Thanks for being nice about it :+1:
