### ISSUE TITLE
[ENHANCE] Roundel interfaces and informations

### ISSUE THREAD

**Issue by Soyaro666** [DarkholmeTenk/TardisModIssues#238]
1.: better Fluiduct Interface
I had some trouble with them recently. I had water, lava and fuel (Buildcraft) in my roundels and wanted to pull out fuel. since it was the last I sent in I had to empty all lava and water first before my Tardis allowed me to access the fuel. The easiest I could imagine would be completely removing the interior tanks so a fluid can only enter a roundel if another roundel is available where that fluid can go out (maybe trying to send a mb of it out before actually accepting the input?). Instead of this better support for thermal expansion filters would be nice if it's possible. So if I activate a servo with a whitelist the Tardis actually provides the whitelisted fluids instead of blocking everything because it want's to release another fluid first. I guess the "better support" would need some more interaction from a servo which probably isn't there right now.

2.: Redstone Interface
this point would be a duplicate of #196 where we suggested 3 different interfaces: one that provides a redstone signal if the Tardis is connected to a landing pad, one that tunnels a redstone signal and one that tunnels a bundled cable from ProjectRed. I mentioned and summarized it because there never were a reaction from @DarkholmeTenk

3.: Computercraft Interface
I'm aware this has been mentioned in some topics but since I didn't see anyting like that ingame and there is no own topic for it I decided to add it here. I could think of two variants. One to simply tunnel a network cable or maybe act as a wireless rednet repeater and one that actually communicates with the Tardis. The last one could allow to read informations about what's in roundels (name and amount of everything in there), what the panels, screens and so on in console room are saying (rooms, exp, skill points, you got the idea), what coordinates are set currently and so on. I don't think about any interaction, I only would like to have a screen with informations where I need such informations (for example my machines aren't near my engines so if my RF level becomes low I would like to know before my machines stop working)

**Comment by DarkholmeTenk** [comment]
The problem with support for TE filters is that there is a method which I implement correctly
`public FluidStack drain(ForgeDirection from, FluidStack resource, boolean doDrain)`
which allows you to specify the fluid to drain using the fluidstack parameter, but as far as I can tell, TE just calls
`public FluidStack drain(ForgeDirection from, int maxDrain, boolean doDrain)`
which from the TARDIS's point of view just means drain from the first non-empty tank; TE then checks "is that the fluid I want" rather than actually using the more appropriate method :p

**Comment by DarkholmeTenk** [comment]
3 & 2 already exist
1 is done
