### ISSUE TITLE
AE2 Intergration Derpiness

### ISSUE THREAD

**Issue by ruifung** [DarkholmeTenk/TardisModIssues#240]
From my post on Minecraft Forums:

```
If theres a security terminal without a default build permission granted, roundels with ME cable
interface may cease to work - and new roundels with ME cable interfaces will completely not be linked
to the network at all. I suspect the player placing the ME cable interface isn't being passed to the AE
network when adding the node - hence it gets rejected.
```

**Comment by Soyaro666** [comment]
at least it doesn't crash the game. That did it when I tried to connect my ME System with Security Station with a logistics pipes system. infinite loop of request and refusion, I had to delete that savegame.
Why does your ME System need a security station when it's in your Tardis? Couldn't you simply lock the door?

**Comment by DarkholmeTenk** [comment]
Even if you can just lock the door, it's still an issue :P

**Comment by Soyaro666** [comment]
of course it is, I just wanted to suggest a workaround until you had time to fix the problem ;-)

**Comment by ruifung** [comment]
Thats because without a security station you cant use wireless terminals? And my network extends outside the tardis by way of QNB's since there are some setups that are more efficient in a desert biome for example.

**Comment by Soyaro666** [comment]
Ah, didn't know about wireless terminal dependencies. last time I used that terminal was MC 1.4.7, there it didn't need anything more than a connection to my drives. 'til this got fixed you could try to use logistics pipes. that mod has a remote requester that works interdimensional. unfortunately it requires a lot of space. and you sould test it in singleplayer because this constellation could damage the world...

**Comment by ruifung** [comment]
Nah I'll stick with a wireless terminal, since I'm mainly playing on a 2 player server security isn't a problem - although I can imagine this being a problem on public servers.

**Comment by DarkholmeTenk** [comment]
Should be fixed in DS build? Uncertain, but I can't replicate it.
