### ISSUE TITLE
"No room for schematic" when there's definitely room?

### ISSUE THREAD

**Issue by NefariousPrime** [DarkholmeTenk/TardisModIssues#242]
I'm running Minecraft 1.7.10, as that's the latest version this works with, to my knowledge.  I wanted to shift some doors around while I was making a farm in my TARDIS, and even with space behind the nine blocks, I keep getting a "not enough room for schematic".  I experimented with my other doors, and it seems they lose viability when I knock out the blue block, even if I replace it with another blue cross "Door" block.  I saw some others had this issue but it went away for them when I looked on Reddit, anyone else know what I can do or what I'm doing wrong?

**Comment by DarkholmeTenk** [comment]
The blue blocks have metadata which determines their orientation. The metadata is set when the schematic is loaded into the world. Simply moving the door blocks won't change that, you'd need to redo the schematic.

**Comment by NefariousPrime** [comment]
I had one door untouched on the left side of my control room, with a tiny corridor loaded in my screwdriver, and I tried knocking the block out and replacing it in the same position, after which it gave me the same message.  I also experimented with a room past my library down an elevator that would load a schematic, and wouldn't after I'd replaced the block, and I had to delete the first room to do so.  Does the metadate govern those situations as well?  I don't know much about the coding and inner workings of the mods personally.

**Comment by DarkholmeTenk** [comment]
But when you replace the block, you change the metadata. If you want to replace it in the same place, breaking the block right clicking the control panel should cause it to recheck all the doors and fix the missing bits

**Comment by NefariousPrime** [comment]
Sorry for asking so many questions about it, some of the documentation didn't click for me when I first read it.  Are you saying I should right click a replaced door block with the screwdriver, or right click the center console in the TARDIS with the screwdriver to fill in the missing metadata?

**Comment by DarkholmeTenk** [comment]
Right click the control panel in the middle of the room to fix doors with holes in the middle. It won't fix doors that are in a different place than expected though.
If you want to modify the doors, you should make a new schema for it.

**Comment by NefariousPrime** [comment]
Got it, will try.  And from when I researched it, you can alter schemas with a /tardis command to see how they look in the game, and then modify them in creative, correct?  Thanks again, sorry for the trouble.

**Comment by DarkholmeTenk** [comment]
Yup, make sure you've got visible schema boundaries in your configs and then do
`/tardisload <SchemaName> <x> <y> <z> 0`
but SchemaName can't contain any spaces, so you may need to rename some files to load the schema you want.
Doors have to line up with the edge of the schema
There needs to be 1 and only 1 primary door
then do
`/tardissave <NewSchemaName> <x> <y> <z>` where x, y, z is the coords of the schema core.

**Comment by NefariousPrime** [comment]
Okay, but this won't be able to change the door for a room I've already modified, will it?  It'll just change the layout for if I load it at another door?

**Comment by DarkholmeTenk** [comment]
Pretty much, yeah. There's not really anything you can do for a schema core that's already loaded into the world.

**Comment by NefariousPrime** [comment]
Well, it might work out anyways, because somehow my TARDIS glitched, spat me out in the overworld, and won't let me back in.  I was trying to delete a small corridor to get right back to the control room, accidentally did sneak when I first clicked, and was then surrounded by door blocks.  Then tried to delete it proper, when it spat me out, but just a bit further away from my base, and won't let me back in.  My screwdriver got taken down to the first three basic modes (I'd gotten it up to Recall), and a Recaller block does nothing for it.  

I think I'll just start a new world and work from there, I'm guessing I could up the level of my TARDIS with a console command, but if it's being buggy, it might be better to start anew. ;~; Thanks again, I'll remember the schemas for when I start again, I suppose.

**Comment by DarkholmeTenk** [comment]
Sounds like you accidentally deleted the time rotor somehow :P

**Comment by NefariousPrime** [comment]
Ugh, I wasn't even on the same level as the control room, I made a library, then corridor, then elevator, then the smaller ones. >~< Whatevs, it's a learning process.  Thanks, and I had one more small question unrelated to this, that I hope isn't too much trouble to answer.  I'm gonna try using this mod on a server with a friend, and she's not much into DW, but likes the idea.  Is it possibly to alter the colors of her TARDIS at all, with a design or at least not only blue (Blasphemy, I know, but still. :P)?  That should be my last question, thanks again.

**Comment by DarkholmeTenk** [comment]
If you have a web server, you can host player skins and modify one of the configs to change where it gets skins from. E.g. http://skins.darkcraft.io/tardis/DarkholmeTenk.png is my TARDIS skin
Interior colours can be changed with dyes.

**Comment by NefariousPrime** [comment]
Thanks very much!  Dunno how to do an uprating on these things, but you helped a lot, hope things go well with future projects!
