### ISSUE TITLE
Regenerate Tardis Dimension

### ISSUE THREAD

**Issue by scarredFalconer** [DarkholmeTenk/TardisModIssues#243]
Hello,

I made a Tardis Key and spawned my Tardis, but when I entered, a Tinker's Construct Slime Island had overwritten a portion of the controle room and one of the doors to another section.  I tried to find a way to recreate the dimension but could not find it in the save file (there was a folder labled "tardis" with a DIM3 inside of it, which I deleted). Long story short i  tried to recreate the dimension and failed, popped into creative, broke the tardis and tried to spawn in another (my key won't work anymore, the mod thinks I already spawned one in) so whenever I try to enter i get the " You already own a TARDIS"  I don't understand why it is saying this after I reinstalled the mod.  Help me please.

Thanks,
SF

**Comment by DarkholmeTenk** [comment]
Use the treg command to delete the dimension registry entry for yourself

**Comment by DarkholmeTenk** [comment]
Due to this being a ticon generation thing, I'm considering this not a bug. Overworld only slime island generation is everybody's friend, though :P
