### ISSUE TITLE
Unintentionally changing external door mode.

### ISSUE THREAD

**Issue by ruifung** [DarkholmeTenk/TardisModIssues#244]
When I'm flying (creative style), when descending holding shift, and right clicking the door with empty hand - it will change the mode of the door even though I'm not holding a key, if it's intentional - it shouldn't happen while im flying in survival mode (with the botania flight thingy)

**Comment by DarkholmeTenk** [comment]
Changing the door on the inside without a key is intentional; it's just a latch. See the end of Utopia for example. Don't see why it shouldn't happen while flying?

**Comment by ruifung** [comment]
Oh ok, my bad!

**Comment by DarkholmeTenk** [comment]
It's cool :)
