### ISSUE TITLE
[BUG] Can dismantle other peoples roundels, but no permission to

### ISSUE THREAD

**Issue by Jwtc2000** [DarkholmeTenk/TardisModIssues#247]

**Comment by DanNetwalker** [comment]
I had a similar "bug" this week. Could you please check if the player doing this was in creative, and if the bug happens only when the player is in creative?

**Comment by DarkholmeTenk** [comment]
This is a legitimate bug, @Jwtc2000 is one of my testers and discussed it with me on teamspeak :)

**Comment by DanNetwalker** [comment]
...sorry. It doesn't look like I'm helping a lot since I got here... -_-U

**Comment by DarkholmeTenk** [comment]
Don't worry about it, you've made some good suggestions :)

**Comment by DanNetwalker** [comment]
I haven't found a source code repository for the mod. Is there one arround I can check for this kind of things before asking something that's already implemented?

**Comment by DarkholmeTenk** [comment]
There is one, but it's private atm, see #93

**Comment by DarkholmeTenk** [comment]
Fixed
