### ISSUE TITLE
[ENHANCE] admin command to "rename" dimensions

### ISSUE THREAD

**Issue by DanNetwalker** [DarkholmeTenk/TardisModIssues#251]
How about an admin command to "rename" a dimension? 

For example, in a mystcraft enabled server, some admin could want to name certain mystcraft dimensions as different locations on the series.

**Comment by DarkholmeTenk** [comment]
There is no setName method I could call, it's entirely up to the dimension what it returns from the getDimensionName() method.
I know RFTools returns whatever you've named the dimension when it was created. Does mystcraft not do the same?

**Comment by AlienXtream** [comment]
an alternative to this is if there was a config file where you put in a DIM id and a "display" name. this would only affect the tardis labeling. an example of how this is useful is the twilight forest. it has no name just an ID

**Comment by DanNetwalker** [comment]
No need for the dimension name to actually change out of the Tardis mod, it could be something that's local to your mod since I still haven't found a way to get a dimension's name in other mods (save for the dimension creation book in mystcraft and only for mystcraft dimensions, that's it).

I could use a config file, too. As long as there's a command to reload that config file... you don't need to stop a server to create new mystcraft dimension, you shouldn't need to restart the server to name it.

**Comment by DarkholmeTenk** [comment]
Display names is doable :)

**Comment by DinixM** [comment]
I'd like to see this, either implemented through the Console or the chat console. Could be fun.

**Comment by DarkholmeTenk** [comment]
Now doable using "/dcd world rename <dimID> <newName>" setting the name to "null" or "" will reset it to its defaults.

Note this is a feature of the latest darkcore, so will be dependant upon that.
