### ISSUE TITLE
[BUG] A permissionless player can change the control room schematic

### ISSUE THREAD

**Issue by DanNetwalker** [DarkholmeTenk/TardisModIssues#252]
A captain of a Tardis can change the control room schematic of another Tardis even withough any permissions (we haven't tried with a player that doesn't own a Tardis, but I presume the same will happen). 

Not too problematic, except that both twelvish control rooms have the door connections in different places, so it could potentially cut a timelord from his/her control room if down a corridor, forcing to create and destroy a room to get back..

**Comment by DarkholmeTenk** [comment]
``` java
                if (ds.hasPermission(pl, TardisPermission.ROOMS))
                {
                    if ((prevLastButton != 73) && pl.isSneaking())
                        lastButton = -1;
                    else if ((prevLastButton == 73) && !pl.isSneaking())
                        lastButton = -1;
                    else if (prevLastButton != 73)
                    {
                        ServerHelper
                                .sendString(pl, "ENGINE",
                                        "Warning: Changing console rooms may replace blocks. Please right click, then sneak-right click this button to proceed");
                    }
                    else
                    {
                        core.loadConsoleRoom(sanitiseConsole(consoleSettingString));
                    }
                }
                else
                {
                    lastButton = -1;
                    ServerHelper.sendString(pl, "ENGINE", CoreTileEntity.cannotModifyMessage.getFormattedText());
                }
```

Are you sure? The player isn't in creative mode or anything, right?

**Comment by DanNetwalker** [comment]
I'll test again in case creative was the reason. But appart from being an OP, I don't see anything else special in the player.

**Comment by DarkholmeTenk** [comment]
the only reason that code should ever be able to run is if ds.hasPermission(pl, TardisPermission.ROOMS) is true, which should only be the case if the player is in creative or has the rooms permission

**Comment by DanNetwalker** [comment]
Ok, strike this one out. The only way I found to recreate the bug is by being in creative. Thanks!
