### ISSUE TITLE
[BUG] Tardis Dim chunk loading

### ISSUE THREAD

**Issue by AlienXtream** [DarkholmeTenk/TardisModIssues#254]
i don't know what caused this but all of a sudden the tardis dimension unloads, preventing the tardis from completing its flight sequence when activated from outside (recall). im sorry i cant provide and more info but a sugested fix, if not already implemented, would be to make the console is self force chunkload. 

my solution, i "cheated" (due to a bug imo) in a chunkloader and bumped the radius up to encompas the console room

NOTE: tardis dim always loaded is set to true.

**Comment by DarkholmeTenk** [comment]
Tardis console is always loaded if darkcore is working. Only time it might not be is the first time the server loads, there's a bug preventing chunks that were loaded from being reloaded sometimes.

**Comment by AlienXtream** [comment]
ok, assuming this was a unique circumstance problem

**Comment by DarkholmeTenk** [comment]
It was pretty easy to replicate. When outside your tardis, go outside player loading distance. Restart server. Tardis interior was then unloaded. _Should_ be fixed with the latest darkcore :)
