### ISSUE TITLE
[ENHANCE] Waila integration for the Tardis' outside

### ISSUE THREAD

**Issue by DanNetwalker** [DarkholmeTenk/TardisModIssues#255]
I was thinking it would be great if you could tell my Tardis from another player's withough entering it. 

Chameleon circuit to change skin or colour may be a little too much (yes, yes, "do not blaspheme", I know), but if I could put the crosshair in a Tardis and read "owner: playername" in Waila, it would be great.

**Comment by DarkholmeTenk** [comment]
Skins are already in place, chameleon circuit is fuihfuiw
Waila will be done
