### ISSUE TITLE
[ENHANCE] A way to turn Tardis' solid blocks into glass blocks and reverse

### ISSUE THREAD

**Issue by DanNetwalker** [DarkholmeTenk/TardisModIssues#256]
I've found myself and other of my server OPs getting into creative just to change glass blocks for solid in each of our Tardis.

In my case, I really don't like to "see outside" of the tardis. It breaks the ilusion for me). For others in my server is the oposite, they run chisel's circuit like blocks on the outside and they want them visible through windows "into the manteinance areas". 

The second case will still need creative, but it got me thinking... could you please make a tool or sonic screwdriver mode where you can turn the glass blocks into solid ones, and viceversa?

(EDIT: slightly less apache-like wording; sorry)

**Comment by handicraftsman** [comment]
Mmmmmm....

**Comment by ruifung** [comment]
or... generally make the textures of the blocks customizable too =P so you can have walls that appear to be made out of any arbitary block =P

**Comment by DarkholmeTenk** [comment]
I may add a thing to change glass to flat/solid blocks, I'm definitely not making every single block in the TARDIS a tile entity (which would be needed for @ruifung's suggestion)

**Comment by ruifung** [comment]
Huh, that would come under the heading of a bad idea hmm? =P

**Comment by DarkholmeTenk** [comment]
Nice idea; not great to implement :P

**Comment by DarkholmeTenk** [comment]
Dun (DS branch)
