### ISSUE TITLE
[ENHANCE] admin commands

### ISSUE THREAD

**Issue by DanNetwalker** [DarkholmeTenk/TardisModIssues#258]
I see this as a feature for moderators. Some admin commands:

-Enter any player's Tardis, by the player name
-Check if a player has a Tardis, by the player name. The command responses "no tardis" or "Level xxx Tardis on dimension d, coords x,y,z".
-List of a player's Tardis latests parking coords, by tthe player name. A last ten positions list would be great. Even better if it had real world date and time of the event.

**Comment by handicraftsman** [comment]
Goooooddd

**Comment by DarkholmeTenk** [comment]
"/ttp #PlayerName" Teleports you to that person's tardis core
"/treg list" shows who has tardis and what dimension ids they are
"/dcd cl list TardisTileEntity" shows all that tardis exteriors that are being chunk loaded
I don't even store landing events or a list of landing positions or anything :P

**Comment by micmou** [comment]
Can we get a list of all available commands?

**Comment by DanNetwalker** [comment]
/ttp playername only appears to work if the player is inside his/her Tardis. I was thinking of "if the player has a Tardis, go to the main room" no matter if the player is online, offline, already banned or whatever.

**Comment by DarkholmeTenk** [comment]
you misunderstand
/ttp playername teleports you to playername
/ttp #playername teleports you to playername's console room

**Comment by DanNetwalker** [comment]
Oh, the hash! Thanks, I'll try it.

**Comment by DanNetwalker** [comment]
Working like a charm. For the list of parking position, could you consider sending to log a "Tardis x landed at dimention D, coords X, Y, Z" message? That's enough for a simple grep to check who parked his Tardis into a bedrock block...

**Comment by DarkholmeTenk** [comment]
It shouldn't be possible to park in bedrock, but I'll add a log eventually :P

**Comment by DarkholmeTenk** [comment]
Pretty much done.
