### ISSUE TITLE
[ENHANCE] Crash landings 

### ISSUE THREAD

**Issue by AlienXtream** [DarkholmeTenk/TardisModIssues#262]
when flying to fast or pressing to few buttons the tardis "rematerealizes" in a laying down position in the middle of a crater (greifing configurable) with smoke particles and a hissing sound. 

P.S whilst typing this i realize that shot of a complete rework of how the tardis exterior is handled that having the tardis actually crash is a bit to much work (though go for it if you ever feel like a challenge :P)
and thus this idea probably goes under the "yeah...no" category. but still, a cool idea no less.

P.P.S how hard would implementing some camera shake and player staggering be?

**Comment by Jwtc2000** [comment]
https://www.youtube.com/watch?v=znGBU5oODz8

**Comment by AlienXtream** [comment]
how so, no GUI's would be implemented...

**Comment by DarkholmeTenk** [comment]
Sideways would require a bit rewrite of how the landing code works :P
The current plan is for crash landings to make the exterior smoke a lot.
Camera shake is feasible, but from my experience trying to fly the tardis in FOWV, camera shake just makes things really hard and awkward.

**Comment by Jwtc2000** [comment]
@DarkholmeTenk http://i.imgur.com/ssBZhCs.gif

**Comment by DarkholmeTenk** [comment]
TARDIS force lands when damaged. No smoke, but oh well.
