### ISSUE TITLE
[BUG] Transmat-entities not appearing in tardis

### ISSUE THREAD

**Issue by AlienXtream** [DarkholmeTenk/TardisModIssues#264]
i was flying around searching for cows, sheep and such and i went back to review my stock only to find that out of a dozen cows, 3-4 sheep and a couple chickens and pigs i had only 3-4 cows in the tardis. changing the transmat point didn't help and nor did making a new game. the bug persists even now and i have no idea whats going on. is there a way to get any debug output for the transmat feature? 

all know info: bug started spontaneously in a world and persists to new games
                      appears to affect all entities ruling out de-spawning

**Comment by DarkholmeTenk** [comment]
SSP or SMP?

**Comment by AlienXtream** [comment]
single player, im actualy launching MC now to see if it happens with a names mob

**Comment by AlienXtream** [comment]
confirmed, named mob vanishes with no death message (thats a thing in 1.7 right, named mobs that die print to chat?)

**Comment by DarkholmeTenk** [comment]
Yeah, I'm not sure why it doesn't work; it's not that the mob dies, I'm not sure if it's that the mob doesn't spawn all the time? or if it's because of some other weird reason :p

**Comment by AlienXtream** [comment]
[STDOUT]: [io.darkcraft.darkcore.mod.helpers.TeleportHelper:teleportEntity:75]: [TTH]Teleport request: 2 > 10.5,69.0,0.5

that gets printed to console on transmat

**Comment by DarkholmeTenk** [comment]
So the teleport code in darkcore is definitely getting called, it's got to be a problem with it getting spawned or something; I'll look into it (feel free to help if you can spot anything https://github.com/DarkholmeTenk/Darkcore/blob/master/src/main/java/io/darkcraft/darkcore/mod/helpers/TeleportHelper.java )

**Comment by AlienXtream** [comment]
im no programmer but i DID spot something counter intuitive to my logic
ent.isDead = true;
wouldnt that "kill" the entitiy?

**Comment by DarkholmeTenk** [comment]
It deletes it, yeah, but we've already copied the entity and placed it in the other world

**Comment by AlienXtream** [comment]
ah ok, so its an issue before that event fires

**Comment by DarkholmeTenk** [comment]
That might work :P

**Comment by AlienXtream** [comment]
ok, will test it and report back

**Comment by AlienXtream** [comment]
nope

**Comment by AlienXtream** [comment]
it woks when transmating them out but not in
edit: in testing this i may or may not have accidentally dropped some baby sheep into the void...

**Comment by DarkholmeTenk** [comment]
How 'bout now?

**Comment by AlienXtream** [comment]
cant download the newer build

**Comment by DarkholmeTenk** [comment]
fixed :P

**Comment by AlienXtream** [comment]
yeh, just got it then

**Comment by AlienXtream** [comment]
appears to have done the trick, any idea what the issue was?

**Comment by DarkholmeTenk** [comment]
Didn't set the position of the entity before trying to spawn it in the world; caused the world to reject the spawning if it tried to spawn in chunks which didn't actually exist :P
Basically just set the position before spawning rather than the other way around

**Comment by AlienXtream** [comment]
ah, so basicly the spawning logic was the wrong way around :P
