### ISSUE TITLE
[ENHANCE] option for youtube safe alternative Tardis sounds

### ISSUE THREAD

**Issue by DanNetwalker** [DarkholmeTenk/TardisModIssues#267]
Ok, this is embarrasing. It appears if you get a video with the Tardis sounds to youtube, the BBC will block the video. Could we please have a config option for safer, more generic sounds?

**Comment by DarkholmeTenk** [comment]
But that doesn't make sense D: I got some of the sounds from https://www.youtube.com/channel/UCSvw5Amh6x9una6IYDlm7lA and this is all still up

**Comment by DanNetwalker** [comment]
I know, but I can asure you one of the players on my server has gotten his "end of season" video down by BBC. They shoot first, ask later... hmm, how american for a british company, actually :P

Anyway. maybe the solution is easier. Whould the mod use sounds loaded by a minecraft resource file? If yes, what sounds are needed?

**Comment by DarkholmeTenk** [comment]
Have a root around in the assets folder, they should be replacable :P

**Comment by DarkholmeTenk** [comment]
http://arstechnica.com/tech-policy/2015/09/eff-scores-a-win-in-long-running-dancing-baby-copyright-case/ if everything goes the way it should, fair usage should apply to this :)

**Comment by DanNetwalker** [comment]
Ok, appeal approved on the video. It looks like it's fair use, actually. Please close this issue, and thank you so much for the help!

Anyone having this problem, please refer to the original source of the assets and refer to fair use in the appeal.

**Comment by DarkholmeTenk** [comment]
Happy times :D

**Comment by Jwtc2000** [comment]
\o/
