### ISSUE TITLE
Tardis Mod potentially causing Mystcraft worlds to unload

### ISSUE THREAD

**Issue by kadamgreene** [DarkholmeTenk/TardisModIssues#269]
Steps to repeat:
1.  Take your Tardis to a Mystcraft world. 
2.  Place a Mekanism Digital Miner in a mystcraft world, set it to mine ore\* and start it, notice how much it says it has to mine (usually around 20,000 in my setup).
3.  Place chunk loader beside digital miner.
4.  Enter the Tardis
5.  Come back out, check the digital miner, it says 0 to mine and stopping it and starting it doesn't change anything.
6.  But picking it up and putting it back down fixes it.

I've already talked to XCompWiz and someone from the Mekanism team about the issue and they say that it is related to chunk unloading, XCompWiz says that Mystcraft obeys chunk loaders and Mekanism team says the problem is that the miner has lost the chunk.  Because of the last error I posted where Tardis causing a OOM exception and it involves Mystcraft in the stack, I'm wondering if Tardis my be the cause?

**Comment by DarkholmeTenk** [comment]
what chunk loader are you using? TARDIS exterior chunk loads 1 chunk around itself and entering your TARDIS shouldn't cause anything to unload.

Edit: With the latest version of darkcore and tardismod from the jenkins, can you do "/dcd cl list TardisTileEntity" and see if the exterior is still showing in the list of chunk loaders?

EditEdit: Also, saying 0 to mine and being unstartable sounds like a bad way to respond to being unloaded :P

**Comment by kadamgreene** [comment]
Chunk Loader from ChickenChunks.

**Comment by kadamgreene** [comment]
FYI:  Everything works properly in the Nether (I can go into the Tardis and see ores dug up by the Digital Miner appearing in my ME system).  I will test with the latest in Mystcraft world.

**Comment by kadamgreene** [comment]
I just noticed this in the logs:   The mod darkcore has attempted to allocate a chunkloading ticket beyond it's currently allocated maximum : 200

EDIT:  After this happens, it stops chunkloading the exterior and even the nether stops working when in the tardis.

**Comment by kadamgreene** [comment]
/dcd cl list TardisTileEntity returns:

World 0:-811,179,263 - tardis.common.tileents.TardisTileEntity@327b2f18

(This is in the overworld, but it does the same in all dimensions)

**Comment by DarkholmeTenk** [comment]
If it still shows the TTE when you're in the mystcraft dimension then as far as I can tell, it should work fine. As for getting too many tickets, I can only say wut? and I'll look into that, but it shouldn't stop other mods chunk loaders from working fine :P

**Comment by DarkholmeTenk** [comment]
Ok, so there was a bug where the things to chunk load from a server restart were never getting cleared from that list even when they were chunk loaded so they spawned infinite chunk loading requests.

There was a bug where worlds which are forcibly unloaded (e.g. the end :\ ) never had their tickets cleared, which they should have been.

There's now also a track of every ticket I allocate even if it's not mapped to an IChunkLoader and any which are not mapped to an IChunkLoader are released. There should be no more problems with running out of tickets.

Also, I can't replicate the issue with my chunk loaders not working and if another mods chunk loader isn't working, I don't think I'm the cause in any way.
