### ISSUE TITLE
[ENHANCE] spanish translation

### ISSUE THREAD

**Issue by DanNetwalker** [DarkholmeTenk/TardisModIssues#271]
Since I have no access to the git repo, would you kindly add this translation file? Already utf-8 encoded, should be drag and drop.

http://www.redblockers.tk/temp/tardismod/es_ES.lang

(The tk domains are not working as good as usual latelly, you may need to try again in some minutes for the domain to give signals of life)

**Comment by DarkholmeTenk** [comment]
Ta
