### ISSUE TITLE
[BUG] Permission light doesn't update when lever is pushed in

### ISSUE THREAD

**Issue by Jwtc2000** [DarkholmeTenk/TardisModIssues#272]
(Note: May not be reproducible)

**Comment by DarkholmeTenk** [comment]
Only occurs when removing the last permission someone has, it seems

**Comment by handicraftsman** [comment]
I know about this bug. Please, fix it)

**Comment by DarkholmeTenk** [comment]
Will do, only got back from a holiday for my bday last night though :P
