### ISSUE TITLE
[SUGGESTION] OreDict Dye Support

### ISSUE THREAD

**Issue by DinixM** [DarkholmeTenk/TardisModIssues#273]
I was wondering if implementing a new Dye to match the Tenthish theme would be at all possible. I really like that color, but it's impossible to get it outside the Console Room.
Also, on a more minor note, the Floral Powder dyes from Botania will not dye the TARDIS' blocks, where it is oreDict'd to work with most dye situations, like Wool blocks. Compatibility with the Painter's Lens might be helpful as well.
Anyways, love the mod and I'm glad to see it progressing so well!

**Comment by DarkholmeTenk** [comment]
95% certain the tenthish colours are obtained using cocoa/brown dye.
oreDict support is on the todo list

**Comment by Jwtc2000** [comment]
Milestone?  ( ͡º ͜ʖ͡º) @DarkholmeTenk

**Comment by Jwtc2000** [comment]
:tada:

**Comment by DinixM** [comment]
Is it? I didn't think of that, I tried orange. Derp. 
Side note: My gods, you're fast :D

**Comment by DarkholmeTenk** [comment]
Yep. It depends when I'm online though; I'm off to London for a few days for my bday so expect response time to drop a bit

**Comment by Jwtc2000** [comment]
:tada:  :birthday: :balloon:   :tada:

**Comment by DinixM** [comment]
Sounds awesome. Let's hope inspiration flows from the locale, amirite? ;) Either way, happy birthday!
