### ISSUE TITLE
Lab

### ISSUE THREAD

**Issue by Blobfish1** [DarkholmeTenk/TardisModIssues#274]
I can't seem to make one, I put a chest on the ground, lab in middle, and hopper on top; but when I put anything in the hopper, nothing happens. Am I doing something wrong?

**Comment by ruifung** [comment]
Did you do it inside a tardis? And depending on what you are trying to make, you might need to be inflight.

**Comment by Blobfish1** [comment]
It was inside the tardis and I only tried making dalektonium or whatever which you don't need to use in midflight

**Comment by AlienXtream** [comment]
the lab needs to be powered vy the time vortex. put the tardis in drifting mode and take off, the lab will function. if the line in the middle is grey, right click to turn it on

**Comment by Blobfish1** [comment]
Tried that too, still nothing

**Comment by ruifung** [comment]
What ARE you trying to make?

**Comment by Blobfish1** [comment]
Ive tried chronosteel and the dalek stuff, both times the material just stay in the hopper

**Comment by AlienXtream** [comment]
take a screen shot of your setup and post it here. just drag and drop it to github and it will upload

**Comment by Blobfish1** [comment]
![lab 1](https://cloud.githubusercontent.com/assets/14254541/9836734/6993679a-59f2-11e5-9e04-33ca02fd1af8.png)

**Comment by ruifung** [comment]
Dude. Your hopper isn't even pointing INTO the lab.

**Comment by Blobfish1** [comment]
how do I do that?

**Comment by ruifung** [comment]
Place it on the lab instead of on the wall.

**Comment by Blobfish1** [comment]
I try, but every time it just turns the lab off and on, do I not right click it to place it down?

**Comment by Blobfish1** [comment]
I finnaly got it guys, thanks
