### ISSUE TITLE
Build #223 Dimension Lever invisible...

### ISSUE THREAD

**Issue by wackypocket** [DarkholmeTenk/TardisModIssues#275]
I went into my TARDIS after updating and the Dimension Lever was not there. i have downgraded back to Build #220 and everything works fine... i have not tried any other versions. i have not tried to duplicate this glitch.

**Comment by DarkholmeTenk** [comment]
Is anyone else able to duplicate before I get back from my holiday?

**Comment by wackypocket** [comment]
https://www.youtube.com/watch?v=WS2pXRWZFQ8&ab_channel=Deathblade

i went ahead and duplicated the problem...

**Comment by wackypocket** [comment]
and i was wondering... not sure if this is where i should put this :p um could you add a commands list in the config folder so we can know all the commands? or are they listed somewhere else? I have not been able to fine them.

**Comment by DarkholmeTenk** [comment]
Just do /tardis and hit tab and it should cycle through them :P

**Comment by DarkholmeTenk** [comment]
With build 223, absolutely nothing changed in TM other than it was built using a newer version of DarkCore; without that newer version of DarkCore, unexpected behaviour will occur.
IIRC, the DarkCore update was in response to #268 and started the caching of dimension names, which could somehow cause problems? :P
Were you using the latest?

**Comment by wackypocket** [comment]
I'm Using darkcore-0.3-45
if thats not the newest could you link me?

**Comment by wackypocket** [comment]
ok... i found it 0.3-59 curse is all sorts of messed up xD i will be downloading from your jenkins from now on

**Comment by wackypocket** [comment]
anyways is there a IRC or forums for this mod i can ask questions at?

**Comment by handicraftsman** [comment]
https://www.youtube.com/watch?v=WS2pXRWZFQ8&ab_channel=Deathblade
It's linux distro with modified windows GUI?

**Comment by handicraftsman** [comment]
Switcher will be shown only from 5 level.

**Comment by wackypocket** [comment]
no its not linux distro and im pretty sure i already said its fixed so that whole 5 level thing is incorrect
thanks for trying to help tho EDIT: i just realized the way i put that made me sound like an ass and im really not... sry btw :)

**Comment by DarkholmeTenk** [comment]
Ok, if the jenkins version of darkcore fixes it, then closed :)
