### ISSUE TITLE
[SUGGESTION]  Just a few ideas

### ISSUE THREAD

**Issue by CanadianHarp85** [DarkholmeTenk/TardisModIssues#277]
In addition to the TARDIS Laboratory I would like to suggest a couple other things:

**BLOCKS**
Chronosteel Blocks
Dalekanium Blocks

Using 9 Bones in the TARDIS Lab gives you a mineable version of the white, colorable blocks.

Using 8 bones and 1 cocoa bean gives you a mineable version of Thenthish colorable blocks. (To change the rooms but keep the feel)

"Gallifreyan Constructor", can be dismantled and moved with Screwdriver, should be 3 long by 1 wide by 3 tall with the middle being hollow with little construction/assembly line arms[with animation during construction, all items needed for a recipe should be thrown at the input segment and licking on a Monitor on it should say what items are currently inside, built in a Workshop (see Rooms below) powered by Artron Batteries and working like the T Lab but with larger items such as:

--"Horizontal Gravity Lift" (Translocation Slider?) with a landing pad/block or, at a higher lever a turner? (So you move on X, then on Y if you hit a turner[or Z I guess too really]) Moves you even over drops/empty space, but only if you hit a level/button or use a screwdriver.

--"Genesis Ark", holds up to 64 of any mobs and can only be moved by recalling it with the TARDIS (like a level 9 button?) and sent back outside with coordinate selection(mob walks into it and gets sucked in, saved. (Think the Cybermen vs Daleks when the Daleks were released from that thing "Prison Transporter", can only be open by touching it directly, or using a remote open button in the Tardis itself, perhaps in the Prison Transport Chamber?  Created with Dalekanium Blocks.

--"Pandoracle"? Make mobs inside it that require recipes like Snowmen, Iron Golems and Withers to be released on your choosing with a Level 10 Screwdriver? (is a 3X3X3 block)

--"Species Matcher" created similar to the screwdriver after a certain level (12ish?) From up to 32 blocks away tells you everything you can imagine about the mob target[health, what mod it's from, like WAILA but long distance.  At a higher level (14?) it should tell you the current line of items a player has in their hotbar.

-- "Temporal Cooker" {could call it a Chronoforge but that was for making weapons} (Think about the Turkey!) [should only be able to cook if there is a full stack, and in motion. Powered the same as recharging an Artron battery

**ROOMS**
Prison Transport Chamber, a small room designed to hold the Genisis Ark Not able to be walked in, but with low enough shields and blowing up console, perhaps your prisoners can escape!

Workshop, should contain a tardis version of a crafting table, a space for the Temporal Cooker, some new buttons on the walls for other new stuff like the Species Matcher and contains a slot for building the Gallifreyan Constructor and a spot to place the TARDIS Laboratory, as well as having more Roundels than any other room.  A workshop should also contain a monitor above the slot for the T Lab that tells you what is currently inside it.

**Comment by handicraftsman** [comment]
It's mod about TARDIS, not about Doctor Who.

**Comment by CanadianHarp85** [comment]
These are all things connected or related directly to the TARDIS and improving on what has been done, not things that were just about the Doctor.  I'm not suggesting Daleks and Cybermen or Bacterial Moon Spiders or adding the Doctor's cradle for a Minecraft Comes Alive support...  The suggestions are there regardless, if some are used- fantastic I'll love the mod even more, if not a single one is used so be it, I tried

**Comment by Jwtc2000** [comment]
What would be the point of Chronosteel and Dalekanium blocks, other than maybe decor?

**Comment by FoxPotato** [comment]
I have to agree. These things are not really TARDIS related. Except maybe the craftable colourable blocks.
But the other things don't really fit in, and like the "pandoracle" or something doesn't really have a use? why make a 3x3 block if you can just place a 1x3 structure to make a snowgolem?

And i think dark was already planning to add something like a furnace. He might've forgotten about it, or it probably just doesn't have priority :p

**Comment by CanadianHarp85** [comment]
The blocks, Decor and perhaps used in the Tlab to make parts of the other stuff? As for Pandoracle, yes a Snowman takes up that many but you could place 40 snow blocks and 10 pumpkins and Sonic it to release them all at once, at least: that's what I was picturing
If this was truly TARDIS only, why can't I make the Tardis look like a large stone pillar like The Master's TARDIS was at one time..?  That would be TARDIS only

**Comment by FoxPotato** [comment]
What about the fact this is still a work in progress mod. Last time I checked dark was thinking about a chameleon circuit. don't know if that's still in tho.

**Comment by Jwtc2000** [comment]
See #80

**Comment by CanadianHarp85** [comment]
Alrighty then, shall I just delete my suggestions then?

**Comment by Jwtc2000** [comment]
@DarkholmeTenk

**Comment by AlienXtream** [comment]
Eniam, there is no need to do that. though a lot are unlikely to be implemented they are good ideas no less. the gen ark would be more fitting as a separate addon mod

**Comment by DarkholmeTenk** [comment]
Thanks for the ideas, I may end up taking bits from them in the future, but I'm going to close this for now.
