### ISSUE TITLE
[ENHANCE] Different types of TARDIS wall blocks

### ISSUE THREAD

**Issue by Zippomoon** [DarkholmeTenk/TardisModIssues#279]
I got this idea after testing Vaildfire's Stonehenge series of schemas, the problem with them was that they had no unbreakable back to the walls, floor, or ceiling so that if the stone blocks were to break you would be left with a hole into the void, which could be a problem if a fight broke out, or the wither chamber you built wasn't strong enough to keep it contained, so in short have a variate of creative only TARDIS wall blocks made to look like the vanilla "building" blocks (Brick, Stone Brick, Chiseled Stone Brick, sandstone, wood, etc.) they could be linked to the vanilla textures too so that when a texture pack is used they would be affected too.

**Comment by DarkholmeTenk** [comment]
There may be other types added later on, but they won't look like vanilla blocks

**Comment by DarkholmeTenk** [comment]
Dun (DS branch)
