### ISSUE TITLE
[BUG] Too Much XP

### ISSUE THREAD

**Issue by wackypocket** [DarkholmeTenk/TardisModIssues#281]
You Cant have over 1000000000000000000000000 xp or this happens: https://www.youtube.com/watch?v=eIbaA_E9paM

**Comment by DarkholmeTenk** [comment]
Not a bug, GIGO applies :P

**Comment by wackypocket** [comment]
xD

**Comment by wackypocket** [comment]
i love how the arrow goes crazy when you do that tho xD

**Comment by DarkholmeTenk** [comment]
That's because it's stuck in a for loop trying to grant you levels, I'll add a cap to the tardisXP command :P

**Comment by wackypocket** [comment]
lol ok
