### ISSUE TITLE
[Suggestion] RF artron

### ISSUE THREAD

**Issue by SomeBadGamer** [DarkholmeTenk/TardisModIssues#282]
I think it would be cool if you could use RF as a bit of a boost like maby 500-1000 RF to bo a extra 10 points of speed of corse  I mean any RF I  the tardis storage  and to activate it their should be a lever (for toggling it ) or a lever  the RF should be used  only once  a flight

**Comment by DarkholmeTenk** [comment]
This has the potential to be way too overpowered, all it would take is like 20/30 advanced photovoltaic cells from enderio and you'd be set for life :P

Edit: Given infinite TARDIS interior and potential for always daytime, you have infinite RF generation potential inside the TARDIS.

**Comment by SomeBadGamer** [comment]
Well maby the cost be  bit higher and decrease  the speed boost maby the cost could go up as your tardis  levels up so it's a way to see if it is "early game or late game" like use a % of the energy it has stored

**Comment by ruifung** [comment]
Also, why would a tardis run on the energy used by lesser beings? =P It's a freaking time machine, the amount of energy required to maintain its standby functions alone is probably more then any amount of RF generation, given that it derives power from a link to the Eye of Harmony.

**Comment by SomeBadGamer** [comment]
It is able to use some normal energy and it is his mod and it's minecraft so it's darks desition

**Comment by PrincessOfEvil** [comment]
I'm pretty sure you need a lot of energy to rip a hole in spacetime...
(Translation: just make the rate massively big)

2015-09-26 22:50 GMT+06:00 buster802 notifications@github.com:

**Comment by FoxPotato** [comment]
I don't quite get if the RF gets turned into energy or makes the TARDIS go faster, or even makes the artron generate faster.
I think the best of the 3 would be either convert it into artron or speed the artron up just slightly.
And I agree with laz, make the conversion rate like alot of RF for maybe 10 artron or something.

**Comment by DarkholmeTenk** [comment]
but a lot doesn't matter because infinite generation potential :P

**Comment by SomeBadGamer** [comment]
True I dident really think ti through  I just thogh it was a cool idea but I just have a question  is the health system going to be implemented  soon like next few months  just wondering  it seams really cool

**Comment by DarkholmeTenk** [comment]
Gonna close this for now; I may end up adding something if I get very bored, but it's not likely rn.
