### ISSUE TITLE
[ENHANCE] unlockables level config

### ISSUE THREAD

**Issue by AlienXtream** [DarkholmeTenk/TardisModIssues#284]
could you add a config option for the upgrade features (scanners, transmat, recall...) to allow changing level requirements/disabling lever requirements?

**Comment by DarkholmeTenk** [comment]
Yeah, why not.

**Comment by Jwtc2000** [comment]
@DarkholmeTenk 

![](http://33.media.tumblr.com/78577677b36aa723ba23456c50182167/tumblr_n9sjl5yZka1tv4k5po1_500.gif)

**Comment by DarkholmeTenk** [comment]
Done
