### ISSUE TITLE
When entering your TARDIS from the end(hardcore ender expansion) its half missing

### ISSUE THREAD

**Issue by ProsperCraft** [DarkholmeTenk/TardisModIssues#290]
https://youtu.be/u-gBowGwa08

tardismod-1.7.10-0.99-240
darkcore-0.3-70
HardcoreEnderExpansion  MC-1.7.10  v1.8.3

relogging fixes it.

Another use in the same dim entered his door, and nothing was there, when he relogged he was in this tardis.

**Comment by AlienXtream** [comment]
this has nothing to do with HCEE i believe. its probably got more to do with the end dim itself. it dose some weird stuff apparently when it comes to chunk loading

**Comment by AlienXtream** [comment]
i like to think of it as the tardis isn't meant to go there so she actively tries to avoid it

**Comment by DarkholmeTenk** [comment]
Disconnecting and reconnecting does invariably fix this; it is a problem with the player failing to respawn properly, it's weird, I've tried to fix it so many times.

**Comment by SomeBadGamer** [comment]
I have had something  similar  when the death transmat activities  if I am in the end visually  I am in the tardis but I still see the mobs and if I right click something it will update  to either air or end stone re login fixes it

**Comment by ProsperCraft** [comment]
We found a new end bug--- when in the end you see people outside the TARDIS like this - 
https://gyazo.com/6b1ed43bed9b69b15fe3ad525b06e49d

And when you enter one TARDIS it looks like the other TARDIS that is in the End as well.  When you interact with blocks from it, they look like they disappear because they are not really there. Relogging syncs it.

**Comment by AlienXtream** [comment]
temp solution, dont go to the end with a tardis

**Comment by DarkholmeTenk** [comment]
Pretty sure this is fixed now!
