### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by runescapejon** [DarkholmeTenk/TardisModIssues#293]
http://hastebin.com/pobonizume.vbs 
i have no idea how to fix this when i do this  Please delete the uid.dat file from tardis/DIM108's world directory if you want to be able to load the duplicate world. and it just keep coming back and also the console keep spamming this line
[Server thread/WARN]: Cannot Hotload Dim: Could not get provider type for dimension 312, does not exist

**Comment by DarkholmeTenk** [comment]
What exactly are the r/w permissions on the tardis folder and the dim subfolders?
Is the owner of the folder the same user as the one the server is operating under?
Could you provide some other info such as the mods that are loaded? what forge version?

**Comment by runescapejon** [comment]
never mind you can close this issue because what i end up doing is resetting the world and it was fix

**Comment by cjburkey01** [comment]
But without resetting, how does one fix this?
