### ISSUE TITLE
[Bug] Crashes when used alongside DragonAPI

### ISSUE THREAD

**Issue by felkami** [DarkholmeTenk/TardisModIssues#295]
crashlog: http://pastebin.com/iLtjyJmj
loaded mods: darkcore-0.3-45.jar, DragonAPI 1.7.10 V9b.jar, tardismod-1.7.10-0.99-207.jar
forge version: 10.13.4.1448 (and on 1492 and 1517, but the paste above is from 1448)

Hihi! I love the mod, unfortunately I can't use it alongside Rotarycraft. When DragonAPI (Rotarycraft dependency), darkcore, and tardis mod are loaded together it causes a silent crash when forge finishes. If either DragonAPI or tardis mod are removed, things load fine.

**Comment by LizzyTrickster** [comment]
DragonAPI is known for shipping old/full APIs which end up breaking a lot of other stuff. My guess is that it includes the CoFH API and the TARDIS mod or darkcore thinks it's actually from CoFH Core itself

**Comment by DarkholmeTenk** [comment]
Actually this looks like a problem with the AE api :P

**Comment by LizzyTrickster** [comment]
@DarkholmeTenk wouldn't surprise me if DragonAPI included that

**Comment by DarkholmeTenk** [comment]
Should be prevented with build 246

**Comment by felkami** [comment]
To make sure I understand, build 246 of tardismod?

**Comment by DarkholmeTenk** [comment]
yes

**Comment by felkami** [comment]
Yay! Any idea of when it'll be released or is it too early to say?

**Comment by DarkholmeTenk** [comment]
Too early to say, 1 or 2 weeks; it's available from the jenkins for now

**Comment by felkami** [comment]
Cool. Thank you.

**Comment by felkami** [comment]
So I tried darkcore 0.3-71 and tardismod 1.7.10-0.99-246 and still got the same problem. Here's the new crashlog:  http://pastebin.com/cZsw4gUQ
