### ISSUE TITLE
[BUG] TARDIS Fluid tanks with fluiduct interface.

### ISSUE THREAD

**Issue by masoniks** [DarkholmeTenk/TardisModIssues#297]
Firstly I'd like to say that this is a great mod and has made my minecrafting experience so much more interesting and getting around significantly easier.

[BUG #1]

I have found an issue with using the TARDIS tanks to store water.  I have set her tank #5 to handle water then hooked up the aqueous accumulators.  Unfortunately she seems to have sprung a leak somewhere and tanks 1-5 are now flooded with water too.  I tried to pump water sequentially from tanks 1-4 to tank 5 however she seems to be generating infinite water by herself despite a tank reporting its self as empty just a minute before.

I have also tried to pump the water directly out of the TARDIS into tanks but this is producing the same results.

[BUG #2]

I saw in a post somewhere that you had fixed the outofboundsarray crash when cycling through the internal tanks.  I am still able to produce this bug but found a simple fix in changing the config to increase the tank number by 1.... or more (TARDIS and all).... then remembering how many tanks there are.

**Comment by DarkholmeTenk** [comment]
Both have been fixed.
Bug 1 was fixed with #278
Bug 2 was fixed with DarkholmeTenk/TardisMod@19a5a0779a74fbc516e11682851ffd2f35a2584b (even though you can't actually see that)
Just need to fix some things up before the next feature version becomes available :)

**Comment by masoniks** [comment]
I downloaded the latest version available on your jenkins (tardismod-1.7.10-0.99-246.jar) and I am still able to produce both bugs mentioned here.  As I said, I have been able to resolve both issues with workarounds.

**Comment by masoniks** [comment]
What sort of time frame do you expect to release the next feature version?  Somewhat excited here...

**Comment by DarkholmeTenk** [comment]
It's fixed in the damage system branch, not in the branch publicly available. @AlienXtream or @FoxPotato should be able to confirm.
Not sure, sudden business has appeared.

**Comment by AlienXtream** [comment]
it is definitly fixed. have fun duping fluids in the mean time :P
