### ISSUE TITLE
Slime Island Generation in TARDIS Dimension

### ISSUE THREAD

**Issue by Zopffware** [DarkholmeTenk/TardisModIssues#298]
I'm not sure whether this is a bug with the TARDIS Mod or with Tinker's Construct, but it seems most applicable to the TARDIS Mod.
![2015-10-16_22 41 17](https://cloud.githubusercontent.com/assets/15205753/10595815/db287e3e-76aa-11e5-95f5-1cc80f7ea4d8.png)
In case it's important, I was using Tinker's Construct v1.8.4a.

**Comment by AlienXtream** [comment]
know "issue". this is on tinkers side. disable the spawning of them in non overworld dims in the configs of tinkers construct

**Comment by Zopffware** [comment]
So it is. Thank you!
