### ISSUE TITLE
[Enhancement] "Lights out" (and day/night cycle)

### ISSUE THREAD

**Issue by LizzyTrickster** [DarkholmeTenk/TardisModIssues#305]
You can already control the day/night setting in the TARDIS console, but what about the light produced from the Roundels? I'd like to put my TARDIS into a 'night mode' but i don't want to have to go around and take all the roundels out.

Another thing is the ability to allow the day/night in the tardis to 'cycle' like it does in the overworld and other dimensions with time.

**Comment by SomeBadGamer** [comment]
I  think it is cool but for one it should  be  a  option  because  what if you only want night mode for the spacey look but don't want it to get dark also don't know how posoble  because  that would require  to replace  them not "toggle it " the light is a aspect  of the block that will need to be rewritten  like you can't toggle  glow stone it's just part of the block

**Comment by FoxPotato** [comment]
you can toggle redstone lamps tho, so your argument doesn't really make sense. But it would probably lagg just a second or 2 if your pc isn't the best and/or your TARDIS is quite big.
And i think they meant like a speerate button for the lights, not when the temporal button is set to night the lights turn off.

**Comment by DarkholmeTenk** [comment]
You can only toggle redstone lamps because it switches from one block to the other and redstone triggers a function in the lamp, no way to trigger all of the roundels like that.

**Comment by TheAmazingSpy** [comment]
Okay, maybe a world edit can change the roundels to a state where there is no light on, and then try and make it try not to cause lag, I don't know how

**Comment by DarkholmeTenk** [comment]
Without causing lag, I'd argue this isn't possible.

**Comment by LizzyTrickster** [comment]
That's a bummer, oh well.
What about the Day/Night cycle button? like every now and then it'll switch from day to night just like if you were pressing the button on the console

**Comment by FoxPotato** [comment]
I do love the idea of a day/night cycle tbh, it would be a really nice touch.

**Comment by SomeBadGamer** [comment]
That would be just as hard because from what I can tell the time not moveing  is coded in to the dimension the button on the console to change the time is essentially  a /time set command

**Comment by FoxPotato** [comment]
Ok yeah it would require for the time stuff to be recoded, but how i would do it would be to make the cycle the default mode. And then lock it in day or night, or ofc leave it in cycle mode. It would be possible, and probably wouldn't cause any real kind of lag.
