### ISSUE TITLE
'Console Maitenence'

### ISSUE THREAD

**Issue by TheAmazingSpy** [DarkholmeTenk/TardisModIssues#306]
This enhancement is for when the damage system is introduced, in a later version after 1.0.0 (maybe 1.1.0?) The TARDIS will also under some circumstances; i.e not pressing buttons in time and damaging the console, will make it so that you have to put the console into 'maintenance mode' which involves using the sonic screwdriver onto reconfigure and opening a panel on the console, revealing the circuitry, and then using issue #299 is some slots where you insert the item and then you sonic it on reconfigure (the slot with the item inserted) to make it absorb it and then you sonic again (somewhere else on the panel) to close it, and then it's fixed

**Comment by AlienXtream** [comment]
trust me, with the DS branch, its challenging enough early game. no need to make it more complex

**Comment by TheAmazingSpy** [comment]
But... It's cool

**Comment by FoxPotato** [comment]
But it shouldn't become too challenging to play this mod, And it's sounds like a pain to code, I know Dark is good, but he isn't a god ;p

**Comment by TheAmazingSpy** [comment]
Come on... It's simple

**Comment by FoxPotato** [comment]
It's not actually,  mean I've only just really started coding. But I know enough to be able to tell it would be a huge pain to make it work.

**Comment by DarkholmeTenk** [comment]
The damage system branch already requires you to put stuff in to the engine to fix the hull when it gets damaged.
