### ISSUE TITLE
[BUG] Energy conduit roundels transfer 4098 RF/t regardless of config setting.

### ISSUE THREAD

**Issue by UniversalMigrator** [DarkholmeTenk/TardisModIssues#311]
When changing the config option under misc.cfg to a value like 32000, the roundel conduits only allow 4098RF to transfer through. Have tested this with one Big Reactor capable of outputting ~160KRF/t, using cryo-stabilised flux ducts (infinite capacty) connected to a roundel, with a resonant frame Magma Crucible with 3 speed augments which uses/draws 8KRF/t. Magma crucibles power drains and sits at 4,000RF until a tesseract is hooked up between the reactor and crucible, which then will allow the full 8KRF/t to power the crucible.

**Comment by AlienXtream** [comment]
hmm... try it with some other power transfer methods above 4098RF (ender io's tier 3 conduits for example) and see if it happens with them. im thinking it may actually be a bug with the cryo flux ducts. not sure how rwtemma did the cryo ducts but if he made them "infinite" then in theory this shouldn't happen (by "infinite" i mean a ridiculously high value that's virtually impossible to reach). however if he coded them in such a way that they ARE infinite then that is likely the cause of the issue. thats my guess anyway

**Comment by UniversalMigrator** [comment]
Alright, did some more indepth testing with this and you're pretty much spot on.

Using EnderIO's Ender-Energieleitung (Flux conduit) from the roundel to the crucible works fine, as well as any other conduit or duct with some kind of transfer limit (TD fluxducts, etc). 

After some more testing I have found that the Cryo ducts are only impacted when drawing from a roundel, not when putting power in the roundel/TARDIS RF storage. It's very likely your assessment is correct when the cryo ducts are used in this instance.

**Comment by AlienXtream** [comment]
ok. then that's either a bug in thermal dynamics or dark is going to have to code an exception for them. i say leave them as is to encourage the use of tesseracts for ultra high power transfer rates

**Comment by DarkholmeTenk** [comment]
Tested, definitely a bug in TE conduits.
