### ISSUE TITLE
Nether Portal Spawning

### ISSUE THREAD

**Issue by TheMinecraftian772** [DarkholmeTenk/TardisModIssues#314]
I was playing around with my friend in his tardis.  Then I noticed that a nether portal outside the window.  We got outside and destroyed it.  it came back later in a different place, taking the place of a few floor blocks because it spawned inside this time.  
then it spawned inside my tardis
http://puu.sh/lfLEq/dba0ffad99.jpg
I'm running tardismod-1.7.10-0.99-246 from the jeinkins.

**Comment by DarkholmeTenk** [comment]
Update darkcore?

**Comment by TheMinecraftian772** [comment]
I've got darkcore-0.3-45.  I'll update it and I'll get back to you if it keeps happening
also,  tinker's construct's slime islands are spawning
http://puu.sh/lfMHM/32dd149567.jpg

**Comment by DarkholmeTenk** [comment]
Tinker's slime islands can't be stopped, unless you change tinker's configs.
See #298

**Comment by FoxPotato** [comment]
That sounds really scary.
"Tinker's islands can't be stopped"

(I know this has nothing to do with the whole problem, but oh well)

**Comment by Werner1201** [comment]
I agree @FoxPotato that sounds Really Really Scary

**Comment by TheMinecraftian772** [comment]
http://puu.sh/licBK/e91947429b.jpg
Still doing it.  this one spawned when my friend teleported into a landing tardis.  I'm not sure why it did this.  He used the magnetic force to teleport.

**Comment by DarkholmeTenk** [comment]
Wait, how are you teleporting? If it's a non-tardismod teleport, chances are they're using the vanilla teleporter which spawns portals.

**Comment by TheMinecraftian772** [comment]
It's the magnetic force from random things.  I'm not sure how it's teleporting works.  Sorry it took so long to get back to you, I had to go out of town.  next opportunity I get, I'll check to see if it spawns every time I use it.

**Comment by DarkholmeTenk** [comment]
95% sure this isn't because of any of my code and there's nothing I can do to fix it. Tell the author of random things to use a teleporter which doesn't cause nether portals to spawn (i.e. not the vanilla teleporter)
