### ISSUE TITLE
JourneyMap compatibility

### ISSUE THREAD

**Issue by techbrew-mc** [DarkholmeTenk/TardisModIssues#315]
https://twitter.com/JourneyMapMod/status/664475506562088960

**Comment by wackypocket** [comment]
:o plz do this! i think it would be nice to see a map of my tardis :D

**Comment by AlienXtream** [comment]
should be fixed as of latest darkcore version

**Comment by DarkholmeTenk** [comment]
Fixed issue with blocks being "transparent", should have fixed this.
