### ISSUE TITLE
AE2 Facades

### ISSUE THREAD

**Issue by ghost** [DarkholmeTenk/TardisModIssues#316]
I do know that blocks and roundels can be recolored but can facades from AE2 also be recolored when using the Tardis blocks or will it just stay white?

**Comment by AlienXtream** [comment]
coloring facades from AE2 would HAVE to be done on AE's side. any changes dark could in theory make would have to modify the AE2 class files meaning he wouldn't be able to publish it. HOWEVER if you manage to get the colored blocks in your inventory i have noticed that when used in a carpenters block they maintain their color. its possible this would also happen with facades but i "can't" test this right now cos... Fallout 4 :P

**Comment by SomeBadGamer** [comment]
The color is from meta data of the block facades can't use meta data

**Comment by AlienXtream** [comment]
really? i thought they did? they can handle the wood types yes?

**Comment by FoxPotato** [comment]
They are able to use metadata blocks iirc, like wool and stuff is all possible.
But facades and stuff always seem to have trouble with 'special' texture blocks.

**Comment by SomeBadGamer** [comment]
Well that  is hafe correct planks are their own block but it dose have meta data the tardis  blocks are not a different  block just meta data if that makes sense
