### ISSUE TITLE
[ENHANCE] bright lighting

### ISSUE THREAD

**Issue by AlienXtream** [DarkholmeTenk/TardisModIssues#317]
i know its possible to have bright lighting in a custom dimension and i think this would be cool BUT i was thinking something more advanced, dark lighting in night mode and bright lighting in day mode. can it be done?

**Comment by TheAmazingSpy** [comment]
#305 all over again, he said it can't be done, better stop asking. Not being mean but informative.

**Comment by AlienXtream** [comment]
actually not really. yes the idea stemmed from that but the execution is different

**Comment by TheAmazingSpy** [comment]
Oh, sorry.

**Comment by AlienXtream** [comment]
no need to apologize :)

**Comment by FoxPotato** [comment]
you mean like, that there isn't really darkness. like if you close yourself in a cube, you can still see. am i right?
 is it possible to changes the properties of a dimension while being in said dimension, because if it is this would be a really cool idea,

**Comment by AlienXtream** [comment]
yeh. like the nether. mystcraft also has a dark variant that has the opposite effect but im not sure if xcomp uses his own method to do that of if he's using some unimplemented vanilla feature

**Comment by FoxPotato** [comment]
imo it would be better to just have normal lighting when night mode. There's not really a use for no lighting.

**Comment by AlienXtream** [comment]
true, but would add more atmosphere

**Comment by FoxPotato** [comment]
then maybe make people turn it on in the config or something. because having no lighting whatsoever, it just sounds like a huge pain to me.

**Comment by DarianLStephens** [comment]
I thought that was a feature already? I know there's one to make all blocks emit light in the TARDIS, or at least that's what it says it does...

**Comment by FoxPotato** [comment]
no, there'es just a button which turns the time to day or night. blocks which emit light do this day and night. nothing changes.

**Comment by DarkholmeTenk** [comment]
I think he's referring to

```
#Should most blocks give off light
#Default: false
Visibility - lit up blocks:B:false
```

**Comment by FoxPotato** [comment]
oh, woops. my mistake :p

**Comment by DarkholmeTenk** [comment]
Don't particularly want to implement this, would mean a lot of messing around for very little benifit and I like the way the lighting looks in the tardis as it is.
