### ISSUE TITLE
[CRASH] Ltardis/common/items/SonicScrewdriverItem

### ISSUE THREAD

**Issue by DestinyPlayer** [DarkholmeTenk/TardisModIssues#318]
Basically, there's this weird crash happening, and I have no idea what caused it, other than the fact that it seems to have something to do with your mod.
http://pastebin.com/qHSA6UZb - Crash Report.
https://dl.dropboxusercontent.com/u/77108893/Crash%20Reports/Tardis%20Log.log - The FML Log.

**Comment by DarkholmeTenk** [comment]
Try the latest tardismod and darkcore from the jenkins pls

**Comment by DestinyPlayer** [comment]
http://pastebin.com/eG0P2Bs9 - The new Crash Report
https://dl.dropboxusercontent.com/u/77108893/Crash%20Reports/Tardis%20Log%202.log - The new FML Log
From what it seems, nothing has changed.

**Comment by DarkholmeTenk** [comment]
Try without dragonapi?

**Comment by DestinyPlayer** [comment]
It worked. But I'm not sure what causes it to crash. It worked before, I've literally changed nothing, and now it refuses to launch with ChromatiCraft. Any ideas what might cause this conflict?

**Comment by DarkholmeTenk** [comment]
DragonAPI for some reason includes enough of buildcraft's api for forge to think buildcraft exists, so the screwdriver tries to act like a buildcraft wrench, but without buildcraft itself, it crashes :P

**Comment by DestinyPlayer** [comment]
Hmm... But why did it work before? Without a hitch, in fact, with the exact configuration of mods like in the first post.

**Comment by DarkholmeTenk** [comment]
No idea, could be DragonAPI is using some new ASM methods or something. Try the new new version, it should try to load before DragonAPI, but no guarantees that will fix.

**Comment by DestinyPlayer** [comment]
Nope, didn't work. Gonna try installing BuildCraft, maybe it'll at least load.

**Comment by DestinyPlayer** [comment]
Yep, installing BuildCraft worked. Thanks a lot for helping me figure it out!

**Comment by DarkholmeTenk** [comment]
No problem, another DragonAPI bug :\

**Comment by AlienXtream** [comment]
hence why i avoid it :P
