### ISSUE TITLE
[ENHANCE] add other types and marks of consoles amd time rotor

### ISSUE THREAD

**Issue by kramlat** [DarkholmeTenk/TardisModIssues#320]
Is there any chance that we will ever be able to for an example, add a time rotor that is just a vertically moving cylinder or any other themed tardis consoles?

**Comment by SomeBadGamer** [comment]
I think dark already  said no on new consoles or it might have Ben time rotors I know thogh  that new console rooms and normal rooms are coming

**Comment by kramlat** [comment]
well, can we at least have a way to replace a time rotor with a piston and block to make more accurate classic console rooms?  The reason I ask is because I tried it and the art for the time rotor shows up even when there is no time rotor in the schematic.

**Comment by DarkholmeTenk** [comment]
You definitely won't be able to replace the time rotor with other blocks because its tile entity handles 90% of the flight logic. New types may end up happening, but no guarantees. Gonna close the issue for now, will reopen if my modeller is up for doing some new console/time rotor types.
