### ISSUE TITLE
[BUG] DS-sonic disappears from inventory on right click

### ISSUE THREAD

**Issue by AlienXtream** [DarkholmeTenk/TardisModIssues#324]
its still there just invisible, a desync issue right? it still functions. it IS possible this is an issue with my instance but its to early for me to be bothered testing it on a clean install :P. even so, some method avoiding this would be good as i doubt im the only one to have encountered it and certainly wont be the last (unless you can fix it :P)

EDIT: appears to only happen on right clicking air

**Comment by DarkholmeTenk** [comment]
Can't replicate. Details.

**Comment by AlienXtream** [comment]
ok. im going to assume this is something specific to my instance (i have had some tps issues on changing dims to so maybe the same thing causing this issue) but i will leave the post open for a little while in case someone else has the same issue

**Comment by DarkholmeTenk** [comment]
Nope, someone else has replicated

**Comment by AlienXtream** [comment]
oh? interesting. this is becoming quite a conundrum.... ether way, dosnt help my tps issue :P jks

**Comment by AlienXtream** [comment]
wana know what else is wierd bout this bug. it stoped happening in the world i was in when i reported it BUT it was happening in a creative world from the same session (havn't quit the game). sereously, wth...???

**Comment by FoxPotato** [comment]
Idk if it's the same bug causing it, and it didn't really dissapear for good. But when i placed down a room the sonic dissapeared for a second or something out of my inventory. It came back tho.

**Comment by AlienXtream** [comment]
probably same issue causing. idk, this thing is really messing with my head :/

**Comment by FoxPotato** [comment]
I didn't really look at it twice,  I couldn't remember if it used to do that or not lol.

**Comment by AlienXtream** [comment]
i never noticed it till reacently so probly a new thing or some wierd stuff with mod heavy clients

**Comment by FoxPotato** [comment]
There's always weird stuff with mod heavy clients, but it's most likely just the mod itself ;p

**Comment by DarkholmeTenk** [comment]
May be fixed?
