### ISSUE TITLE
[Enhance] Screwdriver modify mode

### ISSUE THREAD

**Issue by Belgabor** [DarkholmeTenk/TardisModIssues#325]
It would be nice if the screwdriver would allow you to, to some extend, modify rooms.
- Toggle a block between flat/solid/glass/roundel
- Hide doors as flat/solid/glass. Either undoable or replace permanently.
- Either have a special type of the structure blocks that can be removed with the screwdriver or have mineable survival versions of the block the player can use. This would for example allow you to prepare piping trenches for machines in a schema the player can either uncover or fill in in survival.

All of this is to make schema usage more versatile so you don't have to make a separate schema for minor alterations you might want/need.

**Comment by DarkholmeTenk** [comment]
Done except point 2.

**Comment by DarkholmeTenk** [comment]
Ds branch as a note.
