### ISSUE TITLE
"flyable" tardis

### ISSUE THREAD

**Issue by SomeBadGamer** [DarkholmeTenk/TardisModIssues#326]
is it possible to make the tardis "flyable" for a example imagine a rideing a controllable bat i would assume guess it would need to be "flown" from the outside because i dont see how you can fly while in the tardis dimension

**Comment by DarkholmeTenk** [comment]
This isn't going to happen, it'd be way too much work turning the exterior into an entity and then making it controllable and also defaults the point that this thing is supposed to require a bit of skill to fly, rather than just being generically controllable like any other entity.
