### ISSUE TITLE
[ENHANCEMENT] Admin slash command to summon a player's Tardis

### ISSUE THREAD

**Issue by Vaygrim** [DarkholmeTenk/TardisModIssues#327]
It would be VERY handy to have a slash command for Admins that would relocate a specified player's Tardis to the square infront of the issuing admin. I've already had a situation where someone piloted their Tardis to the SpectreWorld dimension (added by a mod, can't recall which at the moment). As soon as they stepped out, they got teleported to Spawn in the Overworld.

But their Tardis was still in the SpectreWorld. So I had to find their Tardis's dimension, teleport myself there.. then summon them to me (or pilot it back to the overworld for them).

So .. simple admin slash command to recall someone's Tardis would be nice!

**Comment by DarkholmeTenk** [comment]
you could also have just made them right click a tardis recall block, but sure.

**Comment by Jwtc2000** [comment]
But it would be easier to do with a command though. :|

**Comment by Vaygrim** [comment]
I'll be 100% honest, I totally forgot about the recall blocks. I'm going to place one or two of those at spawn on my server now!

That being said however, having access to a simple slash command to do the equivalent would mean that such an action could be performed 'remotely' by an Admin, from anywhere on the server.

Good call on the Recall Blocks, tho!

**Comment by DarkholmeTenk** [comment]
Yeah, but @Jwtc2000 "but sure" means I'll do it :P

**Comment by DarkholmeTenk** [comment]
Done
