### ISSUE TITLE
[Bug] Available room number doesn't reset properly

### ISSUE THREAD

**Issue by Belgabor** [DarkholmeTenk/TardisModIssues#328]
The number of available rooms doesn't reset properly if they get removed indirectly by dismantling their "anchor" room, only one gets deduced from the usage count.

**Comment by AlienXtream** [comment]
well thats...problematic. i will test this in the DS branch and report back later

**Comment by AlienXtream** [comment]
confirmed in damage branch. also waila dosn't update until rightclicking the dial

**Comment by DarkholmeTenk** [comment]
Just clientside or does the server actually report the wrong value when right clicking the dial?

**Comment by AlienXtream** [comment]
reports wrong value on right click. it IS server side. i cannot place anymore rooms yet i have 1 room.

**Comment by DarkholmeTenk** [comment]
I assume restarting/reconnecting fixes? If so, this is now fixed.
