### ISSUE TITLE
[Bug] tardisreload command doesn't work reliably in SMP

### ISSUE THREAD

**Issue by Belgabor** [DarkholmeTenk/TardisModIssues#329]
I had the command work once and so far (tried to use it to add schemas twice now after the first one) never again. The server log shows the schemas loading, but new ones don't show up in the selection, even when going to a different category and back.

**Comment by AlienXtream** [comment]
leave the tardis, repeat the command and then swap the categories on the room selection and see if that works (might also need other players out of tardis worlds). its not just smp that this affects but ssp (given they ARE kinda the same now...). like you said, unreliable, not totally broken

**Comment by DarkholmeTenk** [comment]
Can't replicate, managed to use /trel sucessfully on a server and had them show up.
