### ISSUE TITLE
Please add integration  for Immersive engineering.

### ISSUE THREAD

**Issue by ProsperCraft** [DarkholmeTenk/TardisModIssues#331]
The energy conduit doesn't have a recipe.

Could you add integration for immersive engineering?  Perhaps add a recipe for them using immersive engineering parts if it detects that mod?

**Comment by DarkholmeTenk** [comment]
Does it work if you install CoFHCore

**Comment by ProsperCraft** [comment]
I am not using an COFH or Thermal expansion.

**Comment by DarkholmeTenk** [comment]
But CoFHCore is what defines the RF api, so without it no RF so no energy conduit.

**Comment by ProsperCraft** [comment]
Immersive engineering connectors can transmit RF and EU

**Comment by DarkholmeTenk** [comment]
The mod doesn't support EU currently, so RF is the only option and without CoFHCore the RF api is not defined and the roundel won't be able to transmit power.

**Comment by ProsperCraft** [comment]
What about a crafting recipe for the energy conduit?

**Comment by DarkholmeTenk** [comment]
It won't work either way, the actual interface won't be added to the roundel tile entity because forge removes it if CoFHCore doesn't exist, otherwise I'd need to actually package the interface with my mod and I would prefer not to do that :P

**Comment by DarkholmeTenk** [comment]
Definitely CoFHCore dependency :P
