### ISSUE TITLE
[BUG ?] Thaumcraft Greatwood Trees can destroy Tardis Glass

### ISSUE THREAD

**Issue by Vaygrim** [DarkholmeTenk/TardisModIssues#332]
I set up a "Big Chamber" and filled the very middle circle with dirt (1 layer thick). Then planted a Greatwood Tree Sapling dead center in the middle. It grew up VERY big, so big that it hit the ceiling and broke several blocks of the "Tardis Glass" at the top of the chamber.

Don't know if this is a bug, or even if it's something fixable on your end. Just thought I'd report it!

**Comment by Vaygrim** [comment]
Oh duh, silly me!

FORGE 1558
DarkCore 0.3-45
Tardismod-1.7.10-0.99-250

**Comment by DarkholmeTenk** [comment]
From DarkCore
https://github.com/DarkholmeTenk/Darkcore/blob/master/src/main/java/io/darkcraft/darkcore/mod/abstracts/AbstractBlock.java#L231

``` java
    @Override
    public boolean canBeReplacedByLeaves(IBlockAccess world, int x, int y, int z)
    {
        return false;
    }
```

If a mod doesn't want to respect a very simple method, then there's nothing I can do and I imagine you could get them to grow through bedrock.

**Comment by Vaygrim** [comment]
Should that also account for the logs as well? That's what broke the glass, not leaves. (I don't know if that matters at all?)

**Comment by DarkholmeTenk** [comment]
There's no appropriate method for logs, if you shouldn't replace a block with leaves, you probably shouldn't replace it with logs.

**Comment by AlienXtream** [comment]
problem: trees grow through the roof.
solution: claim it was intentional and make a skylight :P
