### ISSUE TITLE
Feature request- Config option to make chunkloaders only load when player online

### ISSUE THREAD

**Issue by ProsperCraft** [DarkholmeTenk/TardisModIssues#338]
like a railcraft personal anchor, only allow chunks to be loaded when player is online.

**Comment by AlienXtream** [comment]
you can disable tardis dim chunk loading in the configs. just turn that off and make players use chunk loaders from other mods

**Comment by ProsperCraft** [comment]
Still crashes with latest  - http://pastebin.com/qTiNtBTa

**Comment by DarkholmeTenk** [comment]
@AlienXtream actually I'm pretty sure that won't do anything.
@ProsperCraft assume player B has a recall screwdriver to player A's TARDIS. Player A is offline, player B tries to recall, nothing happens because player A's coreTileEntity is not loaded.
The console room Needs to be loaded, as for the cable interfaces, yeah, alright.

**Comment by AlienXtream** [comment]
really? then whats the config option for?

**Comment by ProsperCraft** [comment]
This is for large servers with thousands of users, you can't have all of their bases loaded all of the time or nobody can play.

**Comment by AlienXtream** [comment]
this mod is really more suited to a small server with less than a dozen players. modded servers are notoriously unstable aswell and need CONSTANT babysitting by someone who can access the server computer (to restart it or remove problem mods if needed)

**Comment by ProsperCraft** [comment]
yes...I know...have been running large modded servers with massive modpacks for many years ;)

**Comment by FoxPotato** [comment]
I must agree, this mod probably isn't really suited for huge servers. Should be interesting to see what's gonna happen tho, if u add it :P

**Comment by DarkholmeTenk** [comment]
Someone to sit on the server and restart it? Why not https://github.com/DarkholmeTenk/ServerManager ? :3

**Comment by AlienXtream** [comment]
half the time i dont know why i bother cos you think of virtualy everything dark :P
