### ISSUE TITLE
[BUG] WAILA does not reflect actual values when using custom configs

### ISSUE THREAD

**Issue by cloakable** [DarkholmeTenk/TardisModIssues#339]
Screenshots: https://imgur.com/a/iKytI
Using custom values for energy levels, regen, and xp needed to level.

Also, console features seem to be linked to the amount of XP gained, not actual level. I've levelled my TARDIS to 7 so far, but stabilizers have not unlocked.

**Comment by DarkholmeTenk** [comment]
Is this on a server which doesn't have the same configs as you by any chance?
Console features definitely aren't linked to amount of xp gained, but whether or not you can See them depends on the level your client thinks your TARDIS is.

**Comment by cloakable** [comment]
It is on a server; I'll double-check the client configs against the servers.

Nope; To make sure they matched I deleted both sets, regenerated on the client, edited, then copied to the server. WAILA is still derping, console features still not present. Do I need to do anything else, or is this a genuine bug?

**Comment by cloakable** [comment]
Okay, it turns out the problem was WAILA getting confused, not your mod! Clearing out the WAILA cache in the local save directory fixed everything.
