### ISSUE TITLE
Tardis  "map

### ISSUE THREAD

**Issue by SomeBadGamer** [DarkholmeTenk/TardisModIssues#340]
Is it possible  to have  the  tardis have a extirior map baseicly a normal map in a item frame but it is centered  on the exterior

**Comment by AlienXtream** [comment]
could be done in theory but realistically i cant see it working. no less it would be awesome

**Comment by FoxPotato** [comment]
I think it would be best to just wait for the looking glass API and be able to look outside yourself :p

**Comment by AlienXtream** [comment]
thats going to be a while

**Comment by FoxPotato** [comment]
technically we're only waiting for the documentation and for dark to implement it, but you're probably still right :P

**Comment by SomeBadGamer** [comment]
Well say you want to get a brief  look around you and not just what you can see through the doors and this is a real tardis  feature in the episode  the run away  bride the doctor  used the map on the monitor  to track the bride "can't remember  her name"

**Comment by FoxPotato** [comment]
We know it's a real feature, but the way it would have to be done just doesn't sound doable. But that's up to dark to decide ofc, since he's the modder here :p

**Comment by AlienXtream** [comment]
seriously...how do you not know Donna?!

**Comment by DarkholmeTenk** [comment]
Ok, as far as I'm aware, item maps have the data actually written to them so you can look at them when you're far away from the area.
But as the client knows nothing of the world it's not currently in, this would require me to transmit all the data to the client to have it update. As this is a massive pain to do, I'm not going to do that. Meaning the only other option is another mod like looking glass, so until I add looking glass support, nothing like this is happening, sorry.
