### ISSUE TITLE
Server Crash- at tardis.common.tileents.CoreTileEntity.calculateFlightDistances(CoreTileEntity.java:215)

### ISSUE THREAD

**Issue by ProsperCraft** [DarkholmeTenk/TardisModIssues#342]
http://pastebin.com/C0180Cj0

**Comment by ProsperCraft** [comment]
Fixed by rolling back to darcore .78

**Comment by AlienXtream** [comment]
going to go out on a limb and say dark changes something in darkcore to fix a crash bug in the DS branch but also broke the older method. dully noted that main branch only supports darkcore .78 (and some lower versions)

**Comment by DarkholmeTenk** [comment]
Yeah, this isn't an issue in DS, so this isn't something I need to fix :P

**Comment by wackypocket** [comment]
is there a way for us to use this DS branch? if so id love to know how xD

**Comment by AlienXtream** [comment]
its only accessable to a few people. its in testing phase. i dont know when its going public but (and plz dont quote me on this, its speculaion) it feels like it wont be too long. im confident in saying it will be out before the "Dr who client mod" :P (unless there is something dark REALLY wants to implement first)
