### ISSUE TITLE
A new TARDIS is not allowed to go to the nether but if you summon it in the nether...its stuck.

### ISSUE THREAD

**Issue by ProsperCraft** [DarkholmeTenk/TardisModIssues#344]
If you create your TARDIS in the nether it can't travel to level because it isn't allowed to select the nether dim....that it is already in.

**Comment by wackypocket** [comment]
well.... who would summon a TARDIS in the nether...

**Comment by wackypocket** [comment]
anyways... make it to were it can only be created in the overworld? or make it to where you can fly it in the nether but you cant leave until its leveled up enough.

**Comment by DarkholmeTenk** [comment]
Lol. #286 will fix this.

**Comment by AlienXtream** [comment]
in the mean time, either summon and get in the tardis and level it up like normal OR...dont summon it in the nether... -_-. personaly i have it set to spawn me with a key so i never encounter this issue :P
