### ISSUE TITLE
[ENHANCE] Restoration field

### ISSUE THREAD

**Issue by AlienXtream** [DarkholmeTenk/TardisModIssues#345]
the restoration field would (slowly) repair item durability at a heavy power cost. either a version that works like the temporal lab with a faster repair speed or a roundel version that would (very slowly) repair items in inventory. (if possible tinkers tools too?). i know its not strictly TARDIS oriented but then again neither is a roundel that magically heals and feeds you :P. just had the idea and figured id'e share it :)

**Comment by FoxPotato** [comment]
This is actually quite a good idea (and nanobots aren't magical, they're SCIENCE \o/)

**Comment by AlienXtream** [comment]
yes but how do they feed you? where do they get the food from? (and dont even think about molecular transmutation, that would require the power of a collapsing star... oh wait...nvm :P)

**Comment by FoxPotato** [comment]
they feed you with the powER OF SCIENCE.

**Comment by SomeBadGamer** [comment]
Nice idea and it should be like 5-20 durability per min

**Comment by handicraftsman** [comment]
Nanogenes for items?

**Comment by AlienXtream** [comment]
more like rewinding the item down its won timeline but on a functional standpoint yes

**Comment by FoxPotato** [comment]
rewinding something down it's own timeline sounds quite dangerous lol. Imo just repairing something makes more sense.

**Comment by Werner1201** [comment]
@FoxPotato But it's not rewinding your time stream but only rewinding the Information
I think in this last season of doctor who there was an episode that explained that

**Comment by FoxPotato** [comment]
1. i'd love to see that actually, and that wasn't meant in a sarcastic way im genuinely interested :P 
2. and alien did say rewinding something down it's own time line. And to me that sounds like something that would create a shit ton of paradoxes.

**Comment by AlienXtream** [comment]
dose it really matter HOW it works in regards to lore? the main point of the topic is the function :P

**Comment by FoxPotato** [comment]
yes, yes it does :P 
either don't explain how it works, or have lore that's correct ;p
