### ISSUE TITLE
Breaks walls/rondels

### ISSUE THREAD

**Issue by LatentDesire** [DarkholmeTenk/TardisModIssues#346]
Was playing around with this mod and the dalek mod earlier. Accidentally shot the wall with the sonic blaster from dalek mod. Popped off the wall block. Was in creative at the time but thought it was weird that it dropped the block. Switched to survival, and sure enough it the blocks broke in survival as well. 

Might break everything, haven't tried since I didn't want to break the tardis. (Glad I didn't accidentally hit console. Was in there shooting at daleks and such when this happened.)

**Comment by AlienXtream** [comment]
the sonic blaster dosn't check to see of blocks are destructable, it has its own blacklist. and guess what! tardismod blocks are NOT on said list so...break away. also, not 100% sure about how it affects functionality but i know the console replaces the blocks itself when you break some of them. just make sure to toss those console blocks into the void. 

Dark, is this one fixable on your end at all?

**Comment by DarkholmeTenk** [comment]
Lol, no. I essentially copy bedrock's durability and stuff, if dalek mod can't be arsed checking if the durability is bedrock level, there is absolutely nothing I can do about it.
