### ISSUE TITLE
[Bug] Applied Energistics max of 32 channels

### ISSUE THREAD

**Issue by Firestar311** [DarkholmeTenk/TardisModIssues#347]
I have discovered that you can only run a max of 32 channels through the TARDIS. And I have found no config option to change this fact. Could you add support for the different colored cables within Applied energistics to use more channels connected to the controller

**Comment by DarkholmeTenk** [comment]
Nope, AE2 api does not have that much flexibility. All that I can realistically do is link every roundel to the core. There is no functionality built into the api to allow more channels or anything like that. Use the P2P thingum to work around this, or disable channels.

**Comment by DarkholmeTenk** [comment]
Workaround done in DS build
