### ISSUE TITLE
1.8

### ISSUE THREAD

**Issue by wackypocket** [DarkholmeTenk/TardisModIssues#348]
a lot of my favorite mods are making 1.8 version and leaving 1.7.10 and im wondering if you will make 1.8 support? my current modpack is 1.7.10 with the tardis mod and i will not be moving to 1.8 until it supports it or if i (very unlikely) get bored of it. :D

**Comment by SomeBadGamer** [comment]
Dought full but 1.9 most likely  coding has changed  alot from 1.7 to 1.8 so most modders are waiting for   1.9 so it is on the most recent  version  of  minecraft

**Comment by wackypocket** [comment]
ok cool ill wait for 1.9 :D

**Comment by FoxPotato** [comment]
iirc dark wasn't planning on updating to 1.8, could be wrong tho but i dont think i am.

**Comment by DarkholmeTenk** [comment]
Not planning on updating to 1.8 in the near future

**Comment by MoonlightSystem** [comment]
how about 1.8.8?
