### ISSUE TITLE
Console spam with AE2 interface

### ISSUE THREAD

**Issue by cloakable** [DarkholmeTenk/TardisModIssues#350]
I have an item conduit configured to insert into an interface connected to the tardis via a roundel. This happens every 10 ticks currently (I have a farm putting items into the item storage, which is then extracted and put into the interface.

Every time this happens, I get:
[Server thread/INFO] [STDOUT/]: [tardis.common.core.TardisOutput:print:49]: [TM][TCG]Attempted node get! appeng.me.GridNode@6ff985d5

Which is obviously bloating my log files HUGELY.

No security terminal on the network, channels are disabled in AE2, and I'm using AE2 rv2-stable-10.

(It does actually insert into the interface, but the spam is annoying.)

**Comment by cloakable** [comment]
Okay, less of an issue now that I've hushed Forge down with a custom log4j2.xml. You go Forge, log all the things with no clear way to stop that! :D

**Comment by ProsperCraft** [comment]
http://pastebin.com/AjhCBF7B

We are having it as well.

**Comment by DarkholmeTenk** [comment]
Removed
