### ISSUE TITLE
[ENHANCE] Sonic Screwdriver enchantability

### ISSUE THREAD

**Issue by cloakable** [DarkholmeTenk/TardisModIssues#353]
I'm using a mod (Ender IO) that adds the Soulbound enchant, but I cannot enchant the Sonic Screwdriver with it (which would be desirable for obvious reasons).

Could you make the Screwdriver enchant-able?

**Comment by AlienXtream** [comment]
anvil + book. the sonic is NOT a "tool" as far as MC is concerned (has no durability) which means if it were enchantable (i assume, i dont understand the code all that much) MC wouldnt know what to do with it (which enchants to put on it). what IS interesting though is one of my NEI plugins (no clue which one) says its enchantable with souldbound (among other things) but to be far is actually says that about literally EVERY item in my instance :/

**Comment by PrincessOfEvil** [comment]
That's because literally everything is enchantable with a soulbound book
except for some violently technical items like modular armor.

**Comment by cloakable** [comment]
Yes, book & anvil did the trick.
