### ISSUE TITLE
Ancient warfare animal farm can breed cows but not slay them.

### ISSUE THREAD

**Issue by ProsperCraft** [DarkholmeTenk/TardisModIssues#354]
Something inside the TARDIS is protecting cows from being killed by the animal farm, which leads to a problem with overpopulation because it killed the adults as far as it knows.

tardismod-1.7.10-0.99-103-DS

**Comment by AlienXtream** [comment]
shouldn't be anything to do with the tardis. the only thing it dose with mobs is prevent natural spawns. what ever the issue is it probably has more to do with ancient warfare. havnt played with that mod before so i couldnt say whats happening. just use some other killing mechanism (nothing wrong with even a vanilla lava "bath" ;P)

**Comment by ProsperCraft** [comment]
you don't understand, it breeds them, tries to kill them(you see them go red) and is not allowed to.
This leads to massive amounts of animals.

It works fine outside the TARDIS.

**Comment by AlienXtream** [comment]
once again, to my knowledge the tardis dosnt do anything to entities beyond preventing their spawning. you must test this further.
 try the following to start with
dose it affect all entities or just cows (and other passives)?

can you kill them via other methods from ancient war fair mod?

are you able to kill them with other means not related to the mod and if not dose removing the ancient war fair mod work?

**Comment by AlienXtream** [comment]
fyi. those are the questions i typicaly ask myself when testing things. if possible can you provide a video (youtube link) of the bug happening?

**Comment by DarkholmeTenk** [comment]
The tranquility effect may be the cause, try setting the tranquility level requirement to -1 or 10000 in the leveling cfg

**Comment by AlienXtream** [comment]
tranquility effect?! that a new thing?

**Comment by DarkholmeTenk** [comment]
No, it just doesn't quite work properly :p

**Comment by DarkholmeTenk** [comment]
May be fixed
