### ISSUE TITLE
This version travels to location too quickly then takes a really long time to land.

### ISSUE THREAD

**Issue by ProsperCraft** [DarkholmeTenk/TardisModIssues#355]
tardismod-1.7.10-0.99-103-DS

**Comment by DarkholmeTenk** [comment]
Did you update the server version to 103 too? It's a client sync issue, client not getting told flight length, iirc

**Comment by Werner1201** [comment]
@DarkholmeTenk Where I can Get this DS version ? Is on your server ?

**Comment by ProsperCraft** [comment]
It will be released with my DrTARDIS modpack this month.

**Comment by DarkholmeTenk** [comment]
But is the server on the right version too?

**Comment by Werner1201** [comment]
@ProsperCraft Where I can Get your modpack then ?

**Comment by DarkholmeTenk** [comment]
``` java
-           if ((sourceLocation != null) && (destLocation != null) && !inFlight())
+           if ((sourceLocation != null) && (destLocation != null) && inFlight())
```

I think this should fix it :P
