### ISSUE TITLE
[BUG] Extra Tank Makes Tardis Crash the world.

### ISSUE THREAD

**Issue by MaxBernstein** [DarkholmeTenk/TardisModIssues#356]
[crash-2015-12-06_23.09.53-server.txt](https://github.com/DarkholmeTenk/TardisModIssues/files/55350/crash-2015-12-06_23.09.53-server.txt)
I Also saved the world file, if you try to open it It'll crash. I guess it's an issue with tardis+Ender IO fluid conduict.
Also I have prints.
Print 1: http://prntscr.com/9b7u5o
Print 2: http://prntscr.com/9b7uca
I posted on minecraft forums in your thread but the issues are here, how silly am I xP
[quote]
Hello everyone, creator of the mod, folks!
I'm here, (I don't know if I'm posting this right), I'm here to post a bug, report a bug with tardis fluid module.
Here the prints.
Print 1: http://prntscr.com/9b7u5o
Print 2: http://prntscr.com/9b7uca
So, there is the bug, it show the configuration to a tank number 7, but actually there's only 6 tanks! And more, if you put the config with the sonic screwdriver to the tank 7 and pump ANY liquid into it your world will crash and will not enter anymore. I tried MCEdit, Wolrd Edit, everything, even NBT explorer to change .dat files but nothing, I lost my entire IC2 system because I didn't know that and clicked with the screwdriver and the world crashed.
Also, I don't know if I can post external links here, or anything. Actually, this is my first post! ^^ And I'm here just because Doctor Who is my favorite series and this mod is fantastic, I'm playing minecraft again because of it only! xP
Thanks for the mod, I'll wait your answer. Bye o/
[endquote]
I think this is everything, thanks for reading and thanks again for creating the mod, I LOVED IT! Bye ^^

**Comment by DarkholmeTenk** [comment]
#296 #297

**Comment by DarkholmeTenk** [comment]
Xmasish release date is planned :p
