### ISSUE TITLE
New sonic screwdriver.

### ISSUE THREAD

**Issue by grodax** [DarkholmeTenk/TardisModIssues#357]
It would be nice if there were some kinds of sonic screwdrivers or add customization.

**Comment by DarkholmeTenk** [comment]
Yup

**Comment by TheAmazingSpy** [comment]
How about you model them yourself grodax

**Comment by grodax** [comment]
I modeled. how to put it into the game?

**Comment by TheAmazingSpy** [comment]
Can I see? You could probably ask DarkholemeTenk to give you that part of the code, copy it and replace some files or so and bam

**Comment by FoxPotato** [comment]
It's not that easy. There is no way to put a custom sonic in the game right now.
Not without replacing a current sonic that is. (And that might not even work, haven't tested it)

**Comment by grodax** [comment]
I found an old model of a screwdriver. How to put it in the game? it is made in the techne. Maybe add a parameter in the config example screwdriver old model?
