### ISSUE TITLE
[ENHANCE] user created models via resource pack

### ISSUE THREAD

**Issue by AlienXtream** [DarkholmeTenk/TardisModIssues#358]
this is more of a thing that would be in the API in ver 1.0 but i would like a way to override and/or add custom models for the exterior and the sonic using OBJ (mesh) and MTL (texture) format. the main idea would be to allow users to create new sonic's/tardis's as the show progresses. "but Alien, what if im on a server and i use a custom resource pack?" easy, use default models if one is not found by the client. anyway, this is more an idea i wanted to throw out there to see if
a) is it feasible?
b) can it pop up at some point?
(please answer each separately)
on a side note spell check kept suggesting "repeatedly" for sepeatly as apposed to "separately". i legit opened word and used it to get the spelling :/...)

**Comment by DarkholmeTenk** [comment]
Well it's already in obj/png formats, so it should be replacable already?
If by can it pop up you mean can the screwdriver extend, then probably not.
