### ISSUE TITLE
[ENHANCE] Add Essentia and Centivis cable interfaces

### ISSUE THREAD

**Issue by Durpady** [DarkholmeTenk/TardisModIssues#36]
Thaumcraft support, allowing Roundels to act as Essentia tubes and Vis Relays, respectively.

**Comment by DarkholmeTenk** [comment]
![2015-05-08_16 07 16](https://cloud.githubusercontent.com/assets/2133466/7539239/874c9f4a-f59d-11e4-9bcf-e44a11c0ee58.png)

Can't do anything with centivis, I'm afraid
