### ISSUE TITLE
[Enhance] A lot of feature suggestions

### ISSUE THREAD

**Issue by Validfire** [DarkholmeTenk/TardisModIssues#361]
I posted this a long time ago on the mcforum page, however it seems to have been forgotten. In this document I have explained some features I believe should be added in great detail, if you have any questions just comment on the document page and I will try to get back to you.

https://docs.google.com/document/d/1--dTbsR5vqRlEJhSREhZdic5px9p1vSlv1iCvrs24Vo/edit?usp=docslist_api

**Comment by DarkholmeTenk** [comment]
#103 
#166 
#168 
And the last one will take up a bit more room on the console than I'd like, but may eventually get done at some point, but no guarantees.
