### ISSUE TITLE
Please make it bigger on the inside!

### ISSUE THREAD

**Issue by Eforen** [DarkholmeTenk/TardisModIssues#362]
If you use the LookingGlass api you can make it so that the doors on the tardis can actually open and see into the particular tardis's dimension allowing one to see into the tardis!! Please please implement this!!!

If you need help I am a programmer and would be very willing to help you code it!

http://www.curse.com/mc-mods/minecraft/230541-lookingglass

**Comment by DarkholmeTenk** [comment]
This is very performance intensive, not massively useful and a pain in the neck to change with the chameleon circuit system. It may get done at some point in the future, but for now I have higher priority things.

**Comment by Eforen** [comment]
As for performance I would suggest that you make it so that if the api is installed then it will use it if not then it will not use it.

As to the chameleon circuit system I am not familiar with that yet.
