### ISSUE TITLE
[DOUBT] Can I save my world? ;-;

### ISSUE THREAD

**Issue by MaxBernstein** [DarkholmeTenk/TardisModIssues#363]
[crash-2015-12-11_01.52.18-server.txt](https://github.com/DarkholmeTenk/TardisModIssues/files/59020/crash-2015-12-11_01.52.18-server.txt)

I entered on NBTExplorer and... http://prntscr.com/9cscch
I saw that I can change cordinates, dimension of the tardis, etc. There's A way to I reset the tardis? Like, put it in landed mod from there? Because I can't load my world... Again... ( sorry, I always crash things ;-; ) And, my aromabackup save is a bit late. I invested too much time farming XP to make my enderman powered spawner, there's a way to save it? If not, it's ok... ;-;

**Comment by AlienXtream** [comment]
downgrade darkcore. dark changed some stuff in the latest version and its not compatible woth older versions #342

**Comment by MaxBernstein** [comment]
Thanks for the help. But my inventory is all gone now... ;-;
Well, at least I lose some easy stuff to craft... I guess. The important thing is that my tardis is back to normal (I'll never activate drift and stable flight again) and my ender farm is there. But thanks a lot!!

**Comment by DarkholmeTenk** [comment]
Yep, this is related to using a version of darkcore too recent for that version of TM.
