### ISSUE TITLE
[Enhance] Foxpotato Folder Support

### ISSUE THREAD

**Issue by Validfire** [DarkholmeTenk/TardisModIssues#364]
I don't know where this is where I should post requests for this, however I have many, many schematics made by me, that I have released to the public. I have seen your efforts to make a friendly way of sharing schematics instead of hunting through the forum. However, I will not upload any of my schematics to Foxpotato until there is a better way of organizing things. If I were to upload all of my schematics for the Stonehenge series, that would add 18 new files to the page, it would be a pain to download all of those. That is why I compress them into a .zip file, I would LOVE it if you could allow folder creation to upload schematics into, this would create overall less clutter and would make it easier to find everything one is looking for.

**Comment by AlienXtream** [comment]
this is not likely to happen as the site checks the file to see if its a schema file. it dose this to prevent people posting any viruses or similar content. to my knowledge you cant do this from inside a zip file. though i suggest you upload a "demo" schema and put a link in the description to the zip.

**Comment by Belgabor** [comment]
If not support for folders, then support for packs of some kind? I have the very same issue...

**Comment by FoxPotato** [comment]
The foxpotato website has it's own issue page: https://github.com/DarkholmeTenk/The-FoxPotato-Project/issues
You can post things that relate to it there. :+1:

**Comment by DarkholmeTenk** [comment]
Yup, this is the wrong repo for FoxPotato suggestions
