### ISSUE TITLE
[BUG] Atomic Calculator + Dismantle mode in SonicScrewdriver

### ISSUE THREAD

**Issue by MaxBernstein** [DarkholmeTenk/TardisModIssues#365]
[crash-2015-12-11_10.40.57-server.txt](https://github.com/DarkholmeTenk/TardisModIssues/files/59392/crash-2015-12-11_10.40.57-server.txt)

I tried to click in reconfig mode and it did nothing then I change to dismatle mod and then my world crashed again ( I know, I'm sorry. ) Atomic Calculator it's a 'machine' from Calculator mod.
Thanks ^^

**Comment by DarkholmeTenk** [comment]
Well it's generally considered bad practice to return null on something expecting an arraylist :P

**Comment by DarkholmeTenk** [comment]
I would argue that the calculator mod author should instead return an empty list, but I'm not sure which the interface would suggest :P

**Comment by MaxBernstein** [comment]
Oh, so the problem isn't incompatibility of the tardis, but the calculator. Oh, that's fine, that's fine. I'll just do an ominywrench for the case then xP
Also, I saw that the sonic screwdriver is a wrench for everything, but not iC2, it's just don't recognize, But it's only that. Not a big deal.
Well then, issue closed. And I hope the best for the tardis mod! Best Tardis I ever saw in minecraft. ^^

**Comment by AlienXtream** [comment]
the wrench thing is IC2's fault. dark uses the wrench function built into forge, if IC2 dosnt use this function the thats their fault

**Comment by DarkholmeTenk** [comment]
actually, I use the CoFHCore wrench and the buildcraft wrench and the RedPower screwdriver. Forge has no inbuilt wrench.

**Comment by AlienXtream** [comment]
oh. i stand corrected then :)
