### ISSUE TITLE
how to use it?

### ISSUE THREAD

**Issue by grodax** [DarkholmeTenk/TardisModIssues#366]
http://imgur.com/ejFaVCS

**Comment by Validfire** [comment]
If you know how to place rooms, place down the library, the rest shall be explained

**Comment by grodax** [comment]
there appears only one mode, and I do not understand how to activate

**Comment by MaxBernstein** [comment]
The Locate function, transmat, recall, only apperar if you have enough levels in your tardis.. For example, in the level 11 you unlock the transmat function, and also you will already have the others functions unlocked as you level up by using your tardis. This control there allows you (if you have the three functions already unlocked by levels), you can deactivate the function in the screwdriver that are in place. with means, your default screwdriver automatically have all the functions, but in that menu you can deactivate the transmat function in that screwdriver. Basically that. ^u^

**Comment by grodax** [comment]
it should have been written in the library. Thank you for explanation
