### ISSUE TITLE
[ENHANCE] DS- (c) blocks keep color on pickup

### ISSUE THREAD

**Issue by AlienXtream** [DarkholmeTenk/TardisModIssues#367]
you know, so we can use them as pipe covers and stuff. basically the (c) versions of the Tardis blocks dont keep their metadata on pickup. in a side note changing a block with the decorator resets the metadata of the block, resetting the color to white

**Comment by Entoarox** [comment]
The decorator might reset it simply because not everything you can change the block to is a colorable block (The walkways & glass)

**Comment by AlienXtream** [comment]
oh i full well know what the issue is. im not talking about that. there are craftable, mineable versions of tardis blocks in the newer versions that can be dyed. im talking about them retaining their data value on being mined.

**Comment by DarkholmeTenk** [comment]
Not going to implement because it's a pain in the neck, would break the crafting recipes and the function I'm using to colour them doesn't affect itemblocks so the held blocks wouldn't be coloured, making things confusing.

**Comment by Entoarox** [comment]
Uhhhm, I think crafting recipes might already be broken, since they seem to require metadata 0 while 15 is the version players work with.

**Comment by AlienXtream** [comment]
see #421
