### ISSUE TITLE
[BUG] DS-Leftover Blocks on Console Change

### ISSUE THREAD

**Issue by AlienXtream** [DarkholmeTenk/TardisModIssues#368]
![2015-12-13_17 29 33](https://cloud.githubusercontent.com/assets/12606809/11765869/8a83fad6-a1bf-11e5-85aa-f366e60061d2.png)

tested on newest DS version. changing the "desktop" causes some blocks to remain. these are ACTUAL blocks and not ghost blocks.

**Comment by DarkholmeTenk** [comment]
Delete all your diff schema files and try again.

**Comment by MoonlightSystem** [comment]
how can you get the damage system builds?

**Comment by AlienXtream** [comment]
nope :/ still leaves blocks

**Comment by AlienXtream** [comment]
still an issue in latest builds

**Comment by DarkholmeTenk** [comment]
Can't reproduce, suspected because of schema creation using worldedit or something.
