### ISSUE TITLE
[BUG] DS-Can't Place rooms

### ISSUE THREAD

**Issue by AlienXtream** [DarkholmeTenk/TardisModIssues#369]
In the newest Dev Build i am unable to place rooms at all.
![2015-12-13_17 58 06](https://cloud.githubusercontent.com/assets/12606809/11765935/46b9abda-a1c3-11e5-9f9c-f90a1aa9a536.png)
inside
![2015-12-13_17 58 14](https://cloud.githubusercontent.com/assets/12606809/11765937/52bc2c3c-a1c3-11e5-85d3-417bbd71f8e1.png)
outside.

**Comment by AlienXtream** [comment]
nvm, caused by #368 creating dubble layered doors
 EDIT:or not. idk WHATS going on

**Comment by AlienXtream** [comment]
affected this console room only. but its literaly the default one without any inrerior flooring for total customisation

https://www.dropbox.com/s/m2fsex4jybszb6h/tardisConsoleBlank.schema?dl=0

**Comment by DarkholmeTenk** [comment]
Did you change the bounds of the schema?

**Comment by AlienXtream** [comment]
no, i just loaded the default console room, removed all the flooring and saved it

**Comment by grodax** [comment]
How do you change the standard sonic screwdriver?

**Comment by AlienXtream** [comment]
its a secret :P. there is a button on the temporal engine that changes the model. only in the DS branch

**Comment by grodax** [comment]
What is DS branch?

**Comment by Werner1201** [comment]
I'd like to know too
Em 19/12/2015 09:33, "grodax" notifications@github.com escreveu:

**Comment by AlienXtream** [comment]
DS is the Damage System. in short its an experimental build that adds function to the shields

**Comment by TheAmazingSpy** [comment]
Where is the Ds Branch _pulls out knife_ Nope... _pulls out axe_ noooop... _pulls out katana_ tell me!
Jk, but seriously I can not find the branch

**Comment by AlienXtream** [comment]
not available to the public yet

**Comment by TheAmazingSpy** [comment]
I cri

**Comment by AlienXtream** [comment]
it will be released soon, dont worry. its in the final tweak/bug fix phase i think.

**Comment by TheAmazingSpy** [comment]
I got a version! It's the older one but yeah!

**Comment by grodax** [comment]
When it is released?

**Comment by AlienXtream** [comment]
When dark is satisfied its ready. Be paitent :)

**Comment by DarkholmeTenk** [comment]
I think @ProsperCraft has a public pack with a newer version ;)

**Comment by Werner1201** [comment]
I don't think so .
https://github.com/ProsperCraft/DrTARDIS/tree/master/minecraft/mods
Em 24/12/2015 15:31, "DarkholmeTenk" notifications@github.com escreveu:

**Comment by AlienXtream** [comment]
no longer able to reproduce
