### ISSUE TITLE
[BUG] Roundels will not Dismantle

### ISSUE THREAD

**Issue by Durpady** [DarkholmeTenk/TardisModIssues#37]
New or old, attempting to Dismantle and opened Roundel does nothing.

**Comment by spannerman79** [comment]
Sonic Screwdriver must be in Reconfigure mode to open a Roundel

**Comment by FoxPotato** [comment]
dismantling a roundel means closing it again, which does not work.

**Comment by spannerman79** [comment]
Ok that I admit doesn't work.
Same if there is already a cable interface placed in - you cannot remove it.  Thats if thats the point and the roundel starts to become universal over time with the interfaces slowly placed in over time.
