### ISSUE TITLE
[Enhance] Expand the chunk loader roundel behavior to add more than  passive loading

### ISSUE THREAD

**Issue by astrutzenberg-godaddy** [DarkholmeTenk/TardisModIssues#371]
In this case if there were ways to enable/disable various modes of chunk loading:
- Always On/Passive  (how the current roundel operates)
- While the player is online (how the railcraft personal anchor works)
- Only while it's fed a specific item (like railcraft's world anchor)

In this case what would be useful would be if it could be configured to disallow passive, but allow the other two modes (tie it to player who "owns" the tardis?)

In terms of the 3rd option (feeding it an item):

What if you introduced a new roundel interface that acts as the "central hub" for all of the chunkloaders on the Tardis mod--you would use this as the interface to send it the items for consumption (default this to kontron crystals?)

**Comment by AlienXtream** [comment]
by default the tardis loads all chunks in the tardis iirc. the chunk loading roundel is really only there for you both have this off AND have no other chunk loading mods installed. why not use RC's personal anchor?

**Comment by DarkholmeTenk** [comment]
nup, tardis loads console room and chunk loader areas. #338 by config option in the damage system build. Specific item one isn't going to be implemented, because it makes things a decent bit more complex and adds a module that will be dependant on server configuration.
