### ISSUE TITLE
New screwdriver

### ISSUE THREAD

**Issue by grodax** [DarkholmeTenk/TardisModIssues#372]
I found an old model of a screwdriver. How to put it in the game? it is made in the techne. Maybe add a parameter in the config example screwdriver old model?

**Comment by DarkholmeTenk** [comment]
Can't be done yet. Once the damagesystem build is out, you can just replace one of the obj files, although that won't work unless you convert the techne model to obj format.

**Comment by TheAmazingSpy** [comment]
Get the damage build, and then... WONDERS!
