### ISSUE TITLE
Creating Console Schematics

### ISSUE THREAD

**Issue by ghost** [DarkholmeTenk/TardisModIssues#374]
I do know that creating and sharing tardis schematics for rooms is possible and I have also seen different console schematics. How would I create my own schematic for the tardis console room to be able to be shared?

**Comment by FoxPotato** [comment]
This seems more like something that would have to be posted on minecraftforum, seeing as it's not a bug or an enhancement.
(and I also forgot the precise routine, so maybe if you ask Alien nicely he'll answer :P)

**Comment by AlienXtream** [comment]
bum bu da! /tload tardisConsoleFull <x> <y> <z> 0 
then
 /tsave tardisConsole<console_name> <x> <y> <z>

TIPS:
find "Visible Schema:B:false" in configs and set to true
the "0" it the first command is the rotation the schema spawns in (only affects building, irrelevant for the most part)
you need ONE red door in a schema this will be the "front" and is the door that connects when you create a new room
DO NOT move the tardis console, door or engine blocks. they must stay where they are
don't use spaces in room names cos they aren't supported in the command.

@DarkholmeTenk  can this info be put somewhere either on the FoxPotatoProject sire or GH page for easy access plz

**Comment by FoxPotato** [comment]
Yeah, have like a div to the side with this info in it, just so people don't have to keep asking :p

**Comment by ghost** [comment]
Sorry about this I am having connection problems with the site currently so I used this and thank you for sharing with me on how to do this.
