### ISSUE TITLE
AE2 compatibility oversight

### ISSUE THREAD

**Issue by NightOps007** [DarkholmeTenk/TardisModIssues#377]
Trying to run tardis mod on a previously working instance, gives this crash report:
http://pastebin.com/d3zKYVSe

If I understand the report correctly, at line 57 in the report, tardis mod is trying to call to a function in the AE2 api. That api is unable to be called because AE2 is not installed and tardis mod doesn't know what to do in that case.

Adding AE2 mod fixed the issue, but I do not believe it is intended that it be a required mod. I didn't check to see if a similar error occurs with thaumcraft or the other interfaces; may be worth looking into.

**Comment by DarkholmeTenk** [comment]
Nope this is dragonapi.

**Comment by DarkholmeTenk** [comment]
see #295
DragonAPI ships with partially complete APIs for a bunch of mods so when the AE api code tries to instantiate its own class, it just fails. It also causes forge's Optional annotation to fail for the buildcraft wrench api.
If you remove dragonapi (and all it's dependants) and that fixes it, that will be your evidence :P
