### ISSUE TITLE
Can you copy Tardisi over worlds?

### ISSUE THREAD

**Issue by Validfire** [DarkholmeTenk/TardisModIssues#379]
I'm running a server, and thinking about doing a map reset. If possible, is there a way I can copy the player's Tardisi over to the new one. If so, I would just tell everyone to cram all of their stuff into their Tardis for the move. So is this possible?

**Comment by SomeBadGamer** [comment]
Just copy the tardis folder with the worlds over that's all

**Comment by AlienXtream** [comment]
im not sure its that easy. best thing to do would be just start over imo. fresh start

**Comment by DarkholmeTenk** [comment]
Copy the tardis folder and the TDimReg.dat and the TModPReg.dat from the data folder and everything should be fine, maybe?
