### ISSUE TITLE
[BUG] Landing Pad isn't interacting with TARDIS

### ISSUE THREAD

**Issue by Durpady** [DarkholmeTenk/TardisModIssues#38]
The Landing Pad Lockdown switch does nothing; whether it's out or not, a TARDIS on top of a Landing Pad won't transfer RF or fluids (and likely items).

**Comment by DarkholmeTenk** [comment]
Quick question: You have applied cable interfaces to the landing pad?

**Comment by Durpady** [comment]
Yep, I did that.

**Comment by DarkholmeTenk** [comment]
Kk, I'll look into it :)
