### ISSUE TITLE
[Enhance] TARDIS Skins

### ISSUE THREAD

**Issue by ghost** [DarkholmeTenk/TardisModIssues#380]
I do know that a future update might include different models but what about different skins for one model for the exterior while in game?

**Comment by AlienXtream** [comment]
iirc there is a skin server that is intended to function like MC player skins but the url leads to a dead end

**Comment by ghost** [comment]
I have seen the server and some of the skins on it but what about changing in game or have let's say one with the original and one with the modified skin in-game same time for different player with a command or console button?

**Comment by AlienXtream** [comment]
Like i said, not fully impleented. We dont know how it will work cos its not done. To my knowledge its a low priority thing.

**Comment by DarkholmeTenk** [comment]
The skins server config option is just a place for skins to be hosted. E.g. http://skins.darkcraft.io/tardis/DarkholmeTenk.png
