### ISSUE TITLE
[Doubt?] Is this "DS-" thing is about the Tardis On the Dark server ?

### ISSUE THREAD

**Issue by Werner1201** [DarkholmeTenk/TardisModIssues#381]
I just wanna to to know because I think I have A DS version On my computer after I donwloaded The Modpack for the server

**Comment by DarkholmeTenk** [comment]
yes, there is a damagesystem build on my server's pack. There is a much more up to date one in the pack by @ProsperCraft which should be available sooon :tm:

**Comment by Werner1201** [comment]
OKay. The Hype Is growing In myself
