### ISSUE TITLE
1.8.8 version

### ISSUE THREAD

**Issue by MoonlightSystem** [DarkholmeTenk/TardisModIssues#382]
There is now a version of forge for 1.8.8, so I'm wondering if  you could make a 1.8.8 port of the TARDIS mod for people using that version now that it's available. 1.8.8 is less of a hassle to mod in according to @asiekierka (who has recently released a mod for 1.8.8 called Charset-which you could add compatibility for) and the TIS-3D mod by @MightyPirates (both of which are open-source.

**Comment by DarkholmeTenk** [comment]
Same answer as #348. There was talk at minecon of a future version of forge making it so you don't need to port code again, I shall wait for that orcontinue to add features for 1710 until enough mods have come out for a new version for me to want to port it.
