### ISSUE TITLE
NPE calculating flight distance

### ISSUE THREAD

**Issue by RedeyeTheGoblin** [DarkholmeTenk/TardisModIssues#383]
http://pastebin.com/HdV1HLCr

Crash happened during players first flight. He says he "heard the level up sound and then it crashes". Running on an SMP server with darkcore-0.3-83 and tardismod-1.7.10-0.99-259.

**Comment by DarkholmeTenk** [comment]
Use older darkcore (72 i think) or ds tardismod (on curse)
