### ISSUE TITLE
[ENHANCE] Disable Level Up System in Config

### ISSUE THREAD

**Issue by TheNoim** [DarkholmeTenk/TardisModIssues#384]
Hello ShaneDarkholme,

i really want that you can disable the level up system in the config file. For some projects with friends its better to disable this. And some people only want to have fun with the tardis and don't want to level.

Best greetings Noim

**Comment by wackypocket** [comment]
i can't remember what it is its like ( /tardisxp # ) or something like that someone else will prob say it but you can just use that and level them up real quick

**Comment by TheNoim** [comment]
Yes i know. But for friends with no OP, this don't work.

**Comment by wackypocket** [comment]
i think you can just walk into there tardis and do it... or just op them for a sec so they can do it

**Comment by AlienXtream** [comment]
in the DS version, which is now public, you can set the level requirement for unlocking stuff in the configs.  setting it to unlock at level 1 will mean they will unlock that almost immediately (after first flight). this combind with the ability to spessify room count, power level and requirements and so on means your argument is invalid.

**Comment by DarkholmeTenk** [comment]
@AlienXtream is correct, no need for this in the DS builds (available on curse now) as far as I can see, so this is a null issue.
