### ISSUE TITLE
[Enhance] Label For Saved Locations

### ISSUE THREAD

**Issue by ph1x3r** [DarkholmeTenk/TardisModIssues#385]
Suggestion to add the ability to save a text label when a location is stored on the console.

My idea would be to have this saved internally and only visible with WAILA tooltip or the new tablet feature when hovering over the button.

No need to allow editing since saving again would prompt for the label again.

**Comment by AlienXtream** [comment]
already implemented. with the newest version on curse you can put paper in the temporal lab and get a "temporal name tag'. rename it in an anvil and right click the save slot

**Comment by DarkholmeTenk** [comment]
Yup. Already implemented.
