### ISSUE TITLE
Crashing When trying to open A Library Room

### ISSUE THREAD

**Issue by Werner1201** [DarkholmeTenk/TardisModIssues#386]
here's the log 
---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 30/12/15 14:18
Description: Ticking memory connection

java.lang.NullPointerException: Ticking memory connection
    at tardis.common.core.schema.PartBlueprint.<init>(PartBlueprint.java:283)
    at tardis.common.core.SchemaHandler.getSchema(SchemaHandler.java:217)
    at tardis.common.core.SchemaHandler.getSchema(SchemaHandler.java:210)
    at tardis.common.blocks.InternalDoorBlock.func_149727_a(InternalDoorBlock.java:132)
    at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:376)
    at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at tardis.common.core.schema.PartBlueprint.<init>(PartBlueprint.java:283)
    at tardis.common.core.SchemaHandler.getSchema(SchemaHandler.java:217)
    at tardis.common.core.SchemaHandler.getSchema(SchemaHandler.java:210)
    at tardis.common.blocks.InternalDoorBlock.func_149727_a(InternalDoorBlock.java:132)
    at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:376)
    at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Ticking connection --
Details:
    Connection: net.minecraft.network.NetworkManager@5251a85
Stacktrace:
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 712333920 bytes (679 MB) / 2360344576 bytes (2251 MB) up to 4056416256 bytes (3868 MB)
    JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4352m -Xms256m -XX:PermSize=256m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 13, tcache: 0, allocated: 15, tallocated: 95
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 128 mods loaded, 128 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1558-1.7.10.jar) 
    UCHIJAAAA   Forge{10.13.4.1558} [Minecraft Forge](forge-1.7.10-10.13.4.1558-1.7.10.jar) 
    UCHIJAAAA   appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core](minecraft.jar) 
    UCHIJAAAA   CodeChickenCore{1.0.7.47} [CodeChicken Core](minecraft.jar) 
    UCHIJAAAA   LanteaCraft-Core{1.0} [LanteaCraft Core](minecraft.jar) 
    UCHIJAAAA   MobiusCore{1.2.5} [MobiusCore](minecraft.jar) 
    UCHIJAAAA   NotEnoughItems{1.0.5.118} [Not Enough Items](NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
    UCHIJAAAA   OpenComputers|Core{1.5.20.38} [OpenComputers (Core)](minecraft.jar) 
    UCHIJAAAA   ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core](minecraft.jar) 
    UCHIJAAAA   OpenModsCore{0.8} [OpenModsCore](minecraft.jar) 
    UCHIJAAAA   <CoFH ASM>{000} [CoFH ASM](minecraft.jar) 
    UCHIJAAAA   debug{1.0} [debug](denseores-1.6.2.jar) 
    UCHIJAAAA   bspkrsCore{6.16} [bspkrsCore]([1.7.10]bspkrsCore-universal-6.16.jar) 
    UCHIJAAAA   ArmorStatusHUD{1.28} [ArmorStatusHUD]([1.7.10]ArmorStatusHUD-client-1.28.jar) 
    UCHIJAAAA   FloatingRuins{1.7.10.r02} [FloatingRuins]([1.7.10]FloatingRuins-universal-1.7.10.r02.jar) 
    UCHIJAAAA   StatusEffectHUD{1.27} [StatusEffectHUD]([1.7.10]StatusEffectHUD-client-1.27.jar) 
    UCHIJAAAA   appliedenergistics2{rv2-stable-10} [Applied Energistics 2](appliedenergistics2-rv2-stable-10.jar) 
    UCHIJAAAA   BiblioCraft{1.11.4} [BiblioCraft](BiblioCraft[v1.11.4][MC1.7.10].jar) 
    UCHIJAAAA   AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry](BloodMagic-1.7.10-1.3.3-17.jar) 
    UCHIJAAAA   Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) 
    UCHIJAAAA   Thaumcraft{4.2.3.5} [Thaumcraft](Thaumcraft-1.7.10-4.2.3.5.jar) 
    UCHIJAAAA   Botania{r1.8-244} [Botania](Botania r1.8-244.jar) 
    UCHIJAAAA   CoFHCore{1.7.10R3.0.3} [CoFH Core](CoFHCore-[1.7.10]3.0.3-303.jar) 
    UCHIJAAAA   BuildCraft|Core{7.1.14} [BuildCraft](buildcraft-7.1.14.jar) 
    UCHIJAAAA   BuildCraft|Builders{7.1.14} [BC Builders](buildcraft-7.1.14.jar) 
    UCHIJAAAA   BuildCraft|Transport{7.1.14} [BC Transport](buildcraft-7.1.14.jar) 
    UCHIJAAAA   BuildCraft|Energy{7.1.14} [BC Energy](buildcraft-7.1.14.jar) 
    UCHIJAAAA   BuildCraft|Silicon{7.1.14} [BC Silicon](buildcraft-7.1.14.jar) 
    UCHIJAAAA   BuildCraft|Robotics{7.1.14} [BC Robotics](buildcraft-7.1.14.jar) 
    UCHIJAAAA   BuildCraft|Factory{7.1.14} [BC Factory](buildcraft-7.1.14.jar) 
    UCHIJAAAA   CarpentersBlocks{3.3.7} [Carpenter's Blocks](Carpenter's Blocks v3.3.7 - MC 1.7.10.jar) 
    UCHIJAAAA   ChickenChunks{1.3.4.19} [ChickenChunks](ChickenChunks-1.7.10-1.3.4.19-universal.jar) 
    UCHIJAAAA   Railcraft{9.8.0.0} [Railcraft](Railcraft_1.7.10-9.8.0.0.jar) 
    UCHIJAAAA   ForgeMultipart{1.2.0.345} [Forge Multipart](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCHIJAAAA   chisel{2.5.1.44} [Chisel 2](Chisel2-2.5.1.44.jar) 
    UCHIJAAAA   origin{7.1.1} [Origin](Origin-1.7.10-7.1.1.jar) 
    UCHIJAAAA   compression{0.0.8} [Compression](Compression-1.7.10-0.0.8.jar) 
    UCHIJAAAA   darkcore{0.3} [Dark Core](darkcore-0.3-86.jar) 
    UCHIJAAAA   MineFactoryReloaded{1.7.10R2.8.0} [MineFactory Reloaded](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   EnderIO{1.7.10-2.2.8.381} [Ender IO](EnderIO-1.7.10-2.2.8.381.jar) 
    UCHIJAAAA   EnderStorage{1.4.7.37} [EnderStorage](EnderStorage-1.7.10-1.4.7.37-universal.jar) 
    UCHIJAAAA   ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation](ThermalFoundation-[1.7.10]1.2.0-102.jar) 
    UCHIJAAAA   ThermalExpansion{1.7.10R4.0.3B1} [Thermal Expansion](ThermalExpansion-[1.7.10]4.0.3B1-218.jar) 
    UCHIJAAAA   EnderTech{1.7.10-0.3.2.405} [EnderTech](EnderTech-1.7.10-0.3.2.405.jar) 
    UCHIJAAAA   ExtraUtilities{1.2.12} [Extra Utilities](extrautilities-1.2.12.jar) 
    UCHIJAAAA   FlatSigns{2.1.0.19} [Flat Signs](FlatSigns-1.7.10-universal-2.1.0.19.jar) 
    UCHIJAAAA   iChunUtil{4.2.2} [iChunUtil](iChunUtil-4.2.2.jar) 
    UCHIJAAAA   ImmersiveEngineering{0.6.4} [Immersive Engineering](ImmersiveEngineering-0.6.4.jar) 
    UCHIJAAAA   immersiveintegration{0.6.6} [Immersive Integration](immersiveintegration-0.6.6.jar) 
    UCHIJAAAA   inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks](InventoryTweaks-1.59-dev-152.jar) 
    UCHIJAAAA   IronChest{6.0.60.741} [Iron Chest](ironchest-1.7.10-6.0.60.741-universal.jar) 
    UCHIJAAAA   Waila{1.5.10} [Waila](Waila-1.5.10_1.7.10.jar) 
    UCHIJAAAA   JABBA{1.2.1} [JABBA](Jabba-1.2.1a_1.7.10.jar) 
    UCHIJAAAA   journeymap{5.1.3} [JourneyMap](journeymap-1.7.10-5.1.3-unlimited.jar) 
    UCHIJAAAA   MrTJPCoreMod{1.1.0.31} [MrTJPCore](MrTJPCore-1.1.0.31-universal.jar) 
    UCHIJAAAA   ProjRed|Core{4.7.0pre9.92} [ProjectRed Core](ProjectRed-1.7.10-4.7.0pre9.92-Base.jar) 
    UCHIJAAAA   ProjRed|Transmission{4.7.0pre9.92} [ProjectRed Transmission](ProjectRed-1.7.10-4.7.0pre9.92-Integration.jar) 
    UCHIJAAAA   OpenComputers{1.5.20.38} [OpenComputers](OpenComputers-MC1.7.10-1.5.20.38-universal.jar) 
    UCHIJAAAA   LanteaCraft{1.0.0-70} [LanteaCraft](LanteaCraft-1.7.10-70.jar) 
    UCHIJAAAA   Login_Shield{1.2-5-g59d68ff} [Login Shield](Login_Shield-1.2-5-g59d68ff.jar) 
    UCHIJAAAA   LookingGlass{0.2.0.00} [Looking Glass](lookingglass-1.7.10-0.2.0.00.jar) 
    UCHIJAAAA   malisiscore{1.7.10-0.14.0} [MalisisCore](malisiscore-1.7.10-0.14.0.jar) 
    UCHIJAAAA   malisisdoors{1.7.10-1.13.0} [Malisis' Doors](malisisdoors-1.7.10-1.13.0.jar) 
    UCHIJAAAA   Mantle{1.7.10-0.3.2.jenkins191} [Mantle](Mantle-1.7.10-0.3.2b.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0} [MFR Compat: Applied Energistics](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatAtum{1.7.10R2.8.0} [MFR Compat: Atum](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0} [MFR Compat: BackTools](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0} [MFR Compat: BuildCraft](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0} [MFR Compat: Chococraft](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0} [MFR Compat: ExtraBiomes](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatForestry{1.7.10R2.8.0} [MFR Compat: Forestry](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0} [MFR Compat: ForgeMicroblock](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatIC2{1.7.10R2.8.0} [MFR Compat: IC2](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   Mystcraft{0.12.3.01} [Mystcraft](mystcraft-1.7.10-0.12.3.01.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0} [MFR Compat: Mystcraft](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0} [MFR Compat ProjectRed](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0} [MFR Compat: Railcraft](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0} [MFR Compat: Sufficient Biomes](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0} [MFR Compat: Thaumcraft](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0} [MFR Compat: Thermal Expansion](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct](TConstruct-1.7.10-1.8.8.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0} [MFR Compat: Tinkers' Construct](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0} [MFR Compat: TwilightForest](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0} [MFR Compat: Vanilla](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJAAAA   testdummy{1.0} [MmmMmmMmmMmm](MmmMmmMmmMmm-1.7.10-1.9.jar) 
    UCHIJAAAA   Morph{0.9.2} [Morph](Morph-Beta-0.9.2.jar) 
    UCHIJAAAA   Morpheus{1.7.10-1.6.20} [Morpheus](Morpheus-1.7.10-1.6.20.jar) 
    UCHIJAAAA   Natura{2.2.0} [Natura](natura-1.7.10-2.2.0.1.jar) 
    UCHIJAAAA   NEIAddons{1.12.14.40} [NEI Addons](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|Developer{1.12.14.40} [NEI Addons: Developer Tools](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|AppEng{1.12.14.40} [NEI Addons: Applied Energistics 2](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|Botany{1.12.14.40} [NEI Addons: Botany](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|Forestry{1.12.14.40} [NEI Addons: Forestry](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|CraftingTables{1.12.14.40} [NEI Addons: Crafting Tables](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|ExNihilo{1.12.14.40} [NEI Addons: Ex Nihilo](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UCHIJAAAA   neiintegration{1.1.0} [NEI Integration](NEIIntegration-MC1.7.10-1.1.0.jar) 
    UCHIJAAAA   notenoughkeys{@MOD_VERSION@} [NotEnoughKeys](NotEnoughKeys-1.7.10-3.0.0b43-universal.jar) 
    UCHIJAAAA   ObsidiPlates{3.0.0.18} [ObsidiPlates](ObsidiPlates-1.7.10-universal-3.0.0.18.jar) 
    UCHIJAAAA   OpenMods{0.8} [OpenMods](OpenModsLib-1.7.10-0.8.jar) 
    UCHIJAAAA   OpenBlocks{1.4.4} [OpenBlocks](OpenBlocks-1.7.10-1.4.4.jar) 
    UCHIJAAAA   MapWriter{2.1.2} [MapWriter](Opis-1.2.5_1.7.10.jar) 
    UCHIJAAAA   Opis{1.2.5} [Opis](Opis-1.2.5_1.7.10.jar) 
    UCHIJAAAA   PiP{4.0.0} [PiP](PiP-4.0.0.jar) 
    UCHIJAAAA   PneumaticCraft{1.12.3-146} [PneumaticCraft](PneumaticCraft-1.7.10-1.12.3-146-universal.jar) 
    UCHIJAAAA   ProjRed|Compatibility{4.7.0pre9.92} [ProjectRed Compatibility](ProjectRed-1.7.10-4.7.0pre9.92-Compat.jar) 
    UCHIJAAAA   ProjRed|Integration{4.7.0pre9.92} [ProjectRed Integration](ProjectRed-1.7.10-4.7.0pre9.92-Integration.jar) 
    UCHIJAAAA   ProjRed|Fabrication{4.7.0pre9.92} [ProjectRed Fabrication](ProjectRed-1.7.10-4.7.0pre9.92-Fabrication.jar) 
    UCHIJAAAA   RedstoneArsenal{1.7.10R1.1.1} [Redstone Arsenal](RedstoneArsenal-[1.7.10]1.1.1-89.jar) 
    UCHIJAAAA   Shatter{4.0.0} [Shatter](Shatter-4.0.0.jar) 
    UCHIJAAAA   StevesCarts{2.0.0.b18} [Steve's Carts 2](StevesCarts2.0.0.b18.jar) 
    UCHIJAAAA   Sync{4.0.0} [Sync](Sync-4.0.0.jar) 
    UCHIJAAAA   TardisMod{0.994} [Tardis Mod](tardismod-1.7.10-0.994-124-DS.jar) 
    UCHIJAAAA   thaumcraftneiplugin{@VERSION@} [Thaumcraft NEI Plugin](thaumcraftneiplugin-1.7.10-1.7a.jar) 
    UCHIJAAAA   thaumicenergistics{0.8.10.10} [Thaumic Energistics](thaumicenergistics-0.8.10.10.jar) 
    UCHIJAAAA   thaumicexpansion{4.1.2} [Thaumic Expansion](ThaumicExpansion-1.7.10-4.1.2.jar) 
    UCHIJAAAA   ThaumicTinkerer{unspecified} [Thaumic Tinkerer](ThaumicTinkerer-2.5-1.7.10-164.jar) 
    UCHIJAAAA   ThermalDynamics{1.7.10R1.1.0} [Thermal Dynamics](ThermalDynamics-[1.7.10]1.1.0-161.jar) 
    UCHIJAAAA   TiCTooltips{1.2.5} [TiC Tooltips](TiCTooltips-mc1.7.10-1.2.5.jar) 
    UCHIJAAAA   TMechworks{0.2.14.100} [Tinkers' Mechworks](TMechworks-1.7.10-0.2.14.100.jar) 
    UCHIJAAAA   weepingangels{4.0.1} [Weeping Angels](WeepingAngels-1.7.10-4.0.1.jar) 
    UCHIJAAAA   WR-CBE|Core{1.4.1.9} [WR-CBE Core](WR-CBE-1.7.10-1.4.1.9-universal.jar) 
    UCHIJAAAA   WR-CBE|Addons{1.4.1.9} [WR-CBE Addons](WR-CBE-1.7.10-1.4.1.9-universal.jar) 
    UCHIJAAAA   WR-CBE|Logic{1.4.1.9} [WR-CBE Logic](WR-CBE-1.7.10-1.4.1.9-universal.jar) 
    UCHIJAAAA   McMultipart{1.2.0.345} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCHIJAAAA   denseores{1.0} [Dense Ores](denseores-1.6.2.jar) 
    UCHIJAAAA   IguanaTweaksTConstruct{1.7.10-2.1.5.140} [Iguana Tinker Tweaks](IguanaTinkerTweaks-1.7.10-2.1.5.jar) 
    UCHIJAAAA   ForgeMicroblock{1.2.0.345} [Forge Microblocks](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
    Class transformer null safety: all safe
    AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
    CoFHCore: -[1.7.10]3.0.3-303
    MineFactoryReloaded: -[1.7.10]2.8.0-104
    ThermalFoundation: -[1.7.10]1.2.0-102
    ThermalExpansion: -[1.7.10]4.0.3B1-218
    Mantle Environment: Environment healthy.
    TConstruct Environment: Environment healthy.
    RedstoneArsenal: -[1.7.10]1.1.1-89
    ThermalDynamics: -[1.7.10]1.1.0-161
    Stencil buffer state: Function set: GL30, pool: forge, bits: 8
    AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:ON, BC:ON, RF:ON, RFItem:ON, MFR:ON, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 1 / 8; [EntityPlayerMP['WernerRomling'/2915, l='New World', x=0,15, y=63,00, z=-10,19]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by DarkholmeTenk** [comment]
Is this a standard library room because I can't see how this would happen with a valid library schema? I can't replicate this.

**Comment by Werner1201** [comment]
I really don't Know If It's the Library that come With the Mod or Is another. Because I have A folde With All the most recent Schemas I just Create The modpack loaded Without Them Then I put The Rest of Them.

**Comment by DarkholmeTenk** [comment]
Well if you delete the library room from your config/darkmods/tardismod/schemas folder, then it'll be forced to use the one from the mod itself.
