### ISSUE TITLE
TARDIS Cable Interfaces missing from crafting lookup

### ISSUE THREAD

**Issue by ph1x3r** [DarkholmeTenk/TardisModIssues#387]
Not 100% sure if this is a Tardis mod issue, or some behavior elsewhere. But I am unable to look up the crafting recipe for the various cable interfaces. However, if you know the recipe, then the crafting does work.

The new "upgrades" are there, but not the items for the roundels.

Using the latest v0.994 'DamageSystem' version of the mod from Curse page.
Vaygrim's Chance 3 modpack with Tardis mod upgraded on server and client to solve crashes.

**Comment by AlienXtream** [comment]
i personally had no issues with this

**Comment by ph1x3r** [comment]
Not an issue with Tardis mod. Closing.
