### ISSUE TITLE
[ENHANCE]/[BUG] 

### ISSUE THREAD

**Issue by FoxPotato** [DarkholmeTenk/TardisModIssues#39]

**Comment by FoxPotato** [comment]
I did sonething wrong, i meant to mention that the exterior radar thing thinks at the bottom of the ocean is a safe area to leave the tardis.

**Comment by DarkholmeTenk** [comment]
Well it's not wrong... :)

**Comment by spannerman79** [comment]
Safe: No instant death
Unsafe: Instant death (block/blocks covering door)

**Comment by FoxPotato** [comment]
well if you look at it that way.
