### ISSUE TITLE
Curse D-S build game breaking  bug  

### ISSUE THREAD

**Issue by SomeBadGamer** [DarkholmeTenk/TardisModIssues#394]
Imagine  this your bad tardis  pilot all the auden your tardis takes to much damage  and you don't have any chronological steel or dalekanieumm to fix it and you need to be in the vortex to make it so to fix that I think their should be a passive hull repair just enoghf to get in to flight and maby make a upgrade that can speed the repair up because it should be slow to balance it out so you don't use that to cheat repair

**Comment by FoxPotato** [comment]
some of the bulbs are fixable without the use of chronosteel nor dalekanium. But i can't recall if that was enough to fly or not.

**Comment by SomeBadGamer** [comment]
I know but it is not enough  to  get in to flight plus what if the center master circit is broke then those won't even work

**Comment by AlienXtream** [comment]
the DS branch is still TECHNICALLY in beta. dark just released it as a Christmas present type thing (and probably cos i stopped finding as many bugs :P). there are still some things to fix, i didnt do much with the damage itself as im actually a decent pilot, and by "decent" i mean i have stable flight set to unlock at a relatively low level :P

**Comment by SomeBadGamer** [comment]
I know it's beta but still worth mentioning

**Comment by DarkholmeTenk** [comment]
Dalekanium doesn't require vortex to make, neither does kontron. It's possible to repair your hull up to ~70% without needing to fly.

**Comment by SomeBadGamer** [comment]
Ok sorry thogh it did

**Comment by AlienXtream** [comment]
so did i till he told me how the crafting works :P

**Comment by DarkholmeTenk** [comment]
#286 will fix not having access to materials as well as the fact that you can repair up to flying state already.
