### ISSUE TITLE
[ENHANCE] Telephone teleport 

### ISSUE THREAD

**Issue by LotuxPunk** [DarkholmeTenk/TardisModIssues#395]
Hello!
It is for an improvement that I come this time!
The main function of the TARDIS is of led The Doctor, where at need for him, I thus propose the addition of a telephone craftable which "Doctor" can give for one person.

This telephone will allow in case of call of the other player to put automatically the address and phone number of this one automatically in TARDIS if the call is accepted by "Doctor"

**Comment by FoxPotato** [comment]
But, why not just level up enough to have the precise flight and private message your coordinates to a friend? And i mean, the precise flight isn't even necesarry tbh.

**Comment by DarkholmeTenk** [comment]
This has been suggested several times before and I don't plan on implementing it because it makes life a bit too easy for my liking. Even when the doctor gets calls from companions, he still has to run around and throw levers to actually fly to that person.
