### ISSUE TITLE
[ENHANCE] Temporal Accelerator

### ISSUE THREAD

**Issue by AlienXtream** [DarkholmeTenk/TardisModIssues#397]
a block that, when adjacent to a Tile entity, will accelerate it by a certain factor. could stack with multiple accelerators with diminishing retuns (e.g 1 accelerator= +100%, 2 = +150%, 3 = +175% and 4 = 200%) capping at 4 or so. heavy artron cost per tick, reduced cost while in flight. blacklisting things like the accelerators them selves and things like aura nodes.

**Comment by FoxPotato** [comment]
That actually sounds kinda cool.
But what happens when you place this next to the temporal dirt? kinda curious now lol
but aside from that, amazing idea. (maybe only change the increments though, so it's not 25 every time)

**Comment by AlienXtream** [comment]
those numbers were just examples :P

**Comment by DarkholmeTenk** [comment]
Have you ever tried putting temporal dirt under different things?

**Comment by AlienXtream** [comment]
no...

**Comment by AlienXtream** [comment]
no effect on a furnace

**Comment by ghost** [comment]
This one already in... I don't remember, maybe in... Raika's Chomaticraft... But this mod actualy need it

**Comment by SomeBadGamer** [comment]
i like it and it will be kinda like tocherieno (yes thats a mod it lets you speed up the tick rate of blocks up to 400% times its normal speed) but its more balanced
