### ISSUE TITLE
Client Crash from beginning Unco-ordinated flight

### ISSUE THREAD

**Issue by Reginald-Halifrax** [DarkholmeTenk/TardisModIssues#399]
Boy didn't think id break it that fast. got the mod 10 minutes ago as of this message.

It seems only the client is effected by the error. The server i had it running on however felt no change

[Error.txt](https://github.com/DarkholmeTenk/TardisModIssues/files/83481/Error.txt)

Any ideas what the issue may be?

**Comment by wackypocket** [comment]
try running it on java 7

**Comment by Reginald-Halifrax** [comment]
I am afraid i have a mod currently that is locked down for 8 only. the error only happens from Drift Flight

**Comment by wackypocket** [comment]
what version u using?

**Comment by Reginald-Halifrax** [comment]
tardismod-1.7.10-0.994-124-DS

**Comment by wackypocket** [comment]
try this:

http://tardismod.com:8080/job/Darkcore/95/artifact/build/libs/darkcore-0.3-95.jar

**Comment by Reginald-Halifrax** [comment]
[Error.txt](https://github.com/DarkholmeTenk/TardisModIssues/files/83483/Error.txt)

Seems to persist.

**Comment by Reginald-Halifrax** [comment]
I will just avoid using drift mode (not that it is difficult too) but ill leave this open for Dark if he has a solution.

**Comment by wackypocket** [comment]
yea cause i got no clue... leave it to the big boys xD

**Comment by wackypocket** [comment]
welp all i can suggest is remove one mod at a time until you find the one conflicting with it.

**Comment by DarkholmeTenk** [comment]
#393

**Comment by wackypocket** [comment]
what did i tell you... leave it to the big boys xD
