### ISSUE TITLE
[BUG]Landing Pads still aren't fixed.

### ISSUE THREAD

**Issue by Durpady** [DarkholmeTenk/TardisModIssues#40]
The problem may have been misdiagnosed; the Landing Pads aren't accepting items from Hoppers, or connecting to Buildcraft Item Pipes (when equipped with Itemduct circuits).  Instead of the issue being between the Pads and the TARDIS, it seems to be between the Pads and other blocks.  I will note that even when equipped with an Energy Conduit, WAILA doesn't display an RF rating.  The apparent "connections" by Fluid and Kinesis Pipes are probably visual only.

Also, the console is being spammed with
[10:20:26] [Server thread/INFO] [STDOUT]: [tardis.common.tileents.LandingPadTileEntity:getCore:39]: NE
at about 3-4 per second.  Might want to look into that.

Lastly, Dismantling Pads isn't working - I assume we are supposed to be able to remove circuits without breaking the block.  Same problem as Roundels?

**Comment by DarkholmeTenk** [comment]
NE means you have the TARDIS set to not allow landing pad interaction (yay for debug statements)

Dismantling the landing pad is supposed to break it (i.e. make it drop as an item) and pop off all the circuits aswell; that isn't working atm, so I'll fix that :)

**Comment by DarkholmeTenk** [comment]
Fixed in build 47, to be uploaded to curse later
