### ISSUE TITLE
TARDIS Chameleon Circuit

### ISSUE THREAD

**Issue by TARDIStraveler15** [DarkholmeTenk/TardisModIssues#401]
Hi i am not really sure if this is a bug on my end or if it has not been completed yet. With the Chameleon Circuit i can only get the old police box theme and nothing else... is this something that is still in completion or is there some thing i have to do to change what the TARDIS looks like outside if so could someone please let me know.

Many thanks

**Comment by FoxPotato** [comment]
Right click the chameleon circuit to change option, and then take off and land again to update the exterior.

**Comment by TARDIStraveler15** [comment]
Right click it where because i removed it from the engine and then tried right clicking and nothing changed the same with removing it from the engine and putting it back in.

**Comment by FoxPotato** [comment]
its either right clicking or shift right clicking in the air (probably shift now i think about it, but just try both). And the lore of the item should change, so just mouse over it to see which exterior you have selected.

**Comment by TARDIStraveler15** [comment]
Thanks its shift right clicking while holding it.

**Comment by FoxPotato** [comment]
If it's solved, would you please be so kind to close the issue? Thank you :D
