### ISSUE TITLE
[Enhance] Fast-landing mode lever (NOT fast-return protocol)

### ISSUE THREAD

**Issue by ghost** [DarkholmeTenk/TardisModIssues#405]
Tardis should have special fast-landing mode, that allows in cost of shields, energy and/or hull land faster because it takes too long.

**Comment by SomeBadGamer** [comment]
i say thats a good balance but what if you are at almost minimul hull and you press it not knowing of it or by mistake

**Comment by AlienXtream** [comment]
why? it dosnt take THAT long...

**Comment by SomeBadGamer** [comment]
True but if your in a rush

**Comment by weldinclusion** [comment]
It's a time machine, you're never in a rush.

**Comment by DinixM** [comment]
Isn't the landing sequence the TARDIS trying to load the the surroundings of where it lands?

**Comment by SomeBadGamer** [comment]
That is true  didn't  think  about  that

**Comment by ghost** [comment]
But it isn't takes so much time! And it can have config option or even be placed on TARDIS engine!

**Comment by ghost** [comment]
Oh, mistake you said? Real mistake - activated room deletion protocol!

**Comment by DarkholmeTenk** [comment]
Not going to implement, sorry, makes the flight code more complex than it already is and I think it's fine the way it is.
