### ISSUE TITLE
In-Game Config Menu

### ISSUE THREAD

**Issue by Validfire** [DarkholmeTenk/TardisModIssues#406]
In many mods, if you click on the "Mods" button and then on the mod, it will let you configure it. Is it possible to add compatibility for this sort of thing in your mod? No offence, but it's kind of a pain to go searching through the many config files to change one option, then go through the launch sequence again... This would make my life so much easier.                    Best Regards, -Validfire

**Comment by AlienXtream** [comment]
not really necessary. convenience is the child of laziness ;)

**Comment by ghost** [comment]
Agree with AlienXtream. Wasting of time.

**Comment by DarkholmeTenk** [comment]
I understand why this is useful, but:
I've written my own config system which would take a decent amount of parsing to get it to comply with forge for the gui
You'd still need to restart your client to have most of the options take effect
There are a lot of options which would make it a damn long list to scroll through.
