### ISSUE TITLE
[Enhance/Security] More security for room deletion button

### ISSUE THREAD

**Issue by ghost** [DarkholmeTenk/TardisModIssues#409]
This one fkin button is too dangerous. It adds a new form of griefing: ROOM EXTERMINATING. Please, make it more secure such as "soulbound" - only TARDIS owner can activate it, or remove it at all.
P.S. Sorry for issue flooding))

**Comment by SomeBadGamer** [comment]
Agree

**Comment by DinixM** [comment]
Could be bound with the Modify Rooms permission. Make it so the button rejects those without the correct permission due to isomorphic controls and what have you. I'm in agreement here as well.

**Comment by AlienXtream** [comment]
hang on? so ANYONE regardless of permissions can use this button?

**Comment by DarkholmeTenk** [comment]
``` java
if ((controlID == 901) && ds.hasPermission(pl, TardisPermission.ROOMS))
```

No?

**Comment by ghost** [comment]
I mean, MORE security!

**Comment by DarkholmeTenk** [comment]
Anyone with permission to modify rooms can already just delete the (max using default schemas) 3 rooms directly connected to your console room and have the exact same thing happen.

**Comment by DarkholmeTenk** [comment]
Personally, I don't think this is necessary, but I guess I'm nice so it's now in the DS build.
