### ISSUE TITLE
[ENHANCE] roundels

### ISSUE THREAD

**Issue by FoxPotato** [DarkholmeTenk/TardisModIssues#41]
t's probably already on your to do list. but it's really weird to have a 2d block go to 3d. so maybe 3d models for the roundels?

**Comment by DarkholmeTenk** [comment]
There is actually a 3d model for them; the code to render them isn't running because it caused quite a bit of lag due to the number of them; I'll probably change the open roundel model to a cube overlay so I can get the white texture with the cables in without them being discoloured

**Comment by FoxPotato** [comment]
you could always instead of the model pointing outwards have them go inwards. so like a hole into the block.
