### ISSUE TITLE
[ENHANCE] Being able to look inside the TARDIS before you enter.

### ISSUE THREAD

**Issue by garnerfenoms** [DarkholmeTenk/TardisModIssues#410]
The Looking Glass API would allow you to look in the tardis before you enter to truly give you the "bigger on the inside" experience. i think this would be a great addition to the mod.
http://www.curse.com/mc-mods/minecraft/230541-lookingglass#t1:description

**Comment by Werner1201** [comment]
This is Planned to Be inplemented But not Now. And This was already
Suggested . But You're welcome to try again .
PS :Before you Post try to read The other Suggestions you may get some
ideas from The Ideas.
Em 18 de jan de 2016 8:11 PM, "garnerfenoms" notifications@github.com
escreveu:

**Comment by DarkholmeTenk** [comment]
#151 #181 #391
