### ISSUE TITLE
rooms(its buggin me #puns)[however its not really a bug more like a question and a suggestion]

### ISSUE THREAD

**Issue by Webber88** [DarkholmeTenk/TardisModIssues#414]
so why is there a large chamber, a medium chamber, a med farm but no large farm or small farm or small chamber...it kinda bugs me

ps. it would be great if there was an option(in the config default off) that would have a selection that would just add in a tinkers construct forge(a massive one) or a AM2 room that would have the required stuff and structures for AM2

thanks for reading pps love the mod its the first thing i get in minecraft>_>... i may or may not just go and grab a key from creative :P

**Comment by FoxPotato** [comment]
Why don't you make them yourself and upload them to http://www.foxpotato.com :D 
Plenty of schematics already on there.

**Comment by Webber88** [comment]
i dont think its stopped development actually...just sayin...

**Comment by Webber88** [comment]
ty... but this begs a question for a scrub like me... how do i actually put these schematics in the game ;-; the scrub life is hard

btw u might know... why is the tardis always at a midnight time inside it? is it supposed to represent the time vortex?

**Comment by FoxPotato** [comment]
There is a button on the far side of the console, in the bottom left corner iirc. press that to switch from day to night, and vice versa.
and just place the schematic files in "[mod folder]\config\darkmods\TardisMod\schemas" :D

**Comment by Webber88** [comment]
u da man :D

**Comment by DarkholmeTenk** [comment]
#149
