### ISSUE TITLE
[BUG] Got a few. Farming/AE

### ISSUE THREAD

**Issue by ImDoctorChaos** [DarkholmeTenk/TardisModIssues#415]
Got a couple I ran in to. 

If I hit enter at ant point while in the tardis I get. "a fatal error has occured, this connection is terminated." Can't seem to find a log about this. Doesnt crash the whole game just kicks you out of SP or MP.

If I put down regular dirt inside the TARDIS it doesn't grow without bonemeal. Alternatively Temporal dirt grew things too fast and we turned the bonemeal chance off in the config and not Temporal Dirt doesnt grow anything. Im assuming a Mod we have installed is not playing very nice with the dirt.

If I link ME cable through the roundels, when the server is restarted all the roundels link together.
Example: We restarted our server and I had my AE network through roundels doing things here and there. But a friend had a quantum link in the TARDIS so I could bum yellorium to power a reactor. That AE connection was linked into a roundel as well. When we restarted the server our networks connected and both networks went red.

**Comment by Entoarox** [comment]
I already submitted a report for the AE issue in https://github.com/DarkholmeTenk/TardisModIssues/issues/413

As to the enter problem, have you checked if there is any keybind conflict going on with the enter key?

**Comment by FoxPotato** [comment]
What do you mean by "too fast", because temporal dirt is quite OP.

**Comment by ImDoctorChaos** [comment]
2 impulse itemducts, resonant servo'd out of an Ender IO farming station, at the lowest range, couldn't keep up with the growth rate of the trees on the unedited config Temporal Dirt. 
Edit: Also since growth ticks don't seem to be happening in the TARDIS, only bonemeal, that isn't the full speed of the dirt. That stuff is scary op.

**Comment by ImDoctorChaos** [comment]
Apparently ttrees opnly grow while the TARDIS is set to day.

**Comment by FoxPotato** [comment]
The dirt is indeed OP, but that's why we love it.

And do trees in general only grow during day time? I can't remember tbh.

**Comment by ImDoctorChaos** [comment]
all crops can grow at night provided light is supplied iirc. The vanilla ones atleast
dirt is too op. I sat there and laughed when i filled up a jabba barrel to 128 stacks in 5 minutes.

**Comment by DarkholmeTenk** [comment]
Pretty sure the dirt isn't normally that op and I've definitely grown crops without bonemeal before, so modlist pls. Also, I don't listen for hotkeys, so that definitely isn't my mod's problem :P

**Comment by ImDoctorChaos** [comment]
It wasn't the dirt. Just put down some torches around it and they grow at the night setting.
Guess the roundels weren't close enough or they weren't putting out enough light
And the dirt is crazy. I had every side of the Farming station minus the bottom exporting through resonant servoed impulse itemducts and it just couldn't keep up with the dirt, entities were going everywhere. Even with bone meal set to 0 in the config.

**Comment by DarkholmeTenk** [comment]
Temporal dirt is supposed to be slightly op, hence the diamond cost, but you can always reconfigure it however you want :P
So at this point, as far as I can see, there are no bugs?

**Comment by ImDoctorChaos** [comment]
Enter thing is probably not due to this. I guess the only legitimate issue is the roundels and AE thing
sorry for wasting your time on the other things.

**Comment by DarkholmeTenk** [comment]
No worries. Back to revising for exams! :D

**Comment by ImDoctorChaos** [comment]
the ME thing is still an issue

**Comment by DarkholmeTenk** [comment]
Yeah #413

**Comment by ImDoctorChaos** [comment]
Mine is different from that. His NEEDS to be rebooted. Rebooting BREAKS mine.

**Comment by Entoarox** [comment]
I am currently the only player using AE roundels on my server, so I cannot be certain that a reboot would not cause different tardisses to connect their roundels either way. (I will get on testing that ASAP and get back to you on it)

**Comment by Entoarox** [comment]
Just managed to get another player to give a hand, the 'shared roundels' issue does not show up for us.
