### ISSUE TITLE
[ENHANCE] Colouring

### ISSUE THREAD

**Issue by FoxPotato** [DarkholmeTenk/TardisModIssues#42]
maybe some easier ways to colour the TARDIS. maybe like shift right click on a flat block colours that block and all the other flat blocks touching it but not the solid blocks. idk. just a way to colour in your TARDIS faster.

**Comment by Soyaro666** [comment]
after comparing my idea to this I found a single difference: I would prefer when the blocks aren't just distinguished by it's type but by it's color too. so you could draw a line of one color and sneak+recolor one side of that line without changing the other side.

sorry again. I forgot to check page 2 for something similar

**Comment by DarkholmeTenk** [comment]
Fixed in new darkcore; requires you to not be on the ground to color in big areas (i.e. jump)

**Comment by laz2727** [comment]
Make it cancel while crouching too, unless it already does that. I like
flying.

**Comment by FoxPotato** [comment]
What do you mean with cancel?

**Comment by DarkholmeTenk** [comment]
If you're crouching, there's no way for the block to detect a right click; dyes don't pass sneak right clicks on to the block; it'd need an ASM to overwrite that method and I can't be bothered with that.

**Comment by laz2727** [comment]
Oh,ok then.
