### ISSUE TITLE
[BUG] Cant craft other interior blocks

### ISSUE THREAD

**Issue by AlienXtream** [DarkholmeTenk/TardisModIssues#421]
NEI says there is a recipe but putting the recipe in a crafting grid yields no results. i crafted the solid block (stone and cronosteel) and put it in the crafting grid but the output slot has nothing
![2016-01-25_19 57 52](https://cloud.githubusercontent.com/assets/12606809/12546466/143a4a8c-c39e-11e5-8a00-da31c7e0eefb.png)

**Comment by CultusMechanicus** [comment]
Extra bit of info. This looks like it's due to the recipes producing blocks with damage values (eg. block id:15) but the recipes require blocks without damage values (eg. block_id). Presumably this is to do with color metadata.

**Comment by AlienXtream** [comment]
oh i had a fairly good idea WHAT the problem was. still needs fixing regardless :P

**Comment by CultusMechanicus** [comment]
That wasn't aimed at you :) It was for Dark so as to help him with debugging :)

**Comment by AlienXtream** [comment]
still stuck using solid blocks here. either @DarkholmeTenk or @FoxPotato please fix it

**Comment by FoxPotato** [comment]
"NEI says there is a recipe" Recipe for what exactly?
And what is the exact problem here? The crafting recipes not accepting coloured blocks?

**Comment by AlienXtream** [comment]
Go to survival and try and craft them.

**Comment by FoxPotato** [comment]
NEI is not telling me there's a crafting recipe with the solid block, just that you can either craft one using stone and chronosteel. Or using a crafted flat block.

EDIT: Ok I see the problem now. Using R tells you you can use a single block to craft them. but using U doesn't give the crafting recipe. That's weird

**Comment by AlienXtream** [comment]
yeh, its important with recipes to test them in the actual crafting table i think :P fairly sure its a meta data thing. if the recipe just ignores the meta data entirely that SHOULD cover most bases also @FoxPotato add me on steam :P
