### ISSUE TITLE
[BUG] Saved location labels lost on server exit

### ISSUE THREAD

**Issue by CultusMechanicus** [DarkholmeTenk/TardisModIssues#422]
If you use a Temporal Label to name a saved location button it works but does not persist across a server world save and restart. On restart the location is still set but the name is lost.

edit: this is on the DS branch build 129 with darkcore from curse.

**Comment by FoxPotato** [comment]
Not actually able to recreate because of servers being annoying, could someone confirm this.

**Comment by DarkholmeTenk** [comment]
Can't reproduce. Going to assume fixed.
