### ISSUE TITLE
Console Spam Error

### ISSUE THREAD

**Issue by Reginald-Halifrax** [DarkholmeTenk/TardisModIssues#423]
Minecraft seems to have decided to take a liking to spamming the game output

[Error.txt](https://github.com/DarkholmeTenk/TardisModIssues/files/106103/Error.txt)

This is a message it continues to spam until i disconnect from the server. i tested by removing the mods i was trying to add on to the client but then the spam converted to this. which pointed over to the tardismod and the core file

**Comment by DarkholmeTenk** [comment]
More info is needed. Are you trying to use this mod on the client when it isn't installed on the server? Does it happen in single player? What version of forge are you using? Etc.

**Comment by Reginald-Halifrax** [comment]
the mod is Opencomputers and twilightforest which is on the server also. the forge is 17.10-Forge10.13.4.1492. Something corrupted my singleplayer and crashed it so thats information im still trying to go and get

**Comment by Reginald-Halifrax** [comment]
it appears the spam only happens while on a server

**Comment by Reginald-Halifrax** [comment]
Considering twilight forest throws more dimensions, is it possible the Dimension lever has some sort of cap?

**Comment by Reginald-Halifrax** [comment]
I should also mark that only the client is the one that spams. the server gets no such error. (i am doing way too many comments so apologies)

**Comment by Reginald-Halifrax** [comment]
Right then i have a uh.. much heavier more helpfull note. the issue only appears when you are inside a tardis. the spam doesnt lag or anything but it is you know. in the way.

**Comment by Reginald-Halifrax** [comment]
it seems to have converted to the old spam message 

[17:39:57] [Client thread/ERROR] [FML]: NetworkEventFiringHandler exception
java.lang.NullPointerException
Jan 28, 2016 5:39:57 PM io.netty.channel.embedded.EmbeddedChannel recordException
WARNING: More than one exception was raised. Will report only the first one and log others.
java.lang.NullPointerException

Still havent a clue whats going on

**Comment by DarkholmeTenk** [comment]
Sorry; I have exams atm, but I'll take a look later on. No idea why you're getting exceptions from within forge's network code tho, all I can suggest rn is updating forge.

**Comment by DarkholmeTenk** [comment]
Should be fixed.
