### ISSUE TITLE
[BUG] Server Crash on first flight

### ISSUE THREAD

**Issue by Soyaro666** [DarkholmeTenk/TardisModIssues#424]
Hey there, I'm back ^^

Test scenario is tardismod-1.7.10-0.99-275, darkcore-0.3-103, multiplayer standalone with multiple other mods.

Report is available for 1 Month: https://paste.ee/p/emahO

Test result: On first flight after spawning a tardis (uncoordinated flight) the server died outputting the log above.

just to mention it: With current Curse versions every Client (all players were inside the same tardis) crashed while the server were running stable.

Sorry if I'm writing a duplicate, I didn't find this topic on a quick search

so far
Soyaro

Edit: ah, completely forgot...
the crash happened right before the levelup-sound (Level 0 to 1) was played, in the other setting with Curse versions it occured in the middle of that sound

Edit 2: create singleplayer world, pull Key with /give, spawn Tardis, start uncoordinated, sound starts, crashes... http://pastebin.com/wCn6cPf2

**Comment by DarkholmeTenk** [comment]
Client crash is fixed with https://github.com/DarkholmeTenk/TardisModIssues/issues/393
NPE with flight distances is #383

**Comment by Soyaro666** [comment]
according to those posts I should use 129 DS. thanks!
