### ISSUE TITLE
TARDIS dim corruption; doors caused crashes

### ISSUE THREAD

**Issue by feralknights** [DarkholmeTenk/TardisModIssues#426]
Hi there, I was the one that wrote a little bit back about the major crashes/corruptions over on Curse.  Just to refresh, from Jan 13th:

Sadly, when we upgrading to the release candidate, we ran into a few errors.  It worked fine for a few days, though!  Transitioning into the TARDIS would cause crashes, and any attempt to deregister me from ownership wouldn't work.  When the admin finally got to where, in the TARDIS dim, the entrance was supposed to be, it preserved decoration blocks and anything I had placed in there (workbenches, etc.), but the entire thing itself was just _gone_.

We managed to fix my player object by wiping it, but the registration for my TARDIS was still intact, we managed to track down all registrations and wipe it out but it didn't fix the problem for long-- things went nuts again pretty fast.

Here's the log the admin gave me; I'm feralknights and he's ArmandVestibule.

http://pastebin.com/nywq011H

**Comment by DarkholmeTenk** [comment]
#383
