### ISSUE TITLE
[ENHANCE] TARDIS deletion (solved) & better logging

### ISSUE THREAD

**Issue by ghost** [DarkholmeTenk/TardisModIssues#428]
I'm not sure is it already implemented, but sometimes admins need a command to delete TARDIS dimensions. For example, player banned.
And one more thing. I can't completly disable debug output. Make it less hard and make it function normally. I mean, stop logging using "System.out.println()" because it is annoying.
Code for you 

```
import org.apache.logging.log4j.Level;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

public class LogHelper {
    private static Logger logger = LogManager.getLogger(MODID);

    public static void log(Level level, String format, Object... data){
        logger.log(level, String.format(format, data));
    }

    public static void log(Level level, Throwable ex, String format, Object... data){
        logger.log(level, String.format(format, data), ex);
    }

    public static void error(String format, Object... data){
        log(Level.ERROR, format, data);
    }

    public static void warn(String format, Object... data){
        log(Level.WARN, format, data);
    }

    public static void info(String format, Object... data){
        log(Level.INFO, format, data);
    }

    public static void trace(String format, Object... data){
        log(Level.TRACE, format, data);
    }
}
```

**Comment by FoxPotato** [comment]
There are already a command to delete dimensions, I forgot the exact command. but it's in another issue. It's something like /treg remove/delete or something. Just press tab a few times and try some of the commands :P

**Comment by runescapejon** [comment]
./treg remove total NAME

**Comment by ghost** [comment]
Still opened due to fking logging, my server log now bigger than 1 GB. Dark, you are crazy, make it better as i said for you...

**Comment by DarkholmeTenk** [comment]
What exactly is your log getting filled with?

**Comment by ghost** [comment]
Random information while using TARDIS, such as:
`[03:00:08] [Server thread/INFO] [STDOUT/TardisMod]: [tardis.common.core.TardisOutput:print:50]: [TM][TCH]TCHSS:Corridor Lift.Down Further.schema`

**Comment by DarkholmeTenk** [comment]
Well actually that particular bit of code uses TardisOutput so it should be possible to disable by lowering the default priority to 2 or below in TardisMod.cfg
Most other stuff should now be reduced or relegated to TardisOutput, where individual categories can be disabled too.

EDIT: Also, System.out is easy and is modified by forge to include the line where the code triggered making it very useful for debugging. Good, given that this mod is still in beta and the DS build is technically an alpha.
