### ISSUE TITLE
Tardis Model

### ISSUE THREAD

**Issue by doriun** [DarkholmeTenk/TardisModIssues#429]
is there any way to replace the tardis model? i like to make models and i've made one tardis, and i want to replace :SS

**Comment by wackypocket** [comment]
not sure if the owner wants this... but. download 7zip open the file and find the textures/models and replace them :p (but you didnt hear it from me)

**Comment by doriun** [comment]
already tried, but it crashes :/

**Comment by wackypocket** [comment]
open it in 7zip dont extract it or anything ive done it before and had no issues so im guessing thats what you did.

**Comment by wackypocket** [comment]
also make sure its the same name the model file i mean.

**Comment by doriun** [comment]
only the texture change works, not the model. on the models folder, doesn't have tardis.obj btw ://, and putting one there does nothing

**Comment by wackypocket** [comment]
have not done much with the model but even that as long as its the same file type and name it should work

**Comment by FoxPotato** [comment]
The TARDIS model might not have been updated to the .obj format yet. 
Thought it had been tho, when the chameleon circuit got implemented. But I can't find the model either.

**Comment by doriun** [comment]
i got it! I was using one dev build that has no tardis.obj in the files. I downloaded the forum version and it has the files of the tardises in there :D

thx ppl!!

**Comment by doriun** [comment]
It works, but dont have colision where doesnt have the tardis inv block

![geronimo](https://cloud.githubusercontent.com/assets/16976054/12700220/5e553f4c-c7c1-11e5-949d-c062264dc731.png)

**Comment by DarkholmeTenk** [comment]
Yup, not considering that a bug, lol.
