### ISSUE TITLE
[BUG]Room Calculation Errors

### ISSUE THREAD

**Issue by Durpady** [DarkholmeTenk/TardisModIssues#43]
Rooms spontaneously generated new doors (some Primary, some not) when the world was reloaded, and the dial is telling me I have 30 rooms (it's 17, in the "big chamber surrounded by T-junctions and corners" shape).  I had to smash them open in Creative.  This only happened once, so reproducing it may take some effort.

**Comment by DarkholmeTenk** [comment]
Very strange; right clicking the control panel will cause the schematic to recheck its doors; the only thing I can think might have happened is the schematics forgot which way they were facing due to a saving error; anything get printed to the console?

**Comment by Durpady** [comment]
Not that I saw; I don't usually check the console very often.  I'll look out for that in the future, if I see it again.

**Comment by DarkholmeTenk** [comment]
I really can't replicate this.
For now, I'm going to mark it as closed.
If you want to reset your room count, do
/trep <newRoomCount> 1000
which will reset your room count to newRoomCount and your energy to 1000.
Reopen if you can replicate it :)
