### ISSUE TITLE
[QUESTION] Forum

### ISSUE THREAD

**Issue by doriun** [DarkholmeTenk/TardisModIssues#430]
is there any forum or area of this mod, instead of this issue area, to the community show and provide their creations like textures and custom models? and also to people chat. :)

**Comment by ghost** [comment]
Nope, but if Dark want he can simply configure IPB or phpBB or any other CMS, or ask someone, not a big problem actualy i think... Oh well...

**Comment by FoxPotato** [comment]
There's the minecraftforum post, but that's it really. There will probably be a website at some point. And you're already able to upload custom schematics to http://foxpotato.com

**Comment by doriun** [comment]
nice!

**Comment by ghost** [comment]
@FoxPotato i see only white page :(

**Comment by FoxPotato** [comment]
Not just you, Dark either moved it or there's a problem :P

**Comment by Entoarox** [comment]
You have to go to http://foxpotato.com/ the www. doesnt work.

**Comment by FoxPotato** [comment]
Woops, my mistake. You're completely right. I'll edit my message right away :D

**Comment by DarkholmeTenk** [comment]
Not doing a custom forum, what we've got will have to suffice.
