### ISSUE TITLE
[BUG] Mobs getting stuck in tardis block

### ISSUE THREAD

**Issue by AlienXtream** [DarkholmeTenk/TardisModIssues#431]
sometimes on loading tardis interior, entities are taking suffocation damage. this is a problem as my village is rapidly having its population culled :P

**Comment by DarkholmeTenk** [comment]
Sounds like a vanilla issue.

**Comment by AlienXtream** [comment]
it kinda is but it feels like it happens more frequently in the tardis

**Comment by AlienXtream** [comment]
could it have anything to do with them being "transparent" blocks? i know from past experience that transparent blocks tend to be more susceptible to this bug

**Comment by DarkholmeTenk** [comment]
Pretty sure most blocks are not transparent? Otherwise they wouldn't be suffocating?

**Comment by AlienXtream** [comment]
Tell ya what. Im heading to bed now but tomorrow i will do a large scale test and see if it happens anymore frequently with your blocks versus vanilla ones. Just feels like they can path (and clip) inside blocks. Never had it happen to me outside the tardis before (i.e. in villages/with vanilla blocks)

**Comment by AlienXtream** [comment]
Also, stairs and slabs block light but dont suffocate so is it not plausible the inverse can be true?

**Comment by DarkholmeTenk** [comment]
Not in this case, isOpaqueCube returns false for stairs/slabs, returns true for blocks; it's what decides whether or not a block suffocates :P

**Comment by AlienXtream** [comment]
Well either way light isnt blocked cos beacon beams and solar panels dont have their line of sight blocked.

**Comment by weldinclusion** [comment]
I see your line of thinking here - I thought they were transparent too because in order to make a dark farm using temporal dirt I had to place a non-transparent block between every TARDIS block and the temp dirt or the light would come through.  A nice feature of the material but confusing for something like temp dirt.  Solar panels also function as you mention even with flat  blocks between them and sky.
