### ISSUE TITLE
Roundels

### ISSUE THREAD

**Issue by TARDIStraveler15** [DarkholmeTenk/TardisModIssues#432]
Previously i had RF going into my roundels but now nothing I have tried to get RF into them via taking off + landing along with constant flight, nothing can someone please tell me how I get RF into the roundels.

many thanks

**Comment by FoxPotato** [comment]
What is the exact problem thought, are cables not able to connect anymore, or does power just not flow anymore. Have you checked if the internal capacitors are full?

**Comment by TARDIStraveler15** [comment]
No there's just not any RF power getting into them and how do i check the internal capacitors?

**Comment by AlienXtream** [comment]
rightclick the roundel. i suspect they are full

**Comment by FoxPotato** [comment]
Does right clicking work too? I thought you needed the tablet thing.
I don't know, i tend to use waila to check it :P

**Comment by AlienXtream** [comment]
yeh, rightclick prints to chat

**Comment by TARDIStraveler15** [comment]
Nope capacitors or completely empty. I still have the problem of not getting any RF into the roundels - does anyone know how i do get the RF in to the roundels?

many thanks

**Comment by FoxPotato** [comment]
Maybe show us your set up, we don't really have that much info apart from "it's not working" :P

**Comment by TARDIStraveler15** [comment]
![image](https://cloud.githubusercontent.com/assets/16629631/12828994/95427d28-cb7f-11e5-9f45-d0cc969d5a6a.png)
this is my console room set up with Galacticraft electric arc furnaces, i have tried to fly and no RF going into the furnaces nor the internal capacitors in the roundels.

please help.
many thanks

**Comment by FoxPotato** [comment]
I'm not sure but, does galacticraft use RF? i thought it was universal electricity. or something else. those cables don't look RF-like imo.

**Comment by TARDIStraveler15** [comment]
Yes it does use RF I have a massive room inside the TARDIS that was full of furnaces powered by the TARDISes roundels but now they just don't get any power any more.

**Comment by FoxPotato** [comment]
Have you tried it in another world. have you tried using thermal expansion tubes or whatever theyre called to transfer power. 
have you checked if the generators are even generating power in the first place?

**Comment by AlienXtream** [comment]
i think GC power pipes can only accept GC. use TE pipes

**Comment by DarkholmeTenk** [comment]
Post modlist pls.

**Comment by TARDIStraveler15** [comment]
Ok
here are the mods:
carpenters block.
aircraft mod
all-U-want mod
Archimedes ships
Balkons weapons
biblio craft
build faster
CoFH core
damage indicators
darkcore
deco craft
draconic evolution
galacticraft core
galacticraft planets
lantea craft
malisiscore
malisisdoors
MrCrayfishs furniture mod
open modular turrets
secret rooms
tardismod-1.7.10-0994-124-DS
TF2 sentry
TF2Teleporter

all of these especially galacticraft have all previously worked fine and the roundels used to get RF, but now i was confused to why they no longer do.

hope this helps and hopefully you will know how to fix the problem

many thanks.

**Comment by FoxPotato** [comment]
Ok but did you use those cables previously too? Like I said, check if the cables are even transporting the power. And maybe try some other way of power transport and see if that does work.

**Comment by TARDIStraveler15** [comment]
there the same type of cables yes most other ways of power transportation work.

how are the roundels meant to get RF anyway?

**Comment by DarkholmeTenk** [comment]
you have to pipe energy in from a generator or something

**Comment by TARDIStraveler15** [comment]
How do i do that?

**Comment by FoxPotato** [comment]
by generating power, and pumping it into the roundels

**Comment by DarkholmeTenk** [comment]
Connect another mod's generator to cables and connect those cables to a roundel. The roundels work like tesseracts, they're just for moving power around, they don't generate their own power.

**Comment by TARDIStraveler15** [comment]
ow ok thanks, that would explain why they did not generate them.

thanks for the help.

**Comment by DarkholmeTenk** [comment]
No problem
