### ISSUE TITLE
Uncontrolled Flight Crash

### ISSUE THREAD

**Issue by viper92225** [DarkholmeTenk/TardisModIssues#433]
Upon taking off in uncontrolled flight mode, the moment that the takeoff sequence finishes, players inside the tardis hard crash to desktop. Possibly relevant information is as follows: Tardis lvl 2, no spent upgrade points, single energy recharge upgrade applied, two pilots in control room, uncontrolled flight mode set, land on ground set, ignore landing pads set, dimension lever set to "D:Overworld[0]" . The crash is absolutely repeatable on our end with the tardis in this configuration. It did not crash when we had a single player in the tardis instead of two though.

[crash-2016-02-04_21.59.50-client.txt](https://github.com/DarkholmeTenk/TardisModIssues/files/118621/crash-2016-02-04_21.59.50-client.txt)
[crash-2016-02-04_21.50.59-client.txt](https://github.com/DarkholmeTenk/TardisModIssues/files/118622/crash-2016-02-04_21.50.59-client.txt)
[crash-2016-02-04_21.44.45-client.txt](https://github.com/DarkholmeTenk/TardisModIssues/files/118623/crash-2016-02-04_21.44.45-client.txt)

**Comment by AlienXtream** [comment]
use older version of darkcore.

**Comment by DarkholmeTenk** [comment]
Not a darkcore issue. #393
