### ISSUE TITLE
[BUG]fake players can "own" a tardis

### ISSUE THREAD

**Issue by AlienXtream** [DarkholmeTenk/TardisModIssues#435]
so, purely out of curiosity i decided to give an autonomous activator from thermal expansion a blank tardis key and...... it worked. my autonomous activators (i.e CoFH's fake player) now have a tardis. im am going to assume that other fake players will also cause this bug to occur.
EDIT: can confirm it works other fake players

**Comment by FoxPotato** [comment]
Is it really a bug tho? Everything did it's job :P

**Comment by AlienXtream** [comment]
lol, well it shouldn't REALLY happen. and yes it IS technically a bug unless dark says otherwise (i.e intended "feature"). i do get what you are saying though... i guess its less of a "bug" per say and more of an oversight.

**Comment by FoxPotato** [comment]
so just because they're "fake" players they can't have a TARDIS. I say bullshit, equality for all!
:P

**Comment by AlienXtream** [comment]
but... think of the childr....er i mean lag :P

**Comment by FoxPotato** [comment]
I do wonder, what happens when you give the thing multiple keys, or give another block a key. and what name does it show on the engine?

**Comment by AlienXtream** [comment]
Way ahead of you. Key/tardis shows fake players "name" (i.e for cofh its owned by [CoFH], thaumic tinkerer dynisum tablet [thaumcraft_tablet). All autonomous activators are counted as one player globaly (like wise for other mods) so multiple keys dose the same as it would a true player

**Comment by DarkholmeTenk** [comment]
Should be dealt with now assuming they extend FakePlayer :P
