### ISSUE TITLE
Crash every time Tardis lifts off

### ISSUE THREAD

**Issue by bokeustermans** [DarkholmeTenk/TardisModIssues#438]
Every time I do the lift off sequence it will crash my client as soon as the first button lights up, it was fine the first 2 or 3 times then it just kept happening.
[crash-2016-02-10_23.46.55-client.txt](https://github.com/DarkholmeTenk/TardisModIssues/files/125683/crash-2016-02-10_23.46.55-client.txt)
I love the mod, but I'd like to be able to use the flight part of it as I find it very intricate and useful.

**Comment by AlienXtream** [comment]
#393

**Comment by DarkholmeTenk** [comment]
Alternatively, using the most recent TM and DC from the jenkins should now fix it.
