### ISSUE TITLE
[BUG]RF Problems

### ISSUE THREAD

**Issue by Durpady** [DarkholmeTenk/TardisModIssues#44]
Something has gone wrong with the TARDIS's RF storage.  It's visibly taking in power - directly attached Engines will pump away, and Kinesis Pipes are visibly full of RF energy - but nothing is receiving power.  Pumping it in through a Landing Pad will change the value displayed by WAILA, but even then, nothing will receive RF.  I've been exiting and re-loading the world a lot, so that could have something to do with it.

**Comment by DarkholmeTenk** [comment]
Could you try using EnderIO to transfer the power? It may be something to do with the way I'm handling power?

**Comment by spannerman79** [comment]
Logs?
Screenshots?
Video?

Oh also just remembered - BuildCraft is Kinetic energy (MJ) - not Redstone Flux - RF (CoFH, etc)

**Comment by DarkholmeTenk** [comment]
thought that the latest BC was RF?

**Comment by spannerman79** [comment]
I've always found that Kinetic Energy wasn't RF.  
Example; Connect a Creative Engine (from BuildCraft) via EnderIO to say a Redstone Energy Cell.  It won't charge.
CoFH still sees BuildCraft Kenitic energy as MJ - even though being displayed as RF as per within config files

Switch it around the other way;
You cannot power BuildCraft machines (example; refinery) via RF energy from a Creative Energy Cell - from either EnderIO or Thermal Foundation.  It specifically needs Kinetic Energy which is only supplied by BuildCrafts engines.

.....pain in the @ss if you ask me but it may change in version 7 of BuildCraft

**Comment by Durpady** [comment]
The trouble is that it WAS working.  A Refinery set up in one part of the TARDIS would be powered by a Creative Engine in another part.  It might be another saving error, but now it won't work.

I'll check again with the latest build.

**Comment by laz2727** [comment]
There's no such thing as MJ anymore, guys. All these things are either
glitches or you not understanding the purpose of wooden kinesis pipes.

Yes, i use every power transfer method, and every single one (bc, tell,
exu) works with roundels.

**Comment by DarkholmeTenk** [comment]
Could you upload the save to dropbox or something so I can see if I can replicate it on my end? After that could you dismantle and reset the roundel on the receiving side; see if that fixes it?

**Comment by Durpady** [comment]
I've tried dismantling the Roundels several times, that failed to fix it.
Dropbox:
https://www.dropbox.com/sh/e8pjskusza179za/AABhIYOVsJvrTZdyRIXU4_71a?dl=0

**Comment by DarkholmeTenk** [comment]
I can't replicate it. Gonna mark it as closed, but if it still happens with the latest build, reopen it.
