### ISSUE TITLE
[BUG] Tanks

### ISSUE THREAD

**Issue by FoxPotato** [DarkholmeTenk/TardisModIssues#442]
This is mostly so people (looking at you Alien :P) can check if it's not because i fucked something up, and also so I don't forget about it.
When right clicking a landing pad with a fluid or energy component on it, when there's no TARDIS on top it crashes because the component can't access the TARDIS data store. Easy to fix with an if statement.
If someone could verify this bug, that would be lovely :D

**Comment by AlienXtream** [comment]
kk. will kill MC again :P. whats this? the.... oh... billionth time? :P

**Comment by AlienXtream** [comment]
i tried it with an energy component and no crash. wasnt pumping power in but rightclicking just prints 0/0 power

**Comment by FoxPotato** [comment]
have you tried using the tanks tho. On a landing pad, outside of the TARDIS dimension. With no TARDIS on top of it.

**Comment by AlienXtream** [comment]
Not with fluid tanks no. Im heading to bed now but tomorrow i will break landing pads, even if i have to resort to help from a certain INDUSTRIAL oriented CRAFTing mod ;) (its ic2 nukes...thats what i am hinting at ;D)

**Comment by weldinclusion** [comment]
Confirmed on 0.994-129 DS.  Landing pad, no Tardis on top, fluid interface.  Right click gives Internal Server Error.

**Comment by AlienXtream** [comment]
thanks weldin :)

**Comment by FoxPotato** [comment]
Ok, fixed as soon as Dark merges the branches :P
