### ISSUE TITLE
[Bug?] Can't place sapplings or seeds on temporal dirt.

### ISSUE THREAD

**Issue by MaxBernstein** [DarkholmeTenk/TardisModIssues#445]
Hi dark! It's me again. Well... I love your tardis mod and I always use it in my modpacks and the temporal dirt is an OP stuff,not cheaty because is not cheap. Anyway, in my other modpack (It's like a mix of Feed the Beast with some mods and tardis mod) I have the tardis mod and I use the temporal dirt to farm rubber tree's (MineFactoryRealoaded) and yes I can plant everything (I didn't tested EVERY SINGLE SEED but the most part yes.) And recently I created a new modpack with magic and some tech, not loads of mods but with the tardis mod of course and I did a bunch of temporal dirt waiting to work and suprise, it didn't work. I just can't place anything on the temporal dirt, I tried next to a water source, beside it, I tried to use a hoe on it, I tried all vanilla seeds and sapplings and it just don't place.
http://puu.sh/nbhXq/ad39c3ad74.png
There's the rubber tree that I use on the other modpack.
Tardis mod version: tardismod-1.7.10-0.994-124-DS
Darkcore: darkcore-0.3-86
I could force-crash my game to post here a report file if you want.
Well, I tried to look at the configs file to "active the dirt" but nothing.
It's a bug? Am I being stupid like always? Or some mod incompatibility?
Well, thanks anyway ^^ Your mod is the best!

**Comment by FoxPotato** [comment]
Temporal dirt only works in TARDIS dimensions :P 
Try it in a console room or something, and if it works again close the issue. And if it doesn't work, well we'll see.

**Comment by MaxBernstein** [comment]
@FoxPotato Thank you! Very much! As I said, It's not a bug, It's just me being stupid.
Thanks FoxPotato!
