### ISSUE TITLE
[Improvement?] Artron Battery and Temporal Laboratory

### ISSUE THREAD

**Issue by MaxBernstein** [DarkholmeTenk/TardisModIssues#448]
Heyo ^^ 
I'm going to automate the Chronosteel and Dalekium production conecting more batteries on a Temporal Lab but it doesn't seem to work.
Let's make an exemple (Of course, I guess you'll test on your computers too, but let's imagine)
I put Chronosteel to make on a lab and put two batteries in Uncordinate Flight mode on both. But the Lab uses artron energy from only one and when this battery goes to 0 it's keep using and the other battery (full) won't waste any energy with the lab.
This happen in the Artron Battery, the Advanced Artron Battery and in the Temporal Artron Battery ( I was "playing" with the lab when I put a Advanced Artron Battery there and my reason was like "OMG IS DOING SOMETHING LOL" )
Ahm, I guess is this, thanks and sorry for the trouble ^^

**Comment by FoxPotato** [comment]
I don't exactly get what you mean, but labs already use batteries iirc

**Comment by DarkholmeTenk** [comment]
I believe the issue is labs only use the first battery they find.
