### ISSUE TITLE
[BUG] restoration field not working

### ISSUE THREAD

**Issue by AlienXtream** [DarkholmeTenk/TardisModIssues#449]
either im totally missing something or the restoration field isnt actually working. that or its just VERY slow. im currently holding an iron pick and nothing has changed in 2-3 mins.

**Comment by DarkholmeTenk** [comment]
@FoxPotato

**Comment by FoxPotato** [comment]
I will take a look right now.
EDIT: Actually, how damaged is the pickaxe? The restoration field only repairs up to 75%. This is configurable in the configs.

**Comment by AlienXtream** [comment]
ah. that would be it. 4 durability used or so. im one of those "pseudo OCD" people whom like every thing to be 100%. also, please reframe from doing edits like that as it dosnt give me a notification of new messages then.

**Comment by FoxPotato** [comment]
I like to save space, but i'll try and make new messages next time :P 
And I'll assume this "issue" is now "fixed".

**Comment by AlienXtream** [comment]
I have yet to see it actually do its thing and until then i would just assume it dose. What method are you using to find repairable tools? White list? Damage bar? Or are you referencing the anvil's repair list (or whatever it is in the code). I did go back and test with flint and steel too no avail. I was a little tired then and am in bed now but i can try again tomorrow. Can you please provide some insight as to what you are doing so i know how its SUPPOSED TO? To clarify the method i came up with (and totally more work than needed) was to have it the higher the durability the less likely a repair would happen and vice verca. Dang it im rambling again... Ending this now before i write a lecture... Too late

**Comment by FoxPotato** [comment]
It's just a forloop checking through your inventory, checking if item is damageable. And then if the damage is more than 25%, repair :P 
There might be some items which use energy which might repair, but I already added a fix for rf, eu and ae2 stuff.
