### ISSUE TITLE
Tardis Incompatibility

### ISSUE THREAD

**Issue by HalestormXV** [DarkholmeTenk/TardisModIssues#457]
It appears the TARDIS mod is incompatible with Cauldron, kCauldron, Thermos, unless I am however wrong. However in searching, I haven't been able to find anything with respect to TARDIS getting along with any of those variants as mentioned above. Normally a plugin like Multiverse will bridge the dimension issue with Mods and these prior mentioned server compilations.

However, it appears Tardis is incompatible. What happens if you use the key is the booth spawns and you enter it and then are dropped into an infinite void. If you install a bridge plugin like Multiverse the key ceases to work all together. 

My theory. The Tardis dimension provider is outstanding, and what it looks like you have it set to do is create a folder within the World folder called Tardis and then you store each dimension in there. That is what I think the problem might be for Cauldron, kCauldron, or Thermos variants. They store their Dimension folders within the actual World folder. So for example an Abbyssal Craft dimension once entered will create a folder call DIM-57 (or whatever you have it set to) right there is the World folder so that if you are using a bridge like Multiverse it detects it, or the mod itself just has built in compatibility by checking if you are running a kCaulron variant of Forge.

Finally I ask, is there a way to make Tardis compatible with those variants above, or maybe even have a config option to indicate you are using a kCauldron varient so that the TARDIS dimensions are actually stored within the World folder and not the Tardis folder within the world folder.

This is all theory but I would be happy to test it for you. However I do hope something can be done because this is a great mod and it is unfortunate that it may not be compatible with some widely used alternative Server software like Cauldron, kCauldron, or Thermos.

**Comment by DarkholmeTenk** [comment]
I know a few people that have had everything work on cauldron servers and anything which teleports shouldn't really be accessing the folders anyways, it should be letting forge handle that.

Can you attach some server logs around the time when stuff is being created and verify you're on the latest working darkcore/etc.

**Comment by HalestormXV** [comment]
Quite interesting. I had to actually delete my test world. Here is the breakdown. I tested the mod out on my testworld and the Tardis was created with the key, however it dropped you into an endless void. So I had to use my OP commands to erase my player data and log back in. 

Following that I shutdown the server to erase the Tardis world folder so that I can reset my Tardis, upon restarting the server and giving my-self a new key I would right click the key and it would no longer "Feel Warm" instead the key would just switch its owner to me and nothing would happen. So that means the Tardis data is stored somewhere else, because it was still discovering that I had a Tardis, somewhere. Would you happen to have a debug command or something of that nature to erase a player's Tardis so that doesnt occur? (That is aside from the main point)

Now the main point on further testing I removed the Multiverse bridge and reinstalled Tardis completely and it STILL somehow detected that I was already a Tardis owner and the new key (despite my player data being erased, perhaps I missed it in the documentation which is quite possible) would not create a new Tardis for me.

So then I erased the entire world. (As this is my developer environment) and finally managed to get myself a new Tardis. And upon entering it, was once again dropped into an endless void. 

So I repeat the whole process and then it clicked. For some reason the server WAS NOT downloading the schematic file? I had to go onto single player create a Tardis, have it generate a schematic file for me and bring that into my Dedicated server, and then restarted the whole process again and now the Taris is created and I entered it without issue.

So I guess the question now becomes, why did the server not download the schematic file on first creation? I checked the file ownership (as I run multiple servers, each daemon has a uniqueID) to make sure that all Mods and Configs were owned by this particular Daemon so that there would be no permission conflict, and it still just did not download the schematic files. 

Any idea as to why that would happen? I am running the latest versions of DarkCore and Tardis currently available on curse. As for server software I am running Thermos-1.7.10-1614 Build 34

Another issue that then presents itself, is if it didn't download the main schematic, what will happen if new rooms are attempted to be added such as the library? Since the schematic folder now only contains the main control room schematic.

**Comment by FoxPotato** [comment]
That is weird, because it doesn't download the schematics. They're located inside the mod file. in /assets/tardismod/schema

**Comment by DarkholmeTenk** [comment]
As a note, tardis ownership is kept in a file in world/data/ and you can fully remove a player's tardis using /treg remove total <playername>. Is the config/darkmods/tardismod/schema folder writeable, because if not, I imagine that's the problem?

**Comment by HalestormXV** [comment]
Ahhh, yes that is quite interesting. I see they are within the mod file and not downloaded which is what I thought originally (that they were downloaded). 

Thank you Darkholme for that command. I appreciate it. With respect to if the file is writable yes it is. Although it uses permissions 755 instead of 775 or 777 for that matter. I wonder if the Multicraft daemons are only considered a group and not the owner of the file in which case the 755 permissions would deny them access. (but wouldn't that generate a permission error in the log?) Although under Filezilla they are listed as both owner and group of the files, however I wonder if the server sees it differently. 

I will have to do some testing with the File permissions. But as it stands now I can simply extract the schematics and manually put them in which would be the "quick-fix."

I am not sure if you want to close this issue or not as it really isn't an incompatibility or so it seems as so much as it could be a permission error.

**Comment by DarkholmeTenk** [comment]
Very odd you didn't see an io exception printed to the console when it failed to load it though

**Comment by ProsperCraft** [comment]
We have been using KCauldron with this mod and many others(over 50 dims) in my DrTARIDS modpack with no problems at all.
