### ISSUE TITLE
TARDIS + Galacticraft HQM modpack idea

### ISSUE THREAD

**Issue by TheTenthDoctor95** [DarkholmeTenk/TardisModIssues#459]
So, the other day, I was thinking how awesome it would be to make a modpack that combines Galacticraft and the TARDIS mod, but also includes Hardcore Questing Mode. So, for example, instead of building rockets, maybe there could be upgrades that need to be crafted in order to get to the next planet. And each recipe would have an item that would only be found in dungeons on planets. So, for example, the item needed to make the Mars upgrade would be in a dungeon on the Moon. I was thinking that it could be achievable if its possible to code something that locks the TARDIS from traveling to specific dimensions, the planets, until it has the upgrade needed. Then the dimension would be unlocked and you can fly the TARDIS to the new planet. Also it would be good if the upgrades include the dimension unlocks for the planets before it, so the Mars Upgrade unlocks Mars, and the Moon. And if that is done, it would probably be possible to have an upgrade slot specifically for the dimension unlock upgrades. So, very simple way of putting it, "If (item) is in Upgrade Slot, unlock Dimensions (dimension numbers); Else, Lock Dimensions (all planet dimensions aside from the ones unlocked by previous upgrades. I would take care of choosing the other mods but i would happily take suggestions, and id be happy to work together on making the Quest Book. If anyone would like to help out with this, let me know please! I will try to remember to check this regularly, but your best option to reach me would be at thetenthdoctor1995@gmail.com

**Comment by AlienXtream** [comment]
1. wrong place for this 
2. already exists http://forum.feed-the-beast.com/threads/listed-1-7-10-hqm-survival-galactic-science-something-fresh.86203/

**Comment by TheTenthDoctor95** [comment]
This is where both Darkholme and Foxpotato told me to post this

**Comment by AlienXtream** [comment]
then i retract my prior statement :P

**Comment by SomeBadGamer** [comment]
I have done something  similar  because I wanted the same thing but I don't think that is a way to make a  item unlock a dim but in the configuration you can make a level requirement to reach a dim like to go to the end I think it is level 3 so that may help you

**Comment by TheTenthDoctor95** [comment]
I was thinking, if it could be figured out how to lock a dimension, to keep the TARDIS from traveling to it, until a certain item is inserted into the "Dimension Upgrade Slot" and each item would unlock specific dimensions

**Comment by SomeBadGamer** [comment]
I know but sadly I don't think that is possible at the moment the only way it could be is if dark ads it but if/when it's added the level part is the best you can do

**Comment by FoxPotato** [comment]
I am trying to figure out if it's possible to add items to the mod when a new line gets added to a config. That way people could add upgrades themself for any dimension they want.

But gotta see if it's possible first :P

**Comment by SomeBadGamer** [comment]
From what I can tell no but tell us if you find any thing

**Comment by FoxPotato** [comment]
And if not, It'll be just a set amount of upgrades which you can edit.

**Comment by TheTenthDoctor95** [comment]
Darkholme just told me that it would be possible to do what i suggested

**Comment by FoxPotato** [comment]
It will be possible, but I have to find a solution which makes it useful for everyone. And not just for this pack :P

**Comment by TheTenthDoctor95** [comment]
Of course, i understand
