### ISSUE TITLE
[ENHANCE]Fluid Suction

### ISSUE THREAD

**Issue by Durpady** [DarkholmeTenk/TardisModIssues#46]
Buildcraft Pumps will receive power when placed adjacent to an RF Landing Pad.  However, they will not transfer their fluid when said Pad is also equipped with a Fluidduct circuit.

**Comment by DarkholmeTenk** [comment]
Forge version? Forge changed the visibility of the fluidID field in one of the versions.

**Comment by Durpady** [comment]
Forge is 10.13.3.1370.

**Comment by DarkholmeTenk** [comment]
Probably the reason then; I'll update it shortly

**Comment by spannerman79** [comment]
The change happened around 1355-ish

**Comment by DarkholmeTenk** [comment]
I built the mod on 10.13.2.1291

**Comment by spannerman79** [comment]
FluidRegistry changed at 1355 ( http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.7.10-10.13.3.1355-1.7.10/forge-1.7.10-10.13.3.1355-1.7.10-changelog.txt )
CoFH Core also updated (not sure which one though) to be 1355+
Might have been 3RC5 or 3RC7

**Comment by DarkholmeTenk** [comment]
Should be fixed in the latest build on the jenkins; give it a shot?

**Comment by DarkholmeTenk** [comment]
Going to assume fixed?
Reopen if still a problem with the latest jenkins version

**Comment by FoxPotato** [comment]
I tried the pump thing.
I tried placing it directly under, I tried connecting it with fluiducts.
Lava out of the nether worked for a bit. but then it stopped working.
and now the internal tanks seem to have stopped working in general

**Comment by DarkholmeTenk** [comment]
Fine, I'll look into it some more :)

**Comment by FoxPotato** [comment]
Oh, it might be because I'm on build 55? I'll check out build 59 right now.

**Comment by DarkholmeTenk** [comment]
![2015-05-09_12 45 11](https://cloud.githubusercontent.com/assets/2133466/7550030/56b22d12-f649-11e4-97f5-ce1ad7da43c3.png)
Definitely fixed now
