### ISSUE TITLE
[Bug] Kontron crystals not showing uo in loot chests anymore

### ISSUE THREAD

**Issue by 1skandar** [DarkholmeTenk/TardisModIssues#460]
Sometime among the last few versions kontron crystals stopped spawning in dungeon loot. Not sure when, but despite me not changing configs they are definitely not showing up.

**Comment by FoxPotato** [comment]
Vanilla dungeons?

**Comment by 1skandar** [comment]
None of the vanilla loot tables. I've suspected it for a bit, I've been playing a new world that includes the latest Tardis Mod from the jenkins and noticed I wasn't finding any in village blacksmith chests, dungeon chests, or mod chests that pulled from vanilla dungeon loot.

I then double checked with Not Enough Resources, which lists dungeon loot, and sure enough Kontron Crystals aren't listed on any of the loot tables.

**Comment by FoxPotato** [comment]
What mods are you using? Which of those mods also add dungeon loot, or maybe even like change how it works

**Comment by 1skandar** [comment]
For testing purposes, this bug exists with a minimal mod set: 
TARDIS  293
Darkcore 115
NEI
Not Enough Resources (necessary to check dungeon and other loot table

**Comment by FoxPotato** [comment]
I know this is nitpicky but still, could you perhaps update to TARDIS 296 and darkcore 117?
If by any random event it got fixed there that would save alot of time :P

**Comment by 1skandar** [comment]
After further testing:
Kontron Crystal loot was working in TARDIS 253/darkcore 75 but it was the big update on the Jenkins to 280/111 that appears to have broken it.

**Comment by 1skandar** [comment]
And, yeah, the latest Jenkins build is still broken.

**Comment by FoxPotato** [comment]
So something in the damage system it seems. I will take a look at the code where it gets added to the loot thing and see if something is missing.

**Comment by FoxPotato** [comment]
I think I might've found the problem, testing it out right now.

**Comment by FoxPotato** [comment]
Should be fixed now

**Comment by 1skandar** [comment]
Confirmed fixed. Thank you.

**Comment by KolonelWolf** [comment]
I didn't get what you guys meant by "fixed". I don't understand how I would fix this personally or do I have to like install/update something. Please help

Thanks in advance
