### ISSUE TITLE
[BUG] specific configs reseting

### ISSUE THREAD

**Issue by AlienXtream** [DarkholmeTenk/TardisModIssues#461]
some config elements are restoring to their default values whilst leaving others untouched. the currently known ones are
 Nanogene- Range
restoration field -cost
restoration Field - Range
restoration field - Timer

they are all the ones i have changed that reset themselves

**Comment by FoxPotato** [comment]
Why do you keep breaking my things man :(

**Comment by FoxPotato** [comment]
I can't actually seem to recreate this.
WHen does it happen, how much does it happen.

**Comment by AlienXtream** [comment]
"Why do you keep breaking my things man :(" cos thats my job :P it seams to have stopped... i guess whatever WAS causing it was fixed when i reinslalled windows :/. will reopen if/when more info is avalable (and it happens again)
