### ISSUE TITLE
[BUG] restoration field repair problem

### ISSUE THREAD

**Issue by AlienXtream** [DarkholmeTenk/TardisModIssues#462]
the restoration field wont fix items if unbreakable tinkers tools are in the inventory.
EDIT: ok, its the tinkers arrows aswell (and presumably other tinkers "ammo")

**Comment by FoxPotato** [comment]
I get the feeling because it thinks they are damaged and keeps trying to heal them. Do the particles appear?

**Comment by AlienXtream** [comment]
No. The affect also appears to occur with mana tablets from botania. The particles do appear there. Anyway, not a massive problem to fix i assume. Just blacklist tinkers tools and create an exception for mana storage items :)

**Comment by AlienXtream** [comment]
you know... now i think about it this may be the cause for #449 :P. go not sleeping \o/

**Comment by cloakable** [comment]
Ender IO tools also cause this; if I remove all EIO tools and armor from my inventory the field will start to work, otherwise no.

**Comment by DarkholmeTenk** [comment]
@FoxPotato I assume there's a return where there should be a continue in a loop.

**Comment by DarkholmeTenk** [comment]
https://github.com/DarkholmeTenk/TardisMod/blob/master/src/main/java/tardis/common/tileents/components/ComponentRestorationField.java#L106

Yes, I know it's a 1 word change and I could do it in github in under 20s, but it's @FoxPotato's bug, he can fix it.

**Comment by FoxPotato** [comment]
oh damn, you're right. I'll fix it asap

**Comment by AlienXtream** [comment]
Lol. I cant criticize cos i couldn't do better to save my life :P

**Comment by cloakable** [comment]
This is an interesting version of asap especially for a one word change. xD
