### ISSUE TITLE
[Enhance] Power System

### ISSUE THREAD

**Issue by ghost** [DarkholmeTenk/TardisModIssues#464]
I do know that the tardis has its own power system that it uses to travel. What I was thinking is the ability to allow players to be able to access the power system from the roundels if they wanted to. For example if the natural regeneration for the energy was disabled the player can have the option to make  their own power room or system to supply the tardis or be able to pull energy from the tardis to power rf devices and such to add a challenge to playing with the mod.

**Comment by SomeBadGamer** [comment]
I I think I like that and it's not to over powered because the really only thing that can get infinite  energy Is solar and most mods have that as a semi difficult  thing to get but maby just so you can start out it has some initial energy

**Comment by FoxPotato** [comment]
artron and rf has been requested a few times already, idk what dark's opinion on the matter is tho.
I do know that I don't really like the being able to power the TARDIS, because iirc it's being powered by a dying star. And not everyone plays with energy mods.

**Comment by SomeBadGamer** [comment]
But if it was a configuration it would be a way to make sure your not stranded because you can't make power

**Comment by ghost** [comment]
Except that the dying star was not added when my tardis was on the tardis assembly-line and if its a config option it allows people to choose whether or not if they want to add it to their tardis to use within game if they want that extra challenge.

**Comment by SomeBadGamer** [comment]
Assembly  line just to say tardi(or whatever  the plural for tardis is) are grown not manufactured just FYI

**Comment by ghost** [comment]
I forgot about that then lets go with tardis farm

**Comment by FoxPotato** [comment]
Ok but like, you couldnt possible generate the same amount of power as a star thats about to collapse. or whatever stage in its life it was at.

**Comment by ghost** [comment]
What about a mod that adds power from collapsing stars?

**Comment by FoxPotato** [comment]
Are you gonna make it? :P

**Comment by ghost** [comment]
Maybe one  day if I can learn programming. Then what about the nether star reactor from various mods. It seems  star-ish.

**Comment by FoxPotato** [comment]
exactly, star-ish. They're not real stars, and they probably won't be able to generate the same amount of power.
There's probably a reason why timelords use a dying star as a fuel source and not something else.

**Comment by ghost** [comment]
What about the reactor from Draconic?

**Comment by SomeBadGamer** [comment]
May make in if required  huge amounts  of energy  like extra utilitus nether star generator huge so it  can make the tardis more end game also I have been wanting to get in to making a energy  mod some time so if/when I make it I can give you the link it is going to have a mass energy generation method but it is very late game

**Comment by ghost** [comment]
Now that I think about it could have it where the energy ratio from the input to what is needed can be really large causing the tardis to need a lot more energy than being powered by a furnace to allowing more end gear like items like large reactor setups or powerful/expensive reactors

**Comment by ghost** [comment]
Now that I think about it the one episode of doctor who when he salvaged a tardis together on that planet outside the universe. I didn't see a sun attached to the console in that episode.

**Comment by SomeBadGamer** [comment]
The whole area was filled with artron energy  it was flooded with power for a tardis to use

**Comment by FoxPotato** [comment]
that TARDIS wasn't bigger on the inside, it was really tiny. and didn't have to go that far I think.

**Comment by SomeBadGamer** [comment]
That to

**Comment by FoxPotato** [comment]
And they had Idris, or whatever her name was. Without her it didn't even work.

**Comment by ghost** [comment]
she was the conscientiousness of the tardis not the power source

**Comment by SomeBadGamer** [comment]
It was a living tardiness making a dead one come alive in a Sense

**Comment by SomeBadGamer** [comment]
In that area considering  that thare are probably hundreds of tardises worth of power that was more than sufficient  to get it flying

**Comment by ghost** [comment]
But if the tardis had a ratio that was large enough for the intake needed for the output would it then be logical to add this feature?

**Comment by FoxPotato** [comment]
To me, no. I don't believe that you could power a TARDIS using rf, no matter the source.

**Comment by SomeBadGamer** [comment]
That is true but the scale you can make this on and it should probably  be configureable of how much energy it can take can make a large influence  on what source of power you use

**Comment by ghost** [comment]
Although we are dealing with minecraft meaning that the source can be anything if someone wants to create it and meaning that the rules of the tardis universe may no longer apply the same way as in the tv show.

**Comment by FoxPotato** [comment]
I like to keep things as realistic as possible (realistic lore wise that is).
But seriously, if you could power a TARDIS with just a reactor, why go through the effort of capturing a star.

**Comment by ghost** [comment]
Some reactors in minecraft are just as powerful as a star or even stronger depending on the mod and the only eye of harmony I have seen is made out of normal blocks and can not do much power wise except glow the area a bit.

**Comment by SomeBadGamer** [comment]
The thing is that it doesn't need to be 100%lore related  I don't thing the doctors ever used a gun that changes the material  of the  tardis

**Comment by FoxPotato** [comment]
I know you can't ever be 100% true to lore (and technically we don't know how he decorates his TARDIS ;p)
but yeah, to me it wouldn't make sense if the TARDIS could be powered by rf.

**Comment by SomeBadGamer** [comment]
That's whyour it can be a configuration so for people that do like it or dont like it theyes can decide for them selves

**Comment by ghost** [comment]
I do know of some mods that add their own power unit do to rf needed to be ridiculously high for the devices to work why not do the same and add a custom energy that fits for the tardis and can be coverted to fit depending on the person. For example me doing 1 rf=1 tardis unit or something like rf x 99999999...=1 tardis unit depending on who is playing. If the sun is needed why not have a block that is the mechanics or power for the sun such as a sun block that can be placed inside the schema for the eye of harmony to make it more realistic?

**Comment by FoxPotato** [comment]
Eye of harmony is yet to be added as a room. 
Also (this is nitpicking i know, but whatever), it doesn't need THE sun. It needs a star, our sun doesn't have enough mass to become a blackhole :P

**Comment by ghost** [comment]
The tardis needs enough power equal to a star collapsing but does not say it needs just a collapsing star but something of equal power. Mods from minecraft having different lore giving some items or blocks more power or equal to a star. This still fits the tardis lore as it is being powered by a device with enough power as a star meaning it could power the tardis while still fitting the lore as close as possible in minecraft.

**Comment by DarkholmeTenk** [comment]
One thing you learn in modded minecraft is that resources are not a barrier, there are always infinite resources always. Ergo, to enforce balance, resources cannot be used.
No matter what the ratio, it will always be possible to just build 1000 reactors and pipe stupid amounts of power in. Draconic evolution, the "I need to have the biggest numbers" mod, is a good example of this. When you need to store your power as a long, you should maybe just consider dividing by a few thousand or million.

**Comment by ghost** [comment]
Would it be possible then to add tardis power access if optional depending on the person if they want to use this or just forget about adding this?

**Comment by FoxPotato** [comment]
What i got from his message is that no matter how you do it, as long as the source if fueled by items/blocks/fluids it could be way too op.

**Comment by ghost** [comment]
closing then. :(

**Comment by ghost** [comment]
Last thing before I give up is then why not have the limiters that is used on the tardis to limit the energy storage and such and if the player did not want to have op items why would he get them in the first place?

**Comment by SomeBadGamer** [comment]
I do wish this could be a feature but I guess ithe won't

**Comment by ghost** [comment]
It may be possible that they may change their minds in the distant distant future. But until then it will be nope.

**Comment by FoxPotato** [comment]
If you can come up with a way of generating power that would still require effort but doesn't use any resources to fuel, I'm all for it tbh.
And ofc try to make it a little lore friendly ;p

**Comment by AlienXtream** [comment]
rift energy! ;P. i know it totally NOT going to happen but having a rift in each dimension that has to be located and used to "refuel" the tardis would be the best lore friendly answer to this i can find. i kinda like the idea that the tardis is (in a sense) powered by time. i mean think about it, artron energy isnt TRULY free, if that were the case then we would have literally infinite power. no, instead we must invest TIME itself. not a gather able resource but actual time. not that the recharge rate is really any obstacle anyway but its still a thing ;P

**Comment by FoxPotato** [comment]
Wasn't rift energy suggested before? I do like that, also according to whoniverse "Artron energy can be used to translate thoughts and emotions into History itself.".
but yeah, rift energy or something sounds reasonable. Having to refuel everytime.
There'd have to be a way to get there when out of fuel tho.
Rift energy jerry cans \o/

**Comment by AlienXtream** [comment]
Fast Return Protocol ;p. (Lore) tardis would never get totaly empty and (due to its ability to archive events that have yet to happen) reserve JUST enough energy to get to the nearest rift. The refuel process could create a tear in the sky and spawn lightning on top the tardis. Yrs i know that only happened because of the slithien lady (cant remember names) but the effect would make waiting less boring. As for artron energy, isnt that the radiation from the vortex? I think that both rift and artron should exist. Higher rift energy would increase artron collection while in the vortex  and when empty artron would stop dead. All roundel components could have a passive drain meaning one cannot just stay in the vortex or at a rift indefinitely. I know its a little off topic and messy but im going to bed now so atleast its here. Will likely make a new post with more fleshed out infomaition

**Comment by FoxPotato** [comment]
SO rift energy would be like a boost?
(Maybe it could even unlock some dimensions)

**Comment by AlienXtream** [comment]
not a boost so much. i was thinking that rift and artron energy do different things. rift energy would affect the exterior (i.e de/re materialization and other abilities? hint hint ;p) and artron energy would affect the interior. the idea here was is that when landed artron cant recharge BUT rift can and vice verca

**Comment by AlienXtream** [comment]
just that higher artron energy level would permit a "faster" speed in the vortex and thus able to collect artron faster. would also make artron batteries useful as they could provide power to nearby roundels

**Comment by AlienXtream** [comment]
could also dispense with the room limiter and instead have creating rooms cost artron energy. bigger rooms need more power and the more rooms you have the higher the cost multiplier. dang it Fox! now my mind is to fired up with all these ideas to sleep! :P

**Comment by ghost** [comment]
I like this idea much better than mine.
