### ISSUE TITLE
[Enhance] Console Room

### ISSUE THREAD

**Issue by ghost** [DarkholmeTenk/TardisModIssues#465]
Could it be possible to add in a config or within game to change what the default tardis console room is if the person has multiple schemas before a player first enters his/her tardis?

**Comment by SomeBadGamer** [comment]
I don't see the point in adding it because why have dark work to do that when you can go to the  console and change it your self

**Comment by ghost** [comment]
For a server or adding a kind of schema that may need repairs if a person wants to have it were they created a damaged tardis or you have to slowly fix certain parts or destroy certain things to gain access to other parts such as a obsidian door or casing if they made it into a schema to use.

**Comment by DarkholmeTenk** [comment]
you could always just save a different console to tardisConsoleMain? Since it goes by saved schemas before the ones in the jar, that should do it. Damaged stuff on the other hand probably won't work because the engine, core and console are all placed outside of the schema loading system.

**Comment by ghost** [comment]
Okay
