### ISSUE TITLE
[BUG] mophing in tardis is broken again :/

### ISSUE THREAD

**Issue by AlienXtream** [DarkholmeTenk/TardisModIssues#469]
a change in the newest version of tardis mod has broken morph once more

**Comment by AlienXtream** [comment]
looking at you :P @FoxPotato

**Comment by AlienXtream** [comment]
appears to be related to world time (i.e day/night cycle, or lack there of)

**Comment by AlienXtream** [comment]
issue is ichunn's  tickhandler uses worldtime. ichunns problem. user solution is to enable the day/night cycle while morphing

**Comment by DarkholmeTenk** [comment]
Fixed by putting in stupid hacky functions again.
