### ISSUE TITLE
[ENHANCE]Clean up the configs

### ISSUE THREAD

**Issue by Durpady** [DarkholmeTenk/TardisModIssues#47]
At present, they're hard to read.

**Comment by DarkholmeTenk** [comment]
Bit vague; could you clarify?

**Comment by FoxPotato** [comment]
the configs are quite clear, if you know what you're doing atleast.

**Comment by Durpady** [comment]
There are no enter/return/paragraph marks.  Might want to fix that.

**Comment by DarkholmeTenk** [comment]
There are, it's just it's using the more common UNIX format of just having a newline character rather than the windows format of a newline and a carriage return. Use an editor like notepad++ and it'll show up properly.
