### ISSUE TITLE
problems DarkCore [FPS]

### ISSUE THREAD

**Issue by Andrey-007** [DarkholmeTenk/TardisModIssues#470]
Hello, if DarkCore set higher than v93 on Forge server, KCauldron, Thermos v1614 and client, there are problems with FPS on the client. (OverWorld https://yadi.sk/i/7b_J4TSMq2zWt) (Tardis https://yadi.sk/i/jXza6FZeq2zae)

**Comment by FoxPotato** [comment]
It might not just be darkcore. Does tardismod give any errors? Does it happen in singleplayer? Is TardisMod updated to the latest version? Does it happen on a normal forge server?
And v93 is 2 months old, how did you even find this.

**Comment by Andrey-007** [comment]
No errors, logs attached https://yadi.sk/d/k_zi9hFHq33ci
In a single no brakes
but has been updated to the latest version. There is no difference in the tardismod
Yes
No it happens only in a multiplayer game (on the server).
http://tardismod.com:8080/
Sorry for my lousy English

**Comment by DarkholmeTenk** [comment]
should be fixed with latest darkcore, pls use pastebin for logs.

**Comment by Andrey-007** [comment]
Thank you
