### ISSUE TITLE
[Crash] When i try the new Darkcore with the new TardisMod

### ISSUE THREAD

**Issue by LotuxPunk** [DarkholmeTenk/TardisModIssues#472]
Hello !

I've download & try to launch the new Darkcore 0.35.123 & TardisMod 0.994.310, but before the game launch, server stop. Can you help me please ? :)

[crash-2016-03-10_00.46.21-server.txt](https://github.com/DarkholmeTenk/TardisModIssues/files/167791/crash-2016-03-10_00.46.21-server.txt)

**Comment by DarkholmeTenk** [comment]
Should be fixed when the next darkcore builds

**Comment by LotuxPunk** [comment]
Thanks ! :)
