### ISSUE TITLE
[Bug] Schema Visibility 

### ISSUE THREAD

**Issue by ghost** [DarkholmeTenk/TardisModIssues#473]
The schema visibility option for the config was removed and now I cannot toggle whether or not I can see schema blocks. Is this a bug or intentional?

**Comment by DarkholmeTenk** [comment]
`visibleSchema = toolConfig.getConfigItem(new ConfigItem("Visibility - Schema", CType.BOOLEAN, false, "Should schema boundaries be visible (clientside config)")).getBoolean();`
Are you sure? It's under tools and blocks, but it still appears to be there
