### ISSUE TITLE
[Bug] Dimension Upgrade Nether

### ISSUE THREAD

**Issue by ghost** [DarkholmeTenk/TardisModIssues#474]
I noticed with the new option that you can add a list of dimensions to the config to need a upgrade to access. I tried to put the nether dimension into the list as -1 but when I go to play it is always unlocked without needing an upgrade.  Also how do you obtain these items within game in survival or do they need to be spawned in?

**Comment by DarkholmeTenk** [comment]
They either need a minetweaker recipe or to be spawned in. @FoxPotato on them not working though.

**Comment by FoxPotato** [comment]
Could you maybe send me the exact part of the config where you assign the dimensions? And maybe also what level your TARDIS is.
And ofc, did you update darkcore and tardismod to the latest versions.

**Comment by ghost** [comment]
I am using Darkcore 124 and tardis mod 311. The tardis I used to test this problem was at level 50 and the config is this: 
#Put all the dimension ID's you want to lock using an engine upgrade here, seperating each ID with a comma
#Like this: 1,2,3,4
#Default: 
Dimension ID's locked by upgrades:S: -1,1,-100,40,62,1023,1022,-112,51

**Comment by FoxPotato** [comment]
I know they're not that outdated, but please could you update them? :P 
and just to be sure, does it work when you only do -1,1. So no mod dimensions? or only the nether perhaps.

**Comment by FoxPotato** [comment]
And of course, do the other ones work as expected?

**Comment by ghost** [comment]
I just tried the two dimensions that you listed above in the same order and updated to the latest one on jenkins last night and still only applies to the nether with it still showing on the console still

**Comment by ghost** [comment]
Its Fixed?

**Comment by FoxPotato** [comment]
yes, the problem was that you had a white space before the dimension id of the nether. and thus it didnt recognise it. But it should get rid of all whitespaces now :P

**Comment by ghost** [comment]
oops silly me
