### ISSUE TITLE
[ENHANCE] dismantle function work on unbreakable interior block

### ISSUE THREAD

**Issue by AlienXtream** [DarkholmeTenk/TardisModIssues#475]
having the dismantle function remove the "unbreakable" interior blocks (similar to the lab and dirt) would permit putting things flush with the floor. of course they wouldn't yield and item, just to allow you to put things flush

**Comment by FoxPotato** [comment]
There's probably a reason for them being unbreakable, just like there's bedrock underneath the overworld :P

**Comment by AlienXtream** [comment]
But you cant (typically) die i the void in the tardis. You can in the overworld. Your argument is invalid :P. I jest, but in all seriousness it would come in handy in many scenarios

**Comment by AlienXtream** [comment]
I mean its not like we cant get out of the rooms as is anyway so why not? Dark, thoughts?

**Comment by SomeBadGamer** [comment]
I see the good and bad to this bad what if you remove the  block by accident good is as you said

**Comment by AlienXtream** [comment]
Good point :-\

**Comment by FoxPotato** [comment]
You can indeed leave the rooms, but you're not actually meant to. Ways to get out of rooms usually include other mods, bugs/glitches or custom schematics :P

**Comment by AlienXtream** [comment]
Question 1) dose it hurt anyone. 2) do you get any resources (other than free aura nodes) 3) dose it cause any fatal issues and 4) is it really that big of a deal :P

**Comment by DarkholmeTenk** [comment]
My main complaint is that it will make the mod feel unpolished. If while you're messing around, you accidentally right click with a dismantle screwdriver and now there's a hole in your tardis you can't fix.
Not only that but it means you'll be able to legit get outside of your tardis and wander around on the invisible schema blocks.
No it doesn't hurt anyone, cause fatal issues, etc, but it makes it feel less polished, imo.

**Comment by AlienXtream** [comment]
ok. not happening then. solution. make a custom schema or go to creative

**Comment by FoxPotato** [comment]
There is actually already a schematic on foxpotato.com it seems. 'Debug.Airlock' by Brandon.
dunno if its any good, but its there :P
