### ISSUE TITLE
AE2 channels?

### ISSUE THREAD

**Issue by grlewis1** [DarkholmeTenk/TardisModIssues#48]
Loving this mod!
one thing i've noticed with regards to ae2, is that the tardis has a built in channel system.
i'm not a fan of channels my self and always have them disabled in ae2, is there any way of doing the tame with the tardis wiring?

**Comment by DarkholmeTenk** [comment]
There aren't any AE2 channels as far as I'm aware; it's just all of the roundels act as a single cable; everything connected to one is connected to everything else connected to one. If there's a limit, it's not one, I've imposed :P

**Comment by DarkholmeTenk** [comment]
Don't think there's anything more I can do from looking at the AE api

**Comment by DarkholmeTenk** [comment]
Workaround done in DS build
