### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Shazuli** [DarkholmeTenk/TardisModIssues#480]
Hi!
This mod looks amazing! I'm a big Doctor Who fan!
The thing is, the game crashed on start up. I have made my own private pack for my own, nothing I will post somewhere. The pack starts up as normal when your mod is not installed. So it has nothing to do with some other mod messing up. I do have newest tardis mod (0.994) and newest DarkCore (0.35). I have tried starting up minecraft a few times but same result, it's not a ID conflict, it's not the usuall crash, minecraft simply won't open the window.

I'm using alot of mods, so bare with me.
Alternate Terrain generation, Buildcraft, Buildcraft Compat, Chisel 2, CodeChickenCore, DarkCore, DragonAPI, ElectricCraft, EnderCore, Logistics Pipes, MineTweaker 3, ModTweaker 2, NotEnoughtItems, OpenComputers, ProjectRed Compatibility, ProjectRed Core, ProjectRed Illumination, ProjectRed Transmission, ReactorCraft. RotaryCraft, Tardis mod, Waila, WAILA Plugins, WorldEdit.

Here is the crash report:

[crash-2016-03-18_16.49.52-client.txt](https://github.com/DarkholmeTenk/TardisModIssues/files/180386/crash-2016-03-18_16.49.52-client.txt)

**Comment by DarkholmeTenk** [comment]
Try without DragonAPI and associated mods pls

**Comment by DarkholmeTenk** [comment]
Closing as this is well outside of our control. Something to do with DragonAPI/FML interactions.
