### ISSUE TITLE
1.9 port

### ISSUE THREAD

**Issue by MoonlightSystem** [DarkholmeTenk/TardisModIssues#481]
With 1.9 forge now available is the TardisMod going to be ported to that version instead of 1.8.9?
It would be cool to dual wield a sonic screwdriver and decorator tool!

**Comment by FoxPotato** [comment]
I don't really see the use of this issue seeing as there's been talking about porting to 1.9 in #458 already.

**Comment by AlienXtream** [comment]
dual wielding of the decorator/sonic would be... problematic as the decorator AND the sonic both have left and tight click functions (transmat other entities)
