### ISSUE TITLE
[ENHANCE] Craftable Tardis Blocks

### ISSUE THREAD

**Issue by rascal54321** [DarkholmeTenk/TardisModIssues#484]
Just a small request for a version of the Tardis blocks to be craftable in survival, probably using the Temporal Laboratory. Just walls, roundels etc. Maybe have stairs and slabs etc as well. This would be for internal building purposes, like interior walls, not replacing the Creative blocks or the current room system. I'm currently using Chisel Laboratory blocks, but the coloring isn't as close as I'd like. Unless you could have a colouring scheme that deliberately matches some of the Chisel textures? Concrete, industrial Tardis here I come. I don't seriously expect that last one though.....

Note that I'm NOT asking for this functionality:https://github.com/DarkholmeTenk/TardisModIssues/issues/475

I agree that it could be messy to allow the dismantle function to work on the Tardis interior blocks.

**Comment by DarkholmeTenk** [comment]
This is already a thing, they end in (c) and maintain all the colorability/roundel functions where those exist

**Comment by rascal54321** [comment]
Really? I don't get an NEI recipe for those. Hmmmm.......

**Comment by DarkholmeTenk** [comment]
Try using the jenkins versions of dc and tm
