### ISSUE TITLE
[ENCHANCE] K-9 Companion

### ISSUE THREAD

**Issue by rascal54321** [DarkholmeTenk/TardisModIssues#485]
Another little feature request:

If you've played with Mekanism at all, you might be aware of the Robit, a little robot companion who can follow you around and perform various tasks like crafting, picking up items and whatnot. Basically, that functionality with a K-9 skin could be fun,

**Comment by Jwtc2000** [comment]
![](https://media.giphy.com/media/12XMGIWtrHBl5e/giphy.gif)

**Comment by FoxPotato** [comment]
This is a TARDIS mod, not a doctor who mod.

**Comment by rascal54321** [comment]
......Ok? Yeah, I get it, there's no connection between them at all. Not like it's from  Doctor Who, features a blue police box Tardis or has a sonic screwdriver or anything.......

**Comment by FoxPotato** [comment]
We are focussing on just the TARDIS, not a complete doctor who mod. When there's no way around we do take some things from more general doctor who. But things like the trenchcoat or k-9 won't get added.

**Comment by DarkholmeTenk** [comment]
FoxPotato is one of the developers of the mod and he's not wrong, we are only focussing on the TARDIS, not the entire dr who canon.
