### ISSUE TITLE
[BUG] TARDIS-ception

### ISSUE THREAD

**Issue by FoxPotato** [DarkholmeTenk/TardisModIssues#49]
I have found multiple ways of destroying the exterior while being in the console and thus being able to summon the TARDIS inside the console room.
Just find a way to disable this. people are able to get their exterior back by just flying somewhere.

**Comment by DarkholmeTenk** [comment]
How have you destroyed the exterior from inside the console? Those sound like much more interesting bugs.

Also, if your exterior gets destroyed while you're not inside (e.g. by dark oak trees), then you need the key to resummon, so I'm not going to outright disable it, maybe make it not function inside a TARDIS though.

**Comment by laz2727** [comment]
Because chunkloaders and friends.

**Comment by FoxPotato** [comment]
that was my request. just disable being able to spawn it inside of the console.

and one of the ways is by just putting the x and z controls on max and travel relative not fixed coords. eventually the door won't open and you can spawn it inside. because i guess you reach the edge of the world eventually.

and what laz said, with the right mods installed you can do quite alot.
