### ISSUE TITLE
[Bug?]Stair Shadow Thingy

### ISSUE THREAD

**Issue by ghost** [DarkholmeTenk/TardisModIssues#490]
First this is to make sure everybody is still alive and does anyone know how to update the lighting when using the stairs in this mod? For a while the stairs started to show correctly without the shadow over the step part but now it always shows up. Is this a bug or now intentional?

**Comment by FoxPotato** [comment]
I think that might be something vanilla related. Or it could have something to do with the opaque option, which got changed not too many versions ago. 
Have you tried toggling the day/night button?

**Comment by ghost** [comment]
Yes I have tried Day and Night. I also tried moving a light source (roundels) away and to the stair block but nothing changed. Also in the newer versions it is always displayed with a Shadow but in older versions which I think are before the chameleon update it would occasionally get rid of the shadow. This is also the only mod i have seen that has the glitch with the shadow on the stairs

**Comment by ghost** [comment]
Also the slabs in the mod do show correctly and is just the stairs in this

**Comment by AlienXtream** [comment]
i have seen vanilla stairs do something similar to what you are describing before, can you post screen shots?

**Comment by FoxPotato** [comment]
I have also seen multiple mods with this bug. A few of my test ones had it as well. It probably has to do with opacity and shit.

**Comment by ghost** [comment]
Here are some picks of it in daylight/night and when a roundel or light source is between them:
![2016-04-06_13 52 47](https://cloud.githubusercontent.com/assets/15722462/14327197/4029ae32-fbff-11e5-95f9-7540065c9399.png)
![2016-04-06_13 53 02](https://cloud.githubusercontent.com/assets/15722462/14327203/45f2392e-fbff-11e5-8835-16bd8147d2bf.png)
![2016-04-06_13 53 58](https://cloud.githubusercontent.com/assets/15722462/14327207/49567922-fbff-11e5-8dc6-12452200a6c9.png)
![2016-04-06_13 54 04](https://cloud.githubusercontent.com/assets/15722462/14327210/4b15a83c-fbff-11e5-9f78-53d67f58df3e.png)

**Comment by AlienXtream** [comment]
ok. fix is stairs need to be transparent.

**Comment by ghost** [comment]
?

**Comment by FoxPotato** [comment]
What he meant is; that this bug is most likely fixed by making stairs transparent.

**Comment by AlienXtream** [comment]
^

**Comment by ghost** [comment]
Managed to fix it another problem was that a mod was changing smooth lighting levels by turning them off and such without me knowing but managed to fix the setting so the shadow disappeared
