### ISSUE TITLE
BUG: AE2 roundel interface not working

### ISSUE THREAD

**Issue by XenoVee** [DarkholmeTenk/TardisModIssues#491]
when I try to use an Applied Energistics interface, it crashes my game, here is the report:
---- Minecraft Crash Report ----
// Oops.

Time: 5-4-16 14:37
Description: Ticking block entity

java.lang.NoSuchFieldError: DENSE_CAPACITY
    at tardis.common.tileents.components.ComponentGrid.getFlags(ComponentGrid.java:254)
    at appeng.me.GridNode.updateState(GridNode.java:141)
    at tardis.common.tileents.components.ComponentGrid.createNode(ComponentGrid.java:156)
    at tardis.common.tileents.components.ComponentGrid.revive(ComponentGrid.java:101)
    at tardis.common.tileents.ComponentTileEntity.reviveComps(ComponentTileEntity.java:143)
    at tardis.common.tileents.ComponentTileEntity.init(ComponentTileEntity.java:172)
    at tardis.common.tileents.ComponentTileEntity.func_145845_h(ComponentTileEntity.java:186)
    at net.minecraft.world.World.func_72939_s(World.java:1939)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at tardis.common.tileents.components.ComponentGrid.getFlags(ComponentGrid.java:254)
    at appeng.me.GridNode.updateState(GridNode.java:141)
    at tardis.common.tileents.components.ComponentGrid.createNode(ComponentGrid.java:156)
    at tardis.common.tileents.components.ComponentGrid.revive(ComponentGrid.java:101)
    at tardis.common.tileents.ComponentTileEntity.reviveComps(ComponentTileEntity.java:143)
    at tardis.common.tileents.ComponentTileEntity.init(ComponentTileEntity.java:172)
    at tardis.common.tileents.ComponentTileEntity.func_145845_h(ComponentTileEntity.java:186)

-- Block entity being ticked --
Details:
    Name: tile.TardisMod.ColorableOpenRoundel // tardis.common.tileents.ComponentTileEntity
    Block type: ID #718 (tile.TardisMod.ColorableOpenRoundel // tardis.common.blocks.ColorableOpenRoundelBlock)
    Block data value: 15 / 0xF / 0b1111
    Block location: World: (2,63,-12), Chunk: (at 2,3,4 in 0,-1; contains blocks 0,0,-16 to 15,255,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
    Actual block type: ID #718 (tile.TardisMod.ColorableOpenRoundel // tardis.common.blocks.ColorableOpenRoundelBlock)
    Actual block data value: 15 / 0xF / 0b1111
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1939)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
    Level name: test
    All players: 1 total; [EntityPlayerMP['doggi345'/4, l='test', x=0,91, y=62,00, z=-9,55]]
    Chunk stats: ServerChunkCache: 757 Drop: 0
    Level seed: -1232523842621994470
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 0 game time, 0 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: ~~ERROR~~ NullPointerException: null
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 312116696 bytes (297 MB) / 751304704 bytes (716 MB) up to 954728448 bytes (910 MB)
    JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 29 mods loaded, 29 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1558-1.7.10.jar) 
    UCHIJAAAA   Forge{10.13.4.1558} [Minecraft Forge](forge-1.7.10-10.13.4.1558-1.7.10.jar) 
    UCHIJAAAA   AppliedEnergistics2-Core{rv0-stable-3} [AppliedEnergistics2 Core](minecraft.jar) 
    UCHIJAAAA   CodeChickenCore{1.0.7.46} [CodeChicken Core](minecraft.jar) 
    UCHIJAAAA   NotEnoughItems{1.0.5.110} [Not Enough Items](NotEnoughItems-1.7.10-1.0.5.110-universal.jar) 
    UCHIJAAAA   OpenModsCore{0.9.1} [OpenModsCore](minecraft.jar) 
    UCHIJAAAA   <CoFH ASM>{000} [CoFH ASM](minecraft.jar) 
    UCHIJAAAA   CoFHCore{1.7.10R3.1.1} [CoFH Core](CoFHCore-[1.7.10]3.1.1-324.jar) 
    UCHIJAAAA   ThermalFoundation{1.7.10R1.2.2} [Thermal Foundation](ThermalFoundation-[1.7.10]1.2.2-111.jar) 
    UCHIJAAAA   ThermalExpansion{1.7.10R4.1.1} [Thermal Expansion](ThermalExpansion-[1.7.10]4.1.1-237.jar) 
    UCHIJAAAA   appliedenergistics2{rv0-stable-3} [Applied Energistics 2](appliedenergistics2-rv0-stable-3.jar) 
    UCHIJAAAA   ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships](ArchimedesShips-1.7.1.jar) 
    UCHIJAAAA   BigReactors{0.4.3A} [Big Reactors](BigReactors-0.4.3A.jar) 
    UCHIJAAAA   ForgeMultipart{1.2.0.345} [Forge Multipart](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCHIJAAAA   chisel{2.5.1.44} [Chisel 2](Chisel2-2.5.1.44.jar) 
    UCHIJAAAA   darkcore{0.3} [Dark Core](darkcore-0.3-86.jar) 
    UCHIJAAAA   ExtraUtilities{1.2.12} [Extra Utilities](extrautilities-1.2.12.jar) 
    UCHIJAAAA   McMultipart{1.2.0.345} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCHIJAAAA   IronChest{6.0.60.741} [Iron Chest](ironchest-1.7.10-6.0.60.741-universal.jar) 
    UCHIJAAAA   Mantle{1.7.10-0.3.2.jenkins191} [Mantle](Mantle-1.7.10-0.3.2b.jar) 
    UCHIJAAAA   OpenMods{0.9.1} [OpenMods](OpenModsLib-1.7.10-0.9.1.jar) 
    UCHIJAAAA   OpenBlocks{1.5.1} [OpenBlocks](OpenBlocks-1.7.10-1.5.1.jar) 
    UCHIJAAAA   Waila{1.5.10} [Waila](Waila-1.5.10_1.7.10.jar) 
    UCHIJAAAA   TardisMod{0.994} [Tardis Mod](tardismod-1.7.10-0.994-124-DS.jar) 
    UCHIJAAAA   TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct](TConstruct-1.7.10-1.8.8.jar) 
    UCHIJAAAA   ThermalDynamics{1.7.10R1.1.0} [Thermal Dynamics](ThermalDynamics-[1.7.10]1.1.0-161.jar) 
    UCHIJAAAA   TMechworks{0.2.15.106} [Tinkers' Mechworks](TMechworks-1.7.10-0.2.15.106.jar) 
    UCHIJAAAA   ForgeMicroblock{1.2.0.345} [Forge Microblocks](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
    Class transformer null safety: all safe
    CoFHCore: -[1.7.10]3.1.1-324
    ThermalFoundation: -[1.7.10]1.2.2-111
    ThermalExpansion: -[1.7.10]4.1.1-237
    AE2 Version: stable rv0-stable-3 for Forge 10.12.0.1024
    Mantle Environment: Environment healthy.
    TConstruct Environment: Environment healthy.
    ThermalDynamics: -[1.7.10]1.1.0-161
    Stencil buffer state: Function set: GL30, pool: forge, bits: 8
    AE2 Integration: RotaryCraft:OFF, IC2:OFF, RC:OFF, BC:OFF, MJ5:OFF, MJ6:OFF, RF:ON, MFR:OFF, DSU:ON, FZ:OFF, Waila:ON, CLApi:OFF, RB:OFF, InvTweaks:OFF, NEI:ON, CraftGuide:OFF, FMP:ON
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 1 / 8; [EntityPlayerMP['doggi345'/4, l='test', x=0,91, y=62,00, z=-9,55]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by XenoVee** [comment]
also, the dimension lever seems to be missing

**Comment by AlienXtream** [comment]
do more testing. this has NOT been an issue for me before and i am REALLY good at breaking things. update both tardis mod, darkcore and (if needed) applied energistics. your description is vague, what interface? tardis one (i'm assuming so) or AE one? how is your network setup? all these things could influence the crash.

**Comment by DarkholmeTenk** [comment]
Use something newer than AE rv0. Dimension lever may be missing due to lack of other available dimensions, idk.
