### ISSUE TITLE
Client Crash When Flying Tardis

### ISSUE THREAD

**Issue by Poisonsting** [DarkholmeTenk/TardisModIssues#493]
When anyone tries to fly a Tardis on my server their client crashes and the Tardis proceeds to take massive damage without them. This always happens in uncoordinated flight, and sometimes happens in coordinated flight.

Crash report added below.

**Comment by DarkholmeTenk** [comment]
Use the jenkins versions #393

**Comment by DarkholmeTenk** [comment]
By that, I mean this has already been fixed in #393. Use the version of darkcore/tm from the jenkins.
