### ISSUE TITLE
[Question] Be able to use older tardis model

### ISSUE THREAD

**Issue by ghost** [DarkholmeTenk/TardisModIssues#494]
I do know that it is possible to override the textures of the Tardis exterior just by naming it to the default or texture you are trying to replace and replacing it by deleting original. Can this also work for the model for the exterior by having it being changed from before chameleon was added or does anyone know if it possible to switch to the older model in the newer versions?

**Comment by AlienXtream** [comment]
i asked dark if the original model would be selectable as a chameleon option when he was first implementing it, he said no. as for your query, in theory you should just need to replace the model file in the jar (not recommended!). weather this is doable with a resource pack or not is another thing altogether

**Comment by FoxPotato** [comment]
I don't think it's possible. But I mean; one way to find out amirite.

Well there's multiple ways, but just testing it is the easiest probably.

**Comment by AlienXtream** [comment]
not without the source code. perhaps (with dark's permission) we could have the reference names for the exteriors to try and override the model

**Comment by AlienXtream** [comment]
no harm is trying right? (in an isolated setting that won't break your survival game ofc)

**Comment by FoxPotato** [comment]
I don't know the correct structure of a resourcepack.
but if you make one, and inside of the tardismod folder next to the textures you make a models folder, and inside of there a tardis folder (no capital letters). And put a new, let's say, postbox.obj in there. That should work. And if it doesn't, well, then it doesnt work :P

**Comment by ghost** [comment]
I haven't checked yet but isn't the older model in a different format than the new one so it wouldn't really take its place unless the old one was changed to the newer format used?

**Comment by AlienXtream** [comment]
i have seen its model (at least i THINK it's the one) in the models folder in the jar

**Comment by FoxPotato** [comment]
Aren't there 2 tardis models in the chameleon circuit tho?

**Comment by ghost** [comment]
![image](https://cloud.githubusercontent.com/assets/15722462/14472426/2bf1c730-00c1-11e6-9743-2aa081339851.png)

For this all I would do is switch the name of old tardis to new tardis and delete the original new tardis file?

**Comment by DarkholmeTenk** [comment]
no, those are the existing models that can be used via the chameleon circuit. oldTardis is the default. The original model was techne->java so can't just be swapped in.

**Comment by ghost** [comment]
Unless the model becomes available to use again as an option or something then I am closing this as I see this as answered.
