### ISSUE TITLE
Tardis revs up to travel and then crashes client.

### ISSUE THREAD

**Issue by JMANMARINO** [DarkholmeTenk/TardisModIssues#495]
This is on a server with some other mods and I'm not sure what is happening because it was working just fine, and i got to around level 5 and this would start crashing my client. just mine. not the server and not my buddies, just mine. http://pastebin.com/SUadqHvw crash report is here. Really have no idea what started it, i added a couple of rooms the library and the large room and the med farm... not sure what else to add. other than elaborating that the crash is just before the switches buttons and levers mini-game bit while in travel. it plays the entire sound file for the rev up sequence and then crashes on the spot.

**Comment by FoxPotato** [comment]
How close are you to levelling up? And were you switching dimensions? Try and change the dimensional lever.

**Comment by DarkholmeTenk** [comment]
#393 Use jenkins versions
