### ISSUE TITLE
[ENHANCE] shield

### ISSUE THREAD

**Issue by FoxPotato** [DarkholmeTenk/TardisModIssues#50]
it doesn't really have a name, but in the day of the doctor they managed to make the tower of london TARDIS proof. do you think it is possible to make like a shield block or something (Maybe make it run on artron energy idk) that generates a shield which denies the TARDIS. so it can't land inside the radius of the shield.

**Comment by spannerman79** [comment]
For server owners perhaps something like an "AntiLandZone" used with WorldGuard with say a flag - but that would require hooking into the WorldGuard API

But for players to have something that is powered - keeping with Doctor Who Law the *only* race able to block a TARDIS is the Daleks and other Time Lords.  
Only reason why the Tower of London was TARDIS proof was it was knocked together with other alien technology - most likely dalek technology

**Comment by FoxPotato** [comment]
"Alien technology combined with human stupidity. Unbeatable."

Ok yeah true, that's why I said maybe run it on Artron energy. Idk if the TARDIS is able to give off artron energy when on a landing pad. but maybe you could have it that you have to have your own TARDIS parked or something. like on top of the shield block or something. IDK.

Or indeed make it admin only. And Worldguard would mean you'd have to have bukkit to use it. which doesn't always work with forge.

**Comment by DarkholmeTenk** [comment]
TARDIS can provide Artron Energy to a landing pad; so can an Artron Battery

**Comment by FoxPotato** [comment]
That can be useful. will the landing pad work like an artron battery then?

**Comment by DarkholmeTenk** [comment]
Nope, but stick an Artron Battery next to it and it'll receive Artron power (e.g. for nanogenes ;) )

**Comment by FoxPotato** [comment]
ahhhh, that's handy.
but you could use that, just that you have to have your TARDIS parked for the shield to work :p

**Comment by TorkSlanter** [comment]
You could have a block that works similar to a chunk loader in a gui, where you could set a radius (up to a max configurable in a config file for servers maybe?) where a TARDIS cannot land. But that may cause problems when involving the Sonic Screwdriver's "Recall" ability, if the TARDIS starts flying and theres nobody inside to tell it to stop flying it may get caught in infinite flight unintentionally. That is, assuming you just block the TARDIS from landing in an area. Another possibility is to have the block tell the TARDIS to land elsewhere, outside of the radius of the zone.

**Comment by FoxPotato** [comment]
I jsut remembered something. The time of the doctor. or the night of the doctor. whatever, the last episode with matt. That church had a anti tardis shield around the planet. but he could still summon the TARDIS.

**Comment by spannerman79** [comment]
Church of the Papal Mainframe @FoxPotato , but even still it wasn't impenetrable and it wasn't foolproof either (EG Weeping Angels already got past it after it was in place, then later the Sontarans etc.

In minecraft terms - vanilla minecraft mobs will be blocked but anything from say Ender Zoo  etc would get past it

**Comment by FoxPotato** [comment]
wait, the weeping angels didn't go through. they got there before it was placed.
and isn't it better if it isn't foolproof? that gives you some security but also keeps it fun ;p

**Comment by spannerman79** [comment]
The Time of the Doctor
About 15 mins in

Clara: What are they doing here?
11th Doctor: The same as everyone else.  They must have gotten past Tashas shield

So no, they (Weeping Angels) got past the shield. And Tasha is Mother Superior of the Papal Mainframe - the one that put the shield in place in the first place

**Comment by laz2727** [comment]
The shield never was tardis-proof.

**Comment by FoxPotato** [comment]
I know who tasha is. and i thought they got past by travelling back to when the shield wasn't there or something. bc they were pretty deep in the snow.

He could only get in by being teleported in and calling the TARDIS. but wouldn't that be better? like, you can't enter someone's base with the TARDIS. you have to go in and if you need your TARDIS you can call it.

**Comment by spannerman79** [comment]
I think that would be a better idea.  First getting into the actual shield protected area then using sonic screwdriver to do a recall.  Maybe have a much higher power drain (10 - 100 times) then normal because your going through a shield.

**Comment by FoxPotato** [comment]
Yeah that sounds pretty balanced. It would keep people from coming around without a legit reason. IF they really wanted to get in, they'd have to enter manually.
Of course it's up to darkholmetenk to decide :p

**Comment by DarkholmeTenk** [comment]
DamageSystem build. Should be pretty impossible to get through.
