### ISSUE TITLE
[ENHANCE] Roundels Frequency

### ISSUE THREAD

**Issue by dillasyx** [DarkholmeTenk/TardisModIssues#501]
What about a roundel system with frequencies? so you could have more than one energy networks.

**Comment by AlienXtream** [comment]
possible but not likely to happen. at least not soon

**Comment by dillasyx** [comment]
okay was just a thought :)

**Comment by darkdurza** [comment]
I second this

**Comment by darkdurza** [comment]
Even if it was something like the fluiduct tanks, divide the power between 6 or so different batteries, cycle through them with the screwdriver

**Comment by DarkholmeTenk** [comment]
This is actually much more of a pain in the neck than you'd imagine. I don't think this is going to be implemented any time soon, but I'll reopen if I change my mind.
