### ISSUE TITLE
 [BUG] biome ID

### ISSUE THREAD

**Issue by SvEgiiVEteR** [DarkholmeTenk/TardisModIssues#502]
# The id of the biome which is used in the console room
# Default: 42

Console Room Dimension ID:I:122
not change the biome ID in the config
forg 1614
darkcore-0.41-178.jar
tardismod-1.7.10-0.994-342.jar

**Comment by chaNcharge** [comment]
I think what you're trying to say is even if you change the biome id, it ignores the change and it keeps using the default id. I'm seeing this same issue too, can't play with this version unless this is fixed first unfortunately.
