### ISSUE TITLE
[BUG] TARDIS Biome generates in overworld

### ISSUE THREAD

**Issue by chaNcharge** [DarkholmeTenk/TardisModIssues#503]
There are no biome ID conflicts detected when I install AntiIDConflict, so it's not a biome conflicting with another. I'm not sure if this is intended either. Seed: 1655700806314264929
![2016-05-08_13 47 24](https://cloud.githubusercontent.com/assets/11594018/15100364/8091cdcc-1524-11e6-99ea-081a2ab8f61c.png)

**Comment by FoxPotato** [comment]
welp. that should not be happening. 

While I fix it see it as a rift to the time vortex for now. :P

**Comment by chaNcharge** [comment]
Also, some other unrelated biomes get changed for the worse. I've traced it to TARDIS mod, since it is the only one causing a Biome ID conflict with BOP. I changed **Bamboo Forest** from 42, to 105, and now for whatever reason, **Dense Forests** are missing trees. When I downgrade TARDIS mod to the 0.994 DS version, it doesn't happen. Hopefully this gets fixed soon.

**Comment by chaNcharge** [comment]
Ok so these two bugs seem to have been caused due to #502, and in the latest update, they seem to be fixed now. All is good!

**Comment by FoxPotato** [comment]
Probably because you weren't able to change the biome id. the line that registered the biome got called before the mod checked the configs. woops.

**Comment by AlienXtream** [comment]
gg fox :P
