### ISSUE TITLE
Can't view Schema Boundaries?

### ISSUE THREAD

**Issue by Validfire** [DarkholmeTenk/TardisModIssues#508]
I'm trying this mod out again for the first time in a few months so forgive me if this is just a stupid error of mine. Anyways, when I was starting to create Schematics for the TARDIS as I have done in the past I can not seem to get the schematic boundaries to show up. Also, when I do change it to true, Minecraft won't even launch. I've attached my config file with the latest error report file.

[toolsAndBlocks - Copy.txt](https://github.com/DarkholmeTenk/TardisModIssues/files/287486/toolsAndBlocks.-.Copy.txt)
[crash-2016-05-27_19.39.26-client.txt](https://github.com/DarkholmeTenk/TardisModIssues/files/287488/crash-2016-05-27_19.39.26-client.txt)

Once again, sorry if this was a user error... Thanks.

**Comment by FoxPotato** [comment]
"' falseVisibility - Schema'"
Please fix your config
