### ISSUE TITLE
[ENHANCE] Grey-Scale Coloring System

### ISSUE THREAD

**Issue by Validfire** [DarkholmeTenk/TardisModIssues#512]
As we all know, the leather armors have more color possibilities than just the given dyes, each dye effects the outcome of the color though. I believe this is accomplished with a Grey-Scale affect on the armor. Could we have a system like this with the TARDIS blocks? This would allow more ability for it to fit in with my schematics that often don't include any TARDISMOD blocks at all, plus, variety dude, variety.

**Comment by DarkholmeTenk** [comment]
Nope, metadata on a block is limited to 16 bits, metadata on items is not.
