### ISSUE TITLE
[ENHANCE] Magic doors

### ISSUE THREAD

**Issue by darkdurza** [DarkholmeTenk/TardisModIssues#514]
I think it would be awesome if, instead of the star background, the magic doors had an image of the room on the other side.

**Comment by DarkholmeTenk** [comment]
Nope, tried this, couldn't get it to come anywhere close to working. Too many chances for door a -> door b -> door a rendering causing an infinite render loop, when I tried with looking glass and I don't have the skill nor time to implement this myself.
