### ISSUE TITLE
[BUG] TARDIS Dimension always set to raining

### ISSUE THREAD

**Issue by chaNcharge** [DarkholmeTenk/TardisModIssues#515]
This isn't exactly noticable because rain is disabled in the TARDIS, but if you have NEI installed, you'll notice it. If you step in the TARDIS with NEI installed, it'll show that rain is enabled. This can cause problems with mods that add in special rain sounds, such as MAtmos. This is in the latest dev version of the mod. 

To reproduce:
1. Install Tardis mod and NEI
2. Create a new world
3. Spawn in a TARDIS with TARDIS key
4. Step inside
5. You'll see that NEI and Minecraft detects rain is on, but that's not all
6. Step back outside
7. Minecraft thinks rain is on in the world, not visibly, but can trigger special rain sounds from MAtmos

The issue is resolved temporarily by relogging or turning rain on and off

**Comment by AlienXtream** [comment]
i don't believe i have ever encountered this... :/

**Comment by AlienXtream** [comment]
it is too O.o

**Comment by FoxPotato** [comment]
I'll look into this when i have the time. Which will probably be around the end of this week because of school projects and such

**Comment by AlienXtream** [comment]
yay school stuff \o/  (im being sarcastic :P)
