### ISSUE TITLE
[BUG] Nanogene heal cost

### ISSUE THREAD

**Issue by darkdurza** [DarkholmeTenk/TardisModIssues#516]
The nanogenes do not seem to be using artron energy when healing players. I set the nanogene cost to 100 in both roundels.cfg and Components.cfg, and they still don't use any energy. Is there somewhere to actually enable/disable nanogene cost period, or is this not working?

**Comment by darkdurza** [comment]
The tool repair isn't using energy either

**Comment by AlienXtream** [comment]
are you watching the waila tooltip? if so it may not be updating properly. rightclick the gauge. i can assure you the restoration field DOSE drain energy as i have had it drain my tardis dry. remember, the tardis regenerates artron energy too and the nanogene will not use any power if its not doing anything (same with the restoration field)

**Comment by darkdurza** [comment]
stood in fire and held right click on the gauge, the energy just went up from the regen, none used to heal me. I'm using the latest build, 1.7.10-0.994-344

**Comment by darkdurza** [comment]
Although the restoration field DOES use artron energy to repair tools and just doesn't update the waila interface

**Comment by AlienXtream** [comment]
And you are sure its set to 100 in the configs? What us your energy regen level at?
It is also possible dark just derped with the nanogenes. Everyone makes mistakes, its part of learning :)

**Comment by darkdurza** [comment]
![image](https://cloud.githubusercontent.com/assets/19618027/15654909/1a937f40-2666-11e6-8b06-af6376bbe882.png)

My max energy is at 6000 and my regen is 5

**Comment by AlienXtream** [comment]
odd... i will look into this myself and tell dark if its an issue
