### ISSUE TITLE
[BUG] Ltardis

### ISSUE THREAD

**Issue by FoxPotato** [DarkholmeTenk/TardisModIssues#52]
A user on the forums had a bug where the code was searching for the map Ltardis

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: Ltardis/common/items/SonicScrewdriverItem;

probably a typo

**Comment by FoxPotato** [comment]
this was version 0.97-48

**Comment by DarkholmeTenk** [comment]
Missing CoFHCore in crash report
