### ISSUE TITLE
[BUG] Landing pad crash with Buildcraft

### ISSUE THREAD

**Issue by darkdurza** [DarkholmeTenk/TardisModIssues#520]
Using buildcraft pipes to pump into a landing pad that is not connected to a Tardis causes the game to crash.

**Comment by DarkholmeTenk** [comment]
Pastebin the crash report and post the link pls

**Comment by darkdurza** [comment]
http://pastebin.com/3g68YJ4v

**Comment by FoxPotato** [comment]
Well, the pipes connect to the landing pad and thus think there's a tank available. But there isn't so they try to fill something that isn't there.
I guess just a simple check whether there's a tank or not and then maybe returning a dummy tank with like 0 capacity for the pipes to fill?
