### ISSUE TITLE
[BUG?] Energy conduits outputting infinite energy?

### ISSUE THREAD

**Issue by darkdurza** [DarkholmeTenk/TardisModIssues#521]
Is it intentional that the energy conduits output an infinite amount of energy regardless of energy tier? For instance if I plop an MFE down next to an energy conduit set to LV, the Tardis will be instantaneously drained into the MFE. I would expect it would be limited to the energy tier it's set to: 32EU/t, 512EU/t, etc. Otherwise what's the point in having different tiers? AFAIK anything will except LV, so it could always be LV.

**Comment by DarkholmeTenk** [comment]
http://i.imgur.com/rRFdaNW.png
