### ISSUE TITLE
[BUG] Version 348 doesn't work

### ISSUE THREAD

**Issue by darkdurza** [DarkholmeTenk/TardisModIssues#522]
Loaded it up and nothing Tardis related existed in game

**Comment by FoxPotato** [comment]
... we can't really work with this.
Please post your log on pastebin and link it. Thanks.

**Comment by darkdurza** [comment]
http://pastebin.com/dEcLT2MW

**Comment by darkdurza** [comment]
![image](https://cloud.githubusercontent.com/assets/19618027/15727489/d1c26f22-2824-11e6-8b4a-105e9ff72afb.png)

**Comment by darkdurza** [comment]
Same with 347

**Comment by darkdurza** [comment]
Wait hold on, I just noticed the file size is not right... I think I might be having an issue with the download.

**Comment by darkdurza** [comment]
Yep, download was cutting out before it finished. Restarted my router and got it to work. Sorry about that haha.
