### ISSUE TITLE
Crash every time I attempt to fly tardis.

### ISSUE THREAD

**Issue by Vailyn** [DarkholmeTenk/TardisModIssues#527]
Every time I try to fly the tardis, my game crashes. I am running it on a server that I also run.

Tardis mod version: 1.7.10-0.994-124-DS

Darkcore version: 0.3-86

Crash report:  http://pastebin.com/1uc890yn

If I left out anything please let me know and I will send it.
If I'm just being dumb about something, also let me know, I'm good at being dumb sometimes.
Thanks for the awesome mod!

**Comment by AlienXtream** [comment]
use jenkins builds of TM and darkcore

**Comment by DarkholmeTenk** [comment]
Yup, use latest versions.
