### ISSUE TITLE
[ENHANCE] Better Scanner

### ISSUE THREAD

**Issue by FoxPotato** [DarkholmeTenk/TardisModIssues#53]
Maybe have the scanner check breathable atmosphere and temperature. if galacticraft is installed atleast :p 
Maybe have this at a higher level than the normal scanner.
idk.

**Comment by DarkholmeTenk** [comment]
Rather difficult to do.
Don't know if feasible.
Definitely impossible to support all mods.

**Comment by FoxPotato** [comment]
If it's impossible, it's impossible.

**Comment by DarkholmeTenk** [comment]
I may look into adding support for galacticraft in the future, but for now I'm gonna close it :p
