### ISSUE TITLE
[BUG] Bootup crash

### ISSUE THREAD

**Issue by TheTrueForce** [DarkholmeTenk/TardisModIssues#537]
I'm not sure of what to make of this. I found this when I added the TARDIS mod to an already heavily modded instance, and it crashed on startup. I then tested it with no other mods(apart from darkcore), and reproduced it pretty much exactly. I have attached the log file from the clean instance.
I also tested this with darkcore only, and it did not happen.
MC 1.7.10
Forge 1558

[fml-client-latest.log.txt](https://github.com/DarkholmeTenk/TardisModIssues/files/333031/fml-client-latest.log.txt)

**Comment by TheTrueForce** [comment]
I tried switching to the latest alpha version of the TARDIS mod, and so far, it's worked.

**Comment by Wxam** [comment]
where can i find the latest alpha version of the TARDIS mod??

**Comment by TheTrueForce** [comment]
It's on CurseForge here: http://minecraft.curseforge.com/projects/tardis-mod
look in the sidebar, or in the files section. Look for version 0.995.

**Comment by Wxam** [comment]
it works thx for the help (and srry for the post)
i'm new to this i just made my account because this mod didn't work

Thank you

**Comment by TheTrueForce** [comment]
Hey, it's no problem. We all have to start somewhere.

**Comment by AlienXtream** [comment]
the newest versions are on jenkins http://tardismod.com:8080/

**Comment by DarkholmeTenk** [comment]
Apparently fixed
