### ISSUE TITLE
[BUG] Dupe

### ISSUE THREAD

**Issue by FoxPotato** [DarkholmeTenk/TardisModIssues#54]
I opened a roundel. placed the chunk loader and transmat. sometime later i dismantled the roundel and i picked up the items while they were dropping. but there were still 2 items on the groun which i cannot pick up.
this is build 54

**Comment by DarkholmeTenk** [comment]
It's a client/server desync issue. Just a weird minecraft thing; I imagine closing and reopening the world fixes it?

**Comment by FoxPotato** [comment]
leaving the TARDIS and entering fixes it.
it only happens when you stand 1block away or on top of the block.
just thought to let you know.

**Comment by DarkholmeTenk** [comment]
I'm pretty sure it's a vanilla bug; when I drop items, I give them a time-to-pickup value of 0 so you don't have to let the item sit on the floor for a few seconds; it looks like if you pick them up in the same tick, the client doesn't register it.

**Comment by FoxPotato** [comment]
downloaded latest darkcore and build 55 of TARDIS but it's still there
