### ISSUE TITLE
Tardis Console/Engine Controls Missing, Unmovable, or Strangely animated.

### ISSUE THREAD

**Issue by RogueAngelSeven** [DarkholmeTenk/TardisModIssues#542]
when using tardis mod with client side mods StellarSky (Stellar Sky-v0.1.29[1.7.10]) and its dependency SciAPI (SciAPI-1.1.0.0[1.7.10]) flight controls appear unmovable, and engine/permission controls are either oddly animated or missing entirely depending on tardis/darkcore version.

forge version: forge-1.7.10-10.13.4.1558

unmovable controls and odd animations version:
tardismod-1.7.10-0.985-178
darkcore-0.25-35

unmovable controls and missing engine/perm controls version:
tardismod-1.7.10-0.994-124-DS
darkcore-0.3-86

in either case the tardis appears function fine, and can be flown as well as can be expected with no indication what you are touching.

**Comment by AlienXtream** [comment]
interesting... when I load the mod into my instance it all goes black inside that tardis.... i will take a poke in the configs and see if i can find you a nice balance point with both mods :)

**Comment by AlienXtream** [comment]
it would appear to be due to custom fog rendering interfering with the tardis mod. i don't understand fully how/why it affects it but it does

**Comment by RogueAngelSeven** [comment]
I just pulled stellar sky from my pack.  tardis controls return to normal with out it.  I more or less put it here for the dev(s) and for anyone else who had the problem.

**Comment by DarkholmeTenk** [comment]
Sounds like a problem with another mod not using glPushMatrix and glPopMatrix correctly.
