### ISSUE TITLE
Flying the tardis crashes the clients of everyone in it

### ISSUE THREAD

**Issue by Saereth** [DarkholmeTenk/TardisModIssues#545]
running on vanilla forge 1614, after the destination is locked in and the sound effects play we crash with this crashlog:

https://dl.dropboxusercontent.com/u/28829658/crash-2016-07-04_19.11.04-client.txt

**Comment by DarkholmeTenk** [comment]
#433 Use jenkins versions

**Comment by Saereth** [comment]
ty!
