### ISSUE TITLE
[Bug]TARDIS randomly duplicates items

### ISSUE THREAD

**Issue by shadowbolt79** [DarkholmeTenk/TardisModIssues#552]
Not 100% sure on what causes this, but I think that when an item duct tries to pull an item out of the TARDIS inventory, but cant, it starts filling up the TARDIS inventory with that item. I noticed this after my system backed up too much. Nothing in the logs seems to show what happened.

I have 3 double chests filled with nothing but sawdust. >.>

**Comment by DarkholmeTenk** [comment]
I vaguely remember this happening before. Could you clarify what versions you're using?

**Comment by shadowbolt79** [comment]
Tardis v0.994
DarkCore v0.35

**Comment by DarkholmeTenk** [comment]
Try the latest tm from the jenkins and darkcore 0.40

**Comment by DarkholmeTenk** [comment]
No response in 2 weeks, assuming this is fixed.
