### ISSUE TITLE
Day/Night Selector not working

### ISSUE THREAD

**Issue by ghost** [DarkholmeTenk/TardisModIssues#553]
I go down to the controls and I only have the options Overworld and Space. It's a bit hard to see through generic MC glass, but the space option has some stars, and the overworld option the skybox permanently set to night. How to I get daytime?

**Comment by FoxPotato** [comment]
there's a button in the bottom left on the farside of the console.

**Comment by ghost** [comment]
Found it. Duh. Me smart. Me fly TARDIS...
