### ISSUE TITLE
[Question] How do you set schema blocks to be indestructible

### ISSUE THREAD

**Issue by ghost** [DarkholmeTenk/TardisModIssues#554]
I'd like to try my hand at some schemas using chisel blocks and other glass to give the TARDIS interior a more personal/themed look. How do I set the blocks as removable or not?

**Comment by FoxPotato** [comment]
you can't

**Comment by shadowbolt79** [comment]
Essentially, the TARDIS has two kinds of it's own internal blocks. One set is indestructible, the other set is craftable. (I believe the craftable ones are denoted with a c)

So unfortunately, this does not work with other mods blocks.
