### ISSUE TITLE
[BUG] Wrong (not) implemented compareTo in commands breaks /help

### ISSUE THREAD

**Issue by einsteinK** [DarkholmeTenk/TardisModIssues#557]
There's a common issue in mods that commands don't properly implement compareTo.
A result of this is that /help (and aliases like /?) will not work and error instead.
_(it's actually a bit clouded, as it *_might*\* break it, but doesn't do that always)*
Seems like all compareTo's for TARDIS commands just return 0, which might be bad.
_(Same for /dcdebug in Darkcore)_

**Comment by DarkholmeTenk** [comment]
Should all be fixed in Darkcore's AbstractCommand.
