### ISSUE TITLE
Right click to go into Tardis. Crashes game possible conflict with codechickenlib?

### ISSUE THREAD

**Issue by Gamerbolts** [DarkholmeTenk/TardisModIssues#558]
Hello I just recently saw your mod and wanted to add it to my modpack. But when I spawned the Tardis in creative and right clicked I crashed. The error code says codechickenlib which is looks like something about chunk loading. Curious if I turn off the tardis chunk loading would that help?

Here is my error log
http://pastebin.com/7yrSuKiF

Any help is appreciated. Thanks!

**Comment by AlienXtream** [comment]
this has popped up a bunch before and i cant remember the fix (if there was one). if you don't have the latest versions of TM and dark core try updating otherwise idk :/ sorry

**Comment by Soyaro666** [comment]
the crashlog seems to blame BetterFPS by Guichaguri for this crash which doesn't seem to be installed. maybe it's part of another mod you've installed? I'd suggest to search and deactivate it ingame (main menu/mods)
