### ISSUE TITLE
black list not working

### ISSUE THREAD

**Issue by shadowdrake14** [DarkholmeTenk/TardisModIssues#562]
this is my id black list portion of the cfg
# A comma separated blacklist of dimension ids which no tardis should be able to reach #Default:Blacklisted Dimension IDs:S:-2,112,4,53,-3,69,-42,5,-19-38,-34,-39,-37,-42,5,4,-3

id's from this list are still accessible for some reason.  is this config wrong or something? how is it supposed to be?

**Comment by Soyaro666** [comment]
the line starting with # is an example. the line below is the actual config.
after Default: should be nothing, Blacklisted Dimensions belongs into a new line. In your case it should be
Default:
Blacklisted Dimension IDs:S:-2,112,4,53,-3,69,-42,5,-19-38,-34,-39,-37,-42,5,4,-3
If that's how you actually did it I'd assume this is a duplicate of #530 where I had a similar problem

**Comment by DarkholmeTenk** [comment]
Looks like that's correct.
