### ISSUE TITLE
[ENHANCE] Temporal engine

### ISSUE THREAD

**Issue by FoxPotato** [DarkholmeTenk/TardisModIssues#57]
There is still 1 slot left on the engine. maybe some gauges or displays with the TARDIS internal capacity?
so like RF gauges and liquid gauges. that sort of stuff.
kinda feel blind when pumping stuff in right now.

**Comment by DarkholmeTenk** [comment]
:+1:

**Comment by Xakorik** [comment]
+ + +
Yes+

**Comment by DarkholmeTenk** [comment]
This will probably end up getting used for repairing stuff

**Comment by DarkholmeTenk** [comment]
Panel is now used in the damageSystem update (not yet released or on jenkins), rf level and liquid levels are now visible by right clicking roundels with cable interfaces.
