### ISSUE TITLE
MCEdit Incompatibility?

### ISSUE THREAD

**Issue by Flexico** [DarkholmeTenk/TardisModIssues#576]
The TARDIS dimensions don't seem to be compatible with MCEdit for some reason. When I try to open it, MCEdit says that the dimension contains no chunks and asks if I want it to generate some for me.

**Comment by DarkholmeTenk** [comment]
Presumably related to the fact that the tardis dimensions are all stored under the Tardis folder in the world folder.

Not going to fix, since I like this organisational structure and I don't think there's anything I can do without getting rid of that.

**Comment by Flexico** [comment]
Oh, that's why it doesn't work? That's an easy workaround, I can just manually move the folder before using MCEdit and move it back when I'm done!
