### ISSUE TITLE
Are there any plans for TardisMod for 1.10 versions?

### ISSUE THREAD

**Issue by Schuljakov** [DarkholmeTenk/TardisModIssues#579]

**Comment by DarkholmeTenk** [comment]
There are no plans for a 1.10 versions.

After trying a 1.10 modpack, the performance was far too atrocious for me to want to play on it and if I don't play on a version, there's no reason for me to port it, as far as I'm concerned.

When FTB "Lite" uses less memory to get to the main menu than Skyrim takes to play, maybe then I'll look in to updating.

**Comment by Schuljakov** [comment]
Thank you for answering and for the mod itself. TardisMod is outstanding either as DoctorWho-world  realization and as detailed mod as well. Nowadays we play only with mods for 1.7.10 just because without TardisMod there is no such a delight and freedom in minecraft. 
I would be glad to show my (and friend of mine) gratitude in money, but the is a trick: a decent amount of money for us is a couple of dollars for you. I writing from Russia and 1$ = 65 рублей.
Sorry for my weak English. It took me an hour to formulate sentences above.

**Comment by ghost** [comment]
@DarkholmeTenk I just came back after a break and I'm having luck with the 1.10.2 stuff. Have you tried recently? The new capabilities system seems to help with performance and I miss the TARDIS.
(I checked first, Skyrim recommends 4GB as does FTB Infinity Lite for 1.10.2 ;) )
Thanks.

**Comment by PrincessOfEvil** [comment]
MC just got a big clientside memorysink fixed, so yeah.

**Comment by Schuljakov** [comment]
Yes, we really do miss TARDIS Mod.
