### ISSUE TITLE
[BUG] PLACING BLOCKS WHEN CONTROLLING TARDIS

### ISSUE THREAD

**Issue by FoxPotato** [DarkholmeTenk/TardisModIssues#58]
I keep placing blocks when clicking a button or flipping a lever. I don't know if it's intentional or if it's even fixable. but it's hella annoying.

**Comment by DarkholmeTenk** [comment]
Can't be fixed if you're sneaking; don't have blocks in your hands when using console/engine. Can be fixed for not sneaking.

**Comment by FoxPotato** [comment]
Not sneaking was the main problem. sneaking and placing blocks is only handy
