### ISSUE TITLE
Server Crashes Yet client loads sucessfully.

### ISSUE THREAD

**Issue by mirrormagic1** [DarkholmeTenk/TardisModIssues#580]
[Crashlog: pastebin.com/pDGq47Ky ]
I was forced to update the Darkmodcore and the tardis mod due to a crash on the clients end of going into uncordinated flight mode. After so i updated my client and my server. i boot the game just fine. Yet the server crashes For no reason. 
I deleted the configs that darkmod and the tardis mod adds, and it did nothing.
I also tried removing the world, but it never gets to load the world cause it crashes before that.
I tried removing the tardis mod entirely and the server boots just fine.
I Need help **Urgently** as the server is used by my friends.

**Comment by DarkholmeTenk** [comment]
I'd say just try playing around with different TM and DC versions until you get a working combo

**Comment by mirrormagic1** [comment]
Yeah I got it working. 355 Tardis build seemed to fix it just fine.

**Comment by Flexico** [comment]
Ah,thanks for this! Easy fix.

**Comment by shadowbolt79** [comment]
#589 seems to be the same issue as this one

**Comment by DarkholmeTenk** [comment]
Fixed with #589
