### ISSUE TITLE
Server java.lang.NoClassDefFoundError: AbstractBlockRenderer

### ISSUE THREAD

**Issue by SvEgiiVEteR** [DarkholmeTenk/TardisModIssues#585]
https://gist.github.com/fd486bb51492765606f5867265f3e1f4

**Comment by FoxPotato** [comment]
Please try the latest darkcore from jenkins, danke

**Comment by SvEgiiVEteR** [comment]
No ((
https://gist.github.com/5c203ffe1d8e0785fc44019a5d8d47d1
need appliedenergistics2-rv2-stable-10.jar and Thaumcraft-1.7.10-4.2.3.5.jar &

**Comment by FoxPotato** [comment]
There seems to be a problem with thaumcraft.
When does this crash happen? is this the first time booting up, or loading a world?
Did you perhaps uninstall thaumcraft recently?

**Comment by SvEgiiVEteR** [comment]
the crash occurs without these mods. just when you turn on the server.
your mod causes damage without appliedenergistics2-rv2-stable-10.jar and Thaumcraft-1.7.10-4.2.3.5.jar
this is a bug or so conceived?
these mods need?
the previous version didn't ask Thaumcraft
and thanks for the mod! he's just gorgeous ))

**Comment by FoxPotato** [comment]
That is a bug, it should notice they're not installed..
Have you tried updating both darkcore and tardismod to their latest jenkins versions?

**Comment by SvEgiiVEteR** [comment]
Yes
in log
UCH	darkcore{0.45} [Dark Core] (PACK_2_darkcore-0.45-255-FA1V.jar) 
UCE	TardisMod{0.995} [Tardis Mod] (PACK_2_tardismod-1.7.10-0.995-357_rus-FA1V.jar) 

with appliedenergistics2-rv2-stable-10.jar and Thaumcraft-1.7.10-4.2.3.5.jar all ok

**Comment by FoxPotato** [comment]
could you perhaps show me the **whole** crash log? The latest one has been cut off at the bottom it seems..

**Comment by SvEgiiVEteR** [comment]
broken:
https://gist.github.com/b2b10ae13ab5dee2f631fa56eeed8605
with appliedenergistics2-rv2-stable-10.jar and Thaumcraft-1.7.10-4.2.3.5.jar:
https://gist.github.com/dedcb47ff60c3feb31bb62b6a4870963
PS
as I understand it, your mod is looking for thaumcraft and can not found
with appliedenergistics2 I have the same story

**Comment by FoxPotato** [comment]
Could you perhaps try version [356](http://tardismod.com:8080/job/TardisMod/356/) ?

**Comment by SvEgiiVEteR** [comment]
@FoxPotato I played before with the 356. - Thaumcraft is not asking.
but without appliedenergistics2-rv2 does not work (also crash).
my friends are playing with a 350(without Thaumcraft), I tried to upgrade to the 356 and appeared crash as my 357.
but I have 356 and works.
maybe the reason is in the config files of the mod?

**Comment by FoxPotato** [comment]
wait, are you people playing on the same server? Because maybe the best idea then is to downgrade to 350..
And could you perhaps show me the log from 356 where you don't need thaumcraft but do need applied energistics?

**Comment by SvEgiiVEteR** [comment]
I sometimes play with them. 
I decided to upgrade them to a server(v350) mod. 356 and 357 were not working. caused crash as above.
I left them 350(only works with appliedenergistics2)

on my server the latest is working 356(only works with appliedenergistics2), 357 only works with Thaumcraft + appliedenergistics2

config files .....can help....
https://dl.dropboxusercontent.com/u/26268735/ShareX/2016/12/darkmods.rar

**Comment by FoxPotato** [comment]
Wait, so if i read that correctly; your client mods are a different version than your server mods? please always try and have them be the same
(and configs shouldn't matter)

**Comment by SvEgiiVEteR** [comment]
no no ))
my friends own server. I have my own server.
I have two client: my and friends.
on my server 356 working and they have 350
and I tried to have them upgrade to the 356, but I couldn't.
there was a crash as above.

mod on version 357 is not working without the other two mods.
it's not scary.. can I install Thaumcraft and appliedenergistics2 :)
but I understand you, this is not supposed to be.

sorry for bad English.

UP

if (and configs shouldn't matter), my friends have no Thaumcraft on the server(but a lot of other mods). maybe this error they had on the 356, so a lot of mods.. and maybe a conflict

when I checked 356 version, I only have 3 of the mod:
appliedenergistics2-rv2-stable-10.jar
darkcore-0.45-255.jar
tardismod-1.7.10-0.995-356.jar
and everything is OK.
357 does not work without Thaumcraft.
only:
appliedenergistics2-rv2-stable-10.jar
darkcore-0.45-255.jar
tardismod-1.7.10-0.995-356.jar
Thaumcraft

**Comment by DarkholmeTenk** [comment]
Ok, just to clarify, the most recent version of TM from the jenkins has some weirdness with dependencies. Go back a single version and that should fix your problems.

**Comment by SvEgiiVEteR** [comment]
@DarkholmeTenk 356 doesn't work without Thaumcraft
I'm sitting on 357 with
appliedenergistics2
Thaumcraft
and everything is OK

PS
and you can make a support appliedenergistics2 RV3 beta 6(without removing the support rv2)

my friends want RV3, and I don't want to remove your mod. Tardis I like very much.

**Comment by shadowbolt79** [comment]
#589 seems to be the same issue as this one.

**Comment by DarkholmeTenk** [comment]
Should be fixed with #589
