### ISSUE TITLE
Tardis Biome Options

### ISSUE THREAD

**Issue by Flexico** [DarkholmeTenk/TardisModIssues#586]
It appears that the ID for the Tardis biome conflicts with a Twilight Forest biome. And there's nothing in the config files to change it! I mean, I can change the Twilight Forest config, but then I'd have to re-generate my entire TF dimension, verses just fixing my Tardis interior in MCEdit.

Also, I thought a neat idea would be the ability to customize your grass/tree color within the Tardis biome, such as making the grass red to look like Gallifrey. I'm sure there's a way to do this with resource packs, but if it were implemented each Tardis could have a different color scheme.

**Comment by DarkholmeTenk** [comment]
Well "Console Room Dimension ID" (while badly named @FoxPotato) appears to control the biome id. As for fixing the biome of your tardis, probably not easily possible.

Changing biomes probably not going to be possible within the mod
