### ISSUE TITLE
Roundel Options

### ISSUE THREAD

**Issue by Flexico** [DarkholmeTenk/TardisModIssues#588]
In the config file, there are options to control just how roundels behave when connected with various other mod systems, such as item/liquid/energy transfer. However, they don't seem to actually have any effect. "Number of internal inventory slots:I:30" seems to give the internal item storage 30 slots, but testing tells me there is only one. "RF output per tick:I:4096" doesn't seem to have any bearing on the max energy output either. (I'm only able to reliably test energy flow using the IC2 EU Reader, so that's how I tested.) I set the RF output to 32,000 (which corresponds to 8,000 EU/t), but it only output exactly 2,048 EU/t. (tier 4 power).

Are these options a WIP or have they worked previously?

**Comment by DarkholmeTenk** [comment]
They all work:

Items cannot be in multiple slots (i.e. you can have a slot for cobble, a slot for stone, etc, but you can't have 2 slots for cobble), as it's meant to be for item transfer not item storage.

RF output does vary, however IC2 controls its own energy transfer and that is restricted to the power levels.

**Comment by Flexico** [comment]
Oooohhhh, ok, that makes sense. Thank you.
