### ISSUE TITLE
SEVERE tardis ownership somehow transferred accidentally

### ISSUE THREAD

**Issue by Aaronstar-McClure** [DarkholmeTenk/TardisModIssues#592]
tardis ownership somehow transferred accidentally while trying to repair it with commands, i now have two tardises

**Comment by FoxPotato** [comment]
Could you perhaps be a little more specific how you managed it, i.e. step by step guide, perhaps some screenshots :p 
thanks for telling us tho, this does sound interesting

**Comment by DarkholmeTenk** [comment]
/trep does change the owner.

Try /trep [worldID] [newOwner] 0 0

**Comment by Aaronstar-McClure** [comment]
well, this guy on my server was flying his tardis before he got stabilizers, and his game crashed because of tardismod. when he got back on, his tardis had crashed because of damage. i considered this to be sufficient reason to repair it so i tried to repair it with commands, it did not work, and now i had two tardises, (it later became three) i have now decided to remove tardismod for the time being because of all its problems and because i cannot update it (and because of poor documentation on the commands). if you want to take a look at my pack before i remove it, it can be found on technic with http://api.technicpack.net/modpack/ghastcraft-server-pack

**Comment by FoxPotato** [comment]
Did you perhaps try to repair his tardis using the /trep command? because that would explain your problem tbh. You can repair their tardises by just giving them the materials needed. I think it's like 4 dalekanium 4 chronosteel and 1 kronon crystal. Don't quote me on that tho :P

**Comment by Aaronstar-McClure** [comment]
i thought the command would be easier considering how many items are in my pack and how laggy nei and creative inv is for me...

**Comment by FoxPotato** [comment]
the command would be easier if it did actually repair the tardis. You can transfer the ownership back to the users using that command though.

**Comment by Aaronstar-McClure** [comment]
well it is for more reasons then that that i am removing it...

**Comment by DarkholmeTenk** [comment]
Trep is a debug command used to fix tardises when developing. If you want to cheat fix the engine you can just right click all the bobbles in creative mode, if I remember right.
