### ISSUE TITLE
[Questions]Open Source

### ISSUE THREAD

**Issue by ghost** [DarkholmeTenk/TardisModIssues#594]
- Are we allowed to make an addon for this mod using the source code for the tardis mod that was posted?
- Is making an addon with the source code compatible with current versions of the mod used?

**Comment by FoxPotato** [comment]
iirc the master branch == latest version on jenkins. And of course you're allowed to make addons for the mod!

**Comment by AlienXtream** [comment]
just be sure to post a link on the forum page ;)

**Comment by ghost** [comment]
Is there certain features that I cannot add to the addon and instead put it in as a feature for the original mod because this mod is still adding features and I do not want to make a addon that later has the features in the original mod.

**Comment by AlienXtream** [comment]
the only planned feature i am aware of at this time is the "magic doors" (the things that teleport you around inside the tardis) might be getting the ability to be looked through, think portals from valve's popular FPS puzzle game. this isnt a promise of that feature however as it is a rather taxing thing to render if not done as efficiently as possible and is quite challenging to achieve in MC from what i understand

**Comment by Aaronstar-McClure** [comment]
hey, this might help with figuring out the rendering of magic doors... https://youtu.be/oGRRCR2oJxo

**Comment by Mrdrewlego** [comment]
Sorry for the long reply had account issues. Thank you for your responses. I will now close this.

**Comment by ghost** [comment]
Are we allowed to show clips of what we are working on with the addon on youtube, etc. Additionally my original account has been deleted and I am currently using a separate account and cannot close this thread.

**Comment by DarkholmeTenk** [comment]
You can do whatever you want with content you make.
