### ISSUE TITLE
Command to automatically recall TARDIS?

### ISSUE THREAD

**Issue by comus777** [DarkholmeTenk/TardisModIssues#598]
I just lost several hours of work after I accidentally teleported my TARDIS to the void in a Thaumcraft dimension, where it's permanently destroyed and lost forever. Could you implement a command that summons back the TARDIS to the player without needing to progress through the flight level system?

**Comment by shadowbolt79** [comment]
There's a tardis recaller block which should work regardless. It's made with iron, stone, and a lapis, I think.

**Comment by comus777** [comment]
I was completely unaware of that. Thanks!
