### ISSUE TITLE
Bug with changing Minecraft username and TARDIS ownership

### ISSUE THREAD

**Issue by comus777** [DarkholmeTenk/TardisModIssues#600]
It seems like the TARDIS tracks based on username rather than user ID. After I changed my name I found that I could no longer access my old TARDIS and now am stuck with a blank slate after hours of work.

**Comment by FoxPotato** [comment]
Iirc this was changed some time ago, but apparently not...
Use the /trep command to reassign the TARDIS to you

**Comment by comus777** [comment]
I can't figure out how to use the trep command, all I see in the log is repairing TARDIS and nothing happening ingame.

**Comment by FoxPotato** [comment]
do you know the TARDIS dim id? Use /ttp [id] (I think that was it atleast) to teleport to said TARDIS. Then use the /trep command again
