### ISSUE TITLE
Odd bug with TARDIS recall block?

### ISSUE THREAD

**Issue by comus777** [DarkholmeTenk/TardisModIssues#601]
So, I've seem to run into a hell of an oddity of a problem with the TARDIS recall block. 

It seems like I can now use 2 completely separate TARDISes at once. Both have completely different interiors (the one that the recall block summons is completely empty, the one that it doesn't is my main TARDIS containing my base), and I have no issues entering either, in fact WAILA lists me as the owner of both

![2017-03-16_23 38 14](https://cloud.githubusercontent.com/assets/25848267/24004813/4b607ec2-0aa2-11e7-8e0a-2ef72487644c.png)

Any way I can fix this? I use the recall block pretty often so this is annoying as hell.

**Comment by comus777** [comment]
Right, so after doing some tests, I'm slowly figuring out the problem. 

It seems like, through some glitch with the permissions, I now own the blank slate TARDIS, and I have permission to access the main TARDIS despite me being the only player in the world. 

So is there any way I can reset all TARDIS permissions for the world, in order for me to get back the main TARDIS?

**Comment by AlienXtream** [comment]
/treg has a bunch of functions that may help. i cant quite remember how to use it but it should tell you if you just type that. do note you might need to enable cheats to use the command which you can do by opening the game to lan and enabling cheats :)

**Comment by comus777** [comment]
Managed to do it, turns out my main TARDIS was registered to my old username which I changed, and my new username was registered to the blank TARDIS. Cleared all perms for my new username and then /trep on the main TARDIS solved the problem. 

Thanks!
