### ISSUE TITLE
Crash in server when loading schema

### ISSUE THREAD

**Issue by hitsounds** [DarkholmeTenk/TardisModIssues#605]
https://pastebin.com/9wPPZt1b

**Comment by AlienXtream** [comment]
dose this happen with all schemas or just a specific one? my first guess would be that the schema is missing the red door but i cant tell from the report

**Comment by hitsounds** [comment]
I think i have figured out the problem. At first i downloaded the schemas from foxpotato.com and when i opened the schema file in notepad it gives me this: 
![foxpotato](https://cloud.githubusercontent.com/assets/17516655/24904325/0e478804-1ea8-11e7-84fc-b5033013db50.PNG)
As you can see the file is in English however it give me an error when i try to use it and says internal server error.
I later got the same schema from https://www.dropbox.com/s/09stozs1dflmewh/schemas.zip?dl=0 this gave me a file which looked liked this: 
![dropboxeoh](https://cloud.githubusercontent.com/assets/17516655/24904506/8a3092da-1ea8-11e7-8864-e7c0d6ea08c3.PNG)
This is not readable and works however the dropbox link did not contain all the schemas is there a way I can use both types.

**Comment by AlienXtream** [comment]
"This is not readable and works however the dropbox link did not contain all the schemas is there a way I can use both types." can you please clarify what you mean by "works"? for one the file should be like the first one and second, getting files from the internet is risky, even getting MC mods is not without its hazards (though the MCF team and the community do a very good job of minimizing it where possible)

**Comment by hitsounds** [comment]
As in when i put the second file in the schema folder I can actually use the schema in game without the error ("Internal server error") however the first file disconnects me from the server when i try to build it. The server does not crash it just dissconnects the user.

I know the 2nd file type works but I can't get the first file type to work with my server.

**Comment by TylorBane** [comment]
just to clarify, i know what he's talking about, i just started up a "small" server for me and a few friends, but all the costom schema i downloaded from foxpotato cause this same "internal server error" and disconect the client ALL of the ones i downloaded do this >.>

**Comment by DarkholmeTenk** [comment]
Oh, it's because of the files being gzipped or something.

**Comment by TylorBane** [comment]
??

**Comment by TylorBane** [comment]
but the schema files that the tardis mod are naturally generating look like the second one he posted

**Comment by TylorBane** [comment]
either way, how would one be able to use the files downloaded from fox tato again?
Because schema files that are download from fox tato currently dont work whatsoever.

**Comment by TylorBane** [comment]
or maybe, is it possible to convert the schema files i have downloaded into a format that is able to be read by the current version? im just trying to think of something right now.

**Comment by DarkholmeTenk** [comment]
Ok, should be fixed now. If you'd downloaded the files with wget or something, it would have worked, but the apache server told chrome it was a gzipped file, so chrome unzipped it.

**Comment by TylorBane** [comment]
ah i see, alright thank you ^^

**Comment by DarkholmeTenk** [comment]
Let me know if it's still broken!
