### ISSUE TITLE
Information

### ISSUE THREAD

**Issue by ologantr** [DarkholmeTenk/TardisModIssues#609]
Where can I get a build of the new console of this mod? Thanks in advance

**Comment by FoxPotato** [comment]
if it's not on jenkins the only other option is to build it yourself :p

**Comment by ologantr** [comment]
![2017-05-12_22 06 12](https://cloud.githubusercontent.com/assets/17688810/26014990/4b877326-375f-11e7-93a4-8b7a1b3c65e0.png)

What did I do wrong? Or is it broken?

**Comment by FoxPotato** [comment]
Might be that you didn't update darkcore or that the new console isn't actually available for use yet :p

**Comment by ologantr** [comment]
I updated darkcore and the same thing happened... Simply the console is unfinished, so I'll wait :P

**Comment by DarkholmeTenk** [comment]
It is currently hella unfinished
