### ISSUE TITLE
can i get the new link to the jenkins?

### ISSUE THREAD

**Issue by wackypocket** [DarkholmeTenk/TardisModIssues#612]
tardismod.com:8080 is not working for me is there a new link?

**Comment by DarkholmeTenk** [comment]
It's the same link, I just accidentally let tardismod.com expire, it'll be back once the changes propogate through (although you can force that by doing ipconfig /flushdns in windows)

FYI, darkhol.me darkcraft.io, foxpotato.com, tardismod.com all go to the same server so darkcraft.io:8080 would work fine too.
