### ISSUE TITLE
io.darkcraft.darkcore.mod.client.TextRenderer missing

### ISSUE THREAD

**Issue by ologantr** [DarkholmeTenk/TardisModIssues#616]
I downloaded the TardisMod-newConsole branch , and there are some imports that cannot find TextRenderer, in fact it is missing.

**Comment by FoxPotato** [comment]
Seems dark hasn't pushed the most recent version of darkcore he's using for development

**Comment by DarkholmeTenk** [comment]
Well I just did so :P

**Comment by AlienXtream** [comment]
there's a new branch?! GIMME :P
