### ISSUE TITLE
Can't Spawn TARDIS

### ISSUE THREAD

**Issue by EmeraldTiger64** [DarkholmeTenk/TardisModIssues#625]
I was playing around in my world in Creative mode, and placed down a TARDIS. I later built a landing pad for the TARDIS to go on (and didn't want to go through the pain of putting the coordinates of it exactly), so I broke the TARDIS in creative. When I went to use the key to put it on the landing pad the key wouldn't work. Sometimes it would say "The key feels warm", but the TARDIS wouldn't appear. Can I please get some help with this?

**Comment by EmeraldTiger64** [comment]
I would also like to mention that when I put down another TARDIS in creative, it says that I already own one.

**Comment by FoxPotato** [comment]
One fix would be to /ttp to your TARDIS dimension and then move it and exit.
But I swear you should be able to cheat it in, apparently not tho :P

**Comment by EmeraldTiger64** [comment]
I was able to fix it. I uninstalled the TARDIS mod and deleted all files related to the TARDIS mod in the world file. Then I launched Minecraft and loaded into the world I was having problems with. Afterwards, I quit out of Minecraft, reinstalled the mod, and re-launched the game. Got into the world and discovered that this fix worked.
