### ISSUE TITLE
[ENHANCE] This one is probably impossible

### ISSUE THREAD

**Issue by FoxPotato** [DarkholmeTenk/TardisModIssues#63]
But i'm still gonna reuqest it, because you never know.
do you think it would be possible to register if a player is standing in the spot where the TARDIS is materializing, and thus allowing the player to be teleported in. Seeing as the recall function already spawns the TARDIS on top of you. (Which is kinda annoying)

**Comment by DarkholmeTenk** [comment]
I tried so hard to do this when I was writing the recall function; minecraft either tries to push you out of the block or suffocates you.
