### ISSUE TITLE
The world I used the Tardis mod in crashes on startup, crash report below

### ISSUE THREAD

**Issue by ghost** [DarkholmeTenk/TardisModIssues#635]
---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 3/17/18 7:49 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.client.renderer.entity.Render.func_110776_a(SourceFile:51)
	at JinRyuu.JBRA.RenderPlayerJBRA.func_82441_a(RenderPlayerJBRA.java:1955)
	at net.minecraft.client.renderer.ItemRenderer.func_78440_a(ItemRenderer.java:531)
	at net.minecraft.client.renderer.EntityRenderer.func_78476_b(EntityRenderer.java:736)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1361)
	at JinRyuu.JBRA.JBRAEnRen.func_78471_a(JBRAEnRen.java:23)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1015)
	at JinRyuu.JBRA.JBRAEnRen.func_78480_b(JBRAEnRen.java:62)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.renderer.entity.Render.func_110776_a(SourceFile:51)
	at JinRyuu.JBRA.RenderPlayerJBRA.func_82441_a(RenderPlayerJBRA.java:1955)
	at net.minecraft.client.renderer.ItemRenderer.func_78440_a(ItemRenderer.java:531)
	at net.minecraft.client.renderer.EntityRenderer.func_78476_b(EntityRenderer.java:736)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1361)
	at JinRyuu.JBRA.JBRAEnRen.func_78471_a(JBRAEnRen.java:23)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1015)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['Lukeatronio'/270, l='MpServer', x=-51.35, y=69.62, z=135.94]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-36,64,140), Chunk: (at 12,4,12 in -3,8; contains blocks -48,0,128 to -33,255,143), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 3594509 game time, 974502 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 76 total; [EntityClientPlayerMP['Lukeatronio'/270, l='MpServer', x=-51.35, y=69.62, z=135.94], EntitySpider['Spider'/143, l='MpServer', x=-9.38, y=12.00, z=168.50], EntitySpider['Spider'/144, l='MpServer', x=-0.28, y=12.00, z=172.56], EntitySkeleton['Skeleton'/145, l='MpServer', x=-15.06, y=12.00, z=182.47], EntitySquid['Squid'/147, l='MpServer', x=-5.41, y=56.19, z=196.69], EntitySquid['Squid'/148, l='MpServer', x=-14.19, y=46.66, z=198.50], EntityCreeper['Creeper'/22, l='MpServer', x=-115.50, y=109.00, z=112.66], EntitySpider['Spider'/23, l='MpServer', x=-113.97, y=15.00, z=149.84], EntityBat['Bat'/24, l='MpServer', x=-105.16, y=17.05, z=150.84], EntityCreeper['Creeper'/25, l='MpServer', x=-117.03, y=78.00, z=186.63], EntityCreeper['Creeper'/26, l='MpServer', x=-123.07, y=69.00, z=192.56], EntityCreeper['Creeper'/27, l='MpServer', x=-115.47, y=79.00, z=184.91], EntityRangedRogueAndroidMob['§7§7§7§7§7§7§7§7[0] Robbie'/28, l='MpServer', x=-112.28, y=80.00, z=187.50], EntityHorse['Horse'/163, l='MpServer', x=8.09, y=67.00, z=60.96], EntityCreeper['Creeper'/164, l='MpServer', x=9.41, y=36.00, z=140.31], EntityBat['Bat'/166, l='MpServer', x=15.24, y=13.28, z=141.28], EntitySkeleton['Skeleton'/167, l='MpServer', x=10.50, y=43.00, z=159.50], EntitySkeleton['Skeleton'/40, l='MpServer', x=-100.39, y=37.48, z=80.21], EntityZombie['Zombie'/168, l='MpServer', x=11.66, y=39.00, z=147.38], EntityBat['Bat'/41, l='MpServer', x=-105.66, y=15.10, z=147.53], EntitySkeleton['Skeleton'/169, l='MpServer', x=11.13, y=39.00, z=148.53], EntitySkeleton['Skeleton'/42, l='MpServer', x=-105.03, y=18.00, z=156.50], EntityCreeper['Creeper'/170, l='MpServer', x=5.13, y=11.08, z=175.70], EntitySkeleton['Skeleton'/43, l='MpServer', x=-99.50, y=22.00, z=159.50], EntityCreeper['Creeper'/171, l='MpServer', x=4.30, y=11.08, z=175.70], EntityBat['Bat'/44, l='MpServer', x=-110.69, y=55.10, z=154.31], EntityZombie['Zombie'/172, l='MpServer', x=3.30, y=11.14, z=174.70], EntitySpider['Spider'/45, l='MpServer', x=-97.72, y=26.00, z=189.81], EntityZombie['Zombie'/173, l='MpServer', x=13.63, y=17.00, z=154.05], EntityCreeper['Creeper'/46, l='MpServer', x=-110.50, y=24.00, z=185.00], EntityCreeper['Creeper'/175, l='MpServer', x=11.56, y=15.00, z=179.00], EntitySkeleton['Skeleton'/47, l='MpServer', x=-100.41, y=14.00, z=213.91], EntitySquid['Squid'/176, l='MpServer', x=11.44, y=51.97, z=184.19], EntitySquid['Squid'/177, l='MpServer', x=10.50, y=40.25, z=198.41], EntityCreeper['Creeper'/56, l='MpServer', x=-83.50, y=12.00, z=56.00], EntityCreeper['Creeper'/57, l='MpServer', x=-75.50, y=13.00, z=53.70], EntityHorse['Horse'/58, l='MpServer', x=-96.75, y=64.00, z=85.88], EntityHorse['Horse'/59, l='MpServer', x=-88.66, y=67.00, z=95.03], EntityHorse['Horse'/60, l='MpServer', x=-83.16, y=66.00, z=87.00], EntityHorse['Horse'/61, l='MpServer', x=-96.38, y=64.00, z=82.13], EntityBat['Bat'/62, l='MpServer', x=-81.00, y=14.83, z=161.90], EntityZombie['Zombie'/63, l='MpServer', x=-85.38, y=13.00, z=163.16], EntityZombie['Zombie'/64, l='MpServer', x=-91.38, y=14.00, z=162.69], EntityZombie['Zombie'/65, l='MpServer', x=-89.75, y=14.00, z=162.22], EntityBat['Bat'/66, l='MpServer', x=-92.75, y=44.10, z=178.75], EntityCreeper['Creeper'/67, l='MpServer', x=-94.38, y=11.00, z=215.97], EntitySkeleton['Skeleton'/197, l='MpServer', x=22.50, y=44.00, z=96.50], EntitySkeleton['Skeleton'/198, l='MpServer', x=21.50, y=43.92, z=92.66], EntitySkeleton['Skeleton'/199, l='MpServer', x=20.53, y=44.00, z=100.22], EntityZombie['Zombie'/200, l='MpServer', x=19.06, y=44.00, z=101.47], EntitySkeleton['Skeleton'/201, l='MpServer', x=17.50, y=19.00, z=119.88], EntitySkeleton['Skeleton'/202, l='MpServer', x=23.88, y=33.00, z=119.56], EntityPig['Pig'/203, l='MpServer', x=16.91, y=67.00, z=117.13], EntityZombie['Zombie'/78, l='MpServer', x=-78.97, y=12.00, z=57.53], EntityHorse['Horse'/79, l='MpServer', x=-79.78, y=68.00, z=108.94], EntitySkeleton['Skeleton'/80, l='MpServer', x=-64.88, y=30.00, z=165.47], EntityPig['Pig'/89, l='MpServer', x=-54.22, y=66.00, z=149.50], EntitySquid['Squid'/90, l='MpServer', x=-68.88, y=50.00, z=184.84], EntityCreeper['Creeper'/92, l='MpServer', x=-45.44, y=26.00, z=210.47], EntitySkeleton['Skeleton'/95, l='MpServer', x=-36.91, y=28.00, z=175.53], EntityZombie['Zombie'/96, l='MpServer', x=-39.19, y=25.00, z=182.69], EntityBat['Bat'/97, l='MpServer', x=-34.52, y=27.61, z=178.79], EntitySquid['Squid'/98, l='MpServer', x=-31.72, y=47.19, z=189.09], EntityZombie['Zombie'/99, l='MpServer', x=-39.91, y=26.00, z=213.66], EntityBat['Bat'/113, l='MpServer', x=-24.06, y=14.10, z=155.31], EntityBat['Bat'/114, l='MpServer', x=-28.56, y=15.10, z=148.75], EntityZombie['Zombie'/115, l='MpServer', x=-16.75, y=17.00, z=156.53], EntityCreeper['Creeper'/116, l='MpServer', x=-18.00, y=17.00, z=156.59], EntitySkeleton['Skeleton'/117, l='MpServer', x=-17.84, y=22.00, z=186.38], EntityEnderman['Enderman'/118, l='MpServer', x=-23.09, y=24.00, z=185.38], EntityZombie['Zombie'/119, l='MpServer', x=-25.92, y=27.00, z=180.61], EntityZombie['Zombie'/120, l='MpServer', x=-22.50, y=23.00, z=183.94], EntitySkeleton['Skeleton'/121, l='MpServer', x=-23.50, y=38.00, z=182.88], EntitySquid['Squid'/122, l='MpServer', x=-20.09, y=58.31, z=185.97], EntitySquid['Squid'/124, l='MpServer', x=-32.59, y=52.72, z=194.41], EntitySquid['Squid'/126, l='MpServer', x=-28.97, y=50.22, z=197.66]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 339712912 bytes (323 MB) / 1073741824 bytes (1024 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 31 mods loaded, 31 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJAAAA	AdvancedRocketry{1} [Advanced Rocketry] (minecraft.jar) 
	UCHIJAAAA	OpenComputers|Core{1.6.0.6-beta.4} [OpenComputers (Core)] (minecraft.jar) 
	UCHIJAAAA	TooManyItems{1.7.10} [TooManyItems] (minecraft.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	securitycraft{v1.8.2.2} [SecurityCraft] ([1.7.10] SecurityCraft v1.8.2.2.jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.1.4} [CoFH Core] (CoFHCore-[1.7.10]3.1.4-329.jar) 
	UCHIJAAAA	libVulpes{0.1.19.} [libVulpes] (LibVulpes-1.7.10-0.1.19-universal.jar) 
	UCHIJAAAA	advancedRocketry{1.7.10-1.0.4} [Advanced Rocketry] (AdvancedRocketry-1.7.10-1.0.4.jar) 
	UCHIJAAAA	ThermalFoundation{1.7.10R1.2.6} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.6-118.jar) 
	UCHIJAAAA	ThermalExpansion{1.7.10R4.1.5} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.1.5-248.jar) 
	UCHIJAAAA	BigReactors{0.4.3A} [Big Reactors] (BigReactors-0.4.3A.jar) 
	UCHIJAAAA	chisel{2.9.5.11} [Chisel] (Chisel-2.9.5.11.jar) 
	UCHIJAAAA	customnpcs{1.7.10d} [CustomNpcs] (CustomNPCs_1.7.10(feb16).jar) 
	UCHIJAAAA	dimdoors{2.2.5-test9} [Dimensional Doors] (DimensionalDoors-2.2.5-test9.jar) 
	UCHIJAAAA	jinryuujrmcore{1.3.4} [JinRyuu's JRMCore] (JRMCore-v1.3.4.jar) 
	UCHIJAAAA	jinryuudragonblockc{1.4.44} [Dragon Block C] (DragonBlockC-v1.4.44.jar) 
	UCHIJAAAA	ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.12 (3).jar) 
	UCHIJAAAA	jinryuubetterrenderaddon{1.6.27} [JinRyuu's Better Render Addon] (JBRA-Client-v1.6.27.jar) 
	UCHIJAAAA	jinryuufamilyc{1.2.15} [JinRyuu's Family C] (JFamilyC-v1.2.15.jar) 
	UCHIJAAAA	malisiscore{1.7.10-0.14.3} [MalisisCore] (malisiscore-1.7.10-0.14.3 (1).jar) 
	UCHIJAAAA	malisisdoors{1.7.10-1.13.2} [Malisis' Doors] (malisisdoors-1.7.10-1.13.2.jar) 
	UCHIJAAAA	mo{0.4.2} [Matter Overdrive] (MatterOverdrive-1.7.10-0.4.2.jar) 
	UCHIJAAAA	RadixCore{2.1.3} [RadixCore] (RadixCore-1.7.10-2.1.3-universal.jar) 
	UCHIJAAAA	MCA{1.7.10-5.2.2} [Minecraft Comes Alive] (MCA-1.7.10-5.2.2-universal (1).jar) 
	UCHIJAAAA	cfm{3.4.7} [§9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10).jar) 
	UCHIJAAAA	OpenComputers{1.6.0.6-beta.4} [OpenComputers] (OpenComputers-MC1.7.10-1.6.0.6-beta.4-universal.jar) 
	UCHIJAAAA	scprein{0.1} [SCP-Craft 2: Reincarnation] (SCP-Craft-2-Reincarnation-Mod-1.7.10.jar) 
	UCHIJAAAA	superMassiveTech{0.2.0-alpha} [Super Massive Tech] (Super-Massive-Tech-Mod-1.7.10.jar) 
	GL info: ' Vendor: 'Intel' Version: '3.1.0 - Build 9.17.10.4229' Renderer: 'Intel(R) HD Graphics 3000'
	CoFHCore: -[1.7.10]3.1.4-329
	ThermalFoundation: -[1.7.10]1.2.6-118
	ThermalExpansion: -[1.7.10]4.1.5-248
	Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
	Launched Version: 1.7.10-Forge10.13.4.1558-1.7.10
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 3000 GL version 3.1.0 - Build 9.17.10.4229, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by AlienXtream** [comment]
you can learn a lot about what caused the crash just by the first few lines even if you know NOTHING about programming

"at JinRyuu.JBRA.RenderPlayerJBRA.func_82441_a(RenderPlayerJBRA.java:1955)"
this crash is caused by another mod, not TM. it has nothing to do with TM in the slightest
