### ISSUE TITLE
question about licence and tardis console [Question]

### ISSUE THREAD

**Issue by Aaronstar-McClure** [DarkholmeTenk/TardisModIssues#637]
so i had the idea to re-create your tardis interior for a game called [VRchat](https://store.steampowered.com/app/438100/VRChat/) (This game lets players create and upload custom worlds) but i just wanted to make sure you were fine with it, because i would be using your textures and some block models. and if you dont want me to, i have not made much progress yet, so i can just delete it...

**Comment by Aaronstar-McClure** [comment]
so i figured out some problems with the console, first, the panels are fixed by changing the way unity renders the texture, but the four arms seem to be an error made by whatever program converted the model from a tcn to an obj. the y rotation was not converted...

**Comment by boot2big** [comment]
I know it's been over a year, but you probably shouldn't.
It's not your models and textures, and that probably wouldn't sit well with the owners of VRchat either.
Why not try to make your own instead?

**Comment by Aaronstar-McClure** [comment]
o, i forgot about this idea a long time ago...
