### ISSUE TITLE
1.7.10 Tardis mod (Tardis)

### ISSUE THREAD

**Issue by Josh65-2201** [DarkholmeTenk/TardisModIssues#638]
I accidently destroy my Tardis and I cant get it back the key and recall functions don't do any thing and when I try placing a Tardis it says I already have one.

**Comment by AlienXtream** [comment]
when you say destroyed do you mean that you have damaged it so it won't fly, broken the console blocks themselves or broken the exterior? for the first and last ones a recall block SHOULD do the trick. if the second try the admin command /trepair total (or something similar to that, i can never quite remember).

**Comment by Josh65-2201** [comment]
I destroy the exterior and non of the things you said work.

**Comment by AlienXtream** [comment]
try /ttp <dimensionID> to find your tardis dim you can use /treg list or if you have thermal expansion installed /cofh tps and look for the dimension labeled as "tardis interior" (i think thats what its named. been a while since i messed around in 1.7)

**Comment by MishaPlayer** [comment]
Assuming you're testing on a creative world and not about to ruin a good survival run, try spamming /tardisxp 100000 until the sonic screwdriver can recall the TARDIS.
Unfortunately, if this doesn't work then you'll have to remove the TARDIS from the registry.
