### ISSUE TITLE
1.7.10 tardis mod(V 0.995.365 crash)

### ISSUE THREAD

**Issue by Josh65-2201** [DarkholmeTenk/TardisModIssues#639]
When trying to use the latest version of the Tardis mod it crashes with this error.

Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: tardis/common/tileents/components/ComponentAspect

full crash report attached.
[crash-2018-09-08_11.48.01-client.txt](https://github.com/DarkholmeTenk/TardisModIssues/files/2363250/crash-2018-09-08_11.48.01-client.txt)

**Comment by HighwayStar54** [comment]
Same problem!

**Comment by AlienXtream** [comment]
install latest 1.7.10 version of thaumcraft fixes it iirc

**Comment by tonimark** [comment]
where do i find these versions , their websites are down or forbidden

**Comment by Josh65-2201** [comment]
usually it on http://tardismod.com:8080/job/TardisMod/ but it seems to be down
