### ISSUE TITLE
Ignore Please this is a thought bubble for me to put WIP Suggestions and my orignal Minecraft Forum

### ISSUE THREAD

**Issue by micmou** [DarkholmeTenk/TardisModIssues#64]
Tranquility Zone - Entire inside of the tardis prevents weapons from working

Siege Mode - Locks the tardis into a state of siege??? not to actually familiar as I am a classic who guy

Protocols - System for implementing some more advanced features IE Forcefield Extrapolation or Siege mode

Immortality Gate - Make yourself Invincible for a couple of minutes

Some GUI's For some things Like The Index File or for Coordinate Flight or Spatial Flight

Food Items - Fish FIngers, Jammie Dodgers, Jelly Babies

Perception FIlter - Player becomes invisible

Schematics + Workshop Scanner - Allows you to unlock the crafting of tardis items

Vortex Manipulator - Player Based Coordinate and Dimension Travel

Tardis energy to RF or UE energy - Does what it says on the tin(hard to get and such)

---In Progress of Implementation---

Easier to click tardis controls
More Sonic Functions

---Implemented Already---

Auto Pilot

---Implemented After suggestion---

---Fleshed out suggestions---

Statenheim Remote
Localized Spacial flight
Artron Energy and recharging zones
Junk Tardis
Home location
Companions
Emergency Program one
Pre-Built Rooms
Chameleon Circuit
Lazarus Device
More Sonic Functions
De-Mat Gun
51st Century Blaster
More Documentation

**Comment by FoxPotato** [comment]
Why post them again though? Atleast put an [ENHANCE] in your title for better categorization :p

**Comment by Valiec** [comment]
Good suggestions! I was just about to suggest pre-built rooms myself (including the Eye of Harmony, library, swimming pool). Should I wait for you to suggest it or just suggest it myself in detail?

**Comment by DarkholmeTenk** [comment]
Closing as it's not an issue on its own.
