### ISSUE TITLE
Tardis doesnt reach max speed

### ISSUE THREAD

**Issue by AetherDraco** [DarkholmeTenk/TardisModIssues#642]
Hi I was wondering if anyone had any clue how to help, my tardis' speed lever on reaches 7.3 ive tried restarting the game & changing the config but it doesn't do anything. Any help would be greatly appreciated!

**Comment by AlienXtream** [comment]
rooms reduce top speed iirc, which is intended funcionality.

**Comment by AetherDraco** [comment]
Ah thanks
