### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by UQuark** [DarkholmeTenk/TardisModIssues#643]
If TARDIS takes off from landing pad and some fluid is pumping out from the TARDIS, server crashes.
When chunk with taking-off TARDIS and landing pad loads again, server crashes.

**Comment by tonimark** [comment]
1.i am not the author but I think the real author abandoned the project
2.you should provide a crashlog

**Comment by AlienXtream** [comment]
indeed. this mod is no longer in developement. it is however open source iirc.

**Comment by UQuark** [comment]
So I wrote a fix for the mod and asked author for permission to distribute it. But his last activity on reddit was 2 years ago so maybe someone knows how can I contact him?

**Comment by DarkholmeTenk** [comment]
I am still active on reddit, even though I never post anything. Feel free to open a PR back to master, and I'll get back to you on distribution permissions.

**Comment by UQuark** [comment]
I've just created a pull request so I hope the issue is closed.
