### ISSUE TITLE
"Height limit for building is 128 blocks"

### ISSUE THREAD

**Issue by greengameplayer** [DarkholmeTenk/TardisModIssues#648]
"Height limit for building is 128 blocks" comes up whenever I try to right-click any block with any tool. I can't install any components back into the TARDIS either. By the way great mod devs, keep it up!

**Comment by AlienXtream** [comment]
im guessing your first language isnt english or you are getting this mod and the "new tardis mod" mixed up (that one is not made by Dark). either way, "back" into the tardis would require you to have removed them, which this mod does not permit. also, has nothing to to with this mod as to my knowlage nothing was changed with build hight, in fact i used to often build above 128 blocks. the vanilla limit is 256 but ive heard there is some sort of server setting that can lower it (but cant be higher than 256). as for keeping up the work? um... bit late on that one XD
![image](https://user-images.githubusercontent.com/12606809/64923181-d40ecd80-d81a-11e9-89a7-ce2803325c40.png)

yeh... this mod has been dead for a while now... sorry

**Comment by greengameplayer** [comment]
Yeah I did get it confused. And your solution of the server settings worked for me, it was set to 128. Thanks anyway!
