### ISSUE TITLE
Artron Battery

### ISSUE THREAD

**Issue by Xakorik** [DarkholmeTenk/TardisModIssues#65]
When I try to dismantle the block stays but I get an Artron Battery item with 0 charge.

I have only tried the Basic Artron Battery

**Comment by FoxPotato** [comment]
I don't know if it's because of an update. but it works fine for me? all 3 the batteries.

**Comment by DarkholmeTenk** [comment]
Can't replicate it myself either. Are you perhaps doing it in area with spawn protection somehow?

**Comment by Xakorik** [comment]
Shouldn't be but I'll check
