### ISSUE TITLE
Game Crashing

### ISSUE THREAD

**Issue by tescdon** [DarkholmeTenk/TardisModIssues#657]
I run a server on crazy craft 4 using the void wrath launcher when I used the Tardis key and I entered the Tardis my game crashed and any time I join the server again it crashes is there any way to fix this?

**Comment by AlienXtream** [comment]
are you the one that asked this on the NTM discord server? this mod has been dead for AGES. like, seriously... there's nothing that can be done on our end. only choice you have is to either ditch this mod or remove all mods BUT this one and add them back in small batches at a time, testing to see if it crashes, and if not add back a handful more. recommend you do it in halves. remove half the mods (adding/removing things that complain about dependencies). if it crashes still the problem mod is in that half. remove another half of the mods left until it stops crashing when entering the tardis. then add back half of the mods you last removed. keep doing this until you are down to just one mod that it works without but crashes if you add it.

**Comment by tescdon** [comment]
I just removed the Tardis mod and reset my player data as no one else on the server has a Tardis and it worked thank you for responding and im not the the one who asked this on the discord server
