### ISSUE TITLE
[BUG] Glass

### ISSUE THREAD

**Issue by FoxPotato** [DarkholmeTenk/TardisModIssues#67]
WHy does glass not have a texture? The TARDIS mod glass of course. numeral id = 546:6

**Comment by laz2727** [comment]
The texture is really hard to see.

2015-05-10 17:06 GMT+06:00 FoxPotato <notifications@github.com>:

**Comment by FoxPotato** [comment]
It's not really hard to see. it's quite clear.
can't miss the purple and black boxes.

**Comment by laz2727** [comment]
Oh, okay.

2015-05-10 17:09 GMT+06:00 FoxPotato <notifications@github.com>:

**Comment by DarkholmeTenk** [comment]
The 546 version isn't used anymore. It's a remnant from before I switched it to its own block and may be removed eventually.

**Comment by FoxPotato** [comment]
Don't forget to do it before the v1 update :P

**Comment by DarkholmeTenk** [comment]
I could just get rid of the block entirely; it's only used for the brown stripe thing which isn't used in any of the official rooms anymore.
