### ISSUE TITLE
[ENHANCE] roundels Tenthish console

### ISSUE THREAD

**Issue by FoxPotato** [DarkholmeTenk/TardisModIssues#69]
Shouldn't the roundels technically be yellowish? because of the lights and stuff in his TARDIS.
And please bring back the tentacle tings, loved those.

**Comment by DarkholmeTenk** [comment]
the tentacle things?

**Comment by Jwtc2000** [comment]
These things?
![Thing1](http://i.gyazo.com/4cb52fb95d5ed77a31ad6982c24cad6b.png)
or 
these things?
![Thing2](http://i.gyazo.com/c9539a0227c52326e1e621e6f1bef453.png)
 orrrrrrrrrrrrrrrrrrrrrrr
![Thing3](http://cdn23.us2.fansshare.com/photos/octopus/octopus-tentacles-tentacles-1803255191.jpg)

**Comment by FoxPotato** [comment]
The 3rd ones. Loved those in the series.
;p

I meant the pillar tentacle things. Idk why i said tentacle tbh.

**Comment by DarkholmeTenk** [comment]
Those are nearly impossible to do with blocks; they'd need a full model; I'm not even sure they'd work with the hexagonal room

**Comment by FoxPotato** [comment]
You had something that looked like before. I quite liked those tbh.

**Comment by Jwtc2000** [comment]
![Pillars](https://i.imgur.com/N70QdYo.png)

**Comment by micmou** [comment]
@Jwtc2000 Shots Fired :3
