### ISSUE TITLE
[ENHANCE] Console room dimensions.

### ISSUE THREAD

**Issue by FoxPotato** [DarkholmeTenk/TardisModIssues#70]
I tested out something a user said on minecraftforum. And it's true, the dimensions of the TARDIS console room are just barely the wrong dimensions. You cannot connect them. there is too much space for a med room between two tall lifts. too little space for a big room. not enough room foor either only med corridors or only small corridors

**Comment by DarkholmeTenk** [comment]
Fixed by adding more corridors
