### ISSUE TITLE
[BUG] Y coords

### ISSUE THREAD

**Issue by FoxPotato** [DarkholmeTenk/TardisModIssues#72]
With all the Y levers down you can actually travel to -2. by doing this you will land on 0 and replace bedrock.
Then if you travel back up, go to the x and z coords you landed. mine down, you can actually find a hole in bedrock.
might wanna fix that.

**Comment by DarkholmeTenk** [comment]
The -2 is due to the randomness of the coordinate guesser, it's impossible to get it below 0. There's already code that tries to move you to any open spot, but I suppose near bedrock that might not exist. I'll add a line of code to say if you end up at y=0, move up to y=1
