### ISSUE TITLE
Crash with NO Thaumcraft installed on entering tardis dimension

### ISSUE THREAD

**Issue by BakermanLP** [DarkholmeTenk/TardisModIssues#74]
Hello,

I tried to enter the Tardis dimension and got after some seconds a crash. Seems to be a problem with Thaumcraft, but there was no Thaumcraft installed. Here is the crash report:

http://pastebin.com/yXxTx7Sc

All information of the modpack can be found here:

https://github.com/BakermanLP/ProjectPhoenix/

Thanks for reading

Michael (aka BakermanLP)

**Comment by BakermanLP** [comment]
Thank you, worked!

**Comment by DarkholmeTenk** [comment]
:+1:

**Comment by BakermanLP** [comment]
BTW ... impressive fixing speed :+1:
