### ISSUE TITLE
[ENHANCE] Landing pads

### ISSUE THREAD

**Issue by FoxPotato** [DarkholmeTenk/TardisModIssues#76]
I'd love the ability t hide the block, like change it's texture. Or being able to have a block above it and the TARDIS still lands on that spot.

also maybe a way to increase the radius? maybe by placing an artron battery next to it? idk. just a bigger radius.

also maybe fix the still being able to miss the pad if it's above a lake :p

**Comment by DarkholmeTenk** [comment]
Landing pad on lake requires you to aim near the landing pad, same as a landing pad in the middle of the air.
