### ISSUE TITLE
Website or something for user-submitted schematics

### ISSUE THREAD

**Issue by DarkholmeTenk** [DarkholmeTenk/TardisModIssues#78]
Website where users can submit schematics they've created/download schematics other users have created.

Also would be a good way for me to save time and stick user created schematics into the mod.

**Comment by Xakorik** [comment]
Sounds good

**Comment by micmou** [comment]
Hmm are you looking for a place to host a site as we can do this off of our dedicated server? we have an e5 1260 v2 equivalent to 4770k and 64GB of ram.

You design it and we can host it or we could potentially design it with web press and avada

**Comment by FoxPotato** [comment]
didn't you already have a website?
http://darkcraft.io/
with a modpack even.

**Comment by DarkholmeTenk** [comment]
I have the hosting myself already, I just need to build a website for user schematics upload/download.

**Comment by Xakorik** [comment]
Doesn't need to be very complex, just categorize by type

**Comment by FoxPotato** [comment]
I think he means the website itself too. like the home and stuff.
the website isn't just gonna be schematics i think.

**Comment by DarkholmeTenk** [comment]
Done with The FoxPotato Project.
See https://github.com/DarkholmeTenk/The-FoxPotato-Project or http://foxpotato.com
