### ISSUE TITLE
[ENHANCE] Pre-Built Rooms

### ISSUE THREAD

**Issue by micmou** [DarkholmeTenk/TardisModIssues#79]
Include rooms that are pre-built. Some examples.

Lab - Make food an mod related items, Keep a information database on all creatures encounterd cross mod compatible chemical based refining system.

Library - Place to store Index File pages and volumes, alternative enchanter IE Enchanting Plus Style

Secondary Consoles - Obvious, Allow override and locking down essentially take over control, have a sync mod where if two people are living in the same tardis sync the control states to every console allowing tandem control separate

Workshop - Make repair items for tardis, create components and upgrades allows having to create upgrades an install instead of just unlocking.

Eye of harmony - Looks cool can be opened to allow excess energy to seep in (very Dangerous) huge boost of speed, Include the chamelon arch here as well.

Zero Room - Place seperated from the rest of existence pink in color big empty you can float, allows excess healing, cannot be modified, cure some specific issues.

Swimming pool - Obvious allows a place to call home.

Vault - Place to store things have cool mounts and display cases with a big door in the room for valuables.

**Comment by DarkholmeTenk** [comment]
A chemical refining system probably won't be implemented; it'll probably just stay in the Temporal Laboratory block; I may create a single use schematic which has an improved version or something though.

A library is just a room with book shelves; I don't see why you can't turn one of the existing rooms into a library with something like bibliocraft.

Secondary consoles would be very difficult given the way the mod works; having a console which can be in a possibly random position would make the getConsole function (which is used everywhere and just gets the block 2 blocks below the time rotor so is quick) really complicated and wouldn't be particularly nice.

A workshop might be created eventually, but for now I'm going to stick with the unlocking and temporal laboratory.

Eye of harmony is planned on its own; chameleon arch definitely won't be added. I'm pretty happy with how the speed system works but I may make it generate artron energy faster or something similar.

Can't see much point in a zero room and preventing people from modifying it is next to impossible; if I do decide to add it, it'll just clear status effects.

Pool is easily creatable; will get done eventually, if someone doesn't beat me to it.

Vault is esentially just a big room with armor stands and stuff; definitely user creatable with one of the existing schematics.

**Comment by micmou** [comment]
Did you see the tidbit added to the library though

**Comment by DarkholmeTenk** [comment]
the enchanting thing? that's for other mods to do/players to build. Seems a bit cheaty to just give players enchanting for nothing.

**Comment by FoxPotato** [comment]
He also said he didn't see a use for the zero room. seeing as he already has nanogenes.
And what micmou suggested, with disseases or something.
that would mean to add things that aren't too much TARDIS oriented.
I think atleast.

**Comment by micmou** [comment]
Library - Place to store Index File pages and volumes


Hadnt gottent to sorting out that suggestion yet hehe
