### ISSUE TITLE
[ENHANCE] Lazarus Device

### ISSUE THREAD

**Issue by micmou** [DarkholmeTenk/TardisModIssues#81]
Allow us to change temporarily into other players skins or into animals similar to the morph mod.

restrict Item use and armor showing as a non default player skin IE Pig

**Comment by DarkholmeTenk** [comment]
Not going to implement this since I'm trying to keep the mod focussed on TARDISes rather than just Dr Who stuff.

**Comment by micmou** [comment]
Actually is a device inside of later model tardises to help timelords assimilate on observation

**Comment by DarkholmeTenk** [comment]
If you suggest a type 102 or 103...

**Comment by micmou** [comment]
No sir I suggest a type 105
http://www.whoniverse.net/tardis/105form

Complete With all the fixins if you would like me to flesh it out for you :D

**Comment by FoxPotato** [comment]
Why would you have a TARDIS meant for war (with which is freaking conscious) in a game about mostly exploring?

**Comment by micmou** [comment]
@FoxPotato considering your reaction you read the page

**Comment by FoxPotato** [comment]
Well yeah, I've started reading up some more on the TARDISes :p
