### ISSUE TITLE
[ENHANCE] More Sonic Functions & Improvements

### ISSUE THREAD

**Issue by micmou** [DarkholmeTenk/TardisModIssues#82]
more sonic functions and improvements including
A upgrade system Using the lab and workshop rooms

Break Glass support for mod added stuff as well

Interact with Redstone mod items and such

Thaumcraft wand and focus support

Scanning life forms for the Library database on entities

**Comment by DarkholmeTenk** [comment]
Maybe; I need to rework how you select screwdriver modes before that becomes viable. Also, the screwdriver isn't going to become a thaumcraft wand.

**Comment by micmou** [comment]
Aww Shots Fired

Understandable That would be alot of Shift Right Clicking

**Comment by epicnesslol** [comment]
mah god has everyone forgotten why its this popular...OPENING DOORS
(only iron)
