### ISSUE TITLE
[ENHANCE] De-Mat Gun

### ISSUE THREAD

**Issue by micmou** [DarkholmeTenk/TardisModIssues#83]
A admin item or high tier player item that in admin state deletes players tardises and in 

(optional of course) player mode gives them a condition where the are phasing in and out of time and they must fix it in the zero room with a chemical from the lab

Makes mobs disappear without drops

**Comment by FoxPotato** [comment]
I thought Dark said somewhere on mcf that he wasn't gonna add the de-mat gun, because he wanted to focus on the TARDIS itself. But with these functions his mind might've changed.

**Comment by DarkholmeTenk** [comment]
Not going to implement this since I'm trying to keep the mod focussed on TARDISes rather than just Dr Who stuff.

**Comment by micmou** [comment]
Hmm I have a feeling that he has this statemented saved somewhere especially for me so he can copy paste it XD

Dont worry I have some specific tardis features to suggest I have also read the comics and Books and we will see about a war tardis

**Comment by FoxPotato** [comment]
"we will see about a war tardis" what? you mean like the TARDIS of the war doctor? or a TARDIS meant for war. which probably existed during the time war.

**Comment by micmou** [comment]
@FoxPotato A tardis meant for literal war during rassilon's reign the time lords were more premescuisus with the use of weaponry. IE The Moment, Glove of Rassilon, De-Mat gun

But if it is a Tardis specific thing he requests a tardis specific item he will receive.

**Comment by FoxPotato** [comment]
yeah but, we're not at war. there aren't any mobs at war right now. Even if you have 2 people with a TARDIS, a war TARDIS isn't of any use.
