### ISSUE TITLE
[ENHANCE] 51st Century Blaster

### ISSUE THREAD

**Issue by micmou** [DarkholmeTenk/TardisModIssues#84]
Similar to portable black hole form thaumcraft makes a temporarily predefined hole to the other side.

Thaumcraft support recipe to use the portable black hole

**Comment by DarkholmeTenk** [comment]
Not going to implement this since I'm trying to keep the mod focussed on TARDISes rather than just Dr Who stuff.

**Comment by micmou** [comment]
Fair enough In this case
