### ISSUE TITLE
[ENHANCE] More Documentation

### ISSUE THREAD

**Issue by micmou** [DarkholmeTenk/TardisModIssues#85]
In-Game Wiki called the Index File
Most collect or make after leveling Information on the tardis mod and parts and all information is stored in the form of Crystal Clusters in the library

On-line wiki that has basic information and setup info no Spoilers :D

**Comment by DarkholmeTenk** [comment]
The online info source is definitely going to happen eventually; with exams, I don't have time to do a new website right now.

Ingame info is a maybe; I'm allergic to guis.

**Comment by FoxPotato** [comment]
If you manage to do stuff without GUIs it's more impressive in my opinion

**Comment by Soyaro666** [comment]
just noticed this is still open. I guess the library is an extensive documentation, isn't it?

**Comment by DarkholmeTenk** [comment]
Fair point

**Comment by micmou** [comment]
@Soyaro666 That would be correct

**Comment by Soyaro666** [comment]
"would be" sounds like you're unsatisfied with the library. Am I right? And if yes, whats the problem?

**Comment by FoxPotato** [comment]
Maybe bc it has all information ready instead of the crystal idea.

**Comment by DarkholmeTenk** [comment]
Overanalyzing Mode Activate!!

**Comment by FoxPotato** [comment]
Wooh \o/
