### ISSUE TITLE
[ENHANCE] Statenheim Remote

### ISSUE THREAD

**Issue by micmou** [DarkholmeTenk/TardisModIssues#86]
A device that has to be installed into the engine or engine room that will allow the tardis to be remote called under auto-pilot conditions to the player or companion. As it requires no experience to fly an auto-pilot tardis the companions can use the remote as well doctor must give them one and if they are to be remoted to either by them selves must have an locator. Doctor has no need as it is telepathically linked companions are traditionally not linked.

**Comment by DarkholmeTenk** [comment]
I'm already pretty happy with the recall working from the screwdriver; it's simple and doesn't require me to carry around an extra device, it's already been shown that flight can be used to cause the console to do stuff.
I may use the idea of installing stuff into the engine in the future, though :P

**Comment by micmou** [comment]
Yay so that is a maybe. I like the remote as it is more lore friendly maybe adding it where you can upgrade the Sonic with a remote

**Comment by FoxPotato** [comment]
well what i got out of it, it's not a maybe for the remote. but a maybe for being able to modify the engine.
It seems the sonic recall function will stay.

**Comment by micmou** [comment]
@FoxPotato Dont ruin my moment D:

**Comment by FoxPotato** [comment]
that's what i live for ;D
(jkjk)
