### ISSUE TITLE
[ENHANCE] Localized Spacial flight

### ISSUE THREAD

**Issue by micmou** [DarkholmeTenk/TardisModIssues#87]
A way to fly the tardis without De-Materialization Re-Materialization.

Possibly similar to the Doctor Who Client Mod. Maybe see if TheIking will allow you to use and implement the smart moving api.

**Comment by DarkholmeTenk** [comment]
The problem with this is that navigating without actually being able to see the outside could be very very difficult :P
Also, modifying the flight code to do this would require a massive rewrite.

**Comment by micmou** [comment]
Well you could always use a GUI :P

**Comment by DarkholmeTenk** [comment]
https://www.youtube.com/watch?v=znGBU5oODz8

**Comment by FoxPotato** [comment]
omfg

**Comment by laz2727** [comment]
You can always use the usual coords interface.

2015-05-12 20:22 GMT+06:00 FoxPotato <notifications@github.com>:

**Comment by FoxPotato** [comment]
I don't really see the use of this if you can't see the outside.
If you can't see the outside it would just be like the normal travel for you, only slower.
It would only look cool for the players outside, So why would you use it in singleplayer?

**Comment by laz2727** [comment]
Because it will explode less​ or something. My balance isn't very strong.
