### ISSUE TITLE
[ENHANCE] Junk Tardis

### ISSUE THREAD

**Issue by micmou** [DarkholmeTenk/TardisModIssues#89]
A tardis console that is on the outside of an interior that will allow limited spatial fly and not last forever used incase of eye of harmony destruction to still get places and reconstruct the interior

**Comment by spannerman79** [comment]
This isn't the plugin Tardis-Xern

**Comment by micmou** [comment]
Had to google what that is, and I had no idea that this ever existed. If I am copying somebody else's ideas it is not intentional most of these things are of my own design or referenced from the show.

**Comment by DarkholmeTenk** [comment]
Spatial flight isn't something I'm going to be implementing any time soon and dematerialising an exterior with a player in it sounds annoyingly difficult.

Also, moving large numbers of blocks around is a massive lag causer; see WarpDrive.

**Comment by micmou** [comment]
Fair point for it also there would be no more blocks than a console also see Tardis-Xern I will post video once i find one
