### ISSUE TITLE
[ENHANCE] Home location

### ISSUE THREAD

**Issue by micmou** [DarkholmeTenk/TardisModIssues#90]
A place to set as the home location for the companion Emergency program one and in case of doctor death you have your tardis during an emergency recall.

Allows either player to define with locator or operator to define at companion addition and can be changed

**Comment by DarkholmeTenk** [comment]
There are already bookmarks; good use of those can easily fill that purpose.

**Comment by micmou** [comment]
Hmm true I guess but the companion thing would be awesome and cool and tardis related as it deals with who can control and utilize aspects of the tardis
