### ISSUE TITLE
[ENHANCE] Companions

### ISSUE THREAD

**Issue by micmou** [DarkholmeTenk/TardisModIssues#91]
Allow players to be companions that either have not earned the ability to be time lords or do not wish to.
Links with Emergency Program one and allows them to set there home location in case of operator death it will take them to there home then take the tardis to the operators home

**Comment by DarkholmeTenk** [comment]
Not going to implement this since I'm trying to keep the mod focussed on TARDISes rather than just Dr Who stuff.

**Comment by micmou** [comment]
Companions are part of the tardis systems and allow more complex bits of it

**Comment by micmou** [comment]
Dark do you see the merit in the system and usefullness as a tardis feature?

**Comment by FoxPotato** [comment]
"But the companions are more of a dr who thing; this is dependant on that"
tbh, the fact he has ignored all the talking probably means that he 1, either is far too busy with his elder scrolls or 2, his opnionion hasn't changed
not trying to be a party pooper, I'd love to stop people from using my console. But he said no, and that probably won't change anytime soon.
sorry :/ 

(Of course I'm not Dark, And I'm sorry if I'm saying stuff that's not true)

**Comment by DarkholmeTenk** [comment]
Not trying to ignore conversation, had an exam which I'd missed all the lectures for, had to cram.

Adding a specific companion system isn't something I want to do; flying a TARDIS isn't something which requires you to be a time lord to do, see Tasha Lem, River Song, Donna Noble, etc. Locking down the console is a pain in the backside to implement, but I may eventually get around to it.

Emergency programs which trigger automatically could get annoying, so I'm a bit reluctant to implement that. Maybe if you're carrying a valid control disk, but it's not something I'm committing to yet.

**Comment by FoxPotato** [comment]
In blink the program wasn't automatic, Sally had to put in a CD :p

**Comment by micmou** [comment]
@DarkholmeTenk all of the people you listed are not lower life forms though Donna was modified somehow dont quite remember River Song... Is a time lord and Tasha Lem is part dalek. It is very hard to beat me at Doctor Who Lore and trivia :P

**Comment by DarkholmeTenk** [comment]
Donna definitely flew it before she became part time lord. Tasha heavily implied she could fly it before becoming part dalek.

**Comment by FoxPotato** [comment]
And couldn't adric fly the TARDIS too?
And donna didn't fly the TARDIS before she became part timelord. The second doctor helped her.

**Comment by FoxPotato** [comment]
I'm quoting Tasha here:
"Flying the TARDIS was always easy, it's flying the Doctor I never quite mastered"
So yeah she could fly the TARDIS before she became a dalek, can she even acces the dalek databanks in her?
(I literally just watched this scene on netflix just to quote it, and i need to download the ost again. I frickin' love the music in doctor who)

**Comment by laz2727** [comment]
Tasha is a head of the future church, and River was genetically modified by
Tardis. There are a couple of reasons why one human can't fly the tardis,
but the main ones are that tardis is normally controlled by 6 creatures
that can think in 11 dimensions and because it has to be bound to a
timelord first.

**Comment by FoxPotato** [comment]
wait, timelords can think in 11 dimensions? or can 5 think in 2 and 1 only think in 1?

**Comment by micmou** [comment]
No every time lord can think in 11 Dimensions the issue with humans or other lower life forms is that they cannot usually survive the stresses with the Time Vortex but ones that survive have an immunity after a while. And time lords do not become time lords until they have a Symbiotic Nuclei Printed on to there genetic info in the Matrix not every time lord can fly a tardis until this is done

Although they have defined these rules a long time ago they still make continuity errors here and there also only on timelord is bound per tardis the other 5 people are usually system specialist that maintain the interior during flight no original Console has been exhibited that show the system controls only one actually flies the tardis via his panel then 5 others make sure it works under normal conditions

@FoxPotato Adric was a child that could calculate coordinates into negative space you could argue that his math is superior to that of time lords because time lords cannot even calculate that... 
So adric is not a lower life form arguably superior if that. 

@laz2727 That actually isn't the main issue the stress of the time vortex is as in reality only one Time Lord actually flies a tardis

@DarkholmeTenk According to Orla Brady, Tasha is mostly human but has some alien ancestry as well.
Therefore not lower life form dona had help as well. Also they break there own rules with who can fly a tardis from time to time. 

It would also allow a system where not just anybody can enter the tardis and wouldn't be that hard think of it like a social system

**Comment by FoxPotato** [comment]
I wouldn't call "minecraftians" or however people call 'em these days lower life forms tbh. I mean, I've build a portal that can take me to other worlds. Built massive reactors on my own. Went to another galaxy. Heck, even mastered some magic.
I wouldn't call that a lower life form ;p

**Comment by micmou** [comment]
@FoxPotato You sir are a buzz kill

But I see what your getting at and even though there Micraftians I still see them as humans. SOme humans have done all of this and more.

And some humans in doctor who have manged things like resurrecting kronos to so eat my shorts

**Comment by FoxPotato** [comment]
u wot m8
Well tbh, humans have a tendency to get things working. Didn't they use the TARDIS once to make a time machine, with limited reach yes. but it still got working.
And I wouldn't call minecraftians humans, I wouldn't even put them together in 1 race.
They may be humanoid but No one is alike, some are animals. Others are aliens. 
So I think people should be capable of flying the TARDIS.

**Comment by micmou** [comment]
@FoxPotato 

I petition to have your name changed to Buzzkillington XD

**Comment by FoxPotato** [comment]
no thank you, that would spoil my true intentions to people xD
