### ISSUE TITLE
[ENHANCE] Emergency Program One

### ISSUE THREAD

**Issue by micmou** [DarkholmeTenk/TardisModIssues#92]
A interface that explains that the tardis operator has been damaged to people currently in the tardis if there is no one it does not activate 

Toggle able so if you know you are going to die IE blood altar that he does not appear and recall the tardis 

order of jumps - first to friends set location and if they do not have one to your or expels from tardis option

**Comment by DarkholmeTenk** [comment]
Not going to implement this since I'm trying to keep the mod focussed on TARDISes rather than just Dr Who stuff.

**Comment by micmou** [comment]
It is a tardis specific thing it is only a tardis feature as far as I know

**Comment by DarkholmeTenk** [comment]
But the companions are more of a dr who thing; this is dependant on that

**Comment by micmou** [comment]
It is a cool feature than can be either way and if you wanna get real technical about it.

A tardis usually requires a crew of 7 one master operator and six other speciality operators the tardis allows the entrance of up to six operational timelord units the doctor in the comics has stated the reason that he can have companions is he changed the system that recognizes companions and that the Emergency Program One was initially created for mission failure not operator death so it is according to cannon an explicit function of the tardis that the doctor has fiddled with to meet his needs.

I might argue this until the end of time this is one of the coolest things I can think of so 
pew pew

**Comment by FoxPotato** [comment]
The end of time was 6 years ago.
Even tho I'm also for a companion option, there is no use for this?
I mean, we're in minecraft and people just respawn. ._.

**Comment by micmou** [comment]
@FoxPotato that is the issue with it that we respawn say your 10000 blocks away it would be nice for it to take or boot people out and return home

**Comment by FoxPotato** [comment]
Well yeah that can be a problem, which i've experienced myself. But then make the sonic screwdriver soul bound or something :p

**Comment by micmou** [comment]
@FoxPotato But you see the merit no?

**Comment by FoxPotato** [comment]
I do, It's just, emergency program 1 is made so that companions can be sent home. But there are no companions in this mod so you might as well find an easier way to fix the problem :p

**Comment by micmou** [comment]
But I am not suggesting NPC companions other players will be your companions...

**Comment by FoxPotato** [comment]
I know,  never suggested NPC companions. I just stated the fact that there is no option to have companions in this mod.

**Comment by micmou** [comment]
Well there can be if he adds them

**Comment by FoxPotato** [comment]
"Not going to implement this since I'm trying to keep the mod focussed on TARDISes rather than just Dr Who stuff."

seeing as he posted this on the companions suggestion, I guess it won't be added.

**Comment by micmou** [comment]
Well if he reads this issue he will understand the greatness of it :D it is a tardis feature which is why I push it so much :P

**Comment by FoxPotato** [comment]
"But the companions are more of a dr who thing; this is dependant on that"
just quoting Dark

**Comment by micmou** [comment]
Well they are specifically a function of the tardises mental and social circuits that allows multiple crew members so it is a dr who thing but it is an explicit feature of the tardis...

**Comment by DarkholmeTenk** [comment]
But the emergency program is manually triggered iirc; as I said in the companion issue, I may get around to it eventually, when I have time, but I'm not going to say "I'm going to do this", so I'll keep it closed but mark it as enhancement to make sure it's noticable.

**Comment by micmou** [comment]
Yay at least that is better than no :D

**Comment by Soyaro666** [comment]
If the timelord (tardis' owner) dies the tardis could automatically start to a preset position (at least as soon as there's enough energy to reach that destination). that preset position could be done by one special bookmark button (maybe an aditional button near the bookmark panel) or simply sets itself to owners spawnpoint or the overworld spawnpoint. And the function (or it's activation button) could be unlocked depending on tardis' level or being added by an upgrade for #187 ?
