### ISSUE TITLE
[ENHANCE] Open Source

### ISSUE THREAD

**Issue by micmou** [DarkholmeTenk/TardisModIssues#93]
Actually put code on your github for us to gander at its magnificence oh great shane.

**Comment by DarkholmeTenk** [comment]
Eventually.

**Comment by ruifung** [comment]
Who needs open source when you can run it through a decompiler!
(with cross references to SRG files)

=P

**Comment by micmou** [comment]
@ruifung That is good if you are going to do nothing with it except gawk at it. But with open source we can help him out and fork it legitmatley...

**Comment by ruifung** [comment]
I was being sarcastic.
