### ISSUE TITLE
Fallout who fan

### ISSUE THREAD

**Issue by thesheriff1** [DarkholmeTenk/TardisModIssues#96]
After reading on about the mod it said this was inspired by fallout who so I was thinking add more to the tardis i know you said you don't want to use a gui but I think for things like navcom it's best if you do also if you want I'm not to bad at building Doctor who related stuff if you want to see some of my work just say and il give you the ip it has the tardis plugin so we add custom consoles any way great mod keep it up and what's your favtiote console in fallout who mines Toyota

**Comment by DarkholmeTenk** [comment]
We don't really have fixed nav points so the nav com has been simplified to the bookmarks system.

If you want to design your own consoles for this mod, there's instructions somewhere :3

I prefer the victorian console room
