### ISSUE TITLE
[ENHANCE] sound

### ISSUE THREAD

**Issue by FoxPotato** [DarkholmeTenk/TardisModIssues#97]
PLEASE HAVE A CONFIG OPTION TO DISABLE THE LEVEL UP SOUND.
IT SCARES THE LIVING SHIT OUT OF ME EVERY TIME.

**Comment by FoxPotato** [comment]
btw, is that sound from the ds game? it sounds like that sound it made when you completed a puzzle.

**Comment by DarkholmeTenk** [comment]
It's from the end of I Am The Doctor or Onwards! or something.
Also, disabling one sound in particular is rather annoying since the sounds are handled serverside and sent to Darkcore, so disabling one sound is a big urgh :P

**Comment by FoxPotato** [comment]
I know it's from a sound track (I've listened to all of them like min. 50 times (not even kidding(I wish i was))) but I swear the ds game had a sound like that too :p

**Comment by laz2727** [comment]
Can't you stop sound from happening? I'm seriously afraid of what your code
is, tbh.

**Comment by FoxPotato** [comment]
He can, he said it just might be difficult to disable one sound but keep another enabled.

#How loud should Tardis Mod sounds be (1.0 = full volume, 0.0 = no volume)
#Default: 1.0
Volume:D:1.0

that's in the config

**Comment by laz2727** [comment]
I mean, right in the levelup event or something.

**Comment by DarkholmeTenk** [comment]
It'd have to be serverside though :P

**Comment by FoxPotato** [comment]
Maybe make it less loud in general. It's quite loud, as is the TARDIS itself.

**Comment by Jwtc2000** [comment]
BUM BUM BUM BUM BUM BUM BUMM

**Comment by FoxPotato** [comment]
What he said.

**Comment by Jwtc2000** [comment]
![OHSHIT] (http://i.dailymail.co.uk/i/pix/2011/02/28/article-0-0D6A3F08000005DC-670_468x320.jpg)

**Comment by FoxPotato** [comment]
https://www.youtube.com/watch?v=NlpRBLkgcBo

**Comment by FoxPotato** [comment]
i did not know it would close the thing lmao. forgot this was my thread ;'D

**Comment by DarkholmeTenk** [comment]
How about a darkcore config option which is just a blacklist of sounds which you could add tardismod:levelUp to?

**Comment by FoxPotato** [comment]
That would be nice, Because again it scared the shit out of me when i wasn't paying attention ;-;
