### ISSUE TITLE
[BUG] Locate

### ISSUE THREAD

**Issue by FoxPotato** [DarkholmeTenk/TardisModIssues#98]
I'm level 5192 right now but the locate function isn't available on my sonic. the engine says I've got it enabled but it's not??

**Comment by FoxPotato** [comment]
scrap that, it just doesn't show up while in the TARDIS. my mistake ._.

**Comment by DarkholmeTenk** [comment]
Recall/Locate shouldn't be switchable to inside the TARDIS because you're inside the TARDIS so neither of them make any sense :P

**Comment by FoxPotato** [comment]
well then i got a bug for you. I can still switch to recall inside the TARDIS.
:p

**Comment by DarkholmeTenk** [comment]
Seem to recall fixing recall after I closed this issue. Can you confirm?

**Comment by FoxPotato** [comment]
I can only switch to the default and transmat inside the TARDIS
